My Project: Main Page
gim_time_obj Class Reference
Class useful to manage a timer with resoluti up to Usec.
#include <gim_time.h>
Public Member Functions
char * date (void)
unsigned int get (void)
Use this function in order obtain the difference, absolute or relative,
between the start and the get (relative) or
between the start and the stop (absolute).
Calling get before stop a partial result is obtained and the count is not interrupted.
char * get_usec (void)
Use this function in order obtain the difference from start
.
gim_time_obj ()
char * process (void)
Use this function in order obtain the process time
.
int process_msec (void)
int process_sec (void)
void start (void)
Use this function in order to mark the moment of start.
void start_usec (void)
Use this function in order to mark the moment of start.
void stop (void)
Use this function in order to mark the moment of stop.
Detailed Description
Class useful to manage a timer with resoluti up to Usec.
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
1.0-0
Date
2003-2007
Definition at line 66 of file gim_time.h.
Constructor & Destructor Documentation
gim_time_obj()
gim_time_obj::gim_time_obj () inline
the constructor
Definition at line 124 of file gim_time.h.
{
                 t_start = 0;
                 t_stop  = 0;
                 t_diff  = 0;
                 tvstart.tv_sec = 0;
                 tvstart.tv_usec = 0;
                 tvstop.tv_sec = 0;
                 tvstop.tv_usec = 0;
                 tvdiff.tv_sec = 0;
                 tvdiff.tv_usec = 0;
                 now.tv_sec = 0;
                 now.tv_usec = 0;
             };
Member Function Documentation
date()
char * gim_time_obj::date (void)
Definition at line 107 of file gim_time.cc.
{
     time_t  tp;
     char        timestamp[64];
     time( &tp );
     strftime( timestamp , 64 , "%A %d-%m-%Y %H:%M:%S" , localtime ( &tp ) );
     return strdup( timestamp );
 }
Referenced by gim_log_obj::start().
get()
unsigned int gim_time_obj::get (void)
Use this function in order obtain the difference, absolute or relative,
between the start and the get (relative) or
between the start and the stop (absolute).
Calling get before stop a partial result is obtained and the count is not interrupted.
Returns
the relative time in expressed in seconds
Definition at line 55 of file gim_time.cc.
{
     _gim_flag stop;
     if ( t_stop == 0 ) {
         this->stop();
         stop= __GIM_NO;
     }
     else
         stop = __GIM_YES;
     t_diff = t_stop - t_start;
     if ( stop == __GIM_NO )
         t_stop = 0;
     return ( (unsigned int) t_diff );
 }
References __GIM_NO, __GIM_YES, and stop().
Referenced by stop().
get_usec()
char * gim_time_obj::get_usec (void)
Use this function in order obtain the difference from start
.
Returns
The instant time in string format
Definition at line 73 of file gim_time.cc.
{
     static char res[32];
     gettimeofday( &tvstop , NULL );
     tv_removal();
     sprintf( res , "%2d.%06d" , (unsigned int)tvdiff.tv_sec , (unsigned int)tvdiff.tv_usec );
     return res;
 }
Referenced by gim_log_obj::addline(), and gim_log_obj::addline_format().
process()
char * gim_time_obj::process (void)
Use this function in order obtain the process time
.
Returns
The process time
Definition at line 90 of file gim_time.cc.
{
     static char res[32];
     getrusage( RUSAGE_SELF , &r_usage );
     sprintf( res , "%3d.%03d" , (unsigned int)r_usage.ru_utime.tv_sec , (unsigned int)( r_usage.ru_utime.tv_usec / 1000 ) );
     return res;
 }
Referenced by gim_error_obj::get().
process_msec()
int gim_time_obj::process_msec (void)
Definition at line 102 of file gim_time.cc.
{
     gettimeofday( &now , NULL );
     return tvstop.tv_usec;
 }
process_sec()
int gim_time_obj::process_sec (void)
Definition at line 97 of file gim_time.cc.
{
     gettimeofday( &now , NULL );
     return tvstop.tv_sec;
 }
start()
void gim_time_obj::start (void)
Use this function in order to mark the moment of start.
Definition at line 41 of file gim_time.cc.
{
     t_start = time( NULL );
     t_stop  = 0;
 }
start_usec()
void gim_time_obj::start_usec (void)
Use this function in order to mark the moment of start.
Definition at line 69 of file gim_time.cc.
{
     gettimeofday( &tvstart , NULL );
 }
Referenced by gim_log_obj::start().
stop()
void gim_time_obj::stop (void)
Use this function in order to mark the moment of stop.
Definition at line 46 of file gim_time.cc.
{
     if ( t_start ) {
         t_stop = time( NULL );
         get();
     }
     else {
     }
 }
References get().
Referenced by get().