My Project: Main Page
gim_version.h File Reference
Copyright (C) 2002, 2003
Danilo Zannoni (AsYntote) - Corrado Tumiati (SkyMatrix)
Released under the terms of the GNU General Public License v2
[ http://www.gkript.org/gkript-gpl.html ].
#include <stdio.h>
#include <stdlib.h>
#include "gim_custom_type.h"
#include "gim_lexical.h"
#include "gim_gkmake.h"
Macros
#define GIM_BUILD_LAST GIM_GKMAKE_LAST_BUILD
#define GIM_EXTENDED_NAME "Gim <Generic Information Manager> c++ static library made by gKript.org"
#define GIM_LICENSE "Released under the terms of the GNU General Public License v3"
#define GIM_MAJOR 2
#define GIM_MILESTONE "3.0"
#define GIM_MINOR 8
#define GIM_NAME "Gim"
#define GIM_SINCE "07/12/2003"
#define GIM_SUBMINOR GIM_GKMAKE_BUILD
#define GIM_VERSION "2.8-7"
#define GIM_VERSION_STATE "dev"
#define GKMAKE_VERSIONING
Functions
int gim_check_version (int maj, int min)
int gim_check_version (int maj, int min, int sub)
Use this function to check if Gim is at the required version.
char * gim_version (void)
Use this function to print on stdout the Gim version with extended infos.
char * gim_version_micro (void)
Use this function to print on stdout the Gim version with no infos.
char * gim_version_small (void)
Use this function to print on stdout the Gim version with basic infos.
Detailed Description
Copyright (C) 2002, 2003
Danilo Zannoni (AsYntote) - Corrado Tumiati (SkyMatrix)
Released under the terms of the GNU General Public License v2
[ http://www.gkript.org/gkript-gpl.html ].
Version
2.0-0
Definition in file gim_version.h.
Macro Definition Documentation
GIM_BUILD_LAST
#define GIM_BUILD_LAST GIM_GKMAKE_LAST_BUILD
Definition at line 88 of file gim_version.h.
GIM_EXTENDED_NAME
#define GIM_EXTENDED_NAME "Gim <Generic Information Manager> c++ static library made by gKript.org"
Is the long name of this library
Definition at line 74 of file gim_version.h.
GIM_LICENSE
#define GIM_LICENSE "Released under the terms of the GNU General Public License v3"
Definition at line 75 of file gim_version.h.
GIM_MAJOR
#define GIM_MAJOR 2
The major version of Gim
Definition at line 83 of file gim_version.h.
GIM_MILESTONE
#define GIM_MILESTONE "3.0"
Definition at line 81 of file gim_version.h.
GIM_MINOR
#define GIM_MINOR 8
The minor version of Gim
When defined Gim include the bmake file generetad by bmake that is a built counter
Definition at line 84 of file gim_version.h.
GIM_NAME
#define GIM_NAME "Gim"
Is the short name of this library
Definition at line 73 of file gim_version.h.
GIM_SINCE
#define GIM_SINCE "07/12/2003"
The official first release on http://gkript.org/
Definition at line 76 of file gim_version.h.
GIM_SUBMINOR
#define GIM_SUBMINOR GIM_GKMAKE_BUILD
Definition at line 87 of file gim_version.h.
GIM_VERSION
#define GIM_VERSION "2.8-7"
The string version of Gim
Definition at line 80 of file gim_version.h.
GIM_VERSION_STATE
#define GIM_VERSION_STATE "dev"
Definition at line 78 of file gim_version.h.
GKMAKE_VERSIONING
#define GKMAKE_VERSIONING
Definition at line 52 of file gim_version.h.
Function Documentation
gim_check_version() [1/2]
int gim_check_version (int maj, int min)
Definition at line 96 of file gim_version.cc.
{
     char    gim_ver[16];
     char    req_ver[16];
     sprintf( gim_ver , "%d%d" , GIM_MAJOR , GIM_MINOR );
     sprintf( req_ver , "%d%d" , maj , min );
     if ( atoi(gim_ver) >= atoi(req_ver) )
         return __GIM_OK;
     else
         return __GIM_NOT_OK;
 }
References __GIM_NOT_OK, __GIM_OK, GIM_MAJOR, and GIM_MINOR.
gim_check_version() [2/2]
int gim_check_version (int maj, int min, int sub)
Use this function to check if Gim is at the required version.
Parameters
maj The major version number of th required gim
min The minor version number of th required gim
sub The subminor version number of th required gim
Returns
__GIM_OK if Gim is at the required version, __GIM_NOT_OK if not.
Parameters
maj The major version number of th required gim
min The minor version number of th required gim
Returns
__GIM_OK if Gim is at the required version, __GIM_NOT_OK if not.
Definition at line 84 of file gim_version.cc.
{
     char    gim_ver[16];
     char    req_ver[16];
     sprintf( gim_ver , "%d%d%d" , GIM_MAJOR , GIM_MINOR , GIM_SUBMINOR );
     sprintf( req_ver , "%d%d%d" , maj , min , sub );
     if ( atoi(gim_ver) >= atoi(req_ver) )
         return __GIM_OK;
     else
         return __GIM_NOT_OK;
 }
References __GIM_NOT_OK, __GIM_OK, GIM_MAJOR, GIM_MINOR, and GIM_SUBMINOR.
gim_version()
char * gim_version (void)
Use this function to print on stdout the Gim version with extended infos.
Definition at line 42 of file gim_version.cc.
{
     static char gim_ver[256];
     if ( Lexical.str_equal( GIM_VERSION_STATE , "rel" ) == __GIM_YES )
         sprintf( gim_ver , "Gim %s - Ver %d.%d-%d compiled on %s" , (const char *)GIM_MILESTONE , GIM_MAJOR , GIM_MINOR , GIM_SUBMINOR , GIM_BUILD_LAST );
     if ( Lexical.str_equal( GIM_VERSION_STATE , "dev" ) == __GIM_YES )
         sprintf( gim_ver , "Gim %s - Ver %d.%d-%d-d compiled on %s" , (const char *)GIM_MILESTONE , GIM_MAJOR , GIM_MINOR , GIM_SUBMINOR , GIM_BUILD_LAST );
     return gim_ver;
 }
References __GIM_YES, GIM_BUILD_LAST, GIM_MAJOR, GIM_MILESTONE, GIM_MINOR, GIM_SUBMINOR, GIM_VERSION_STATE, Lexical, and prsr_lexical_class::str_equal().
Referenced by gim_log_obj::start().
gim_version_micro()
char * gim_version_micro (void)
Use this function to print on stdout the Gim version with no infos.
Definition at line 74 of file gim_version.cc.
{
     static char gim_ver[256];
     if ( Lexical.str_equal( GIM_VERSION_STATE , "rel" ) == __GIM_YES )
         sprintf( gim_ver , "%d.%d-%d" , GIM_MAJOR , GIM_MINOR , GIM_SUBMINOR );
     if ( Lexical.str_equal( GIM_VERSION_STATE , "dev" ) == __GIM_YES )
         sprintf( gim_ver , "%d.%d-%d-d" , GIM_MAJOR , GIM_MINOR , GIM_SUBMINOR );
     return gim_ver;
 }
References __GIM_YES, GIM_MAJOR, GIM_MINOR, GIM_SUBMINOR, GIM_VERSION_STATE, Lexical, and prsr_lexical_class::str_equal().
gim_version_small()
char * gim_version_small (void)
Use this function to print on stdout the Gim version with basic infos.
Definition at line 64 of file gim_version.cc.
{
     static char gim_ver[256];
     if ( Lexical.str_equal( GIM_VERSION_STATE , "rel" ) == __GIM_YES )
         sprintf( gim_ver , "Gim - Ver %d.%d-%d" , GIM_MAJOR , GIM_MINOR , GIM_SUBMINOR );
     if ( Lexical.str_equal( GIM_VERSION_STATE , "dev" ) == __GIM_YES )
         sprintf( gim_ver , "Gim - Ver %d.%d-%d-d" , GIM_MAJOR , GIM_MINOR , GIM_SUBMINOR );
     return gim_ver;
 }
References __GIM_YES, GIM_MAJOR, GIM_MINOR, GIM_SUBMINOR, GIM_VERSION_STATE, Lexical, and prsr_lexical_class::str_equal().