My Project: Main Page
gim_file_obj Class Reference
The Gim's file object class is useful in order to use the files like objects fastly and easily. _gim_file is a type defined as this class. In this example we create a backup of our precious /etc/X11/xorg.conf
.
#include <gim_file.h>
Public Member Functions
_gim_buffer buffer (void)
With this method you can obtain the pointer of the buffer loaded.
_gim_flag check (void)
Use this method to check if the file exist or not.
void close (void)
Use this to close a file previously opened.
_gim_flag error (void)
Use this method to verify if all it is ok or some error occurred.
int fd (void)
With this method you can obtain the file descriptor of the file only if you have opened the file in __GIM_FILE_DESCRIPTOR.
_gim_flag flush (char *data, int data_len)
Use this method if you want tu flush a buffer into a file opened in __GIM_WRITE.
char * fm (void)
With this method you can obtain the pointer of the file only if you have opened the file in __GIM_FILE_MAPPING.
FILE * fp (void)
With this method you can obtain the file pointer of the file only if you have opened the file in __GIM_FILE_POINTER.
_gim_handler * get_handler (void)
With this method you can get the relative _gim_handler pointer of the file opened using gim_file_obj.
struct stat * get_stat (void)
gim_file_obj (const char *fname)
gim_file_obj (const char *fname, _gim_flag Method)
gim_file_obj (const char *fname, _gim_flag Method, _gim_flag Mode)
_gim_buffer load (void)
Use this method to load an opened file in __GIM_READ to a buffer.
void name (const char *filename)
char * name (void)
To get the setted file name.
_gim_handler * open (_gim_flag method, _gim_flag mode)
Use it to open the file previously setted.
_gim_flag put (const char *string)
Use this method if you want tu put a string into a file opened in __GIM_WRITE.
_gim_Uint32 size (_gim_Uint32 offset)
To get the size of an opened file with an offset...
(it will return (size - offset) useful in some occasion)
_gim_Uint32 size (void)
To get the size of an opened file.
_gim_flag type (void)
Use this method to know wich kind of file is it.
void unload (void)
Use this method to free the buffer previously load.
Detailed Description
The Gim's file object class is useful in order to use the files like objects fastly and easily. _gim_file is a type defined as this class. In this example we create a backup of our precious /etc/X11/xorg.conf
.
#include <gim/gim.h>
int main(int argc , char **argv) {
    gim_obj * gim = new gim_obj;
    _gim_file   source( "/etc/X11/xorg.conf" );
    _gim_file   destination( "/etc/X11/xorg.conf.backup" , __GIM_FILE_POINTER , __GIM_WRITE );
    destination.flush( source.fm() , source.size() );
    source.close();
    destination.close();
    delete gim;
    return 0;
}
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
2.0-0
Date
2003-2008
Definition at line 284 of file gim_file.h.
Constructor & Destructor Documentation
gim_file_obj() [1/3]
gim_file_obj::gim_file_obj (const char * fname)
Definition at line 575 of file gim_file.cc.
{
     if ( gim_file_manager != NULL ) {
         handler = gim_file_manager->open( filename , __GIM_FILE_MAPPING , __GIM_READ );
         if ( handler != NULL ) {
             exist = __GIM_EXIST;
             handler->loadp = NULL;
             method = __GIM_FILE_MAPPING;
             mode = __GIM_READ;
             errors = __GIM_OK;
             gim_error->set( "gim_file_obj::gim_file_obj" , "End of constructor" );
         }
         else {
             errors = __GIM_ERROR;
             exist = __GIM_NOT_EXIST;
             char message[256];
             sprintf( message , "[%s] File not found" , filename );
             gim_error->set( GIM_ERROR_CRITICAL , "gim_file_obj::gim_file_obj" , message , __GIM_ERROR );
         }
     }
     else
         gim_error->set( GIM_ERROR_FATAL , "gim_file_obj::gim_file_obj" , "Gim File Manager is down" , __GIM_ERROR );
 }
References __GIM_ERROR, __GIM_EXIST, __GIM_FILE_MAPPING, __GIM_NOT_EXIST, __GIM_OK, __GIM_READ, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_FATAL, gim_file_manager, gim_global_item_handler::loadp, gim_file_manager_obj::open(), and gim_error_obj::set().
gim_file_obj() [2/3]
gim_file_obj::gim_file_obj (const char * fname, _gim_flag Method)
Definition at line 598 of file gim_file.cc.
{
     if ( gim_file_manager != NULL ) {
         handler = gim_file_manager->open( filename , Method , __GIM_READ );
         if ( handler != NULL ) {
             exist = __GIM_EXIST;
             handler->loadp = NULL;
             method = Method;
             mode = __GIM_READ;
             errors = __GIM_OK;
             gim_error->set( "gim_file_obj::gim_file_obj" , "End of constructor" );
         }
         else {
             errors = __GIM_ERROR;
             exist = __GIM_NOT_EXIST;
             char message[256];
             sprintf( message , "[%s] File not found" , filename );
             gim_error->set( GIM_ERROR_CRITICAL , "gim_file_obj::gim_file_obj" , message , __GIM_ERROR );
         }
     }
     else
         gim_error->set( GIM_ERROR_FATAL , "gim_file_obj::gim_file_obj" , "Gim File Manager is down" , __GIM_ERROR );
 }
References __GIM_ERROR, __GIM_EXIST, __GIM_NOT_EXIST, __GIM_OK, __GIM_READ, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_FATAL, gim_file_manager, gim_global_item_handler::loadp, gim_file_manager_obj::open(), and gim_error_obj::set().
gim_file_obj() [3/3]
gim_file_obj::gim_file_obj (const char * fname, _gim_flag Method, _gim_flag Mode)
Definition at line 621 of file gim_file.cc.
{
     if ( gim_file_manager != NULL ) {
         handler = gim_file_manager->open( filename , Method , Mode );
         if ( handler != NULL ) {
             exist = __GIM_EXIST;
             handler->loadp = NULL;
             method = Method;
             mode = Mode;
             errors = __GIM_OK;
             gim_error->set( "gim_file_obj::gim_file_obj" , "End of constructor" );
         }
         else {
             errors = __GIM_ERROR;
             exist = __GIM_NOT_EXIST;
             char message[256];
             sprintf( message , "[%s] File not found" , filename );
             gim_error->set( GIM_ERROR_CRITICAL , "gim_file_obj::gim_file_obj" , message , __GIM_ERROR );
         }
     }
     else
         gim_error->set( GIM_ERROR_FATAL , "gim_file_obj::gim_file_obj" , "Gim File Manager is down" , __GIM_ERROR );
 }
References __GIM_ERROR, __GIM_EXIST, __GIM_NOT_EXIST, __GIM_OK, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_FATAL, gim_file_manager, gim_global_item_handler::loadp, gim_file_manager_obj::open(), and gim_error_obj::set().
Member Function Documentation
buffer()
_gim_buffer gim_file_obj::buffer (void)
With this method you can obtain the pointer of the buffer loaded.
Returns
The pointer of the buffer
Definition at line 841 of file gim_file.cc.
{
     return f_buffer;
 }
check()
_gim_flag gim_file_obj::check (void)
Use this method to check if the file exist or not.
Returns
__GIM_EXIST if exist or __GIM_NOT_EXIST if not
Definition at line 674 of file gim_file.cc.
{
     return exist;
 }
Referenced by gim_checksum_obj::sha1(), gim_checksum_obj::sha256(), and gim_checksum_obj::sha512().
close()
void gim_file_obj::close (void)
Use this to close a file previously opened.
Definition at line 664 of file gim_file.cc.
{
     gim_file_manager->close( handler );
 }
References gim_file_manager_obj::close(), and gim_file_manager.
Referenced by gim_checksum_obj::sha1(), gim_checksum_obj::sha256(), and gim_checksum_obj::sha512().
error()
_gim_flag gim_file_obj::error (void)
Use this method to verify if all it is ok or some error occurred.
Returns
__GIM_OK if allit's ok or __GIM_ERROR if not
Definition at line 679 of file gim_file.cc.
{
     return errors;
 }
fd()
int gim_file_obj::fd (void)
With this method you can obtain the file descriptor of the file only if you have opened the file in __GIM_FILE_DESCRIPTOR.
Returns
The file descriptor
Definition at line 832 of file gim_file.cc.
{
     return handler->fd;
 }
References gim_global_item_handler::fd.
flush()
_gim_flag gim_file_obj::flush (char * data, int data_len)
Use this method if you want tu flush a buffer into a file opened in __GIM_WRITE.
Parameters
data A pointer to the buffer to flush
data_len The size of the buffer in bytes
Returns
__GIM_OK if ok and __GIM_NOT_OK if some error happens
Definition at line 743 of file gim_file.cc.
{
     if ( ( mode == __GIM_WRITE ) && ( exist == __GIM_EXIST ) ) {
         switch ( method ) {
             case __GIM_FILE_DESCRIPTOR : {
                 write( handler->fd , data , data_len );
                 break;
             }
             case __GIM_FILE_POINTER : {
                 fwrite( data , data_len , 1 , handler->fp );
                 break;
             }
             case __GIM_FILE_MAPPING : {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_file_obj::flush" , "Flush is not possible in __GIM_FILE_MAPPING" , __GIM_ERROR );
                 return __GIM_NOT_OK;
             }
         }
         gim_error->set( "gim_file_obj::flush" , "Flushed succesfully" );
         return __GIM_OK;
     }
     else {
         if ( mode != __GIM_WRITE ) {
             gim_error->set( GIM_ERROR_CRITICAL , "gim_file_obj::flush" , "Flush is possible in __GIM_WRITE only" , __GIM_ERROR );
         }
         else if  ( exist == __GIM_EXIST ) {
             gim_error->set( GIM_ERROR_CRITICAL , "gim_file_obj::flush" , "The file not exist" , __GIM_ERROR );
         }
     }
     return __GIM_NOT_OK;
 }
References __GIM_ERROR, __GIM_EXIST, __GIM_FILE_DESCRIPTOR, __GIM_FILE_MAPPING, __GIM_FILE_POINTER, __GIM_NOT_OK, __GIM_OK, __GIM_WRITE, gim_global_item_handler::fd, gim_global_item_handler::fp, gim_error, GIM_ERROR_CRITICAL, and gim_error_obj::set().
fm()
char * gim_file_obj::fm (void)
With this method you can obtain the pointer of the file only if you have opened the file in __GIM_FILE_MAPPING.
Returns
The pointer
Definition at line 836 of file gim_file.cc.
{
     return handler->fm;
 }
References gim_global_item_handler::fm.
fp()
FILE * gim_file_obj::fp (void)
With this method you can obtain the file pointer of the file only if you have opened the file in __GIM_FILE_POINTER.
Returns
The file pointer
Definition at line 828 of file gim_file.cc.
{
     return handler->fp;
 }
References gim_global_item_handler::fp.
get_handler()
_gim_handler * gim_file_obj::get_handler (void)
With this method you can get the relative _gim_handler pointer of the file opened using gim_file_obj.
Returns
The _gim_handler pointer of the file.
Definition at line 669 of file gim_file.cc.
{
     return handler;
 }
get_stat()
struct stat * gim_file_obj::get_stat (void)
Todo:
maybe present in future releases
Returns
Now, if you call it, return always NULL
Definition at line 659 of file gim_file.cc.
{
     return NULL;
 }
load()
_gim_buffer gim_file_obj::load (void)
Use this method to load an opened file in __GIM_READ to a buffer.
Returns
A poiter to the buffer or NULL if error.
Definition at line 703 of file gim_file.cc.
{
     if ( handler->loadp != NULL ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_file_obj::load" , "File already loaded" , __GIM_ERROR );
         return handler->loadp;
     }
     if ( ( mode == __GIM_READ ) && ( exist == __GIM_EXIST ) ) {
         switch ( method ) {
             case __GIM_FILE_DESCRIPTOR : {
                 handler->loadp = (char *)gim_memory->Alloc( handler->size * sizeof( char ) , __GIM_MEM_FOBJ_LOAD , __GIM_HIDE );
                 if ( handler->loadp == NULL ) return NULL;
                 read( handler->fd , handler->loadp , handler->size );
                 break;
             }
             case __GIM_FILE_POINTER : {
                 handler->loadp = (char *)gim_memory->Alloc( handler->size * sizeof( char ) , __GIM_MEM_FOBJ_LOAD , __GIM_HIDE );
                 if ( handler->loadp == NULL ) return NULL;
                 fread( handler->loadp , handler->size , 1 , handler->fp );
                 break;
             }
             case __GIM_FILE_MAPPING : {
                 handler->loadp = (char *)gim_memory->Alloc( handler->size * sizeof( char ) , __GIM_MEM_FOBJ_LOAD , __GIM_HIDE );
                 if ( handler->loadp == NULL ) return NULL;
                 memcpy( handler->loadp , handler->fm , handler->size );
                 break;
             }
         }
         gim_error->set( "gim_file_obj::load" , "Loaded succesfully"  );
     }
     else {
         if ( mode != __GIM_READ ) {
             gim_error->set( GIM_ERROR_WARNING , "gim_file_obj::load" , "Load is possible in __GIM_READ only" , __GIM_ERROR );
         }
         else if  ( exist == __GIM_EXIST ) {
             gim_error->set( GIM_ERROR_WARNING , "gim_file_obj::load" , "The file not exist" , __GIM_ERROR );
         }
     }
     f_buffer = handler->loadp;
     return handler->loadp;
 }
References __GIM_ERROR, __GIM_EXIST, __GIM_FILE_DESCRIPTOR, __GIM_FILE_MAPPING, __GIM_FILE_POINTER, __GIM_HIDE, __GIM_MEM_FOBJ_LOAD, __GIM_READ, gim_memory_obj::Alloc(), gim_global_item_handler::fd, gim_global_item_handler::fm, gim_global_item_handler::fp, gim_error, GIM_ERROR_WARNING, gim_memory, gim_global_item_handler::loadp, gim_error_obj::set(), and gim_global_item_handler::size.
Referenced by gim_checksum_obj::sha1(), gim_checksum_obj::sha256(), and gim_checksum_obj::sha512().
name() [1/2]
void gim_file_obj::name (const char * filename)
name() [2/2]
char * gim_file_obj::name (void)
To get the setted file name.
Returns
The file name setted
Definition at line 645 of file gim_file.cc.
{
     return handler->name;
 }
References gim_global_item_handler::name.
open()
_gim_handler * gim_file_obj::open (_gim_flag method, _gim_flag mode)
Use it to open the file previously setted.
Parameters
method The method you want to use. Please to make reference to open_method
mode The mode in which you want to open a file. Please to make reference to open_mode
Returns
The _gim_handler pointer of the file or NULL if any problem.
put()
_gim_flag gim_file_obj::put (const char * string)
Use this method if you want tu put a string into a file opened in __GIM_WRITE.
Parameters
string The string to append in the opened file
Returns
__GIM_OK if ok and __GIM_NOT_OK if some error happens
Definition at line 774 of file gim_file.cc.
{
     if ( ( mode == __GIM_WRITE ) && ( exist == __GIM_EXIST ) ) {
         switch ( method ) {
             case __GIM_FILE_DESCRIPTOR : {
                 write( handler->fd , string , strlen( string ) );
                 break;
             }
             case __GIM_FILE_POINTER : {
                 fprintf( handler->fp , "%s\n" , string );
                 break;
             }
             case __GIM_FILE_MAPPING : {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_file_obj::puts" , "Puts is not possible in __GIM_FILE_MAPPING" , __GIM_ERROR );
                 return __GIM_NOT_OK;
             }
         }
         return __GIM_OK;
     }
     else {
         if ( mode != __GIM_WRITE ) {
             gim_error->set( GIM_ERROR_CRITICAL , "gim_file_obj::puts" , "Puts is possible in __GIM_WRITE only" , __GIM_ERROR );
         }
         else if  ( exist == __GIM_EXIST ) {
             gim_error->set( GIM_ERROR_CRITICAL , "gim_file_obj::puts" , "The file not exist" , __GIM_ERROR );
         }
     }
     return __GIM_NOT_OK;
 }
References __GIM_ERROR, __GIM_EXIST, __GIM_FILE_DESCRIPTOR, __GIM_FILE_MAPPING, __GIM_FILE_POINTER, __GIM_NOT_OK, __GIM_OK, __GIM_WRITE, gim_global_item_handler::fd, gim_global_item_handler::fp, gim_error, GIM_ERROR_CRITICAL, and gim_error_obj::set().
size() [1/2]
_gim_Uint32 gim_file_obj::size (_gim_Uint32 offset)
To get the size of an opened file with an offset...
(it will return (size - offset) useful in some occasion)
Returns
The file size
Definition at line 654 of file gim_file.cc.
{
     return ( handler->size - offset );
 }
References gim_global_item_handler::size.
size() [2/2]
_gim_Uint32 gim_file_obj::size (void)
To get the size of an opened file.
Returns
The file size
Definition at line 649 of file gim_file.cc.
{
     return handler->size;
 }
References gim_global_item_handler::size.
Referenced by gim_checksum_obj::sha1(), gim_checksum_obj::sha256(), and gim_checksum_obj::sha512().
type()
_gim_flag gim_file_obj::type (void)
Use this method to know wich kind of file is it.
Returns
One of define listed in item_type enum.
Definition at line 684 of file gim_file.cc.
{
     if ( gim_utils.isdir( this->fname ) == __GIM_YES )
         return __GIM_REGULAR_NODE;
     if ( gim_utils.isregular( this->fname ) == __GIM_YES ) {
         if ( this->handler->size == 0 ) {
             return __GIM_EMPTY_FILE;
         }
         else {
             return __GIM_REGULAR_FILE;
         }
     }
     if ( gim_utils.islink( this->fname ) == __GIM_YES )
         return __GIM_LINK;
     if ( gim_utils.isdevice( this->fname ) == __GIM_YES )
         return __GIM_DEVICE;
     return __GIM_FILE_UNKNOWN;
 }
References __GIM_DEVICE, __GIM_EMPTY_FILE, __GIM_FILE_UNKNOWN, __GIM_LINK, __GIM_REGULAR_FILE, __GIM_REGULAR_NODE, __GIM_YES, gim_utils, gim_utils_obj::isdevice(), gim_utils_obj::isdir(), gim_utils_obj::islink(), gim_utils_obj::isregular(), and gim_global_item_handler::size.
unload()
void gim_file_obj::unload (void)
Use this method to free the buffer previously load.
Definition at line 818 of file gim_file.cc.
{
     if ( handler->loadp != NULL ) {
         if ( gim_memory->Free( handler->loadp ) == __GIM_OK )
             gim_error->set( "gim_file_obj::unload" , "Unloaded succesfully" );
         else
             gim_error->set( GIM_ERROR_CRITICAL , "gim_file_obj::unload" , "Some memory issue" , __GIM_ERROR );
     }
 }
References __GIM_ERROR, __GIM_OK, gim_memory_obj::Free(), gim_error, GIM_ERROR_CRITICAL, gim_memory, gim_global_item_handler::loadp, and gim_error_obj::set().