My Project: Main Page
gim_directory_obj Class Reference
This class helps you to work with directory on a file system.
#include <gim_directory.h>
Public Member Functions
void also_hide (_gim_flag _hide)
_gim_flag free_item (_gim_dir_item *to_free)
_gim_dir_item * get_item (_gim_flag inc=0)
_gim_dir_item * get_item_id (_gim_Uint32 id)
gim_directory_obj ()
gim_directory_obj (const char *dir, _gim_flag rec, _gim_flag _hide=__GIM_NO)
_gim_Uint32 items (void)
_gim_Uint32 make (const char *dir_name)
_gim_flag recursion (_gim_flag rec)
_gim_Uint32 refresh (void)
void reset_position (void)
~gim_directory_obj ()
Detailed Description
This class helps you to work with directory on a file system.
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
2.5-0
Date
2003-2008
Definition at line 85 of file gim_directory.h.
Constructor & Destructor Documentation
gim_directory_obj() [1/2]
gim_directory_obj::gim_directory_obj () inline
gim_directory_obj constructor
Definition at line 117 of file gim_directory.h.
{
                 gim_error->set( "gim_directory_obj::~gim_directory_obj" , "Start constructor" );
                 item = 0;
                 startlist   = NULL;
                 currentlist = NULL;
                 endlist     = NULL;
                 recursive   = GIM_DIR_NOT_RECURSIVE;
                 hide        = __GIM_NO;
                 memory = new _gim_mempage;
                 gim_error->set( "gim_directory_obj::~gim_directory_obj" , "End constructor" );
             };
References __GIM_NO, GIM_DIR_NOT_RECURSIVE, gim_error, and gim_error_obj::set().
gim_directory_obj() [2/2]
gim_directory_obj::gim_directory_obj (const char * dir, _gim_flag rec, _gim_flag _hide = __GIM_NO) inline
gim_directory_obj constructor
Definition at line 131 of file gim_directory.h.
{
                 gim_error->set( "gim_directory_obj::~gim_directory_obj" , "Start constructor" );
                 item = 0;
                 startlist   = NULL;
                 currentlist = NULL;
                 endlist     = NULL;
                 recursive   = rec;
                 hide        = _hide;
                 memory = new _gim_mempage;
                 p_make( dir , __GIM_ROOT );
                 reset_position();
                 gim_error->set( "gim_directory_obj::~gim_directory_obj" , "End constructor" );
             };
References __GIM_ROOT, gim_error, reset_position(), and gim_error_obj::set().
~gim_directory_obj()
gim_directory_obj::~gim_directory_obj () inline
gim_directory_obj destructor
Definition at line 147 of file gim_directory.h.
{
                 gim_error->set( "gim_directory_obj::~gim_directory_obj" , "Start destructor" );
                 destroy();
                 delete memory;
                 gim_error->set( "gim_directory_obj::~gim_directory_obj" , "End destructor" );
             };
References gim_error, and gim_error_obj::set().
Member Function Documentation
also_hide()
void gim_directory_obj::also_hide (_gim_flag _hide)
Definition at line 234 of file gim_directory.cc.
{
     if ( ( _hide == __GIM_YES ) || ( _hide == __GIM_NO ) ) {
         hide = _hide;
     }
 }
References __GIM_NO, and __GIM_YES.
free_item()
_gim_flag gim_directory_obj::free_item (_gim_dir_item * to_free)
Definition at line 286 of file gim_directory.cc.
{
     return gim_memory->Free( to_free );
 }
References gim_memory_obj::Free(), and gim_memory.
get_item()
_gim_dir_item * gim_directory_obj::get_item (_gim_flag inc = 0)
Definition at line 260 of file gim_directory.cc.
{
     char message[256];
     if ( ! startlist ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_directory_obj::get_item" , "Startlist is NULL : error" , __GIM_ERROR );
         return NULL;
     }
     if ( ! currentlist ) {
         gim_error->set( "gim_directory_obj::get_item" , "Endlist reached" );
         return NULL;
     }
     _gim_dir_item * res = (_gim_dir_item *)gim_memory->Alloc( sizeof (gim_dir_item) , __GIM_MEM_DIRECTORY_ITEM , __GIM_HIDE );
     if ( ! res ) {
         gim_error->set( GIM_ERROR_FATAL , "gim_directory_obj::get_item" , "Allocation of a new item failed"  , __GIM_ERROR );
         return NULL;
     }
     sprintf( res->name , "%s%s" , currentlist->path , currentlist->name );
     res->size = currentlist->size;
     res->type = currentlist->type;
     res->id = currentlist->id;
     if ( inc == GIM_DIR_INCREMENT )
         currentlist = currentlist->link;
 //  sprintf( message , "Got item id [%d]" , res->id );
 //  gim_error->set( "gim_directory_obj::get_item" , message );
     return res;
 }
References __GIM_ERROR, __GIM_HIDE, __GIM_MEM_DIRECTORY_ITEM, gim_memory_obj::Alloc(), GIM_DIR_INCREMENT, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_FATAL, gim_memory, gim_dir_file_list::id, gim_dir_item::id, gim_dir_file_list::link, gim_dir_file_list::name, gim_dir_item::name, gim_dir_file_list::path, gim_error_obj::set(), gim_dir_file_list::size, gim_dir_item::size, gim_dir_file_list::type, and gim_dir_item::type.
get_item_id()
_gim_dir_item * gim_directory_obj::get_item_id (_gim_Uint32 id)
Definition at line 291 of file gim_directory.cc.
{
     if ( id > item ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_directory_obj::get_item" , "ERROR : Id more high than item" , __GIM_ERROR );
         return NULL;
     }
     currentlist = startlist;
     while ( currentlist != NULL ) {
         if ( currentlist->id == id ) {
             char message[256];
             _gim_dir_item * res = (_gim_dir_item *)gim_memory->Alloc( sizeof (gim_dir_item) , __GIM_MEM_DIRECTORY_ITEM , __GIM_HIDE );
             if ( ! res ) {
                 gim_error->set( GIM_ERROR_FATAL , "gim_directory_obj::get_item" , "ERROR : Allocation of a new item failed"  , __GIM_ERROR );
                 return NULL;
             }
             sprintf( res->name , "%s%s" , currentlist->path , currentlist->name );
             res->size = currentlist->size;
             res->type = currentlist->type;
             res->id = currentlist->id;
 //          sprintf( message , "Got item id [%d]" , res->id );
 //          gim_error->set( "gim_directory_obj::get_item" , message );
             return res;
         }
         currentlist = currentlist->link;
     }
     gim_error->set( GIM_ERROR_CRITICAL , "gim_directory_obj::get_item" , "ERROR : Item not found" , __GIM_ERROR );
     return NULL;
 }
References __GIM_ERROR, __GIM_HIDE, __GIM_MEM_DIRECTORY_ITEM, gim_memory_obj::Alloc(), gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_FATAL, gim_memory, gim_dir_file_list::id, gim_dir_item::id, gim_dir_file_list::link, gim_dir_file_list::name, gim_dir_item::name, gim_dir_file_list::path, gim_error_obj::set(), gim_dir_file_list::size, gim_dir_item::size, gim_dir_file_list::type, and gim_dir_item::type.
items()
_gim_Uint32 gim_directory_obj::items (void)
Referenced by refresh().
make()
_gim_Uint32 gim_directory_obj::make (const char * dir_name)
Definition at line 184 of file gim_directory.cc.
{
     if ( strlen( dir_name ) == 0 ) {
         gim_error->set( "gim_directory_obj::make" , "" );
     }
     p_make( dir_name , __GIM_ROOT );
     reset_position();
 }
References __GIM_ROOT, gim_error, reset_position(), and gim_error_obj::set().
recursion()
_gim_flag gim_directory_obj::recursion (_gim_flag rec)
Definition at line 221 of file gim_directory.cc.
{
     if ( rec == __GIM_YES ) {
         recursive = GIM_DIR_RECURSIVE;
         return rec;
     }
     if ( rec == __GIM_NO ) {
         recursive = GIM_DIR_NOT_RECURSIVE;
         return rec;
     }
     return __GIM_ERROR;
 }
References __GIM_ERROR, __GIM_NO, __GIM_YES, GIM_DIR_NOT_RECURSIVE, and GIM_DIR_RECURSIVE.
refresh()
_gim_Uint32 gim_directory_obj::refresh (void)
Definition at line 240 of file gim_directory.cc.
{
     _gim_Uint32     items;
     if ( ! startlist ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_directory_obj::refresh" , "Startlist is NULL : error" , __GIM_ERROR );
         return 0;
     }
     gim_error->set( "gim_directory_obj::refresh" , "Start to refresh" );
     destroy();
     items = p_make( path , __GIM_ROOT );
     gim_error->set( "gim_directory_obj::refresh" , "Refreshed" );
     reset_position();
     return items;
 }
References __GIM_ERROR, __GIM_ROOT, gim_error, GIM_ERROR_CRITICAL, items(), reset_position(), and gim_error_obj::set().
reset_position()
void gim_directory_obj::reset_position (void)
Definition at line 254 of file gim_directory.cc.
{
     currentlist = startlist;
     gim_error->set( "gim_directory_obj::reset_position" , "Current position setted to startlist" );
 }
References gim_error, and gim_error_obj::set().
Referenced by gim_directory_obj(), make(), and refresh().