My Project: Main Page
gim_identity_obj Class Reference
It is a clas with all the informations about user and host.
#include <gim_identity.h>
Public Member Functions
char * arch (void)
Method useful to get the architecture of the host.
void get (void)
Method useful to fill all inner struct with the relative information.
gim_identity_obj ()
char * home (void)
Method useful to get the home path.
long hostid (void)
Method useful to know the processor hostid.
char * login (void)
Method useful to get the login name.
int n_proc (void)
Method useful to know how many processor are in the system.
char * node (void)
Use it to get the host name.
char * version (void)
Method useful to get the running kernel version.
~gim_identity_obj ()
Public Attributes
_gim_memory * mi
_gim_processor * processor
Detailed Description
It is a clas with all the informations about user and host.
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
1.0-0
Date
2003-2007
Definition at line 123 of file gim_identity.h.
Constructor & Destructor Documentation
gim_identity_obj()
gim_identity_obj::gim_identity_obj () inline
Definition at line 207 of file gim_identity.h.
{
                 host_id = gethostid();
                 init();
             };
~gim_identity_obj()
gim_identity_obj::~gim_identity_obj () inline
Definition at line 214 of file gim_identity.h.
{
                 release();
             };
Member Function Documentation
arch()
char * gim_identity_obj::arch (void)
Method useful to get the architecture of the host.
Returns
the architecture of the host
Definition at line 365 of file gim_identity.cc.
{
     return Arch;
 }
get()
void gim_identity_obj::get (void)
Method useful to fill all inner struct with the relative information.
Definition at line 68 of file gim_identity.cc.
{
     if ( filled == __GIM_NO ) {
         uid_t           me;
         struct passwd   * user_id;
         struct utsname  my_system;
         char tot[128];
         char disp[128];
         char message[256];
         _gim_processor * tmp_prc;
         gim_error->set( "gim_identity_obj::get" , "Getting identity..." );
         me = getuid ();
         user_id = getpwuid( me );
         uname ( & my_system );
         User_id = user_id->pw_uid;
         strcpy( Login       , user_id->pw_name );
         strcpy( Home        , user_id->pw_dir );
         strcpy( Real_name   , Lexical.char_filter( user_id->pw_gecos , ',' ) );
         strcpy( System_name , my_system.sysname );
         strcpy( Node_name   , my_system.nodename );
         strcpy( Release     , my_system.release );
         strcpy( Version     , my_system.version );
         strcpy( Arch        , my_system.machine );
         filled = __GIM_YES;
         processor = cpu();
         memory();
         strcpy( tot  , gim_memory->metric_converter( mi->total ) );
         strcpy( disp , gim_memory->metric_converter( mi->free )  );
         sprintf( message , "User detected  : %s@%s on %s" , gim_identity->Login , gim_identity->Node_name , gim_identity->Release );
         gim_error->set( "gim_identity_obj::get" , message );
         for( tmp_prc = processor ; tmp_prc != NULL ; tmp_prc = tmp_prc->next ) {
             if ( tmp_prc->bogomips != 0 )
                 sprintf( message , "Cpu  #%-2d  : %s @ %6.2fMHz (%6.3f) - Arch %s" , tmp_prc->proc_number , tmp_prc->model_name , tmp_prc->cpu_mhz , tmp_prc->bogomips , my_system.machine );
             else
                 sprintf( message , "Cpu  #%-2d  : %s @ %6.2fMHz - Arch %s" , tmp_prc->proc_number , tmp_prc->model_name , tmp_prc->cpu_mhz ,my_system.machine );
             gim_error->set( "gim_identity_obj::get" , message );
             n_processors = tmp_prc->proc_number + 1;
             tot_bogomips += tmp_prc->bogomips;
         }
         if ( n_processors > 1 ) {
             sprintf( message , "Cpu       : Total Bogomips [ %6.3f ]" , tot_bogomips );
             gim_error->set( "gim_identity_obj::get" , message );
         }
         sprintf( message , "Mem  detected  : Total :%s | Free :%s | Ratio %2.2f%%" , tot , disp , mi->ratio );
         gim_error->set( "gim_identity_obj::get" , message );
         get_fs_stat();
         sprintf( message , "Processor hostid : %04X" , host_id );
         gim_error->set( "gim_identity_obj::get" , message );
         gim_error->set( "gim_identity_obj::get" , "Getting identity...Done" );
     }
     else
         gim_error->set( GIM_ERROR_WARNING , "gim_identity_obj::get" , "Identity already filled" , __GIM_ERROR );
 }
References __GIM_ERROR, __GIM_NO, __GIM_YES, gim_processor_struct::bogomips, prsr_lexical_class::char_filter(), gim_processor_struct::cpu_mhz, gim_memory_struct::free, gim_error, GIM_ERROR_WARNING, gim_identity, gim_memory, Lexical, gim_memory_obj::metric_converter(), mi, gim_processor_struct::model_name, gim_processor_struct::next, gim_processor_struct::proc_number, processor, gim_memory_struct::ratio, gim_error_obj::set(), and gim_memory_struct::total.
home()
char * gim_identity_obj::home (void)
Method useful to get the home path.
Returns
the home path
Definition at line 361 of file gim_identity.cc.
{
     return Home;
 }
hostid()
long gim_identity_obj::hostid (void)
Method useful to know the processor hostid.
Returns
the hostid of the processor
Definition at line 373 of file gim_identity.cc.
{
     return host_id;
 }
login()
char * gim_identity_obj::login (void)
Method useful to get the login name.
Returns
the login name
Definition at line 348 of file gim_identity.cc.
{
     return Login;
 }
Referenced by gim_gkfp_obj::New(), and gim_gkdp_obj::New().
n_proc()
int gim_identity_obj::n_proc (void)
Method useful to know how many processor are in the system.
Returns
the architecture of the host
Definition at line 369 of file gim_identity.cc.
{
     return n_processors;
 }
node()
char * gim_identity_obj::node (void)
Use it to get the host name.
Returns
the host name
Definition at line 352 of file gim_identity.cc.
{
     return Node_name;
 }
Referenced by gim_gkfp_obj::New(), and gim_gkdp_obj::New().
version()
char * gim_identity_obj::version (void)
Method useful to get the running kernel version.
Returns
the running kernel version
Definition at line 357 of file gim_identity.cc.
{
     return Version;
 }
Member Data Documentation
mi
_gim_memory* gim_identity_obj::mi
A pointer to the informations about memory
Definition at line 126 of file gim_identity.h.
Referenced by get().
processor
_gim_processor* gim_identity_obj::processor
A pointer to the informations about processor
Definition at line 125 of file gim_identity.h.
Referenced by get().