My Project: Main Page
gim_log_obj Class Reference
Class used by Gim to analyze configuration file.
#include <gim_log.h>
Public Member Functions
void add_event (const char *t, const char *func, const char *mess, int val)
void add_event (pid_t cur_pid, const char *t, const char *func, const char *mess, int val)
_gim_log * add_log_system (const char *program_name, const char *log_file_name)
_gim_log * add_log_system (const char *program_name, const char *log_file_name, const char *log_path_name)
void addline (const char *t, const char *func, const char *mess, int val)
This method is used by Gim to add a line to the log.
void addline (pid_t cur_pid, const char *t, const char *func, const char *mess, int val)
void addline_format (const char *t, const char *func, const char *mess, int val)
void addline_format (pid_t cur_pid, const char *t, const char *func, const char *mess, int val)
gim_log_obj ()
_gim_flag is_open (void)
void start (void)
This method is necessary to Gim to start the log system.
void stop (void)
This method is used by Gim to stop the log system.
~gim_log_obj ()
Detailed Description
Class used by Gim to analyze configuration file.
Warning
It is not possible to use directly this class.
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
1.0-0
Date
2003-2007
Definition at line 118 of file gim_log.h.
Constructor & Destructor Documentation
gim_log_obj()
gim_log_obj::gim_log_obj () inline
The constructor
Definition at line 167 of file gim_log.h.
{
                 initialized = __GIM_NO;
                 enabled     = __GIM_NO;
                 log_fd = NULL;
             };
References __GIM_NO.
~gim_log_obj()
gim_log_obj::~gim_log_obj () inline
The destructor
Definition at line 175 of file gim_log.h.
{
                 if ( initialized == __GIM_YES ) {
                     if ( gim_error )
                         gim_error->set( "gim_log_obj::~gim_log_obj" , "Closing log on destructor" );
                     stop();
                 }
             };
References __GIM_YES, gim_error, gim_error_obj::set(), and stop().
Member Function Documentation
add_event() [1/2]
void gim_log_obj::add_event (const char * t, const char * func, const char * mess, int val)
add_event() [2/2]
void gim_log_obj::add_event (pid_t cur_pid, const char * t, const char * func, const char * mess, int val)
add_log_system() [1/2]
_gim_log * gim_log_obj::add_log_system (const char * program_name, const char * log_file_name)
Definition at line 313 of file gim_log.cc.
{
     return NULL;
 }
add_log_system() [2/2]
_gim_log * gim_log_obj::add_log_system (const char * program_name, const char * log_file_name, const char * log_path_name)
Definition at line 317 of file gim_log.cc.
{
     return NULL;
 }
addline() [1/2]
void gim_log_obj::addline (const char * t, const char * func, const char * mess, int val)
This method is used by Gim to add a line to the log.
Parameters
t It is the type of a message
func It is the name of coller function
mess The message to add
val The returned value for this message
Definition at line 120 of file gim_log.cc.
{
     if ( enabled ) {
         if ( initialized == __GIM_YES ) {
             if ( log_fd != NULL ) {
                 time_t  tp;
                 char    timestamp[256] , function[256];
                 time( &tp );
                 strftime( timestamp , 256 , "%A %x %H:%M:%S" , localtime ( &tp ) );
                 sprintf( function , "%s()" , func );
                 if ( Lexical.str_equal( strdup( t ) , strdup( GIM_ERROR_FATAL ) ) == __GIM_YES )
 //                  fprintf( log_fd , "%s %5d %s %s %-45s : %s\n" , debug_timer.get_usec() , syscall(SYS_gettid) , (syscall(SYS_gettid) != getpid())?"TH":"  " , __GIM_LOG_FATAL , Lexical.string_trunc( function , 48 ) , mess );
                     fprintf( log_fd , "%s %5d %s %s %-45s : %s\n" , debug_timer.get_usec() , syscall(SYS_gettid) , (syscall(SYS_gettid) != getpid())?"TH":"  " , __GIM_LOG_FATAL , Lexical.string_trunc( function , 48 ) , mess );
                 else
                     fprintf( log_fd , "%s %5d %s %s %-45s : %s\n" , debug_timer.get_usec() , syscall(SYS_gettid) , (syscall(SYS_gettid) != getpid())?"TH":"  " , t ,  Lexical.string_trunc( function , 48 ) , mess );
                 fflush( log_fd );
             }
             else {
                 gim_error->set( "gim_log_obj::addline" , 7 );
             }
         }
     }
 }
References __GIM_LOG_FATAL, __GIM_YES, debug_timer, gim_time_obj::get_usec(), gim_error, GIM_ERROR_FATAL, Lexical, gim_error_obj::set(), prsr_lexical_class::str_equal(), and prsr_lexical_class::string_trunc().
addline() [2/2]
void gim_log_obj::addline (pid_t cur_pid, const char * t, const char * func, const char * mess, int val)
Definition at line 144 of file gim_log.cc.
{
     if ( enabled ) {
         if ( initialized == __GIM_YES ) {
             if ( log_fd != NULL ) {
                 time_t  tp;
                 char    timestamp[256] , function[256];
                 time( &tp );
                 strftime( timestamp , 256 , "%A %x %H:%M:%S" , localtime ( &tp ) );
                 sprintf( function , "%s()" , func );
                 if ( Lexical.str_equal( strdup( t ) , strdup( GIM_ERROR_FATAL ) ) == __GIM_YES )
                     fprintf( log_fd , "%s %5d %s %s %-45s : %s\n" , debug_timer.get_usec() , cur_pid , (cur_pid!=getpid())?"TH":"  " , __GIM_LOG_FATAL , Lexical.string_trunc( function , 48 ) , mess );
                 else
                     fprintf( log_fd , "%s %5d %s %s %-45s : %s\n" , debug_timer.get_usec() , cur_pid , (cur_pid!=getpid())?"TH":"  " , t , Lexical.string_trunc( function , 48 ) , mess );
                 fflush( log_fd );
             }
             else {
                 gim_error->set( "gim_log_obj::addline" , 7 );
             }
         }
     }
 }
References __GIM_LOG_FATAL, __GIM_YES, debug_timer, gim_time_obj::get_usec(), gim_error, GIM_ERROR_FATAL, Lexical, gim_error_obj::set(), prsr_lexical_class::str_equal(), and prsr_lexical_class::string_trunc().
addline_format() [1/2]
void gim_log_obj::addline_format (const char * t, const char * func, const char * mess, int val)
Definition at line 167 of file gim_log.cc.
{
     if ( enabled ) {
         if ( initialized == __GIM_YES ) {
             if ( log_fd != NULL ) {
             }
             else {
                 gim_error->set( "gim_log_obj::addline_format" , 7 );
             }
             char tmp[1024];
             int c, len;
             strcpy( tmp , "" );
             for ( c = 0 , len = strlen( format ) ; c <= len ; c++ ) {
                 switch ( format[c] ) {
                     case '$' : {
                         switch ( format[++c] ) {
                             case 't' : {
                                 sprintf( tmp , "%s%s" , tmp , debug_timer.get_usec() );
                                 break;
                             }
                             case 'p' : {
                                 sprintf( tmp , "%s%5d" , tmp , syscall(SYS_gettid) );
                                 break;
                             }
                             case 'k' : {
                                 if ( Lexical.str_equal( strdup( t ) , strdup( GIM_ERROR_FATAL ) ) == __GIM_YES )
                                     sprintf( tmp , "%s%-4s" , tmp , __GIM_LOG_FATAL );
                                 else
                                     sprintf( tmp , "%s%-4s" , tmp , t );
                                 break;
                             }
                             case 'f' : {
                                 sprintf( tmp , "%s%s" , tmp , Lexical.string_trunc( (char *)func , 48 ) );
                                 break;
                             }
                             case 'm' : {
                                 sprintf( tmp , "%s%-45s" , tmp , mess );
                                 break;
                             }
                             case 'v' : {
                                 sprintf( tmp , "%s%3d" , tmp , val );
                                 break;
                             }
                             case 'T' : {
                                 sprintf( tmp , "%s%s" , tmp , (syscall(SYS_gettid) != getpid()) ? "TH" : "  " );
                                 break;
                             }
                             case '$' : {
                                 sprintf( tmp , "%s$" , tmp );
                                 break;
                             }
                             default : {
                                 gim_error->set( GIM_ERROR_WARNING , "gim_log_obj::addline_format" , "Unknow variable in DEBUG::debug_format value" , __GIM_NOT_OK );
                                 break;
                             }
                         }
                     }
                     case '_' : {
                         sprintf( tmp , "%s " , tmp );
                         break;
                     }
                     default : {
                         sprintf( tmp , "%s%c" , tmp , format[c] );
                         break;
                     }
                 }
             }
             fprintf( log_fd , "%s\n" , tmp );
             fflush( log_fd );
         }
     }
 }
References __GIM_LOG_FATAL, __GIM_NOT_OK, __GIM_YES, debug_timer, gim_time_obj::get_usec(), gim_error, GIM_ERROR_FATAL, GIM_ERROR_WARNING, Lexical, gim_error_obj::set(), prsr_lexical_class::str_equal(), and prsr_lexical_class::string_trunc().
Referenced by gim_error_obj::set().
addline_format() [2/2]
void gim_log_obj::addline_format (pid_t cur_pid, const char * t, const char * func, const char * mess, int val)
Definition at line 240 of file gim_log.cc.
{
     if ( enabled ) {
         if ( initialized == __GIM_YES ) {
             if ( log_fd != NULL ) {
             }
             else {
                 gim_error->set( "gim_log_obj::addline_format" , 7 );
             }
             char tmp[1024];
             int c, len;
             strcpy( tmp , "" );
             for ( c = 0 , len = strlen( format ) ; c <= len ; c++ ) {
                 switch ( format[c] ) {
                     case '$' : {
                         switch ( format[++c] ) {
                             case 't' : {
                                 sprintf( tmp , "%s%s" , tmp , debug_timer.get_usec() );
                                 break;
                             }
                             case 'p' : {
                                 sprintf( tmp , "%s%5d" , tmp , syscall(SYS_gettid) );
                                 break;
                             }
                             case 'k' : {
                                 if ( Lexical.str_equal( strdup( t ) , strdup( GIM_ERROR_FATAL ) ) == __GIM_YES )
                                     sprintf( tmp , "%s%-4s" , tmp , __GIM_LOG_FATAL );
                                 else
                                     sprintf( tmp , "%s%-4s" , tmp , t );
                                 break;
                             }
                             case 'f' : {
                                 sprintf( tmp , "%s%s" , tmp , Lexical.string_trunc( (char *)func , 48 ) );
                                 break;
                             }
                             case 'm' : {
                                 sprintf( tmp , "%s%-45s" , tmp , mess );
                                 break;
                             }
                             case 'v' : {
                                 sprintf( tmp , "%s%3d" , tmp , val );
                                 break;
                             }
                             case 'T' : {
                                 sprintf( tmp , "%s%s" , tmp , (cur_pid!=getpid())?"TH":"  "  );
                                 break;
                             }
                             case '$' : {
                                 sprintf( tmp , "%s$" , tmp );
                                 break;
                             }
                             default : {
                                 gim_error->set( GIM_ERROR_WARNING , "gim_log_obj::addline_format" , "Unknow variable in DEBUG::debug_format value" , __GIM_NOT_OK );
                                 break;
                             }
                         }
                     }
                     case '_' : {
                         sprintf( tmp , "%s " , tmp );
                         break;
                     }
                     default : {
                         sprintf( tmp , "%s%c" , tmp , format[c] );
                         break;
                     }
                 }
             }
             fprintf( log_fd , "%s\n" , tmp );
             fflush( log_fd );
         }
     }
 }
References __GIM_LOG_FATAL, __GIM_NOT_OK, __GIM_YES, debug_timer, gim_time_obj::get_usec(), gim_error, GIM_ERROR_FATAL, GIM_ERROR_WARNING, Lexical, gim_error_obj::set(), prsr_lexical_class::str_equal(), and prsr_lexical_class::string_trunc().
is_open()
_gim_flag gim_log_obj::is_open (void)
Definition at line 321 of file gim_log.cc.
{
     if ( log_fd == NULL )
         return __GIM_NO;
     else
         return __GIM_YES;
 }
References __GIM_NO, and __GIM_YES.
Referenced by gim_error_obj::set().
start()
void gim_log_obj::start (void)
This method is necessary to Gim to start the log system.
Definition at line 42 of file gim_log.cc.
{
     char message[256];
     if ( ! initialized ) {
 //      gim_error->Set( "gim_log_obj::start" , "[" ,
         if ( __GIM_LOG_FORCE == __GIM_YES ) {
             log_fd = fopen ( __GIM_LOG_FILENAME , "wb" );
             if ( log_fd == NULL ) {
                 gim_error->set( "gim_log_obj::start" , 6 );
             }
             else {
                 initialized = __GIM_YES;
                 enabled = __GIM_YES;
                 debug_timer.start_usec();
                 strcpy( format , "|$t|$p|$k_$f_|_$m" );
                 gim_error->set( "gim_log_obj::start" , "Start before configuration file due __GIM_LOG_FORCE" );
                 sprintf( message , "File log start on %s" , debug_timer.date() );
                 gim_error->set( "gim_log_obj::start" , message );
                 gim_error->set( "gim_log_obj::start" , "This log use a standard format [ |$t|$p|$k_$f_|_$m ] due __GIM_LOG_FORCE" );
             }
         }
         if ( __GIM_LOG_FORCE == __GIM_NO ) {
             if ( ! enabled ) {
                 if ( gim_conf->prsr_obj != NULL ) {
                     IF_EXIST_KEY_IN_CONF( "debug" , "f_debug" ) {
                         enabled = gim_conf->GetKeyFLAG( "debug" , "f_debug" );
                     }
                     IF_EXIST_KEY_IN_CONF( "DEBUG" , "debug_format" ) {
                         strcpy( format , gim_conf->GetKeySTR( "DEBUG" , "debug_format" ) );
                     }
                     else {
                         gim_error->set( GIM_ERROR_CRITICAL , "gim_log_obj::addline_format" , "Format NOT present in configuration file" , __GIM_ERROR );
                     }
                 }
                 else {
                     gim_error->set( GIM_ERROR_WARNING , "gim_log_obj::start" , "I cannot start the File debug in gim " , -1 );
                     gim_error->set( GIM_ERROR_WARNING , "gim_log_obj::start" , "    'cause the gim.conf was not loaded " , -1 );
                 }
             }
             if ( enabled ) {
                 log_fd = fopen ( gim_conf->GetKeySTR( "debug" , "f_debug_file" ) , "wb" );
                 if ( log_fd == NULL ) {
                     gim_error->set( "gim_log_obj::start" , 6 );
                 }
                 else {
                     initialized = __GIM_YES;
                     debug_timer.start_usec();
                     gim_error->set( "gim_log_obj::start" , 3 );
                     sprintf( message , "File log start on %s" , debug_timer.date() );
                     gim_error->set( "gim_log_obj::start" , message );
                     gim_error->set( "gim_log_obj::start" , gim_version() );
                 }
             }
         }
     }
     else {
         gim_error->set( GIM_ERROR_WARNING , "gim_log_obj::start" , "The timer is already initialized" , __GIM_OK );
     }
 }
References __GIM_ERROR, __GIM_LOG_FILENAME, __GIM_LOG_FORCE, __GIM_NO, __GIM_OK, __GIM_YES, gim_time_obj::date(), debug_timer, gim_prsr_obj::GetKeyFLAG(), gim_prsr_obj::GetKeySTR(), gim_conf, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, gim_version(), IF_EXIST_KEY_IN_CONF, gim_error_obj::set(), and gim_time_obj::start_usec().
stop()
void gim_log_obj::stop (void)
This method is used by Gim to stop the log system.
Definition at line 102 of file gim_log.cc.
{
     if ( enabled ) {
         if ( initialized == __GIM_YES ) {
             if ( log_fd != NULL ) {
                 if ( gim_error ) gim_error->set( "gim_log_obj::stop" , 4 );
                 fflush ( log_fd );
                 fclose ( log_fd );
                 log_fd = NULL;
                 initialized = __GIM_NO;
             }
             else {
                 if ( gim_error ) gim_error->set( "gim_log_obj::stop" , 5 );
             }
         }
     }
 }
References __GIM_NO, __GIM_YES, gim_error, and gim_error_obj::set().
Referenced by ~gim_log_obj().