My Project: Main Page
gim_gkdp_obj Class Reference
Generic Information Manager Documentation gkfp object
GKP - GKript Package
With this class you can create, open and use only GKDP file and you are not able to manage GKFP files
GKDP - GKript Data Packaged
GKFP - GKript File Packaged
.
#include <gim.h>
Public Member Functions
void close (void)
gim_gkdp_obj ()
void leave (_gim_gkdp *gkdp)
void New (const char *filename, _gim_flag crypt)
void new_path (const char *path_in)
void open (const char *filename)
void set_password (const char *passwd)
With this method you can set a password in a GKDP file.
void set_prg (const char *prg_name, _gim_Uint8 major, _gim_Uint8 minor, _gim_Uint8 subminor)
_gim_gkdp * take (const char *name)
_gim_flag tmp_extract (_gim_gkdp *to_extract, const char *path)
With this method you can extract an item (file) physically on the disk at the specified path.
void write (void)
virtual ~gim_gkdp_obj ()
Detailed Description
Generic Information Manager Documentation gkfp object
GKP - GKript Package
With this class you can create, open and use only GKDP file and you are not able to manage GKFP files
GKDP - GKript Data Packaged
GKFP - GKript File Packaged
.
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
2.0-0
Date
2003-2008
Definition at line 417 of file gim.h.
Constructor & Destructor Documentation
gim_gkdp_obj()
gim_gkdp_obj::gim_gkdp_obj () inline
gim_gkdp_obj constructor
Definition at line 585 of file gim.h.
{
                 crypt       = new gim_cryptography_obj;
                 __GIM_CLEAR( file_name , 256  , char );
                 hand = NULL;
                 __GIM_CLEAR( &header  , 1   , gim_file_header_struct );
                 __GIM_CLEAR( &verify  , 1   , gim_file_header_verify );
                 header.gim_major = GIM_MAJOR;
                 header.gim_minor = GIM_MINOR;
                 header.gim_subminor = (_gim_Uint16)GIM_SUBMINOR;
                 init();
             };
References __GIM_CLEAR, gim_file_header_struct::gim_major, GIM_MAJOR, gim_file_header_struct::gim_minor, GIM_MINOR, gim_file_header_struct::gim_subminor, and GIM_SUBMINOR.
~gim_gkdp_obj()
virtual gim_gkdp_obj::~gim_gkdp_obj () inline virtual
gim_gkdp_obj destructor
Definition at line 600 of file gim.h.
{
                 delete crypt;
                 release();
             };
Member Function Documentation
close()
void gim_gkdp_obj::close (void)
Definition at line 352 of file gim.cc.
{
     char message[256];
     sprintf( message , "Closing GKDP file [%s]" , hand->name );
     gim_error->set( "gim_gkp_obj::gkdp_close" , message );
     gim_file_manager->close( hand );
     __GIM_CLEAR( &(header) , 1 , gim_file_header_struct );
     destroy();
     gim_error->set( "gim_gkp_obj::close" , "Closed" );
 }
References __GIM_CLEAR, gim_file_manager_obj::close(), gim_error, gim_file_manager, gim_global_item_handler::name, and gim_error_obj::set().
leave()
void gim_gkdp_obj::leave (_gim_gkdp * gkdp)
Definition at line 391 of file gim.cc.
{
     char message[256];
     _gim_gkp_flist * currentlist = lget();
     for( currentlist = next( currentlist ) ; currentlist != NULL ; currentlist = next( currentlist ) ) {
         if ( Lexical.str_equal( gkdp->name , currentlist->name ) == __GIM_YES ) {
             if ( currentlist->buffer != NULL ) {
                 gim_memory->Free( currentlist->buffer );
                 currentlist->buffer = NULL;
                 gim_memory->Free( gkdp );
                 sprintf( message , "File GKP::%s left" , currentlist->name );
                 gim_error->set( "gim_gkp_obj::leave" , message );
             }
         }
     }
 }
References __GIM_YES, gim_file_list_struct::buffer, gim_memory_obj::Free(), gim_error, gim_memory, Lexical, gim_file_list_struct::name, gim_gkdp_data_struct::name, gim_error_obj::set(), and prsr_lexical_class::str_equal().
New()
void gim_gkdp_obj::New (const char * filename, _gim_flag crypt)
Definition at line 294 of file gim.cc.
{
     strcpy( header.title , __GKP_TITLE_DATA );
     strcpy( file_name , filename );
     strcpy( header.user , gim_identity->login() );
     strcpy( header.hostname , gim_identity->node() );
     header.recursive = __GIM_NO;
     header.crypt = crypt;
     header.compression = __GIM_NO;
     header.hashed_file = __GIM_NO;
     header.xhk = __GIM_NO;
 }
References __GIM_NO, __GKP_TITLE_DATA, gim_file_header_struct::compression, gim_file_header_struct::crypt, gim_identity, gim_file_header_struct::hashed_file, gim_file_header_struct::hostname, gim_identity_obj::login(), gim_identity_obj::node(), gim_file_header_struct::recursive, gim_file_header_struct::title, gim_file_header_struct::user, and gim_file_header_struct::xhk.
new_path()
void gim_gkdp_obj::new_path (const char * path_in)
Definition at line 307 of file gim.cc.
{
     header.members = make_gkdp( path_in );
 }
References gim_file_header_struct::members.
open()
void gim_gkdp_obj::open (const char * filename)
Definition at line 330 of file gim.cc.
{
     char message[1024];
     strcpy( file_name , filename );
     hand = gim_file_manager->open( filename , __GIM_FILE_MAPPING , __GIM_READ );
     if ( hand == NULL ) {
         gim_error->set( GIM_ERROR_FATAL , "gim_gkp_obj::open" , "GKP data file not found" , __GIM_ERROR );
     }
     _gim_map map = hand->fm;
     map = hread( map );
     sprintf( message , "Calculated : %s" , gim_checksum->md5( (char *)&(header) , sizeof( gim_file_header_struct) ) );
     gim_error->set( "gim_gkp_obj::open" , message );
     sprintf( message , "Readed     : %s" , verify.hash );
     gim_error->set( "gim_gkp_obj::open" , message );
     if ( Lexical.str_equal( verify.hash , gim_checksum->md5( (char *)&(header) , sizeof( gim_file_header_struct) ) ) != __GIM_YES ) {
         gim_file_manager->close( hand );
         gim_error->set( GIM_ERROR_FATAL , "gim_gkp_obj::open" , "Gkp file header corrupted." , __GIM_ERROR );
     }
     map = lread( map );
     read_gkdp( map );
 }
References __GIM_ERROR, __GIM_FILE_MAPPING, __GIM_READ, __GIM_YES, gim_file_manager_obj::close(), gim_global_item_handler::fm, gim_checksum, gim_error, GIM_ERROR_FATAL, gim_file_manager, gim_file_header_verify::hash, Lexical, gim_checksum_obj::md5(), gim_file_manager_obj::open(), gim_error_obj::set(), and prsr_lexical_class::str_equal().
set_password()
void gim_gkdp_obj::set_password (const char * passwd)
With this method you can set a password in a GKDP file.
Parameters
passwd The password to set
Definition at line 407 of file gim.cc.
{
     if ( passwd != NULL ) {
         crypt->set( passwd );
         gim_error->set( "gim_gkdp_obj::set_password" , "A new password succesfully setted" );
     }
     else {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_gkdp_obj::set_password" , "You cannot pass NULL to this function" , __GIM_ERROR );
     }
 }
References __GIM_ERROR, gim_error, GIM_ERROR_CRITICAL, gim_password_obj::set(), and gim_error_obj::set().
set_prg()
void gim_gkdp_obj::set_prg (const char * prg_name, _gim_Uint8 major, _gim_Uint8 minor, _gim_Uint8 subminor)
Definition at line 284 of file gim.cc.
{
     strcpy( header.program , prg_name );
     header.major = major;
     header.minor = minor;
     header.built = subminor;
 }
References gim_file_header_struct::built, gim_file_header_struct::major, gim_file_header_struct::minor, and gim_file_header_struct::program.
take()
_gim_gkdp * gim_gkdp_obj::take (const char * name)
Definition at line 363 of file gim.cc.
{
     char message[256];
     if ( name == NULL )
         gim_error->set( GIM_ERROR_CRITICAL , "gim_gkp_obj::gkdp_take" , "You cannot take a NULL name" , __GIM_ERROR );
     for( currentlist = startlist->link ; currentlist != NULL ; currentlist = currentlist->link ) {
         if ( Lexical.str_equal( name , currentlist->name ) == __GIM_YES ) {
             _gim_gkdp * gkdp = (_gim_gkdp *)gim_memory->Alloc( sizeof( _gim_gkdp ) , __GIM_MEM_GKDP_TAKE , __GIM_HIDE );
             strcpy( gkdp->name , currentlist->name );
             currentlist->buffer = (_gim_buffer)gim_memory->Alloc( currentlist->size , __GIM_MEM_GKDP_TAKE , __GIM_HIDE );
             memcpy( currentlist->buffer , currentlist->handle , currentlist->size );
             gkdp->data = currentlist->buffer;
             gkdp->size = currentlist->size;
             if ( header.crypt == __GIM_FOG ) {
                 crypt->set_secondary( currentlist->name );
                 crypt->advanced_password( gkdp->data , gkdp->size );
             }
             gkdp->size--;
             sprintf( message , "File GKP::%s taken" , gkdp->name );
             gim_error->set( "gim_gkp_obj::gkdp_take" , message );
             return gkdp;
         }
     }
     sprintf( message , "File GKP::%s not found" , name );
     gim_error->set( GIM_ERROR_CRITICAL , "gim_gkp_obj::gkdp_take" , message , __GIM_ERROR );
     return NULL;
 }
References __GIM_ERROR, __GIM_FOG, __GIM_HIDE, __GIM_MEM_GKDP_TAKE, __GIM_YES, gim_cryptography_obj::advanced_password(), gim_memory_obj::Alloc(), gim_file_list_struct::buffer, gim_file_header_struct::crypt, gim_gkdp_data_struct::data, gim_error, GIM_ERROR_CRITICAL, gim_memory, gim_file_list_struct::handle, Lexical, gim_file_list_struct::link, gim_file_list_struct::name, gim_gkdp_data_struct::name, gim_error_obj::set(), gim_password_obj::set_secondary(), gim_file_list_struct::size, gim_gkdp_data_struct::size, and prsr_lexical_class::str_equal().
tmp_extract()
_gim_flag gim_gkdp_obj::tmp_extract (_gim_gkdp * to_extract, const char * path)
With this method you can extract an item (file) physically on the disk at the specified path.
Parameters
to_extract The _gim_gkdp obj you want to extract.
path The path where you want to extract the item.
Returns
__GIM_OK on success or __GIM_NOT_OK if fail.
Definition at line 418 of file gim.cc.
{
     char            message[256] , AbsoluteFileName[2048];
     _gim_handler    *hand;
     if ( to_extract == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_gkdp_obj::tmp_extract" , "You cannot extract a NULL item" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( path == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_gkdp_obj::tmp_extract" , "Path cannot be NULL" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     sprintf( AbsoluteFileName , "%s%s" , path , to_extract->name );
     sprintf( message , "Item GKP::%s is ready to extract in %s" , to_extract->name , path );
     gim_error->set( "gim_gkdp_obj::tmp_extract::gkdp_take" , message );
     hand = gim_file_manager->open( AbsoluteFileName , __GIM_FILE_POINTER , __GIM_WRITE );
     if ( hand == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_gkdp_obj::tmp_extract" , "Error in opening file for writing" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     gim_file_manager->flush( hand , to_extract->data , to_extract->size );
     gim_file_manager->close( hand );
     sprintf( message , "Item GKP::%s succesfully extracted" , to_extract->name );
     gim_error->set( "gim_gkdp_obj::tmp_extract::gkdp_take" , message );
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_FILE_POINTER, __GIM_NOT_OK, __GIM_OK, __GIM_WRITE, gim_file_manager_obj::close(), gim_gkdp_data_struct::data, gim_file_manager_obj::flush(), gim_error, GIM_ERROR_CRITICAL, gim_file_manager, gim_gkdp_data_struct::name, gim_file_manager_obj::open(), gim_error_obj::set(), and gim_gkdp_data_struct::size.
write()
void gim_gkdp_obj::write (void)
Definition at line 312 of file gim.cc.
{
     if ( ! strlen( file_name ) ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_gkp_obj::write" , "New file not yet setted. I don't write anything" , __GIM_NOT_OK );
     }
     else {
         _gim_handler * out = gim_file_manager->open( file_name , __GIM_FILE_POINTER , __GIM_WRITE );
         if ( out == NULL ) {
             gim_error->set( GIM_ERROR_FATAL , "gim_gkp_obj::write" , "Is not possible to write on disk" , __GIM_ERROR );
         }
         hwrite( out );
         lwrite( out );
         write_gkdp( out );
         gim_file_manager->close( out );
         gim_error->set( "gim_gkp_obj::write" , "New GKP file wrote" );
     }
 }
References __GIM_ERROR, __GIM_FILE_POINTER, __GIM_NOT_OK, __GIM_WRITE, gim_file_manager_obj::close(), gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_FATAL, gim_file_manager, gim_file_manager_obj::open(), and gim_error_obj::set().