My Project: Main Page
gim_gkfp_obj Class Reference
Generic Information Manager Documentation gkfp object
GKP - GKript Package
With this class you can create, open and use only GKFP file and you are not able to manage GKDP files
GKDP - GKript Data Packaged
GKFP - GKript File Packaged
.
#include <gim.h>
Public Member Functions
void Extract (const char *filename)
_gim_flag extract_data (_gim_gkp_flist *startlist)
gim_gkfp_obj ()
void lclear (void)
_gim_gkp_flist * lget (void)
_gim_Uint32 lmake (const char *dir_name, _gim_Uint16 level)
_gim_gkp_flist * lnext (_gim_gkp_flist *tmplist)
_gim_map lread (_gim_map map)
void lwrite (_gim_handler *out)
void New (const char *filename, _gim_flag recursion, _gim_flag crypt, _gim_flag compress, _gim_flag hash)
_gim_Ulong New_path (const char *path_in)
void New_root (const char *path_in)
_gim_map Open (const char *filename)
_gim_flag read_data (_gim_map map, _gim_gkp_flist *startlist)
void set_password (const char *passwd)
With this method you can set a password in a GKDP file.
void Set_prg (const char *prg_name, _gim_Uint8 major, _gim_Uint8 minor, _gim_Uint8 subminor)
_gim_flag Write (void)
_gim_flag write_data (_gim_handler *out, _gim_gkp_flist *startlist)
~gim_gkfp_obj ()
Public Attributes
gim_cryptography_obj * crypt
gim_file_header_struct header
gim_file_header_verify verify
Detailed Description
Generic Information Manager Documentation gkfp object
GKP - GKript Package
With this class you can create, open and use only GKFP file and you are not able to manage GKDP files
GKDP - GKript Data Packaged
GKFP - GKript File Packaged
.
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Corrado Tumiati - skyma.nosp@m.trix.nosp@m.@gkri.nosp@m.pt.o.nosp@m.rg
Version
2.0-0
Date
2003-2008
Examples
gkfp.cc.
Definition at line 282 of file gim.h.
Constructor & Destructor Documentation
gim_gkfp_obj()
gim_gkfp_obj::gim_gkfp_obj () inline
Definition at line 390 of file gim.h.
{
                 __GIM_CLEAR( file_name , 256  , char );
                 __GIM_CLEAR( &header  , 1   , gim_file_header_struct );
                 header.gim_major = GIM_MAJOR;
                 header.gim_minor = GIM_MINOR;
                 header.gim_subminor = (_gim_Uint16)GIM_SUBMINOR;
                 hand            = NULL;
                 linit();
                 crypt           = new gim_cryptography_obj;
             };
References __GIM_CLEAR, crypt, gim_file_header_struct::gim_major, GIM_MAJOR, gim_file_header_struct::gim_minor, GIM_MINOR, gim_file_header_struct::gim_subminor, GIM_SUBMINOR, and header.
~gim_gkfp_obj()
gim_gkfp_obj::~gim_gkfp_obj () inline
Definition at line 401 of file gim.h.
{
                 delete  crypt;
                 lrelease();
             };
References crypt.
Member Function Documentation
Extract()
void gim_gkfp_obj::Extract (const char * filename)
Examples
gkfp.cc.
Definition at line 529 of file gim.cc.
{
     strcpy( file_name , filename );
     hand = gim_file_manager->open( filename , __GIM_FILE_MAPPING , __GIM_READ );
     if ( hand == NULL ) {
         gim_error->set( GIM_ERROR_FATAL , "gim_gkfp_obj::open" , "GKFP file not found" , __GIM_ERROR );
     }
     _gim_map map = hand->fm;
     map = hread( map );
     if ( Lexical.str_equal( verify.hash , gim_checksum->md5( (char *)&(header) , sizeof( gim_file_header_struct) ) ) != __GIM_YES ) {
         gim_file_manager->close( hand );
         gim_error->set( GIM_ERROR_FATAL , "gim_gkfp_obj::open" , "GKFP file header corrupted." , __GIM_ERROR );
     }
     map = lread( map );
     read_data( map , lget() );
     extract_data( lget() );
 }
References __GIM_ERROR, __GIM_FILE_MAPPING, __GIM_READ, __GIM_YES, gim_file_manager_obj::close(), extract_data(), gim_global_item_handler::fm, gim_checksum, gim_error, GIM_ERROR_FATAL, gim_file_manager, gim_file_header_verify::hash, header, Lexical, lget(), lread(), gim_checksum_obj::md5(), gim_file_manager_obj::open(), read_data(), gim_error_obj::set(), prsr_lexical_class::str_equal(), and verify.
extract_data()
_gim_flag gim_gkfp_obj::extract_data (_gim_gkp_flist * startlist)
Definition at line 155 of file gim_gkfp_file_data.cc.
{
     _gim_gkp_flist  * currentlist = NULL;
     _gim_gkp_chunk  chunk;
     _gim_buffer     data = NULL;
     char            message[256] , tname[1024];
     char            TmpFileName[2048];
     gim_utils_obj   * util = new gim_utils_obj;
     char            * path_tmp;
     int             len;
     for( currentlist = startlist ; currentlist != NULL ; currentlist = currentlist->link ) {
         switch ( currentlist->type ) {
             case ROOT : {
                 if ( strlen( new_root ) != 0 ) {
                     //printf("Root - %s..." , new_root );
                     mkdir( new_root , currentlist->stat.st_mode );
                     //puts( "Created" );
                 }
                 else {
                     //printf("Root - %s..." , currentlist->name );
                     mkdir( currentlist->name , currentlist->stat.st_mode );
                     //puts( "Created" );
                 }
                 break;
             }
             case REGFILE    :
             case EMPTY      : {
                 _gim_handler * file;
                 gim_interface->data->dst_ratio = (float)( (float)currentlist->id / (float)endlist->id );
                 sprintf( message , "Cur id : %d  |  end id : %d  |  dst_ratio %f" , currentlist->id , endlist->id , gim_interface->data->dst_ratio );
                 gim_error->set( "gim_gkfp_obj::extract_data" , message );
                 sprintf( tname , "%s%s" , currentlist->path , currentlist->name ) ;
                 if ( internal_gim->get_state() == __GIM_TH_STOP )
                     return __GIM_NOT_OK;
                 sprintf( TmpFileName , "%s%s" , currentlist->path , currentlist->name );
                 if ( strlen( new_root ) != 0 ) {
                     char m[2048];
                     //printf( " tmpfilename before : %s\n after : %s\n" , TmpFileName , util->str_subtraction( TmpFileName , old_root ) );
                     sprintf( m , "%s%s" , new_root , util->str_subtraction( TmpFileName , old_root ) );
                     strcpy( TmpFileName , m );
 //                  printf( " tmpfilename : %s\n" , TmpFileName );
                 }
                 file = gim_file_manager->open( TmpFileName , __GIM_FILE_POINTER , __GIM_WRITE );
                 if ( file == NULL ) {
                     sprintf( message , "Cannot open %s for writing" , TmpFileName );
                     gim_error->set( GIM_ERROR_FATAL , "gim_gkfp_obj::extract_data" , message , __GIM_ERROR );
                 }
                 if ( header.crypt == __GIM_SUN ) {
                     gim_file_manager->flush( file , currentlist->handle , currentlist->size );
                 }
                 if ( header.crypt == __GIM_FOG ) {
                     sprintf( gim_interface->data->item_dst_name , "%s" , currentlist->name );
                     sprintf( gim_interface->data->item_dna_name , "Loading" );
                     currentlist->buffer = (_gim_buffer)gim_memory->Alloc( currentlist->size * sizeof( char ) );
                     memcpy( currentlist->buffer , currentlist->handle , currentlist->size );
                     crypt->set_secondary( currentlist->name );
                     sprintf( gim_interface->data->item_dst_name , "%s" , currentlist->name );
                     sprintf( gim_interface->data->item_dna_name , "Crypting" );
                     crypt->advanced_password( currentlist->buffer , currentlist->size );
                     if ( internal_gim->get_state() == __GIM_TH_STOP ) return __GIM_NOT_OK;
                     sprintf( gim_interface->data->item_dst_name , "%s" , currentlist->name );
                     sprintf( gim_interface->data->item_dna_name , "Flushing" );
                     if ( internal_gim->get_state() == __GIM_TH_STOP ) return __GIM_NOT_OK;
                     gim_file_manager->flush( file , currentlist->buffer , currentlist->size );
                     gim_memory->Unlock_and_free( currentlist->buffer );
                 }
                 gim_file_manager->close( file );
                 chmod( TmpFileName , currentlist->stat.st_mode );
                 break;
             }
             case REGNODE    : {
                 //~ sprintf( TmpFileName , "%s%s" , currentlist->path , currentlist->name );
                 //~ printf("Node  - CREATE  -  %s\n" , TmpFileName );
                 sprintf( TmpFileName , "%s%s" , currentlist->path , currentlist->name );
                 if ( strlen( new_root ) != 0 ) {
                     char m[2048];
                     //printf( " tmpfilename before : %s\n after : %s\n" , TmpFileName , util->str_subtraction( TmpFileName , old_root ) );
                     sprintf( m , "%s%s/" , new_root , util->str_subtraction( TmpFileName , old_root ) );
                     strcpy( TmpFileName , m );
                     //printf( " tmpfilename : %s\n" , TmpFileName );
                 }
 //              sprintf( TmpFileName , "%s%s" , currentlist->path , currentlist->name );
                 mkdir( TmpFileName , currentlist->stat.st_mode );
                 break;
             }
             case LINK : {
                 //~ sprintf( TmpFileName , "%s%s" , currentlist->path , currentlist->name );
                 //~ printf("Link  - SKIPPED - %s\n" , TmpFileName );
                 break;
             }
             case BLK : {
                 break;
             }
             case FIFO : {
                 break;
             }
             case CHR : {
                 break;
             }
             case SOCK : {
                 break;
             }
             case UNKNOWN : {
                 break;
             }
             default: {
             }
         }
     }
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_FILE_POINTER, __GIM_FOG, __GIM_NOT_OK, __GIM_OK, __GIM_SUN, __GIM_TH_STOP, __GIM_WRITE, gim_cryptography_obj::advanced_password(), gim_memory_obj::Alloc(), BLK, gim_file_list_struct::buffer, CHR, gim_file_manager_obj::close(), gim_file_header_struct::crypt, crypt, gim_interface_data::dst_ratio, EMPTY, FIFO, gim_file_manager_obj::flush(), gim_obj::get_state(), gim_error, GIM_ERROR_FATAL, gim_file_manager, gim_interface, gim_memory, gim_file_list_struct::handle, header, gim_file_list_struct::id, internal_gim, gim_interface_data::item_dna_name, gim_interface_data::item_dst_name, LINK, gim_file_list_struct::link, gim_file_list_struct::name, gim_file_manager_obj::open(), gim_file_list_struct::path, REGFILE, REGNODE, ROOT, gim_error_obj::set(), gim_password_obj::set_secondary(), gim_file_list_struct::size, SOCK, gim_file_list_struct::stat, gim_utils_obj::str_subtraction(), gim_file_list_struct::type, UNKNOWN, and gim_memory_obj::Unlock_and_free().
Referenced by Extract().
lclear()
void gim_gkfp_obj::lclear (void)
Definition at line 250 of file gim_gkfp_file_list.cc.
{
     ldestroy();
 }
lget()
_gim_gkp_flist * gim_gkfp_obj::lget (void)
Definition at line 205 of file gim_gkfp_file_list.cc.
{
     if ( startlist != NULL )
         return startlist;
     else {
         gim_error->set( GIM_ERROR_FATAL , "gim_gkfp_file_list_obj::get" , "No file list" , __GIM_ERROR );
         return NULL;
     }
 }
References __GIM_ERROR, gim_error, GIM_ERROR_FATAL, and gim_error_obj::set().
Referenced by Extract(), Open(), and Write().
lmake()
_gim_Uint32 gim_gkfp_obj::lmake (const char * dir_name, _gim_Uint16 level)
Definition at line 46 of file gim_gkfp_file_list.cc.
{
     struct dirent   ** eps;
     int             n , cnt;
     char            TmpFileName[1024];
     char            message[256];
     n = scandir ( dir_name , &eps , NULL , alphasort );
     if ( n ) {
         if ( level == __GIM_ROOT ) {
             sprintf( message , "Adding root %s" , dir_name );
             gim_error->set( "gim_gkfp_file_list_obj::make" , message );
             currentlist = ladd();
             strcpy( currentlist->path , "" );
             strcpy( currentlist->name , dir_name );
             currentlist->size = 0;
             currentlist->type = ROOT;
             stat( dir_name , &( currentlist->stat ) );
         }
         gim_interface->data->sou_size += n;
         for ( cnt = 0 ; cnt < n ; cnt++ ) {
             struct stat tmp;
             sprintf( TmpFileName , "%s%s" , dir_name , eps[cnt]->d_name );
             if ( ( ! strcmp( "." , eps[cnt]->d_name ) ) || ( ! strcmp( ".." , eps[cnt]->d_name ) ) )
                 continue;
             if ( stat( TmpFileName , &tmp ) )
                 continue;
             switch ( eps[cnt]->d_type ) {
                 case DT_REG : {
                     __GIM_CLEAR( message , 256 , char );
                     currentlist = ladd( );
                     gim_interface->data->sou_position = endlist->id;
                     sprintf( TmpFileName , "%s%s" , dir_name , eps[cnt]->d_name );
                     __GIM_CLEAR( currentlist->name , 256 , char );
                     strcpy( currentlist->name , eps[cnt]->d_name );
                     strcpy( currentlist->path , dir_name );
                     if ( gim_file_manager->length( TmpFileName ) != 0 ) {
                         currentlist->type = REGFILE;
                         currentlist->size = gim_file_manager->length( TmpFileName );
                         if ( header.hashed_file == __GIM_YES )
                             strcpy( currentlist->hash , gim_checksum->sha1( TmpFileName ) );
                         sprintf( message , "Added regular file %s..." , eps[cnt]->d_name );
                     }
                     else {
                         currentlist->type = EMPTY;
                         currentlist->size = 0;
                         sprintf( message , "Added empty regular file %s..." , eps[cnt]->d_name );
                     }
                     stat( TmpFileName , &( currentlist->stat ) );
                     gim_error->set( "gim_gkfp_file_list_obj::make" , message );
                     break;
                 }
                 case DT_DIR : {
                     currentlist = ladd( );
                     gim_interface->data->sou_position = endlist->id;
                     sprintf( TmpFileName , "%s%s/" , dir_name , eps[cnt]->d_name );
                     __GIM_CLEAR( currentlist->name , 256 , char );
                     strcpy( currentlist->name , eps[cnt]->d_name );
                     strcpy( currentlist->path , dir_name );
                     currentlist->type = REGNODE;
                     stat( TmpFileName , &( currentlist->stat ) );
                     sprintf( message , "Added regular node %s..." , eps[cnt]->d_name );
                     gim_error->set( "gim_gkfp_file_list_obj::make" , message );
                     sprintf( message , "%s" , TmpFileName );
                     gim_error->set( "gim_gkfp_file_list_obj::make" , message );
                     if ( header.recursive == __GIM_YES )
                         lmake( TmpFileName , level + 1 );
                     break;
                 }
                 case DT_LNK : {
                     currentlist = ladd( );
                     gim_interface->data->sou_position = endlist->id;
                     sprintf( TmpFileName , "%s%s" , dir_name , eps[cnt]->d_name );
                     strcpy( currentlist->name , eps[cnt]->d_name );
                     strcpy( currentlist->path , dir_name );
                     currentlist->type = LINK;
                     lstat( TmpFileName , &( currentlist->stat ) );
                     sprintf( message , "Added link %s..." , eps[cnt]->d_name );
                     gim_error->set( "gim_gkfp_file_list_obj::make" , message );
                     break;
                 }
                 case DT_BLK : {
                     sprintf( message , "Skipped Block file %s..." , eps[cnt]->d_name );
                     gim_error->set( "gim_gkfp_file_list_obj::make" , message );
                     break;
                 }
                 case DT_FIFO : {
                     sprintf( message , "Skipped Fifo file %s..." , eps[cnt]->d_name );
                     gim_error->set( "gim_gkfp_file_list_obj::make" , message );
                     break;
                 }
                 case DT_CHR : {
                     sprintf( message , "Skipped Character file %s..." , eps[cnt]->d_name );
                     gim_error->set( "gim_gkfp_file_list_obj::make" , message );
                     break;
                 }
                 case DT_SOCK : {
                     sprintf( message , "Skipped Socket file %s..." , eps[cnt]->d_name );
                     gim_error->set( "gim_gkfp_file_list_obj::make" , message );
                     break;
                 }
                 case DT_UNKNOWN : {
                     sprintf( message , "Skipped UNKNOWN file %s..." , eps[cnt]->d_name );
                     gim_error->set( "gim_gkfp_file_list_obj::make" , message );
                     break;
                 }
             }
         }
     }
     if ( n <= 0 ) gim_error->set( GIM_ERROR_CRITICAL , "gim_gkfp_file_list_obj::make" , "Couldn't open the directory" , __GIM_ERROR );
     if ( n == 2 ) gim_error->set( GIM_ERROR_WARNING , "gim_gkfp_file_list_obj::make" , "The directory is empty" , __GIM_ERROR );
     if ( n >  2 ) {
         char message [256];
         sprintf( message , "File list maked : added %d members" , endlist->id + 1 );
         gim_error->set( "gim_gkfp_file_list_obj::make" , message );
     }
     header.members = endlist->id;
     return endlist->id;
 }
References __GIM_CLEAR, __GIM_ERROR, __GIM_ROOT, __GIM_YES, EMPTY, gim_checksum, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, gim_file_manager, gim_interface, gim_file_list_struct::hash, gim_file_header_struct::hashed_file, header, gim_file_list_struct::id, gim_file_manager_obj::length(), LINK, gim_file_header_struct::members, gim_file_list_struct::name, gim_file_list_struct::path, gim_file_header_struct::recursive, REGFILE, REGNODE, ROOT, gim_error_obj::set(), gim_checksum_obj::sha1(), gim_file_list_struct::size, gim_interface_data::sou_position, gim_interface_data::sou_size, gim_file_list_struct::stat, and gim_file_list_struct::type.
Referenced by New_path().
lnext()
_gim_gkp_flist * gim_gkfp_obj::lnext (_gim_gkp_flist * tmplist)
Definition at line 255 of file gim_gkfp_file_list.cc.
{
     if ( tmplist != NULL )
         return tmplist->link;
     else
         return NULL;
 }
References gim_file_list_struct::link.
lread()
_gim_map gim_gkfp_obj::lread (_gim_map map)
Definition at line 231 of file gim_gkfp_file_list.cc.
{
     for( unsigned int c = 0 ; c <= header.members ; c++ ) {
         currentlist = ladd();
         memcpy( currentlist , map , sizeof( _gim_gkp_flist ) );
         map += sizeof( _gim_gkp_flist );
         currentlist->buffer = NULL;
         currentlist->handle = NULL;
         if ( currentlist->type == ROOT ) {
             strcpy( old_root , currentlist->name );
             char message[256];
             sprintf( message , "New root found : %s" , old_root );
             gim_error->set( "gim_gkfp_file_list_obj::get" , message );
         }
         gim_interface->data->sou_position = c;
     }
     return map;
 }
References gim_file_list_struct::buffer, gim_error, gim_interface, gim_file_list_struct::handle, header, gim_file_header_struct::members, gim_file_list_struct::name, ROOT, gim_error_obj::set(), gim_interface_data::sou_position, and gim_file_list_struct::type.
Referenced by Extract(), and Open().
lwrite()
void gim_gkfp_obj::lwrite (_gim_handler * out)
Definition at line 215 of file gim_gkfp_file_list.cc.
{
     _gim_gkp_flist  FileList;
     for( currentlist = startlist ; currentlist != NULL ; currentlist = currentlist->link ) {
         strcpy( FileList.name , currentlist->name ) ;
         strcpy( FileList.path , currentlist->path ) ;
         FileList.size   =   currentlist->size;
         FileList.type   =   currentlist->type;
         FileList.id     =   currentlist->id;
         memcpy( &(FileList.stat) , &(currentlist->stat) , sizeof( struct stat ) );
         FileList.handle =   NULL ;
         FileList.link   =   NULL ;
         gim_file_manager->flush( out , (char *)&FileList , sizeof( FileList ) );
     }
 }
References gim_file_manager_obj::flush(), gim_file_manager, gim_file_list_struct::handle, gim_file_list_struct::id, gim_file_list_struct::link, gim_file_list_struct::name, gim_file_list_struct::path, gim_file_list_struct::size, gim_file_list_struct::stat, and gim_file_list_struct::type.
Referenced by Write().
New()
void gim_gkfp_obj::New (const char * filename, _gim_flag recursion, _gim_flag crypt, _gim_flag compress, _gim_flag hash)
Examples
gkfp.cc.
Definition at line 451 of file gim.cc.
{
     strcpy( header.title , __GKP_TITLE_FILE );
     strcpy( file_name , filename );
     strcpy( header.user , gim_identity->login() );
     strcpy( header.hostname , gim_identity->node() );
     header.recursive = recursion;
     header.crypt = crypt;
     header.compression = compress;
     header.hashed_file = hash;
     header.xhk = __GIM_NO;
 }
References __GIM_NO, __GKP_TITLE_FILE, gim_file_header_struct::compression, gim_file_header_struct::crypt, crypt, gim_identity, gim_file_header_struct::hashed_file, header, gim_file_header_struct::hostname, gim_identity_obj::login(), gim_identity_obj::node(), gim_file_header_struct::recursive, gim_file_header_struct::title, gim_file_header_struct::user, and gim_file_header_struct::xhk.
New_path()
_gim_Ulong gim_gkfp_obj::New_path (const char * path_in)
Examples
gkfp.cc.
Definition at line 464 of file gim.cc.
{
     header.members = lmake( path_in , __GIM_ROOT );
     return header.members;
 }
References __GIM_ROOT, header, lmake(), and gim_file_header_struct::members.
New_root()
void gim_gkfp_obj::New_root (const char * path_in)
Definition at line 469 of file gim.cc.
{
     char m[256];
     strcpy( new_root , path_in );
     sprintf( m , "New root changed in %s" , new_root );
     gim_error->set( "gim_gkfp_obj::New_root" , m );
 }
References gim_error, and gim_error_obj::set().
Open()
_gim_map gim_gkfp_obj::Open (const char * filename)
Definition at line 508 of file gim.cc.
{
     strcpy( file_name , filename );
     hand = gim_file_manager->open( filename , __GIM_FILE_MAPPING , __GIM_READ );
     if ( hand == NULL ) {
         char m[256];
         sprintf( m , "GKFP file not found : %s" , filename );
         gim_error->set( GIM_ERROR_FATAL , "gim_gkfp_obj::open" , m , __GIM_ERROR );
     }
     _gim_map map = hand->fm;
     map = hread( map );
     if ( Lexical.str_equal( verify.hash , gim_checksum->md5( (char *)&(header) , sizeof( gim_file_header_struct) ) ) != __GIM_YES ) {
         gim_file_manager->close( hand );
         gim_error->set( GIM_ERROR_FATAL , "gim_gkfp_obj::open" , "GKFP file header corrupted." , __GIM_ERROR );
     }
     map = lread( map );
     read_data( map , lget() );
     return map;
 }
References __GIM_ERROR, __GIM_FILE_MAPPING, __GIM_READ, __GIM_YES, gim_file_manager_obj::close(), gim_global_item_handler::fm, gim_checksum, gim_error, GIM_ERROR_FATAL, gim_file_manager, gim_file_header_verify::hash, header, Lexical, lget(), lread(), gim_checksum_obj::md5(), gim_file_manager_obj::open(), read_data(), gim_error_obj::set(), prsr_lexical_class::str_equal(), and verify.
read_data()
_gim_flag gim_gkfp_obj::read_data (_gim_map map, _gim_gkp_flist * startlist)
Definition at line 113 of file gim_gkfp_file_data.cc.
{
     _gim_gkp_flist  * currentlist = NULL;
     _gim_gkp_chunk  chunk;
     _gim_buffer     data = NULL;
     int             c;
     for( c = 0 , currentlist = startlist->link ; currentlist != NULL ; currentlist = currentlist->link , c++ ) {
         if ( currentlist->type == REGFILE ) {
             char message[256];
             gim_interface->data->sou_size = gim_interface->data->sou_position = c + 1;
             sprintf( message , "Reading GKP::%s " , currentlist->name );
             gim_error->set( "gim_file_data_obj::data" , message );
             __GIM_CLEAR( &chunk , 1 , chunk );
             memcpy( &chunk , map , sizeof( chunk ) );
             map += sizeof( chunk );
             currentlist->handle = map;
             data = (_gim_buffer)gim_memory->Alloc( currentlist->size , __GIM_MEM_FILE_DATA_R , __GIM_HIDE );
             memcpy( data , map , currentlist->size );
             map += currentlist->size;
             sprintf( gim_interface->data->item_dst_name , "%s" , currentlist->name );
             sprintf( gim_interface->data->item_dna_name , "Hashing" );
             if ( internal_gim->get_state() == __GIM_TH_STOP ) return __GIM_NOT_OK;
             if ( header.crypt == __GIM_SUN ) {
                 if ( Lexical.str_equal( chunk.id , gim_checksum->md5( data , currentlist->size ) ) == __GIM_NO ) {
                     char message[256];
                     sprintf( message , "GKP::%s checksum error" , currentlist->name );
                     gim_error->set( GIM_ERROR_CRITICAL , "gim_file_data_obj::data" , message , __GIM_ERROR );
                 }
             }
             if ( header.crypt == __GIM_FOG ) {
                 if ( Lexical.str_equal( chunk.xhash , gim_checksum->md5( data , currentlist->size ) ) == __GIM_NO ) {
                     char message[256];
                     sprintf( message , "GKP::%s checksum error" , currentlist->name );
                     gim_error->set( GIM_ERROR_CRITICAL , "gim_file_data_obj::data" , message , __GIM_ERROR );
                 }
             }
             gim_memory->Free( data );
         }
     }
     return __GIM_OK;
 }
References __GIM_CLEAR, __GIM_ERROR, __GIM_FOG, __GIM_HIDE, __GIM_MEM_FILE_DATA_R, __GIM_NO, __GIM_NOT_OK, __GIM_OK, __GIM_SUN, __GIM_TH_STOP, gim_memory_obj::Alloc(), gim_file_header_struct::crypt, gim_memory_obj::Free(), gim_obj::get_state(), gim_checksum, gim_error, GIM_ERROR_CRITICAL, gim_interface, gim_memory, gim_file_list_struct::handle, header, gim_file_chunk_struct::id, internal_gim, gim_interface_data::item_dna_name, gim_interface_data::item_dst_name, Lexical, gim_file_list_struct::link, gim_checksum_obj::md5(), gim_file_list_struct::name, REGFILE, gim_error_obj::set(), gim_file_list_struct::size, gim_interface_data::sou_position, gim_interface_data::sou_size, prsr_lexical_class::str_equal(), gim_file_list_struct::type, and gim_file_chunk_struct::xhash.
Referenced by Extract(), and Open().
set_password()
void gim_gkfp_obj::set_password (const char * passwd)
With this method you can set a password in a GKDP file.
Parameters
passwd The password to set
Examples
gkfp.cc.
Definition at line 546 of file gim.cc.
{
     if ( passwd != NULL ) {
         crypt->set( passwd );
         gim_error->set( "gim_gkdp_obj::set_password" , "A new password succesfully setted" );
     }
     else {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_gkdp_obj::set_password" , "You cannot pass NULL to this function" , __GIM_ERROR );
     }
 }
References __GIM_ERROR, crypt, gim_error, GIM_ERROR_CRITICAL, gim_password_obj::set(), and gim_error_obj::set().
Set_prg()
void gim_gkfp_obj::Set_prg (const char * prg_name, _gim_Uint8 major, _gim_Uint8 minor, _gim_Uint8 subminor)
Examples
gkfp.cc.
Definition at line 500 of file gim.cc.
{
     strcpy( header.program , prg_name );
     header.major = major;
     header.minor = minor;
     header.built = subminor;
 }
References gim_file_header_struct::built, header, gim_file_header_struct::major, gim_file_header_struct::minor, and gim_file_header_struct::program.
Write()
_gim_flag gim_gkfp_obj::Write (void)
Examples
gkfp.cc.
Definition at line 477 of file gim.cc.
{
     if ( ! strlen( file_name ) ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_gkfp_obj::Write" , "New file not yet setted. I don't write anything" , __GIM_ERROR );
         return __GIM_NOT_EXIST;
     }
     else {
         _gim_handler * out = gim_file_manager->open( file_name , __GIM_FILE_POINTER , __GIM_WRITE );
         if ( out == NULL ) {
             gim_error->set( GIM_ERROR_FATAL , "gim_gkfp_obj::Write" , "Is not possible to write on disk" , __GIM_ERROR );
         }
         if ( internal_gim->get_state() == __GIM_TH_STOP ) return __GIM_NOT_OK;
         hwrite( out );
         if ( internal_gim->get_state() == __GIM_TH_STOP ) return __GIM_NOT_OK;
         lwrite( out );
         if ( internal_gim->get_state() == __GIM_TH_STOP ) return __GIM_NOT_OK;
         if ( write_data( out , lget() ) == __GIM_NOT_OK )
             return __GIM_NOT_OK;
         gim_file_manager->close( out );
         gim_error->set( "gim_gkfp_obj::Write" , "New GKP file wrote" );
     }
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_FILE_POINTER, __GIM_NOT_EXIST, __GIM_NOT_OK, __GIM_OK, __GIM_TH_STOP, __GIM_WRITE, gim_file_manager_obj::close(), gim_obj::get_state(), gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_FATAL, gim_file_manager, internal_gim, lget(), lwrite(), gim_file_manager_obj::open(), gim_error_obj::set(), and write_data().
write_data()
_gim_flag gim_gkfp_obj::write_data (_gim_handler * out, _gim_gkp_flist * startlist)
Definition at line 40 of file gim_gkfp_file_data.cc.
{
     char            path[1024];
     char            message[256];
     _gim_gkp_flist  * currentlist = NULL;
     _gim_handler    * in = NULL;
     char            * file = NULL , tname[1024];
     _gim_gkp_chunk  chunk;
     //gim_interface->clear();
     for( currentlist = startlist->link ; currentlist != NULL ; currentlist = currentlist->link ) {
         if ( internal_gim->get_state() == __GIM_TH_STOP ) return __GIM_NOT_OK;
         if ( currentlist->type == REGFILE ) {
             gim_interface->data->dst_ratio = (float)( (float)currentlist->id / (float)endlist->id );
             sprintf( message , "Cur id : %d  |  end id : %d  |  dst_ratio %f" , currentlist->id , endlist->id , gim_interface->data->dst_ratio );
             gim_error->set( "gim_gkfp_file_data_obj::write" , message );
             sprintf( tname , "%s%s" , currentlist->path , currentlist->name ) ;
             __GIM_CLEAR( &chunk , 1 ,  _gim_gkp_chunk );
             if ( internal_gim->get_state() == __GIM_TH_STOP ) return __GIM_NOT_OK;
             if ( header.crypt == __GIM_FOG )
                 in = gim_file_manager->open( tname , __GIM_FILE_POINTER , __GIM_READ );
             if ( header.crypt == __GIM_SUN )
                 in = gim_file_manager->open( tname , __GIM_FILE_MAPPING , __GIM_READ );
             if ( in == NULL ) {
                 sprintf( message , "I cannot open file %s" , currentlist->name );
                 gim_error->set( GIM_ERROR_FATAL , "gim_file_data_obj::data" , message , __GIM_ERROR );
             }
             if ( header.crypt == __GIM_FOG ) {
                 sprintf( gim_interface->data->item_dst_name , "%s" , currentlist->name );
                 strcpy( gim_interface->data->item_dna_name , "Loading" );
                 file = gim_file_manager->load( in );
                 if ( file == NULL )
                     gim_error->set( GIM_ERROR_FATAL , "gim_file_data_obj::data" , "I cannot load file" , __GIM_NOT_OK );
                 strcpy( chunk.id , gim_checksum->md5( file , in->size ) ) ;
                 crypt->set_secondary( currentlist->name );
                 sprintf( gim_interface->data->item_dst_name , "%s" , currentlist->name );
                 strcpy( gim_interface->data->item_dna_name , "Crypting" );
                 crypt->advanced_password( file , in->size );
                 if ( internal_gim->get_state() == __GIM_TH_STOP ) return __GIM_NOT_OK;
                 sprintf( gim_interface->data->item_dst_name , "%s" , currentlist->name );
                 strcpy( gim_interface->data->item_dna_name , "Hashing" );
                 if ( internal_gim->get_state() == __GIM_TH_STOP ) return __GIM_NOT_OK;
                 strcpy( chunk.xhash , gim_checksum->md5( file , in->size ) );
                 if ( internal_gim->get_state() == __GIM_TH_STOP ) return __GIM_NOT_OK;
             }
             else {
                 sprintf( gim_interface->data->item_dst_name , "%s" , currentlist->name );
                 strcpy( gim_interface->data->item_dna_name , "Hashing" );
                 if ( internal_gim->get_state() == __GIM_TH_STOP ) return __GIM_NOT_OK;
                 strcpy( chunk.id , gim_checksum->md5( in->fm , in->size ) ) ;
                 if ( internal_gim->get_state() == __GIM_TH_STOP ) return __GIM_NOT_OK;
             }
             char message[1024];
             sprintf( message , "writing chunk id - %d" , currentlist->id );
             gim_error->set( "gim_file_data_obj::data" , message );
             if ( internal_gim->get_state() == __GIM_TH_STOP ) return __GIM_NOT_OK;
             gim_file_manager->flush( out , (char *)&chunk , sizeof( chunk ) );
             __GIM_CLEAR( message , 1024 , char );
             sprintf( message , "writing file - %s" , currentlist->name );
             gim_error->set( "gim_file_data_obj::data" , message );
             if ( header.crypt == __GIM_FOG ) {
                 sprintf( gim_interface->data->item_dst_name , "%s" , currentlist->name );
                 strcpy( gim_interface->data->item_dna_name , "Flushing" );
                 gim_file_manager->flush( out , file , in->size );
             }
             if ( internal_gim->get_state() == __GIM_TH_STOP ) return __GIM_NOT_OK;
             if ( header.crypt == __GIM_SUN )
                 gim_file_manager->flush( out , in->fm , in->size );
             gim_file_manager->close( in );
         }
     }
     return __GIM_OK;
 }
References __GIM_CLEAR, __GIM_ERROR, __GIM_FILE_MAPPING, __GIM_FILE_POINTER, __GIM_FOG, __GIM_NOT_OK, __GIM_OK, __GIM_READ, __GIM_SUN, __GIM_TH_STOP, gim_cryptography_obj::advanced_password(), gim_file_manager_obj::close(), gim_file_header_struct::crypt, crypt, gim_interface_data::dst_ratio, gim_file_manager_obj::flush(), gim_global_item_handler::fm, gim_obj::get_state(), gim_checksum, gim_error, GIM_ERROR_FATAL, gim_file_manager, gim_interface, header, gim_file_chunk_struct::id, gim_file_list_struct::id, internal_gim, gim_interface_data::item_dna_name, gim_interface_data::item_dst_name, gim_file_list_struct::link, gim_file_manager_obj::load(), gim_checksum_obj::md5(), gim_file_list_struct::name, gim_file_manager_obj::open(), gim_file_list_struct::path, REGFILE, gim_error_obj::set(), gim_password_obj::set_secondary(), gim_global_item_handler::size, gim_file_list_struct::type, and gim_file_chunk_struct::xhash.
Referenced by Write().
Member Data Documentation
crypt
gim_cryptography_obj* gim_gkfp_obj::crypt
Definition at line 358 of file gim.h.
Referenced by extract_data(), gim_gkfp_obj(), New(), set_password(), write_data(), and ~gim_gkfp_obj().
header
gim_file_header_struct gim_gkfp_obj::header
Definition at line 360 of file gim.h.
Referenced by Extract(), extract_data(), gim_gkfp_obj(), lmake(), lread(), New(), New_path(), Open(), read_data(), Set_prg(), and write_data().
verify
gim_file_header_verify gim_gkfp_obj::verify
Definition at line 361 of file gim.h.
Referenced by Extract(), and Open().