My Project: Main Page
gim_cnc_obj Class Reference
Code 'N' Crypt Documentation.
#include <gim_cnc.h>
Public Member Functions
_gim_flag get (_gim_int8 feature)
Get the state (ON or OFF) of a feature of CnC ; e.g. get(ADVANCEDPASSWORD)
gim_cnc_obj ()
_gim_flag set (_gim_int8 feature, _gim_flag state)
Set a CnC feature ON or Off; e.g. set(ADVANCEDPASSWORD , ON)
~gim_cnc_obj ()
Public Attributes
gim_cnc_decoding_obj * decoding
gim_cnc_encoding_obj * encoding
Detailed Description
Code 'N' Crypt Documentation.
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Corrado Tumiati - skyma.nosp@m.trix.nosp@m.@gkri.nosp@m.pt.o.nosp@m.rg
Version
0.3-5
Date
2003-2006
Definition at line 144 of file gim_cnc.h.
Constructor & Destructor Documentation
gim_cnc_obj()
gim_cnc_obj::gim_cnc_obj () inline
Definition at line 173 of file gim_cnc.h.
{
                 gim_error->set( "gim_cnc_obj::gim_cnc_obj" , "Start CNC kernel initialize" );
                 encoding        = new gim_cnc_encoding_obj;
                 decoding        = new gim_cnc_decoding_obj;
                 cnc_password    = new gim_password_obj;
                 __GIM_CLEAR( &cnc_data , 1 , cnc_Kernel_data_struct );
                 __GIM_CLEAR( &cnc_feature , 1 , cnc_Kernel_feature_struct );
                 gim_error->set( "gim_cnc_obj::gim_cnc_obj" , "CNC kernel succesfully initialized" );
             }
References __GIM_CLEAR, cnc_data, cnc_feature, cnc_password, decoding, encoding, gim_error, and gim_error_obj::set().
~gim_cnc_obj()
gim_cnc_obj::~gim_cnc_obj () inline
Definition at line 185 of file gim_cnc.h.
{
                 gim_error->set( "gim_cnc_obj::~gim_cnc_obj" , "Start CNC kernel shutdown" );
                 delete encoding;
                 delete decoding;
                 delete cnc_password;
                 gim_error->set( "gim_cnc_obj::~gim_cnc_obj" , "CNC now is down" );
             }
References cnc_password, decoding, encoding, gim_error, and gim_error_obj::set().
Member Function Documentation
get()
_gim_flag gim_cnc_obj::get (_gim_int8 feature)
Get the state (ON or OFF) of a feature of CnC ; e.g. get(ADVANCEDPASSWORD)
Parameters
feature One of the possible macro defined before in this file
(search // BEGIN OF FEATURES)
((feature == NOSKEMA) ||
(feature == ENCODING) ||
(feature == VARIABLEAB) ||
Returns
ON if the feature is setted , OFF if not. ERROR if feature does not exists
Definition at line 51 of file gim_cnc.cc.
{
     switch ( feature_to_get )
     {
         case NOSKEMA :  {
             return cnc_feature.NoSkema ;
         }
         case VARIABLEAB : {
             return cnc_feature.VariableAB ;
         }
     }
     return __GIM_ERROR;
 }
References __GIM_ERROR, cnc_feature, NOSKEMA, cnc_Kernel_feature_struct::NoSkema, VARIABLEAB, and cnc_Kernel_feature_struct::VariableAB.
set()
_gim_flag gim_cnc_obj::set (_gim_int8 feature, _gim_flag state)
Set a CnC feature ON or Off; e.g. set(ADVANCEDPASSWORD , ON)
Parameters
feature One of the possible macro defined before in this file
(search // BEGIN OF FEATURES)
((feature == NOSKEMA) ||
(feature == ENCODING) ||
(feature == VARIABLEAB) ||
state the value of specified feature, ON or OFF
((state == ON) || (state == OFF))
Returns
OK if the feature is setted , NOT_OK if not
Definition at line 23 of file gim_cnc.cc.
{
     gim_error->set( "gim_cnc_obj::set" , "Changeged a Feature in CNC kernel" );
     if ( ( state == __GIM_ON ) || ( state == __GIM_OFF ) ) {
         switch (feature_to_set)
         {
             case NOSKEMA :  {
                 cnc_feature.NoSkema = state;
                 return __GIM_OK;
                 break;
             }
             case VARIABLEAB : {
                 cnc_feature.VariableAB = state;
                 cnc_VariableAB( __GIM_YES ) {
                     cnc_alfabeto.init();
                     cnc_alfabeto.make();
                 }
                 return __GIM_OK;
                 break;
             }
             default : {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_cnc_obj::set" , "Changeged a Feature in CNC kernel" , __GIM_ERROR );
                 return __GIM_NOT_OK;
             }
         }
     }
     return __GIM_NOT_OK;
 }
References __GIM_ERROR, __GIM_NOT_OK, __GIM_OFF, __GIM_OK, __GIM_ON, __GIM_YES, cnc_alfabeto, cnc_feature, cnc_VariableAB, gim_error, GIM_ERROR_CRITICAL, gim_cnc_alfabeto_obj::init(), gim_cnc_alfabeto_obj::make(), NOSKEMA, cnc_Kernel_feature_struct::NoSkema, gim_error_obj::set(), VARIABLEAB, and cnc_Kernel_feature_struct::VariableAB.
Member Data Documentation
decoding
gim_cnc_decoding_obj* gim_cnc_obj::decoding
Definition at line 147 of file gim_cnc.h.
Referenced by gim_cnc_obj(), and ~gim_cnc_obj().
encoding
gim_cnc_encoding_obj* gim_cnc_obj::encoding
Definition at line 146 of file gim_cnc.h.
Referenced by gim_cnc_obj(), and ~gim_cnc_obj().