My Project: Main Page
gim_file_manager_obj Class Reference
The Gim's file manager is useful to hold trace of file you have used, and is very easy
to use files in advanced mode like file mapping. In this example we create a backup of our precious /etc/X11/xorg.conf
.
#include <gim_file.h>
Public Member Functions
void close (_gim_handler *hand)
This method is used to close a file opened with this file manager.
void close (const char *name)
_gim_flag DELETE (const char *fname)
This method is in capital in order placing greater attention
on the meant of it's name.
_gim_flag exist (const char *fname)
To know if a file exist or not on filesystem.
_gim_flag flush (_gim_handler *hand, _gim_buffer data, int data_len)
Use this method if you want tu flush a buffer into a file opened in __GIM_WRITE.
gim_file_manager_obj ()
int length (const char *fname)
Useful to know the size of a file not yet opened.
_gim_buffer load (_gim_handler *hand)
Use this method to load an opened file in __GIM_READ to a buffer.
_gim_handler * open (const char *filename, _gim_flag method, _gim_flag mode)
Use this method to open a file. You can open a file in Read/Write/Append and you
can use three different methods as buffered, unbuffered and mapped. These methods
are described in open_method.
~gim_file_manager_obj ()
Detailed Description
The Gim's file manager is useful to hold trace of file you have used, and is very easy
to use files in advanced mode like file mapping. In this example we create a backup of our precious /etc/X11/xorg.conf
.
#include <stdio.h>
#include <unistd.h>
#include <gim/gim.h>
int main(int argc , char **argv) {
    gim_obj * gim = new gim_obj;
    _gim_handler * source;
    _gim_handler * destination;
    source = gim->file_manager->open( "/etc/X11/xorg.conf" , __GIM_FILE_MAPPING , __GIM_READ );
    destination = gim->file_manager->open( "/etc/X11/xorg.conf.backup" , __GIM_FILE_POINTER , __GIM_WRITE );
    gim->file_manager->flush( destination , source->fm , source->size );
    gim->file_manager->close( source );
    gim->file_manager->close( destination );
    delete gim;
    return 0;
}
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
2.0-0
Date
2003-2008
Definition at line 149 of file gim_file.h.
Constructor & Destructor Documentation
gim_file_manager_obj()
gim_file_manager_obj::gim_file_manager_obj () inline
gim_file_manager_obj constructor
Definition at line 248 of file gim_file.h.
{
                 init();
             };
~gim_file_manager_obj()
gim_file_manager_obj::~gim_file_manager_obj () inline
gim_file_manager_obj destructor
Definition at line 254 of file gim_file.h.
{
                 release();
             };
Member Function Documentation
close() [1/2]
void gim_file_manager_obj::close (_gim_handler * hand)
This method is used to close a file opened with this file manager.
Parameters
hand is the pointer to a _gim_handler previously obtained by an open call.
Definition at line 220 of file gim_file.cc.
{
     gim_file_manager_list * item;
     //~ gim_error->set( "gim_file_manager_obj::close" , "Getting item pointer from handler" );
     item = gim_file_manager_obj::item( hand->name );
     if ( item != NULL ) {
         //~ gim_error->set( "gim_file_manager_obj::close" , "Item pointer found" );
         switch( item->method ) {
             case __GIM_FILE_DESCRIPTOR : {
                 //~ gim_error->set( "gim_file_manager_obj::close" , "File desctiptor closing" );
                 ::close( item->hand->fd );
                 gim_error->Set( GIM_ERROR_MESSAGE , "gim_file_manager_obj::close" , "File desctiptor [%s] closed" , hand->name );
                 break;
             }
             case __GIM_FILE_POINTER : {
                 //~ gim_error->set( "gim_file_manager_obj::close" , "File pointer closing" );
                 fclose( item->hand->fp );
                 gim_error->Set( GIM_ERROR_MESSAGE , "gim_file_manager_obj::close" , "File pointer [%s] closed" , hand->name );
                 break;
             }
             case __GIM_FILE_MAPPING : {
                 //~ gim_error->set( "gim_file_manager_obj::close" , "File mapping closing" );
                 ::close( item->hand->fd );
                 munmap( item->hand->fm , item->hand->size );
                 gim_error->Set( GIM_ERROR_MESSAGE , "gim_file_manager_obj::close" , "File mapping [%s] closed" , hand->name );
                 break;
             }
             default : {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_file_manager_obj::close" , "Unknown method" , __GIM_ERROR );
                 break;
             }
         }
         if ( hand->loadp != NULL ) {
             //~ gim_error->set( "gim_file_manager_obj::close" , "Unloading buffer" );
             gim_memory->Free( item->hand->loadp );
             //~ item->hand->loadp = NULL;
             gim_error->set( "gim_file_manager_obj::close" , "Unloaded succesfully" );
         }
         //~ del_item( item );
         //~ gim_memory->Free( hand );
         //~ gim_error->set( "gim_file_manager_obj::close" , "Backup item handler" );
         //~ _gim_handler    * tmp = item->hand;
         //~ gim_error->set( "gim_file_manager_obj::close" , "Deleting item from list" );
         del_item( item );
         //~ gim_error->set( "gim_file_manager_obj::close" , "Item memory releasing" );
         //~ gim_memory->Free( tmp );
     }
     else
         gim_error->set( GIM_ERROR_CRITICAL , "gim_file_manager_obj::close" , "item not found. Maybe never opened or close twice" , __GIM_ERROR );
 }
References __GIM_ERROR, __GIM_FILE_DESCRIPTOR, __GIM_FILE_MAPPING, __GIM_FILE_POINTER, gim_global_item_handler::fd, gim_global_item_handler::fm, gim_global_item_handler::fp, gim_memory_obj::Free(), gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_MESSAGE, gim_memory, gim_file_manager_list::hand, gim_global_item_handler::loadp, gim_file_manager_list::method, gim_global_item_handler::name, gim_error_obj::set(), gim_error_obj::Set(), and gim_global_item_handler::size.
Referenced by close(), gim_file_obj::close(), gim_gkdp_obj::close(), gim_html_obj::close_page(), gim_gkfp_obj::Extract(), gim_gkfp_obj::extract_data(), gim_db_obj::gdbs_close(), gim_checksum_obj::md5(), gim_gkfp_obj::Open(), gim_gkdp_obj::open(), gim_gkdp_obj::tmp_extract(), gim_gkfp_obj::Write(), gim_gkdp_obj::write(), and gim_gkfp_obj::write_data().
close() [2/2]
void gim_file_manager_obj::close (const char * name)
Definition at line 273 of file gim_file.cc.
{
     gim_file_manager_list * item;
     gim_error->set( "gim_file_manager_obj::close" , "Getting item pointer from name" );
     item = gim_file_manager_obj::item( name );
     if ( item != NULL ) {
         gim_error->set( "gim_file_manager_obj::close" , "Item pointer found" );
         switch( item->method ) {
             case __GIM_FILE_DESCRIPTOR : {
                 gim_error->set( "gim_file_manager_obj::close" , "File desctiptor closing" );
                 ::close( item->hand->fd );
                 gim_error->set( "gim_file_manager_obj::close" , "File closed" );
                 break;
             }
             case __GIM_FILE_POINTER : {
                 gim_error->set( "gim_file_manager_obj::close" , "File pointer closing" );
                 fclose( item->hand->fp );
                 gim_error->set( "gim_file_manager_obj::close" , "File closed" );
                 break;
             }
             case __GIM_FILE_MAPPING : {
                 gim_error->set( "gim_file_manager_obj::close" , "File mapping closing" );
                 ::close( item->hand->fd );
                 munmap( item->hand->fm , item->hand->size );
                 gim_error->set( "gim_file_manager_obj::close" , "File closed" );
                 break;
             }
             default : {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_file_manager_obj::close" , "Unknown method" , __GIM_NOT_OK );
                 break;
             }
         }
         if ( item->hand->loadp != NULL ) {
             gim_error->set( "gim_file_manager_obj::close" , "Unloading buffer" );
             gim_memory->Free( item->hand->loadp );
             item->hand->loadp = NULL;
             gim_error->set( "gim_file_manager_obj::close" , "Unloaded succesfully" );
         }
         gim_error->set( "gim_file_manager_obj::close" , "Backup item handler" );
         _gim_handler    * tmp = item->hand;
         gim_error->set( "gim_file_manager_obj::close" , "Deleting item from list" );
         del_item( item );
         gim_error->set( "gim_file_manager_obj::close" , "Item memory releasing" );
         gim_memory->Free( tmp );
     }
     else
         gim_error->set( GIM_ERROR_CRITICAL , "gim_file_manager_obj::close" , "item not found. Maybe never opened or close twice" , __GIM_NOT_OK );
     gim_error->set( "gim_file_manager_obj::close" , "Operatin terminated" );
 }
References __GIM_FILE_DESCRIPTOR, __GIM_FILE_MAPPING, __GIM_FILE_POINTER, __GIM_NOT_OK, close(), gim_global_item_handler::fd, gim_global_item_handler::fm, gim_global_item_handler::fp, gim_memory_obj::Free(), gim_error, GIM_ERROR_CRITICAL, gim_memory, gim_file_manager_list::hand, gim_global_item_handler::loadp, gim_file_manager_list::method, gim_error_obj::set(), and gim_global_item_handler::size.
DELETE()
_gim_flag gim_file_manager_obj::DELETE (const char * fname)
This method is in capital in order placing greater attention
on the meant of it's name.
Warning
This method remove a file from your filesystem.
Parameters
fname The name of the file you want to remove
Returns
__GIM_OK if the file is removed or __GIM_NOT_OK if not
Definition at line 554 of file gim_file.cc.
{
     if ( exist( fname ) == __GIM_EXIST ) {
         char message[256];
         remove( fname );
         sprintf( message , "[%s] Deleted !!!" , fname );
         gim_error->set( "gim_file_manager_obj::DELETE" , message );
         return __GIM_OK;
     }
     return __GIM_NOT_OK;
 }
References __GIM_EXIST, __GIM_NOT_OK, __GIM_OK, exist(), gim_error, and gim_error_obj::set().
exist()
_gim_flag gim_file_manager_obj::exist (const char * fname)
To know if a file exist or not on filesystem.
Parameters
fname The file name
Returns
__GIM_EXIST if exist and __GIM_NOT_EXIST if not
Definition at line 424 of file gim_file.cc.
{
     if ( access( fname , F_OK ) == 0 )
         return __GIM_EXIST;
     else
         return __GIM_NOT_EXIST;
 }
References __GIM_EXIST, and __GIM_NOT_EXIST.
Referenced by DELETE(), open(), and prsr_lexical_class::scan_syntax().
flush()
_gim_flag gim_file_manager_obj::flush (_gim_handler * hand, _gim_buffer data, int data_len)
Use this method if you want tu flush a buffer into a file opened in __GIM_WRITE.
Parameters
hand The _gim_handler pointer to the file in which yo want to flush the buffer
data A pointer to the buffer to flush
data_len The size of the buffer in bytes
Returns
__GIM_OK if ok and __GIM_NOT_OK if some error happens
Definition at line 521 of file gim_file.cc.
{
     if ( data == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_file_obj::flush" , "The source buffer cannot be NULL" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     gim_file_manager_list * tmp = NULL;
     tmp = item( hand->name );
     if ( tmp->mode == __GIM_WRITE ) {
         switch ( tmp->method ) {
             case __GIM_FILE_DESCRIPTOR : {
                 write( hand->fd , data , data_len );
                 break;
             }
             case __GIM_FILE_POINTER : {
                 fwrite( data , data_len , 1 , hand->fp );
                 break;
             }
             case __GIM_FILE_MAPPING : {
                 gim_error->set( GIM_ERROR_WARNING , "gim_file_obj::flush" , "Flush is not possible in __GIM_FILE_MAPPING" , __GIM_ERROR );
                 return __GIM_NOT_OK;
             }
         }
         gim_error->set( "gim_file_obj::flush" , "Flushed succesfully" );
         return __GIM_OK;
     }
     else
         if ( tmp->mode != __GIM_WRITE ) {
             gim_error->set( GIM_ERROR_WARNING , "gim_file_obj::flush" , "Flush is possible in __GIM_WRITE only" , __GIM_ERROR );
         }
     return __GIM_NOT_OK;
 }
References __GIM_ERROR, __GIM_FILE_DESCRIPTOR, __GIM_FILE_MAPPING, __GIM_FILE_POINTER, __GIM_NOT_OK, __GIM_OK, __GIM_WRITE, gim_global_item_handler::fd, gim_global_item_handler::fp, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, gim_file_manager_list::method, gim_file_manager_list::mode, gim_global_item_handler::name, and gim_error_obj::set().
Referenced by gim_gkfp_obj::extract_data(), gim_gkfp_obj::lwrite(), gim_gkdp_obj::tmp_extract(), and gim_gkfp_obj::write_data().
length()
int gim_file_manager_obj::length (const char * fname)
Useful to know the size of a file not yet opened.
Parameters
fname The name of the file
Returns
The file size if ok or __GIM_ERROR if not
Definition at line 411 of file gim_file.cc.
{
     FILE * fid = fopen (fname, "r");
     if ( ! fid ) {
 //      gim_error->set( GIM_ERROR_WARNING , "gim_file_manager_obj::length" , "File not found" , __GIM_NOT_EXIST );
         return __GIM_ERROR;
     }
     fseek (fid, 0L, SEEK_END);
     int flen = ftell( fid );
     fclose( fid );
     return flen;
 }
References __GIM_ERROR.
Referenced by gim_gkfp_obj::lmake().
load()
_gim_buffer gim_file_manager_obj::load (_gim_handler * hand)
Use this method to load an opened file in __GIM_READ to a buffer.
Parameters
hand The _gim_handler pointer of the opened file.
Returns
A poiter to the buffer or NULL if error.
Definition at line 470 of file gim_file.cc.
{
     gim_file_manager_list * tmp = NULL;
     tmp = item( hand->name );
     if ( tmp != NULL ) {
         if ( tmp->hand->loadp != NULL ) {
             if ( gim_memory->Check( hand->loadp ) == __GIM_EXIST ) {
                 char message[256];
                 sprintf( message , "File already loaded [0x%p]" , hand->loadp );
                 gim_error->set( GIM_ERROR_WARNING , "gim_file_manager_obj::load" , message , __GIM_NOT_OK );
                 return hand->loadp;
             }
             else
                 hand->loadp = NULL;
         }
         if ( tmp->mode == __GIM_READ ) {
             switch ( tmp->method ) {
                 case __GIM_FILE_DESCRIPTOR : {
                     hand->loadp = (char *)gim_memory->Alloc( hand->size * sizeof( char ) , __GIM_MEM_FMAN_LOAD , __GIM_HIDE );
                     read( hand->fd , hand->loadp , hand->size );
                     break;
                 }
                 case __GIM_FILE_POINTER : {
                     hand->loadp = (char *)gim_memory->Alloc( hand->size * sizeof( char ) , __GIM_MEM_FMAN_LOAD , __GIM_HIDE );
                     unsigned int tot = fread( hand->loadp , 1 , hand->size ,  hand->fp );
                     if ( tot != hand->size ) {
                         char message[256];
                         sprintf( message , "Some problem with fread. Read %d/%d bytes" , tot , hand->size );
                         gim_error->set( GIM_ERROR_CRITICAL , "gim_file_manager_obj::load" , message , __GIM_ERROR );
                     }
                     break;
                 }
                 case __GIM_FILE_MAPPING : {
                     hand->loadp = (char *)gim_memory->Alloc( hand->size * sizeof( char ) , __GIM_MEM_FMAN_LOAD , __GIM_HIDE );
                     memcpy( hand->loadp , hand->fm , hand->size );
                     break;
                 }
             }
             gim_error->set( "gim_file_manager_obj::load" , "Loaded succesfully" );
         }
         else {
             if ( tmp->mode != __GIM_READ ) {
                 gim_error->set( "gim_file_manager_obj::load" , "Load is possible in __GIM_READ only" );
             }
         }
         return hand->loadp;
     }
     return NULL;
 }
References __GIM_ERROR, __GIM_EXIST, __GIM_FILE_DESCRIPTOR, __GIM_FILE_MAPPING, __GIM_FILE_POINTER, __GIM_HIDE, __GIM_MEM_FMAN_LOAD, __GIM_NOT_OK, __GIM_READ, gim_memory_obj::Alloc(), gim_memory_obj::Check(), gim_global_item_handler::fd, gim_global_item_handler::fm, gim_global_item_handler::fp, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, gim_memory, gim_file_manager_list::hand, gim_global_item_handler::loadp, gim_file_manager_list::method, gim_file_manager_list::mode, gim_global_item_handler::name, gim_error_obj::set(), and gim_global_item_handler::size.
Referenced by gim_gkfp_obj::write_data().
open()
_gim_handler * gim_file_manager_obj::open (const char * filename, _gim_flag method, _gim_flag mode)
Use this method to open a file. You can open a file in Read/Write/Append and you
can use three different methods as buffered, unbuffered and mapped. These methods
are described in open_method.
Parameters
filename The name of th file you want to open
method The method in which you want to open the file and this must be :
__GIM_FILE_POINTER for buffered file
__GIM_FILE_DESCRIPTOR for unbuffered file
__GIM_FILE_MAPPING for mapped file
mode With this parameter you specify to gim in which mode you want to open
the file. Mode must be :
__GIM_READ to open the file in read mode
__GIM_WRITE to open the file in write mode
__GIM_APPEND to open the file in append mode
Returns
a pointer to a _gim_handler. See the documentation of gim_global_item_handler to know is it.
Definition at line 324 of file gim_file.cc.
{
     gim_file_manager_list * item;
     char message[256];
     if ( exist( filename ) == __GIM_NO ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_file_manager_obj::open" , "File not found" , __GIM_NOT_EXIST );
         return NULL;
     }
     if ( mode != __GIM_WRITE ) {
         if ( gim_utils.isregular( filename ) == __GIM_NO ) {
             gim_error->set( GIM_ERROR_CRITICAL , "gim_file_manager_obj::open" , "This file is not a regular file" , __GIM_NOT_EXIST );
             return NULL;
         }
     }
     sprintf( message , "Opening file [%s] in %s %s..." , Lexical.string_trunc ( filename , 30 ) , method_str( method ) , mode_str( mode ) );
     gim_error->set( "gim_file_manager_obj::open" , message );
     item = new_item();
     item->hand = (_gim_handler *)gim_memory->Alloc( sizeof( _gim_handler ) , __GIM_MEM_FMAN_OPEN , __GIM_HIDE );
     strcpy( item->hand->name , filename );
     if ( mode == __GIM_READ ) {
         stat( item->hand->name , &(item->st) );
         item->hand->size = item->st.st_size;
     }
     item->mode = mode;
     item->method = method;
     switch( method ) {
         case __GIM_FILE_DESCRIPTOR : {
             open_fd( item , mode );
             if ( item->hand->fd == 0 ) {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_file_manager_obj::open" , "Some problem opening file" , __GIM_NOT_OK );
                 del_item( item );
                 return NULL;
             }
             break;
         }
         case __GIM_FILE_POINTER : {
             open_fp( item , mode );
             if ( item->hand->fp == NULL ) {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_file_manager_obj::open" , "Some problem opening file" , __GIM_NOT_OK );
                 del_item( item );
                 return NULL;
             }
             break;
         }
         case __GIM_FILE_MAPPING : {
             if ( mode == __GIM_READ ) {
                 open_fm( item );
                 if ( item->hand->fm == NULL ) {
                     gim_error->set( GIM_ERROR_CRITICAL , "gim_file_manager_obj::open" , "Some problem opening file" , __GIM_NOT_OK );
                     del_item( item );
                     return NULL;
                 }
             }
             else {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_file_manager_obj::open" , "In file mapping method is possible to open a file in __GIM_READ only" , __GIM_NOT_OK );
                 return NULL;
             }
             break;
         }
         default : {
             gim_error->set( GIM_ERROR_CRITICAL , "gim_file_manager_obj::open" , "Incorrect method" , __GIM_NOT_OK );
             return NULL;
         }
     }
     return item->hand;
 }
References __GIM_FILE_DESCRIPTOR, __GIM_FILE_MAPPING, __GIM_FILE_POINTER, __GIM_HIDE, __GIM_MEM_FMAN_OPEN, __GIM_NO, __GIM_NOT_EXIST, __GIM_NOT_OK, __GIM_READ, __GIM_WRITE, gim_memory_obj::Alloc(), exist(), gim_global_item_handler::fd, gim_global_item_handler::fm, gim_global_item_handler::fp, gim_error, GIM_ERROR_CRITICAL, gim_memory, gim_utils, gim_file_manager_list::hand, gim_utils_obj::isregular(), Lexical, gim_file_manager_list::method, gim_file_manager_list::mode, gim_global_item_handler::name, gim_error_obj::set(), gim_global_item_handler::size, gim_file_manager_list::st, and prsr_lexical_class::string_trunc().
Referenced by gim_gkfp_obj::Extract(), gim_gkfp_obj::extract_data(), gim_db_obj::gdbs_open(), gim_file_obj::gim_file_obj(), gim_checksum_obj::md5(), gim_html_obj::new_page(), gim_gkfp_obj::Open(), gim_gkdp_obj::open(), gim_gkdp_obj::tmp_extract(), gim_gkfp_obj::Write(), gim_gkdp_obj::write(), and gim_gkfp_obj::write_data().