My Project: Main Page
gim_error_obj Class Reference
The inner management of the errors.
#include <gim_error.h>
Public Member Functions
_gim_flag get (_gim_int8 cmd)
With this method you can know the behavior of Gim when an eventual error happens.
void get (void)
Gim has one inner management of the errors
With this function it is possible to interrogate, anytime, Gim on the last error setted.
gim_error_obj ()
void set (_gim_int8 cmd, _gim_flag val)
With this method you can change the behavior of Gim when an error happens.
Inside the enum variable_set there are four command you can set __GIM_YES or __GIM_NO.
void Set (const char *function, const char *format,...)
void set (const char *function, const char *message)
void set (const char *function, int index)
void Set (const char *type, const char *function, const char *format,...)
void set (const char *type, const char *function, const char *message, int value)
void set (pid_t cur_pid, const char *type, const char *function, const char *message, int value)
Detailed Description
The inner management of the errors.
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
2.0-0
Date
2003-2008
Definition at line 97 of file gim_error.h.
Constructor & Destructor Documentation
gim_error_obj()
gim_error_obj::gim_error_obj () inline
gim_error_obj constructor
Definition at line 167 of file gim_error.h.
{
                 strcpy  ( type      , GIM_ERROR_OK );
                 strcpy  ( function  , "__init" );
                 strcpy  ( message   , "Initialization ok" );
                 value = 0;
                 on_fatal_exit       = __GIM_YES;
                 on_fatal_verbose    = __GIM_YES;
                 always_verbose      = __GIM_NO;
                 verbose_on_critical = __GIM_YES;
                 autoget             = __GIM_YES;
                 log_enable          = __GIM_YES;
                 first_in            = NULL;
                 last_in             = NULL;
             };
References __GIM_NO, __GIM_YES, and GIM_ERROR_OK.
Member Function Documentation
get() [1/2]
_gim_flag gim_error_obj::get (_gim_int8 cmd)
With this method you can know the behavior of Gim when an eventual error happens.
Parameters
cmd One command in the enum variable_set
Definition at line 248 of file gim_error.cc.
{
     switch(cmd) {
         case GIM_ON_FATAL_EXIT :        return ( on_fatal_exit );
         case GIM_ON_FATAL_VERBOSE :     return ( on_fatal_verbose );
         case GIM_ALWAYSE_VERBOSE :      return ( always_verbose );
         case GIM_AUTOGET :              return ( autoget );
         case GIM_VERBOSE_ON_CRITICAL :  return ( verbose_on_critical );
         default :                       return __GIM_ERROR;
     }
 }
References __GIM_ERROR, GIM_ALWAYSE_VERBOSE, GIM_AUTOGET, GIM_ON_FATAL_EXIT, GIM_ON_FATAL_VERBOSE, and GIM_VERBOSE_ON_CRITICAL.
get() [2/2]
void gim_error_obj::get (void)
Gim has one inner management of the errors
With this function it is possible to interrogate, anytime, Gim on the last error setted.
Definition at line 207 of file gim_error.cc.
{
     if ( value || always_verbose ) {
         if ( ( ( ! ( strcmp ( type , GIM_ERROR_CRITICAL ) ) )  &&  ( verbose_on_critical == __GIM_YES ) ) ) {
             fprintf ( stderr , "[%s] %s%-40s:#%2d: | %s \n" , error_time.process() , type , function , value , message );
             fflush( stderr );
         }
         if ( ( ( ! ( strcmp ( type , GIM_ERROR_FATAL ) ) )  &&  ( on_fatal_verbose == __GIM_YES ) ) || ( always_verbose ) ) {
             fprintf ( stderr , "[%s] %s%-40s:#%2d: | %s \n" , error_time.process() , type , function , value , message );
             fflush( stderr );
             if ( ( ! ( strcmp ( type , GIM_ERROR_FATAL ) ) )  &&  ( on_fatal_exit == __GIM_YES ) )
                 internal_gim->down( value );
         }
     }
 }
References __GIM_YES, gim_obj::down(), error_time, GIM_ERROR_CRITICAL, GIM_ERROR_FATAL, internal_gim, and gim_time_obj::process().
Referenced by set().
set() [1/5]
void gim_error_obj::set (_gim_int8 cmd, _gim_flag val)
With this method you can change the behavior of Gim when an error happens.
Inside the enum variable_set there are four command you can set __GIM_YES or __GIM_NO.
Parameters
cmd One command in the enum variable_set
val Must be __GIM_YES or __GIM_NO
Definition at line 222 of file gim_error.cc.
{
     switch(cmd) {
         case GIM_ON_FATAL_EXIT : {
             on_fatal_exit = val;
             break;
         }
         case GIM_ON_FATAL_VERBOSE : {
             on_fatal_verbose = val;
             break;
         }
         case GIM_ALWAYSE_VERBOSE : {
             always_verbose = val;
             break;
         }
         case GIM_AUTOGET : {
             autoget = val;
             break;
         }
         case GIM_VERBOSE_ON_CRITICAL : {
             verbose_on_critical = val;
             break;
         }
     }
 }
References GIM_ALWAYSE_VERBOSE, GIM_AUTOGET, GIM_ON_FATAL_EXIT, GIM_ON_FATAL_VERBOSE, and GIM_VERBOSE_ON_CRITICAL.
Set() [1/2]
void gim_error_obj::Set (const char * function, const char * format, ...)
Definition at line 149 of file gim_error.cc.
{
     char    message[1024];
     va_list VAList;
     va_start( VAList , format );
     vsprintf( message , format , VAList );
     va_end( VAList );
     set( GIM_ERROR_MESSAGE , function , message , 0 );
 }
References GIM_ERROR_MESSAGE, and set().
Referenced by gim_file_manager_obj::close(), gim_db_obj::exist_environment(), gim_db_obj::gdbs_execute(), gim_db_obj::gdbs_line_syntax_check(), gim_db_obj::gdbs_tokenizer(), gim_db_obj::init(), gim_db_obj::init_from_gdbs(), gim_db_obj::read(), gim_db_obj::set_name(), gim_db_obj::table_exist(), and gim_db_obj::~gim_db_obj().
set() [2/5]
void gim_error_obj::set (const char * function, const char * message)
Definition at line 144 of file gim_error.cc.
{
     set( GIM_ERROR_MESSAGE , function , message , 0 );
 }
References GIM_ERROR_MESSAGE, and set().
set() [3/5]
void gim_error_obj::set (const char * function, int index)
Definition at line 173 of file gim_error.cc.
{
     _gim_flag fatal = __GIM_NO;
     if  ( ! ( strcmp ( type , GIM_ERROR_FATAL ) ) )
         fatal = __GIM_YES;
     strcpy  ( type , gim_error_list[index].type );
     sprintf ( this->function , "%s()" , function );
     strcpy  ( message , gim_error_list[index].message );
     value = gim_error_list[index].value;
     if ( index != 7 ) {
         if ( gim_log->is_open() == __GIM_YES ) {
             if ( first_in != NULL ) {
                 lflush();
             }
             else {
                 gim_log->addline_format( type , this->function , message , value );
             }
         }
         else {
             if ( log_enable == __GIM_YES ) {
                 if ( ladd( type , this->function , message , value ) == __GIM_NOT_OK ) {
                     puts( "errore" );
                 }
             }
 //          else
 //              lflush();
         }
     }
     if ( autoget )
         get ();
     if ( ( fatal == __GIM_YES )  &&  ( on_fatal_exit == __GIM_YES ) ) {
         internal_gim->down( value );
     }
 }
References __GIM_NO, __GIM_NOT_OK, __GIM_YES, gim_log_obj::addline_format(), gim_obj::down(), get(), GIM_ERROR_FATAL, gim_error_list, gim_log, internal_gim, gim_log_obj::is_open(), and gim_error_list_str::value.
Set() [2/2]
void gim_error_obj::Set (const char * type, const char * function, const char * format, ...)
Definition at line 159 of file gim_error.cc.
{
     char    message[1024];
     if ( ! ( strcmp ( type , GIM_ERROR_FATAL ) ) )
         value = __GIM_ERROR;
     else
         value = 0;
     va_list VAList;
     va_start( VAList , format );
     vsprintf( message , format , VAList );
     va_end( VAList );
     set( type , function , message , value );
 }
References __GIM_ERROR, GIM_ERROR_FATAL, and set().
set() [4/5]
void gim_error_obj::set (const char * type, const char * function, const char * message, int value)
Definition at line 86 of file gim_error.cc.
{
     char mess[512];
     strcpy  ( this->type , type );
     sprintf ( this->function , "%s()" , function );
     strcpy  ( this->message , message );
     this->value = value;
     if  ( ! ( strcmp ( type , GIM_ERROR_CRITICAL ) ) )
         sprintf( mess , "ERROR : %s" , message );
     else
         strcpy( mess , message );
     if ( gim_log->is_open() == __GIM_YES ) {
         if ( first_in != NULL ) {
             lflush();
         }
         else {
             gim_log->addline_format( type , this->function , mess , value );
         }
     }
     else {
         if ( log_enable == __GIM_YES ) {
             if ( ladd( type , this->function , mess , value ) == __GIM_NOT_OK ) {
                 puts( "errore" );
             }
         }
 //      else
 //          lflush();
     }
     if ( autoget ) get ();
 }
References __GIM_NOT_OK, __GIM_YES, gim_log_obj::addline_format(), get(), GIM_ERROR_CRITICAL, gim_log, and gim_log_obj::is_open().
Referenced by gim_prsr_obj::AddComment(), gim_prsr_obj::AddKey(), gim_prsr_obj::AddKeyComment(), gim_log_obj::addline(), gim_log_obj::addline_format(), gim_prsr_obj::AddSection(), gim_prsr_obj::AddSectionComment(), gim_cryptography_obj::advanced_password(), gim_memory_obj::Alloc(), gim_ascii_file_obj::append(), gim_password_obj::calc(), gim_prsr_obj::ChangeKey(), gim_file_manager_obj::close(), gim_gkdp_obj::close(), gim_html_obj::close_page(), gim_list_obj::del_item(), gim_file_manager_obj::DELETE(), gim_prsr_obj::DelKey(), gim_prsr_obj::DelSection(), gim_obj::down(), gim_prsr_obj::Down(), gim_prsr_obj::Exist(), gim_db_obj::exist_environment(), gim_html_obj::Export(), gim_html_obj::Export_tag(), gim_html_obj::Export_tag_close(), gim_html_obj::Export_tag_open(), gim_html_obj::Export_with_tag(), gim_gkfp_obj::Extract(), gim_gkfp_obj::extract_data(), gim_file_manager_obj::flush(), gim_file_obj::flush(), gim_cnc_encoding_obj::Fog_a_buffer(), gim_memory_obj::Free(), gim_db_obj::gdbs_close(), gim_db_obj::gdbs_execute(), gim_db_obj::gdbs_getline(), gim_db_obj::gdbs_line_syntax_check(), gim_db_obj::gdbs_open(), gim_db_obj::gdbs_tokenizer(), gim_identity_obj::get(), gim_ascii_file_obj::get_buffer(), gim_list_obj::get_item(), gim_directory_obj::get_item(), gim_directory_obj::get_item_id(), gim_memory_obj::Get_lock_status(), gim_prsr_obj::GetHowManyKey(), gim_prsr_obj::GetHowManySection(), gim_prsr_obj::GetKeyFLAG(), gim_prsr_obj::GetKeyFLT(), gim_prsr_obj::GetKeyINT(), gim_prsr_obj::GetKeyName(), gim_prsr_obj::GetKeySTR(), gim_prsr_obj::GetSectionName(), gim_ascii_file_obj::gim_ascii_file_obj(), gim_checksum_obj::gim_checksum_obj(), gim_cnc_obj::gim_cnc_obj(), gim_cryptography_obj::gim_cryptography_obj(), gim_db_obj::gim_db_obj(), gim_directory_obj::gim_directory_obj(), gim_fatal_test(), gim_file_obj::gim_file_obj(), gim_forever(), gim_getopt_obj::gim_getopt_obj(), gim_html_obj::gim_html_obj(), gim_list_obj::gim_list_obj(), gim_memory_page_obj::gim_memory_page_obj(), gim_password_obj::gim_password_obj(), gim_picgim_obj::gim_picgim_obj(), gim_picgim_gkh32_obj::gim_picgim_obj(), gim_signal_handler(), gim_signal_received(), gim_string_obj::gim_string_obj(), gim_db_obj::init(), gim_db_obj::init_from_gdbs(), gim_utils_obj::isdevice(), gim_utils_obj::isdir(), gim_utils_obj::islink(), gim_utils_obj::isregular(), gim_gkdp_obj::leave(), gim_ascii_file_obj::lenght(), gim_gkfp_obj::lget(), gim_ascii_file_obj::lines(), gim_prsr_obj::List(), gim_gkfp_obj::lmake(), gim_file_manager_obj::load(), gim_file_obj::load(), gim_memory_obj::Lock(), gim_gkfp_obj::lread(), gim_directory_obj::make(), gim_cnc_alfabeto_obj::make(), gim_db_obj::make_env(), gim_checksum_obj::md5(), gim_html_obj::new_page(), gim_gkfp_obj::New_root(), gim_list_obj::next_item(), gim_file_manager_obj::open(), gim_gkfp_obj::Open(), gim_gkdp_obj::open(), gim_file_obj::put(), gim_db_obj::read(), gim_prsr_obj::Read(), gim_gkfp_obj::read_data(), gim_password_obj::recalc(), gim_directory_obj::refresh(), gim_prsr_obj::RenameKey(), gim_prsr_obj::RenameSection(), gim_prsr_obj::RenameTitle(), gim_directory_obj::reset_position(), gim_list_obj::rewind(), prsr_lexical_class::scan(), prsr_lexical_class::scan_a(), prsr_lexical_class::scan_b(), prsr_lexical_class::scan_lex_type(), gim_ascii_file_obj::seek(), gim_list_obj::seek(), gim_ascii_file_obj::seekf(), gim_string_obj::set(), gim_password_obj::set(), set(), Set(), gim_cnc_obj::set(), gim_ascii_file_obj::set_dimension(), gim_db_obj::set_name(), gim_gkfp_obj::set_password(), gim_gkdp_obj::set_password(), gim_db_obj::set_property(), gim_password_obj::set_secondary(), gim_prsr_obj::SetLex(), gim_checksum_obj::sha1(), gim_checksum_obj::sha256(), gim_checksum_obj::sha512(), gim_cryptography_obj::simple_password(), gim_log_obj::start(), gim_log_obj::stop(), gim_utils_obj::str_subtraction(), prsr_lexical_class::syntax_a(), prsr_lexical_class::syntax_b(), gim_db_obj::table_exist(), gim_gkdp_obj::take(), gim_prsr_obj::ThereIsASection(), gim_gkdp_obj::tmp_extract(), prsr_lexical_class::tokenizer(), gim_file_obj::unload(), gim_memory_obj::Unlock(), gim_prsr_obj::Up(), gim_memory_obj::Vmem(), gim_prsr_obj::Write(), gim_gkfp_obj::Write(), gim_gkdp_obj::write(), gim_gkfp_obj::write_data(), gim_prsr_obj::WriteOnBuffer(), gim_ascii_file_obj::~gim_ascii_file_obj(), gim_cnc_obj::~gim_cnc_obj(), gim_db_obj::~gim_db_obj(), gim_directory_obj::~gim_directory_obj(), gim_getopt_obj::~gim_getopt_obj(), gim_html_obj::~gim_html_obj(), gim_log_obj::~gim_log_obj(), and gim_memory_page_obj::~gim_memory_page_obj().
set() [5/5]
void gim_error_obj::set (pid_t cur_pid, const char * type, const char * function, const char * message, int value)
Definition at line 117 of file gim_error.cc.
{
     strcpy  ( this->type , type );
     sprintf ( this->function , "%s()" , function );
     strcpy  ( this->message , message );
     this->value = value;
     if ( gim_log->is_open() == __GIM_YES ) {
         if ( first_in != NULL ) {
             lflush();
         }
         else {
             gim_log->addline_format( type , this->function , message , value );
         }
     }
     else {
         if ( log_enable == __GIM_YES ) {
             if ( ladd( type , this->function , message , value ) == __GIM_NOT_OK ) {
                 puts( "errore" );
             }
         }
 //      else
 //          lflush();
     }
     if ( autoget )
         get ();
 }
References __GIM_NOT_OK, __GIM_YES, gim_log_obj::addline_format(), get(), gim_log, and gim_log_obj::is_open().