My Project: Main Page
gim_cryptography_obj Class Reference
A Gim class to encrypt and decrypt whichever things.
#include <gim_gkp_cryptography.h>
Public Member Functions
_gim_buffer advanced_dna (_gim_buffer buffer, _gim_Ulong size, char *dna_file_name)
An very good method to encrypt or decrypt a buffer
It use an external file as key, so an other file is needed. Performance = not excessive good
Safety = maximum
Password = not needed
_gim_buffer advanced_password (_gim_buffer buffer, _gim_Ulong size)
An efficient method to encrypt or decrypt a buffer
Performance = not excessive good
Safety = very good
Password = needed
.
void calc (void)
This function is used to calc the password digest and the inner seeds.
_gim_buffer dna (_gim_buffer buffer, _gim_Ulong size, char *dna_file_name)
An very good method to encrypt or decrypt a buffer
It use an external file as key, so an other file is needed. Performance = good
Safety = optimal
Password = not needed
.
gim_cryptography_obj ()
void recalc (void)
This function is used to recalc the password digest and the inner seeds.
void set (const char *passwd)
This function is used to set a password, used by Gim when necessary.
void set_secondary (const char *passwd)
This function is used to set a password, used by Gim when necessary.
_gim_buffer simple_password (_gim_buffer buffer, _gim_Ulong size)
Detailed Description
A Gim class to encrypt and decrypt whichever things.
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
1.0-0
Date
2003-2007
Definition at line 54 of file gim_gkp_cryptography.h.
Constructor & Destructor Documentation
gim_cryptography_obj()
gim_cryptography_obj::gim_cryptography_obj ()
gim_cryptography_obj constructor
Definition at line 43 of file gim_gkp_cryptography.cc.
{
     char message[256];
     IF_EXIST_KEY_IN_CONF( "crypt" , "iterations" ) {
         iter = gim_conf->GetKeyINT( "crypt" , "iterations" );
         sprintf( message , "Iterations setted to %d" , iter );
         gim_error->set( "gim_cryptography_obj::gim_cryptography_obj" , message );
     }
     else {
         gim_error->set( GIM_ERROR_WARNING , "gim_cryptography_obj::gim_cryptography_obj" , "Itarations not found in config file. Setted default 2 iteration" , __GIM_ERROR );
     }
 }
References __GIM_ERROR, gim_prsr_obj::GetKeyINT(), gim_conf, gim_error, GIM_ERROR_WARNING, IF_EXIST_KEY_IN_CONF, and gim_error_obj::set().
Member Function Documentation
advanced_dna()
_gim_buffer gim_cryptography_obj::advanced_dna (_gim_buffer buffer, _gim_Ulong size, char * dna_file_name)
An very good method to encrypt or decrypt a buffer
It use an external file as key, so an other file is needed. Performance = not excessive good
Safety = maximum
Password = not needed
Parameters
buffer The buffer you want to crypt/decrypt
size The size of the buffer
dna_file_name The name of the file used as key
Returns
a buffer crypted/decrypted
Definition at line 143 of file gim_gkp_cryptography.cc.
{
     _gim_buffer dna;
     _gim_Ulong  j=0;
     _gim_file   dnafile( dna_file_name );
     _gim_rand   mt;
     calc();
     mt.seed( seed_main );
     if ( dnafile.check() == __GIM_EXIST ) {
         dna = dnafile.load();
         if ( dna ) {
             for ( j = 0 ; j < size ; j++ )
                 *(buffer + j) ^= *(dna + mt.randInt( dnafile.size() ) );
             dnafile.close();
             return buffer;
         }
     }
     return NULL;
 }
References __GIM_EXIST, gim_password_obj::calc(), and dna().
advanced_password()
_gim_buffer gim_cryptography_obj::advanced_password (_gim_buffer buffer, _gim_Ulong size)
An efficient method to encrypt or decrypt a buffer
Performance = not excessive good
Safety = very good
Password = needed
.
Parameters
buffer The buffer you want to crypt/decrypt
size The size of the buffer
Returns
a buffer crypted/decrypted
Definition at line 73 of file gim_gkp_cryptography.cc.
{
     internal_gim->set_state( __GIM_TH_CRYPT );
     _gim_Ulong  y = 0 , j = 0;
     _gim_rand   mt;
     int rnd[4];
     char message[64];
     calc();
     sprintf( gim_interface->data->item_sou_name , "Step 1/%d" , iter+1 );
     mt.seed( seed_main );
     gim_interface->data->sou_size = size;
     for ( j = 0 ; j < size ; j++ ) {
 //      if ( internal_gim->get_state() != __GIM_TH_STOP ) {
             rnd[0] =  mt.randInt( GIM_SHA1_SIZE     - 1 );
             rnd[1] =  mt.randInt( GIM_MD5_SIZE      - 1 );
             rnd[2] =  mt.randInt( GIM_SHA256_SIZE   - 1 );
             rnd[3] =  mt.randInt( GIM_SHA512_SIZE   - 1 );
             *(buffer + j) ^= password_sha1  [ rnd[0] ];
             *(buffer + j) ^= password_md5   [ rnd[1] ];
             *(buffer + j) ^= password_sha256[ rnd[2] ];
             *(buffer + j) ^= password_sha512[ rnd[3] ];
             *(buffer + j) ^= mt.randInt( 255 );
             *(buffer + j) ^= mt.randInt( 255 );
             gim_interface->data->sou_ratio = (float)( (float)j / (float)size );
             gim_interface->data->sou_position = j;
 /*      }
         else {
             gim_error->set( "gim_cryptography_obj::advanced_password" , "Stopped by user" );
             internal_gim->set_state( __GIM_TH_STOPPED );
             return NULL;
         }
 */  }
     for ( y = 0 ; y < iter ; y++ ) {
         sprintf( gim_interface->data->item_sou_name , "Step %d/%d" , y+2 , iter+1 );
         for ( j = 0 ; j < size ; j++ ) {
 //          if ( internal_gim->get_state() != __GIM_TH_STOP ) {
                 *(buffer + j) ^= mt.randInt( 255 );
                 gim_interface->data->sou_ratio = (float)( (float)j / (float)size );
                 gim_interface->data->sou_position = j;
 /*          }
             else {
                 gim_error->set( "gim_cryptography_obj::advanced_password" , "Stopped by user" );
                 internal_gim->set_state( __GIM_TH_STOPPED );
                 return NULL;
             }
 */      }
     }
     gim_error->set( "gim_cryptography_obj::advanced_password" , "Done" );
     internal_gim->set_state( __GIM_TH_IDLE );
     return buffer;
 }
References __GIM_TH_CRYPT, __GIM_TH_IDLE, gim_password_obj::calc(), gim_error, gim_interface, GIM_MD5_SIZE, GIM_SHA1_SIZE, GIM_SHA256_SIZE, GIM_SHA512_SIZE, internal_gim, gim_interface_data::item_sou_name, gim_error_obj::set(), gim_obj::set_state(), gim_interface_data::sou_position, gim_interface_data::sou_ratio, and gim_interface_data::sou_size.
Referenced by gim_gkfp_obj::extract_data(), gim_gkdp_obj::take(), and gim_gkfp_obj::write_data().
calc()
void gim_password_obj::calc (void) inherited
This function is used to calc the password digest and the inner seeds.
Definition at line 161 of file gim_gkp_password.cc.
{
     _gim_Uint8  c = 0 , t=0 ;
     gim_error->set( "gim_password_obj::calc" , "Calculating passworg digest and seed..." );
     if ( strlen( password ) == 0 )
         gim_error->set( GIM_ERROR_CRITICAL , "gim_password_obj::calc" , "No password setted. Security issue?" , __GIM_ERROR );
     if ( password_already_calc == __GIM_NO ) {
 //      puts("Calcolo!!!");
         t   = (_gim_int8)strlen( password );
         seed_md5    = 0 ;
         seed_sha1   = 0 ;
         seed_sha256 = 0 ;
         seed_sha512 = 0 ;
         seed_secondary = 0;
         seed_main   = 1 ;
     //  init - Digest
 //      puts("Copio i digest nella struttura");
         strncpy(password_md5    , gim_checksum->md5   ( password            , (unsigned long)t - 1 ) , sizeof(password_md5) );
         strncpy(password_sha1   , gim_checksum->sha1  ( password_md5        , (unsigned long)strlen( password_md5    ) - 1 ) , sizeof(password_sha1) );
         strncpy(password_sha256 , gim_checksum->sha256( password_sha1   , (unsigned long)strlen( password_sha1   ) - 1 ) , sizeof(password_sha256) );
         strncpy(password_sha512 , gim_checksum->sha512( password_sha256 , (unsigned long)strlen( password_sha256 ) - 1 ) , sizeof(password_sha512) );
 //      puts("Fatto... mi occupo della secondary");
         if ( strlen( secondary ) )
             strcpy(secondary_sha512 , gim_checksum->sha512( secondary   , (unsigned long)strlen( secondary ) ) );
     //  init - Sha1     Seed
 //      puts("Fatto... un po' di calcoli sui digest");
         for ( c = 0 ; c < GIM_SHA1_SIZE ; c++ )
             seed_sha1       += password_sha1[c] * Prime[c];
     //  init - Md5      Seed
         for ( c = 0 ; c < GIM_MD5_SIZE ; c++ )
             seed_md5        += password_md5[c] * Prime[c];
     //  init - Sha256   Seed
         for ( c = 0 ; c < GIM_SHA256_SIZE ; c++ )
             seed_sha256 += password_sha256[c] * Prime[c];
     //  init - Sha512   Seed
         for ( c = 0 ; c < GIM_SHA512_SIZE  ; c++ )
             seed_sha512 += password_sha512[c]  * Prime[c];
         if ( strlen( secondary_sha512 ) ) {
             for ( c = 0 ; c < GIM_SHA512_SIZE  ; c++ )
                 seed_secondary  += secondary_sha512[c]  * Prime[c];
         }
 //      puts("Fatto... altri calcoli");
         seed_main *= seed_md5;
         seed_main *= seed_sha1;
         seed_main *= seed_sha256;
         seed_main *= seed_sha512;
         if ( seed_secondary )
             seed_main *= seed_secondary;
 //      puts("Fatto... sto uscendo");
         //  NO recalc anymore
         password_already_calc = __GIM_YES;
         char message[256];
         sprintf( message , "Calculated. main_seed is 0x%ld" , seed_main );
         gim_error->set( "gim_password_obj::calc" , message );
     }
 }
References __GIM_ERROR, __GIM_NO, __GIM_YES, gim_checksum, gim_error, GIM_ERROR_CRITICAL, GIM_MD5_SIZE, GIM_SHA1_SIZE, GIM_SHA256_SIZE, GIM_SHA512_SIZE, gim_checksum_obj::md5(), gim_error_obj::set(), gim_checksum_obj::sha1(), gim_checksum_obj::sha256(), and gim_checksum_obj::sha512().
Referenced by advanced_dna(), advanced_password(), gim_cnc_encoding_obj::Fog_a_buffer(), gim_cnc_alfabeto_obj::make(), gim_password_obj::recalc(), and simple_password().
dna()
_gim_buffer gim_cryptography_obj::dna (_gim_buffer buffer, _gim_Ulong size, char * dna_file_name)
An very good method to encrypt or decrypt a buffer
It use an external file as key, so an other file is needed. Performance = good
Safety = optimal
Password = not needed
.
Parameters
buffer The buffer you want to crypt/decrypt
size The size of the buffer
dna_file_name The name of the file used as key
Returns
a buffer crypted/decrypted
Definition at line 124 of file gim_gkp_cryptography.cc.
{
     _gim_buffer dna;
     _gim_Ulong  c=0,j=0;
     _gim_file   dnafile( dna_file_name );
     if ( dnafile.check() == __GIM_EXIST ) {
         dna = dnafile.load();
         if ( dna ) {
             for ( j = 0 ; j < size ; j++ ) {
                 *(buffer + j) ^= *(dna + c);
                 ++c < dnafile.size() ? c : c = 0;
             }
             dnafile.close();
             return buffer;
         }
     }
     return NULL;
 }
References __GIM_EXIST.
Referenced by advanced_dna().
recalc()
void gim_password_obj::recalc (void) inherited
This function is used to recalc the password digest and the inner seeds.
Definition at line 218 of file gim_gkp_password.cc.
{
     gim_error->set( "gim_password_obj::recalc" , "Recalculating passworg digest and seed..." );
 //  puts("__GIM_CLEAR( password_md5...");
     __GIM_CLEAR( password_md5       , GIM_MD5_SIZE , char );
 //  puts("__GIM_CLEAR( password_sha1...");
     __GIM_CLEAR( password_sha1      , GIM_SHA1_SIZE , char );
 //  puts("__GIM_CLEAR( password_sha256...");
     __GIM_CLEAR( password_sha256    , GIM_SHA256_SIZE , char );
 //  puts("__GIM_CLEAR( password_sha512...");
     __GIM_CLEAR( password_sha512    , GIM_SHA512_SIZE , char );
 //  puts("__GIM_CLEAR( secondary_sha512...");
     __GIM_CLEAR( secondary_sha512   , GIM_SHA512_SIZE , char );
     seed_md5    = 0;
     seed_sha1   = 0;
     seed_sha256 = 0;
     seed_sha512 = 0;
     seed_secondary = 0;
     seed_main   = 0;
     password_already_calc = __GIM_NO;
 //  puts("Chiamo la calc");
     calc();
 }
References __GIM_CLEAR, __GIM_NO, gim_password_obj::calc(), gim_error, GIM_MD5_SIZE, GIM_SHA1_SIZE, GIM_SHA256_SIZE, GIM_SHA512_SIZE, and gim_error_obj::set().
Referenced by gim_password_obj::set(), and gim_password_obj::set_secondary().
set()
void gim_password_obj::set (const char * passwd) inherited
This function is used to set a password, used by Gim when necessary.
Parameters
passwd The password you want to set
Definition at line 124 of file gim_gkp_password.cc.
{
     if ( passwd == NULL )
         gim_error->set( GIM_ERROR_CRITICAL , "gim_password_obj::set" , "Null password. NO PASSWORD SETTED. Security issue?" , __GIM_ERROR );
     else {
         if ( strlen( passwd ) < min_lenght ) {
             gim_error->set( GIM_ERROR_WARNING , "gim_password_obj::set" , "Password very short. Security issue?" , __GIM_ERROR );
         }
         strcpy( password , passwd );
         gim_error->set( "gim_password_obj::set" , "New password setted" );
         recalc();
     }
 }
References __GIM_ERROR, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, gim_password_obj::recalc(), and gim_error_obj::set().
Referenced by gim_gkfp_obj::set_password(), and gim_gkdp_obj::set_password().
set_secondary()
void gim_password_obj::set_secondary (const char * passwd) inherited
This function is used to set a password, used by Gim when necessary.
Parameters
passwd The secondary password you want to set
Definition at line 138 of file gim_gkp_password.cc.
{
     if ( ! strlen( password ) )
         gim_error->set( GIM_ERROR_CRITICAL , "gim_password_obj::set_secondary" , "Null password. NO PASSWORD SETTED. Security issue?" , __GIM_ERROR );
     else {
         strcpy( secondary , passwd );
         gim_error->set( "gim_password_obj::set_secondary" , "New secondary password setted" );
         recalc();
     }
 }
References __GIM_ERROR, gim_error, GIM_ERROR_CRITICAL, gim_password_obj::recalc(), and gim_error_obj::set().
Referenced by gim_gkfp_obj::extract_data(), gim_gkdp_obj::take(), and gim_gkfp_obj::write_data().
simple_password()
_gim_buffer gim_cryptography_obj::simple_password (_gim_buffer buffer, _gim_Ulong size)
Definition at line 55 of file gim_gkp_cryptography.cc.
{
     _gim_Ulong  j=0;
     _gim_Ulong  c=0,len=0;
     _gim_rand   mt;
     calc();
     mt.seed( seed_main );
     len = (_gim_int8)strlen( password );
     for ( j = 0 ; j < size ; j++ ) {
         *(buffer+j) ^= password[c];
         *(buffer+j) ^= mt.randInt( 255 );
         ++c < len ? c : c = 0;
     }
     gim_error->set( "gim_cryptography_obj::simple_password" , "Done" );
     return buffer;
 }
References gim_password_obj::calc(), gim_error, and gim_error_obj::set().