My Project: Main Page
gim_utils_obj Class Reference
It is a clas with some useful methods for Gim.
#include <gim_gkp_utils.h>
Public Member Functions
char * del_path (char *str)
const char * dir_name_check (const char *dname)
_gim_flag isdevice (const char *)
_gim_flag isdir (const char *)
_gim_flag islink (const char *)
_gim_flag isregular (const char *)
char * keep_path (char *str)
char * pwd (void)
char * str_subtraction (char *main_str, char *to_subtract)
Detailed Description
It is a clas with some useful methods for Gim.
Warning
It is not possible to use directly this class.
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
1.0-0
Date
2003-2007
Definition at line 56 of file gim_gkp_utils.h.
Member Function Documentation
del_path()
char * gim_utils_obj::del_path (char * str)
Definition at line 39 of file gim_gkp_utils.cc.
{
     for ( char * s2 = str ; *s2 != '\0' ; s2++ )
         if ( *s2 == '/' )
             str = s2;
     return ++str;
 }
dir_name_check()
const char * gim_utils_obj::dir_name_check (const char * dname)
Definition at line 27 of file gim_gkp_utils.cc.
{
     _gim_int16  len;
     static char * res = NULL;
     len = strlen( dname );
     if ( dname[ len - 1 ] != '/' ) {
         res = strdup( dname );
         strcat( res , "/" );
         return res;
     }
     return dname;
 }
isdevice()
_gim_flag gim_utils_obj::isdevice (const char * d)
Definition at line 139 of file gim_gkp_utils.cc.
{
     struct stat buf;
     if ( lstat( d , &buf ) != 0) {
         gim_error->set( "gim_utils_obj::isdevice" , 24 );
         return __GIM_ERROR;
     }
     if ( S_ISCHR(buf.st_mode) || S_ISBLK(buf.st_mode) ) {
         //~ gim_error->set( "gim_utils_obj::isdevice" , 31 );
         return __GIM_YES;
     }
     else {
         //~ gim_error->set( "gim_utils_obj::isdevice" , 32 );
         return __GIM_NO;
     }
 }
References __GIM_ERROR, __GIM_NO, __GIM_YES, gim_error, and gim_error_obj::set().
Referenced by gim_file_obj::type().
isdir()
_gim_flag gim_utils_obj::isdir (const char * d)
Definition at line 86 of file gim_gkp_utils.cc.
{
     struct stat buf;
     if ( stat( d , &buf ) != 0 ) {
         gim_error->set( "gim_utils_obj::isdir" , 24 );
         return __GIM_ERROR;
     }
     if ( S_ISDIR( buf.st_mode ) ) {
         //~ gim_error->set( "gim_utils_obj::isdir" , 25 );
         return __GIM_YES;
     }
     else {
         //~ gim_error->set( "gim_utils_obj::isdir" , 26 );
         return __GIM_NO;
     }
 }
References __GIM_ERROR, __GIM_NO, __GIM_YES, gim_error, and gim_error_obj::set().
Referenced by gim_file_obj::type().
islink()
_gim_flag gim_utils_obj::islink (const char * d)
Definition at line 122 of file gim_gkp_utils.cc.
{
     struct stat buf;
     if ( lstat( d , &buf ) != 0) {
         gim_error->set( "gim_utils_obj::islink" , 24 );
         return __GIM_ERROR;
     }
     if ( S_ISLNK(buf.st_mode) ) {
         //~ gim_error->set( "gim_utils_obj::islink" , 29 );
         return __GIM_YES;
     }
     else {
         //~ gim_error->set( "gim_utils_obj::islink" , 30 );
         return __GIM_NO;
     }
 }
References __GIM_ERROR, __GIM_NO, __GIM_YES, gim_error, and gim_error_obj::set().
Referenced by gim_file_obj::type().
isregular()
_gim_flag gim_utils_obj::isregular (const char * d)
Definition at line 103 of file gim_gkp_utils.cc.
{
     struct stat buf;
     char message[2048];
     if (lstat( d , &buf ) != 0) {
         sprintf( message , "Some problem with stat/lstat : %s" , d );
         gim_error->set( GIM_ERROR_CRITICAL , "gim_utils_obj::isregular" , message , __GIM_ERROR );
         return __GIM_ERROR;
     }
     if ( S_ISREG( buf.st_mode ) ) {
         //~ gim_error->set( "gim_utils_obj::isregular" , 27 );
         return __GIM_YES;
     }
     else {
         //~ gim_error->set( "gim_utils_obj::isregular" , 28 );
         return __GIM_NO;
     }
 }
References __GIM_ERROR, __GIM_NO, __GIM_YES, gim_error, GIM_ERROR_CRITICAL, and gim_error_obj::set().
Referenced by gim_file_manager_obj::open(), and gim_file_obj::type().
keep_path()
char * gim_utils_obj::keep_path (char * str)
Definition at line 66 of file gim_gkp_utils.cc.
{
     int c;
     char *str2 = strdup( str );
     int l = strlen( str2 );
     for ( c = l-1 ; c > 0 ; c-- ) {
         if ( *(str2 + c)  == '/' ) {
             *(str2 + c + 1) = '\0';
             return str2;
         }
     }
     return str2;
 }
pwd()
char * gim_utils_obj::pwd (void)
Definition at line 80 of file gim_gkp_utils.cc.
{
     static char curdir[1024];
     getcwd( curdir , sizeof( curdir ) );
     return curdir;
 }
str_subtraction()
char * gim_utils_obj::str_subtraction (char * main_str, char * to_subtract)
Definition at line 47 of file gim_gkp_utils.cc.
{
     int     c;
     int     l  = strlen( main_str );
     int     l1 = strlen( to_subtract );
     char    message[1024];
 //  printf( "M:%s@(%d)  -  S:%s@(%d)\n" , main_str , strlen( main_str ) , to_subtract , strlen( to_subtract ) );
     if ( strlen( main_str ) <= strlen( to_subtract ) ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_utils_obj::str_subtraction" , "Main string cannot be <= the subtraction string" , __GIM_ERROR );
         return NULL;
     }
     for ( c = 0 ; c <= l1 ; c++ ) {
         if ( *(main_str+c)  != *(to_subtract+c) ) {
 //          puts( main_str+c );
             return main_str+c;
         }
     }
     return NULL;
 }
References __GIM_ERROR, gim_error, GIM_ERROR_WARNING, and gim_error_obj::set().
Referenced by gim_gkfp_obj::extract_data().