My Project: Main Page
gim_string_obj Class Reference
This class allows you to use the texts as objects.
#include <gim_string.h>
Public Member Functions
char * c_str (void)
_gim_Uint16 capacity (void)
void cat (char *to_cat)
void clean (void)
_gim_flag empty (void)
_gim_flag equal (char *to_compare)
_gim_flag equal (gim_string_obj to_compare)
_gim_flag find (char *to_find)
gim_string_obj ()
gim_string_obj (char *to_set)
char * left_find (char *to_find)
char * left_find (char to_find)
char * left_find (gim_string_obj to_find)
_gim_Uint16 length (void)
char * right_find (char *to_find)
char * right_find (char to_find)
char * right_find (gim_string_obj to_find)
void set (char *to_set)
_gim_Uint16 size (void)
~gim_string_obj ()
Detailed Description
This class allows you to use the texts as objects.
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
2.0-0
Date
2003-2008
Definition at line 66 of file gim_string.h.
Constructor & Destructor Documentation
gim_string_obj() [1/2]
gim_string_obj::gim_string_obj () inline
Definition at line 93 of file gim_string.h.
{
                 gim_error->set( "gim_string_obj::gim_string_obj" , "String requested" );
                 data = new gim_string_data;
                 __GIM_CLEAR( data->str , 32768 , char );
                 __GIM_CLEAR( data->str_bkup , 32768 , char );
                 data->str_len = 0;
                 gim_error->set( "gim_string_obj::gim_string_obj" , "Done" );
             };
References __GIM_CLEAR, gim_error, gim_error_obj::set(), gim_string_data::str, gim_string_data::str_bkup, and gim_string_data::str_len.
gim_string_obj() [2/2]
gim_string_obj::gim_string_obj (char * to_set) inline
Definition at line 102 of file gim_string.h.
{
                 gim_error->set( "gim_string_obj::gim_string_obj" , "String requested with parameter" );
                 data = new gim_string_data;
                 __GIM_CLEAR( data->str , 32768 , char );
                 __GIM_CLEAR( data->str_bkup , 32768 , char );
                 strcpy( data->str , to_set );
                 data->str_len = strlen( data->str );
                 gim_error->set( "gim_string_obj::gim_string_obj" , "Done" );
             };
References __GIM_CLEAR, gim_error, gim_error_obj::set(), gim_string_data::str, gim_string_data::str_bkup, and gim_string_data::str_len.
~gim_string_obj()
gim_string_obj::~gim_string_obj () inline
Definition at line 112 of file gim_string.h.
{
                 delete data;
             };
Member Function Documentation
c_str()
char * gim_string_obj::c_str (void)
Definition at line 46 of file gim_string.cc.
{
     if ( strlen( data->str ) != 0 )
         return data->str;
     return NULL;
 }
References gim_string_data::str.
capacity()
_gim_Uint16 gim_string_obj::capacity (void)
Definition at line 63 of file gim_string.cc.
{
     return 32768;
 }
cat()
void gim_string_obj::cat (char * to_cat)
Definition at line 75 of file gim_string.cc.
{
     if ( strlen( data->str ) != 0 )
         strcat( data->str , to_cat );
 }
References gim_string_data::str.
clean()
void gim_string_obj::clean (void)
Definition at line 39 of file gim_string.cc.
{
     __GIM_CLEAR( data->str_bkup , 32768 , char );
     __GIM_CLEAR( data->str_bkup , 32768 , char );
     data->str_len = 0;
 }
References __GIM_CLEAR, gim_string_data::str_bkup, and gim_string_data::str_len.
empty()
_gim_flag gim_string_obj::empty (void)
Definition at line 68 of file gim_string.cc.
{
     if ( strlen( data->str ) != 0 )
         return __GIM_NO;
     return __GIM_YES;
 }
References __GIM_NO, __GIM_YES, and gim_string_data::str.
equal() [1/2]
_gim_flag gim_string_obj::equal (char * to_compare)
Definition at line 118 of file gim_string.cc.
{
 }
equal() [2/2]
_gim_flag gim_string_obj::equal (gim_string_obj to_compare)
Definition at line 123 of file gim_string.cc.
{
 }
find()
_gim_flag gim_string_obj::find (char * to_find)
Definition at line 81 of file gim_string.cc.
{
     if ( strstr( data->str , to_find ) != NULL )
         return __GIM_YES;
     return __GIM_NO;
 }
References __GIM_NO, __GIM_YES, and gim_string_data::str.
left_find() [1/3]
char * gim_string_obj::left_find (char * to_find)
Definition at line 93 of file gim_string.cc.
{
     return NULL;
 }
left_find() [2/3]
char * gim_string_obj::left_find (char to_find)
Definition at line 88 of file gim_string.cc.
{
     return NULL;
 }
left_find() [3/3]
char * gim_string_obj::left_find (gim_string_obj to_find)
Definition at line 98 of file gim_string.cc.
{
     return NULL;
 }
length()
_gim_Uint16 gim_string_obj::length (void)
Definition at line 58 of file gim_string.cc.
{
     return data->str_len;
 }
References gim_string_data::str_len.
right_find() [1/3]
char * gim_string_obj::right_find (char * to_find)
Definition at line 108 of file gim_string.cc.
{
     return NULL;
 }
right_find() [2/3]
char * gim_string_obj::right_find (char to_find)
Definition at line 103 of file gim_string.cc.
{
     return NULL;
 }
right_find() [3/3]
char * gim_string_obj::right_find (gim_string_obj to_find)
Definition at line 113 of file gim_string.cc.
{
     return NULL;
 }
set()
void gim_string_obj::set (char * to_set)
Definition at line 28 of file gim_string.cc.
{
     gim_error->set( "gim_string_obj::set" , "Setting a new string value" );
     if ( strlen( data->str ) != 0 )
         strcpy( data->str_bkup , data->str );
     __GIM_CLEAR( data->str , 32768 , char );
     strcpy( data->str , to_set );
     data->str_len = strlen( data->str );
     gim_error->set( "gim_string_obj::set" , "Done" );
 }
References __GIM_CLEAR, gim_error, gim_error_obj::set(), gim_string_data::str, gim_string_data::str_bkup, and gim_string_data::str_len.
size()
_gim_Uint16 gim_string_obj::size (void)
Definition at line 53 of file gim_string.cc.
{
     return data->str_len;
 }
References gim_string_data::str_len.