My Project: Main Page
gim_db_obj Class Reference
This class is an integrated and generic pourpose light database.
#include <gim_db.h>
Public Member Functions
_gim_flag add_field_to_table (const char *table_name, const char *field_name, _gim_flag is_key, _gim_flag field_type)
_gim_flag add_field_to_table (const char *table_name, const char *field_name, _gim_flag is_key, _gim_flag field_type, _gim_db_value *value)
_gim_flag check (void)
_gim_flag create_table (const char *table_name)
_gim_flag exist_environment (const char *dbname)
void gdbs_close (void)
_gim_flag gdbs_execute (void)
_gim_flag gdbs_feof (void)
char * gdbs_getline (void)
_gim_flag gdbs_line_syntax_check (_gim_Uint8 NoT)
_gim_flag gdbs_open (void)
_gim_int8 gdbs_tokenizer (char *line)
char * get_name (void)
gim_db_obj ()
_gim_flag init (void)
_gim_flag init_from_gdbs (const char *gdbs_name)
_gim_flag make_env (void)
_gim_flag read (const char *dbname)
_gim_db_table * seek_table (char *table_name)
_gim_flag set_name (const char *dbname)
_gim_flag set_property (_gim_flag property, _gim_flag value)
_gim_flag table_exist (char *table_name)
~gim_db_obj ()
Detailed Description
This class is an integrated and generic pourpose light database.
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
2.5-0
Date
2003-2008
Definition at line 57 of file gim_db.h.
Constructor & Destructor Documentation
gim_db_obj()
gim_db_obj::gim_db_obj () inline
gim_db_obj constructor
Definition at line 133 of file gim_db.h.
{
                 if ( strlen( gim_application_name ) != 0 ) {
                     gim_error->set( "gim_db_obj::gim_db_obj" , "DB : Constructor start" );
                     db = (_gim_db_main *)gim_memory->Alloc( sizeof( _gim_db_main ) , __GIM_MEM_DB_MAIN , __GIM_HIDE );
                     strcpy( name            , "" );
                     strcpy( comment         , "" );
                     strcpy( file_name       , "" );
                     strcpy( file_name_long  , "" );
                     db->mode = GIM_DB_PERFORMANCE;
                     db->type = GIM_DB_VOLATILE;
                     db->tables_number = 0;
                     strcpy( db->pin_table , "" );
                     db->pin = __GIM_NO;
                     db->conf = new _gim_prsr;
                     db->tables = new _gim_list;
                     cs = new gim_checksum_obj;
                     lex = new _gim_lex;
                     initiated   = __GIM_NO;
                     changed     = __GIM_NO;
                     syntax = (SyntaxCoerence_obj *)gim_memory->Alloc( sizeof( SyntaxCoerence_obj ) , __GIM_MEM_DB_MAIN , __GIM_HIDE );
                     syntax->Title = __GIM_OFF;
                     syntax->Section = __GIM_OFF;
                     syntax->Feof = __GIM_OFF;
                     gdbs_script  = new _gim_list;
                     gdbs_run = __GIM_NOT_RUNNING;
                     gim_error->set( "gim_db_obj::gim_db_obj" , "DB : Constructor end" );
                 }
                 else
                     gim_error->set( GIM_ERROR_FATAL , "gim_db_obj::gim_db_obj" , "DB : initialization error : use of db is not allowed without the application name" , __GIM_ERROR );
             };
References __GIM_ERROR, __GIM_HIDE, __GIM_MEM_DB_MAIN, __GIM_NO, __GIM_NOT_RUNNING, __GIM_OFF, gim_memory_obj::Alloc(), _gim_db_main::conf, SyntaxCoerence_obj::Feof, gim_application_name, GIM_DB_PERFORMANCE, GIM_DB_VOLATILE, gim_error, GIM_ERROR_FATAL, gim_memory, _gim_db_main::mode, _gim_db_main::pin, _gim_db_main::pin_table, SyntaxCoerence_obj::Section, gim_error_obj::set(), _gim_db_main::tables, _gim_db_main::tables_number, SyntaxCoerence_obj::Title, and _gim_db_main::type.
~gim_db_obj()
gim_db_obj::~gim_db_obj () inline
gim_db_obj destructor
Definition at line 166 of file gim_db.h.
{
                 delete lex;
                 delete cs;
                 if ( strlen( name  ) ) {
                     gim_error->Set( GIM_ERROR_MESSAGE ,  "gim_db_obj::~gim_db_obj" , "DB [%s] : start to shutting down..." , name );
                 }
                 else
                     gim_error->set( "gim_db_obj::~gim_db_obj" , "DB : start to shutting down..." );
                 if ( ( db->type == GIM_DB_PERMANENT ) && ( changed == __GIM_YES ) ) {
                     gim_error->set( "gim_db_obj::~gim_db_obj" , "DB : Something is changed in configuration. Updating" );
                     db->conf->Write();
                 }
                 if ( db->tables->items() ) {
                     gim_error->set( "gim_db_obj::~gim_db_obj" , "DB : Some allocated Table found. Deallocating" );
                     db->tables->rewind();
                     for ( _gim_int32 c = 0 ; c < db->tables_number ; c++ ) {
                         _gim_db_table * Ttmp = (_gim_db_table *)db->tables->get_item();
                         Ttmp->Tstruct->Down();
                         Ttmp->Tdata->Down();
 /*                      if ( Ttmp->fields->items() )
                             Ttmp->fields->destroy_list();
 */                      delete Ttmp->fields;
                         if ( Ttmp->records->items() ) {
                             gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::~gim_db_obj" , "DB : Found some records [%d]. Deallocating..." , Ttmp->records->items() );
                             for( _gim_int32 r = 1 ; r <= Ttmp->records->items() ; r++ ) {
                                 _gim_db_record * tr = (_gim_db_record *)Ttmp->records->get_item();
                                 tr->values->destroy_list();
                                 Ttmp->records->next_item();
                             }
                             Ttmp->records->destroy_list();
                         }
                         delete Ttmp->records;
                         gim_memory->Free( Ttmp );
                         db->tables->next_item();
                     }
                 }
                 delete gdbs_script;
                 gim_memory->Free ( syntax );
                 delete db->tables;
                 db->conf->Down();
                 delete db->conf;
                 gim_memory->Free( db );
                 gim_error->set( "gim_db_obj::~gim_db_obj" , "DB : shutted down" );
             };
References __GIM_YES, _gim_db_main::conf, _gim_db_table::fields, gim_memory_obj::Free(), GIM_DB_PERMANENT, gim_error, GIM_ERROR_MESSAGE, gim_memory, _gim_db_table::records, gim_error_obj::set(), gim_error_obj::Set(), _gim_db_main::tables, _gim_db_main::tables_number, _gim_db_table::Tdata, _gim_db_table::Tstruct, _gim_db_main::type, and _gim_db_record::values.
Member Function Documentation
add_field_to_table() [1/2]
_gim_flag gim_db_obj::add_field_to_table (const char * table_name, const char * field_name, _gim_flag is_key, _gim_flag field_type)
add_field_to_table() [2/2]
_gim_flag gim_db_obj::add_field_to_table (const char * table_name, const char * field_name, _gim_flag is_key, _gim_flag field_type, _gim_db_value * value)
check()
_gim_flag gim_db_obj::check (void)
create_table()
_gim_flag gim_db_obj::create_table (const char * table_name)
exist_environment()
_gim_flag gim_db_obj::exist_environment (const char * dbname)
Definition at line 365 of file gim_db.cc.
{
     if ( ( strlen( dbname ) > 64 ) || ( strlen( dbname ) < 1 ) ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_db_obj::exist_environment" , "The db name must be lenght between 1 and 64 std characters" , __GIM_ERROR );
         return __GIM_ERROR;
     }
     char        tmp_name[64];
     _gim_flag   result;
     strcpy( tmp_name    , dbname );
     strcpy( name    , lex->char_subst( tmp_name , ' ' , '_' ) );
     sprintf( home   , "%s%s" , env_data->home , name );
     sprintf( file_name  , "%s.conf" , name );
     sprintf( file_name_long , "%s/%s" , home , file_name );
     result = db->conf->Exist( file_name_long );
     if ( result != __GIM_EXIST ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_db_obj::exist_environment" , "I cannot found the DB environment." , __GIM_ERROR );
         return __GIM_NOT_EXIST;
     }
     gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::exist_environment" , "DB environment succesfully found." );
     return __GIM_EXIST;
 }
References __GIM_ERROR, __GIM_EXIST, __GIM_NOT_EXIST, _gim_db_main::conf, env_data, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_MESSAGE, GIM_ERROR_WARNING, gim_conf_data::home, gim_error_obj::set(), and gim_error_obj::Set().
gdbs_close()
void gim_db_obj::gdbs_close (void)
Definition at line 421 of file gim_db.cc.
{
     if ( !strlen( gdbs_file_name ) ) {
         gim_error->set( GIM_ERROR_WARNING , "prsr_lexical_class::gdbs_close" , "No file name set" , __GIM_ERROR  );
     }
     else if ( ! gdbs_file ) {
         gim_error->set( GIM_ERROR_WARNING , "prsr_lexical_class::gdbs_close" , "File is not open" , __GIM_ERROR  );
     }
     else {
         gim_file_manager->close( gdbs_file );
         gim_error->set( "prsr_lexical_class::gdbs_close" , "File closed" );
     }
 }
References __GIM_ERROR, gim_file_manager_obj::close(), gim_error, GIM_ERROR_WARNING, gim_file_manager, and gim_error_obj::set().
Referenced by init_from_gdbs().
gdbs_execute()
_gim_flag gim_db_obj::gdbs_execute (void)
Definition at line 822 of file gim_db.cc.
{
     if ( ! gdbs_script->items() ) {
         gim_error->Set( GIM_ERROR_WARNING , "gim_db_obj::gdbs_execute" , "Script list is empty. Nothing to do." );
         return __GIM_ERROR;
     }
     gdbs_script->rewind();
     _gim_gdbs_line   * line = NULL;
     gim_error->Set( "gim_db_obj::gdbs_execute" , "EXECUTING GDBS ITEMS [%3d]..." , gdbs_script->items() );
     do {
         line = (_gim_gdbs_line *)gdbs_script->get_item();
         if ( line != NULL ) {
             switch ( line->command ) {
                 case __GDBS_CREATE_DB : {
                     gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , "EXECUTING LINE [%3d] : CREATE DB..." , line->lline  );
                     set_name( line->fparameter );
                     init();
                     break;
                 }
                 case __GDBS_ADD_FIELD : {
                     gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , "EXECUTING LINE [%3d] : ADD FIELD..." , line->lline  );
                     make_add_field( line->fvalue , line->svalue , line->tparameter );
                     break;
                 }
                 case __GDBS_CREATE_TABLE : {
                     make_create_table( line->fparameter );
                     break;
                 }
                 case __GDBS_PIN_TABLE : {
                     gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , "EXECUTING LINE [%3d] : PIN TABLE..." , line->lline  );
                     if ( db->pin == __GIM_YES ) {
                         gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , "A table is already pinned [%s]" , db->pin_table );
                         break;
                     }
                     if ( table_exist( line->fparameter ) == __GIM_YES ) {
                         strcpy( db->pin_table , line->fparameter );
                         db->pin = __GIM_YES;
                         db->Ttab = seek_table( db->pin_table );
                         gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , "table succesfully pinned [%s]" , db->pin_table );
                     }
                     else
                         gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , "table not found [%s]" , line->fparameter );
                     break;
                 }
                 case __GDBS_SET_DB : {
                     gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , "EXECUTING LINE [%3d] : SET DB..." , line->lline  );
                     make_set_db( line->fvalue );
                     break;
                 }
                 case __GDBS_SET_FIELD : {
                     gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , "EXECUTING LINE [%3d] : SET FIELD..." , line->lline  );
                     make_set_field( line->fvalue , line->svalue );
                     break;
                 }
                 case __GDBS_SET_TABLE : {
                     gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , "EXECUTING LINE [%3d] : SET TABLE..." , line->lline  );
                     make_set_table( line->fvalue );
                     break;
                 }
                 case __GDBS_UNPIN_TABLE : {
                     gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , "EXECUTING LINE [%3d] : UNPIN TABLE..." , line->lline  );
                     if ( db->pin == __GIM_NO ) {
                         gim_error->Set( GIM_ERROR_WARNING , "gim_db_obj::gdbs_execute" , "No table is pinned" , __GIM_ERROR );
                         break;
                     }
                     if ( db->Ttab == NULL ) {
                         gim_error->Set( GIM_ERROR_WARNING , "gim_db_obj::gdbs_execute" , "NO table pointer is pinned" , __GIM_ERROR );
                         break;
                     }
                     strcpy( db->pin_table , "" );
                     db->pin = __GIM_NO;
                     db->Ttab = NULL;
                     gim_error->set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , "table succesfully unpinned" , __GIM_OK );
                     break;
                 }
                 case __GDBS_INSERT : {
                     gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , "EXECUTING LINE [%3d] : INSERT..." , line->lline  );
                     if ( db->pin == __GIM_YES ) {
                         gim_error->Set( GIM_ERROR_WARNING , "gim_db_obj::gdbs_execute" , "A table is already pinned [%s]" , db->pin_table );
                         break;
                     }
                     if ( table_exist( line->fparameter ) == __GIM_YES ) {
                         char H[128];
                         strcpy( db->pin_table , line->fparameter );
                         db->pin = __GIM_YES;
                         db->Ttab = seek_table( db->pin_table );
                         gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , "table succesfully pinned [%s]" , db->pin_table );
                         db->Ttab->items++;
                         _gim_db_record * Trec = (_gim_db_record *)gim_memory->Alloc( sizeof( _gim_db_record ) , __GIM_MEM_DB_MAIN , __GIM_HIDE );
                         strcpy( Trec->hash , "" );
                         Trec->index = db->Ttab->items;
                         Trec->values = new _gim_list;
                         sprintf( H , "Record %d - Address id %p" , db->Ttab->items , Trec );
                         strcpy( Trec->hash , cs->md5( H , strlen( H ) ) );
                         gim_error->set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , H , __GIM_OK );
                         gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , "Generated Hash [%s]" , Trec->hash );
                         db->Ttab->Tdata->AddSection( Trec->hash );
                         db->Ttab->fields->rewind();
                         line->ins->rewind();
                         _gim_Uint8 iter = db->Ttab->fields->items();
                         if ( iter ) {
                             for( _gim_Uint8 i = 1 ; i <= iter ; i++ ) {
                                 _gim_db_field * Tfield = (_gim_db_field *)db->Ttab->fields->get_item( i );
                                 _gim_gdbs_line_insert * Tlins = (_gim_gdbs_line_insert *)line->ins->get_item( i );
                                 _gim_db_value * Tv = (_gim_db_value *)gim_memory->Alloc( sizeof( _gim_db_value ) , __GIM_MEM_DB_MAIN , __GIM_HIDE );
                                 gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , "Record [%d] - Label [%16s] - Value[%12s] - Type [%2d]" , db->Ttab->items , Tlins->label , Tlins->value.value.Char , Tfield->type );
                                 Tv->type = Tfield->type;
                                 switch ( Tv->type ) {
                                     case GIM_DB_TYPE_INT : {
                                         Tv->value.Int = atoi( Tlins->value.value.Char );
                                         db->Ttab->Tdata->AddKey( Trec->hash , Tfield->name , Tv->value.Int );
                                         break;
                                     }
                                     case GIM_DB_TYPE_FLOAT : {
                                         break;
                                     }
                                     case GIM_DB_TYPE_PERCENTAGE : {
                                         Tv->value.Int = atoi( Tlins->value.value.Char );
                                         db->Ttab->Tdata->AddKey( Trec->hash , Tfield->name , Tv->value.Int );
                                         break;
                                     }
                                     case GIM_DB_TYPE_BOOL : {
                                         if      ( lex->str_equal( lex->str_down( Tlins->value.value.Char , strlen( Tlins->value.value.Char ) ) , "true" ) == __GIM_YES )
                                             Tv->value.Bool = __GIM_TRUE;
                                         else if ( lex->str_equal( lex->str_down( Tlins->value.value.Char , strlen( Tlins->value.value.Char ) ) , "false" ) == __GIM_YES )
                                             Tv->value.Bool = __GIM_FALSE;
                                         db->Ttab->Tdata->AddKeyFlag( Trec->hash , Tfield->name , Tv->value.Bool );
                                         break;
                                     }
                                     case GIM_DB_TYPE_FLAG : {
                                         if      ( lex->str_equal( lex->str_down( Tlins->value.value.Char , strlen( Tlins->value.value.Char ) ) , "on" ) == __GIM_YES )
                                             Tv->value.Flag = __GIM_ON;
                                         else if ( lex->str_equal( lex->str_down( Tlins->value.value.Char , strlen( Tlins->value.value.Char ) ) , "off" ) == __GIM_YES )
                                             Tv->value.Flag = __GIM_OFF;
                                         else if ( lex->str_equal( lex->str_down( Tlins->value.value.Char , strlen( Tlins->value.value.Char ) ) , "yes" ) == __GIM_YES )
                                             Tv->value.Flag = __GIM_YES;
                                         else if ( lex->str_equal( lex->str_down( Tlins->value.value.Char , strlen( Tlins->value.value.Char ) ) , "no" ) == __GIM_YES )
                                             Tv->value.Flag = __GIM_NO;
                                         db->Ttab->Tdata->AddKeyFlag( Trec->hash , Tfield->name , Tv->value.Flag );
                                         break;
                                     }
                                     case GIM_DB_TYPE_STRING : {
                                         strcpy( Tv->value.Char , Tlins->value.value.Char );
                                         db->Ttab->Tdata->AddKey( Trec->hash , Tfield->name , Tv->value.Char );
                                         break;
                                     }
                                     case GIM_DB_TYPE_DATE : {
                                         strcpy( Tv->value.Char , Tlins->value.value.Char );
                                         db->Ttab->Tdata->AddKey( Trec->hash , Tfield->name , Tv->value.Char );
                                         break;
                                     }
                                     case GIM_DB_TYPE_TIME : {
                                         strcpy( Tv->value.Char , Tlins->value.value.Char );
                                         db->Ttab->Tdata->AddKey( Trec->hash , Tfield->name , Tv->value.Char );
                                         break;
                                     }
                                     case GIM_DB_TYPE_TIMESTAMP : {
                                         Tv->value.Int = atoi( Tlins->value.value.Char );
                                         db->Ttab->Tdata->AddKey( Trec->hash , Tfield->name , Tv->value.Int );
                                         break;
                                     }
                                 }
                                 Trec->values->add_item( Tv );
                             }
                             if ( db->type == GIM_DB_PERMANENT )
                                 db->Ttab->Tdata->Write();
                             line->ins->destroy_list();
                         }
                         else {
                         }
                         strcpy( db->pin_table , "" );
                         db->pin = __GIM_NO;
                         db->Ttab = NULL;
                         gim_error->set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_execute" , "table succesfully unpinned" , __GIM_OK );
                     }
                     else
                         gim_error->Set( GIM_ERROR_WARNING , "gim_db_obj::gdbs_execute" , "table not found [%s]" , line->fparameter );
                     break;
                 }
             }
             gdbs_script->next_item();
         }
     } while ( line != NULL );
     return __GIM_OK;
 }
References __GDBS_ADD_FIELD, __GDBS_CREATE_DB, __GDBS_CREATE_TABLE, __GDBS_INSERT, __GDBS_PIN_TABLE, __GDBS_SET_DB, __GDBS_SET_FIELD, __GDBS_SET_TABLE, __GDBS_UNPIN_TABLE, __GIM_ERROR, __GIM_FALSE, __GIM_HIDE, __GIM_MEM_DB_MAIN, __GIM_NO, __GIM_OFF, __GIM_OK, __GIM_ON, __GIM_TRUE, __GIM_YES, gim_memory_obj::Alloc(), gim_db_value_u::Bool, gim_db_value_u::Char, _gim_gdbs_line::command, _gim_db_table::fields, gim_db_value_u::Flag, _gim_gdbs_line::fparameter, _gim_gdbs_line::fvalue, GIM_DB_PERMANENT, GIM_DB_TYPE_BOOL, GIM_DB_TYPE_DATE, GIM_DB_TYPE_FLAG, GIM_DB_TYPE_FLOAT, GIM_DB_TYPE_INT, GIM_DB_TYPE_PERCENTAGE, GIM_DB_TYPE_STRING, GIM_DB_TYPE_TIME, GIM_DB_TYPE_TIMESTAMP, gim_error, GIM_ERROR_MESSAGE, GIM_ERROR_WARNING, gim_memory, _gim_db_record::hash, _gim_db_record::index, init(), _gim_gdbs_line::ins, gim_db_value_u::Int, _gim_db_table::items, _gim_gdbs_line_insert::label, _gim_gdbs_line::lline, gim_checksum_obj::md5(), _gim_db_field::name, _gim_db_main::pin, _gim_db_main::pin_table, seek_table(), gim_error_obj::set(), gim_error_obj::Set(), set_name(), _gim_gdbs_line::svalue, table_exist(), _gim_db_table::Tdata, _gim_gdbs_line::tparameter, _gim_db_main::Ttab, _gim_db_value::type, _gim_db_field::type, _gim_db_main::type, _gim_db_value::value, _gim_gdbs_line_insert::value, and _gim_db_record::values.
Referenced by init_from_gdbs().
gdbs_feof()
_gim_flag gim_db_obj::gdbs_feof (void)
Definition at line 333 of file gim_db.cc.
{
     if ( syntax->Feof == __GIM_OFF )
         return __GIM_NO;
     return __GIM_YES;
 }
References __GIM_NO, __GIM_OFF, __GIM_YES, and SyntaxCoerence_obj::Feof.
Referenced by init_from_gdbs().
gdbs_getline()
char * gim_db_obj::gdbs_getline (void)
Definition at line 388 of file gim_db.cc.
{
     if ( ! gdbs_file ) {
         gim_error->set( GIM_ERROR_CRITICAL , "prsr_lexical_class::gdbs_getline" , "No open file" , __GIM_ERROR  );
         return NULL;
     }
     static char line[PRSR_MAX_LINE];
     __GIM_VCLEAR( line , PRSR_MAX_LINE , char ,'\0' );
     fgets( line , PRSR_MAX_LINE , gdbs_file->fp );
     if ( feof( gdbs_file->fp ) )
         syntax->Feof = __GIM_ON;
     strcat( line, "\0" );
     return line;
 }
References __GIM_ERROR, __GIM_ON, __GIM_VCLEAR, SyntaxCoerence_obj::Feof, gim_global_item_handler::fp, gim_error, GIM_ERROR_CRITICAL, PRSR_MAX_LINE, and gim_error_obj::set().
Referenced by init_from_gdbs().
gdbs_line_syntax_check()
_gim_flag gim_db_obj::gdbs_line_syntax_check (_gim_Uint8 NoT)
Definition at line 435 of file gim_db.cc.
{
     static _gim_Uint8   id;
     id = 0;
     if      ( ( lex->str_equal( Tok[0] , "CREATE" ) == __GIM_YES ) && ( NoT == 3 ) )
         id += 10;
     else if ( ( lex->str_equal( Tok[0] , "ADD" ) == __GIM_YES ) && ( ( NoT == 5 ) || ( NoT == 6 ) ) )
         id += 20;
     else if ( ( lex->str_equal( Tok[0] , "SET" ) == __GIM_YES ) && ( ( NoT == 4 ) || ( NoT == 3 ) ) )
         id += 30;
     else if ( ( lex->str_equal( Tok[0] , "PIN" ) == __GIM_YES ) && ( NoT == 3 ) )
         id += 40;
     else if ( ( lex->str_equal( Tok[0] , "UNPIN" ) == __GIM_YES ) && ( NoT == 2 ) )
         id += 50;
     else if ( ( lex->str_equal( Tok[0] , "INSERT" ) == __GIM_YES ) && ( NoT >= 4 ) )
         id += 60;
     else
         id = 0;
     if      ( ( lex->str_equal( Tok[1] , "DB" ) == __GIM_YES ) && ( id == 10 ) )
         id += 1;
     else if ( ( lex->str_equal( Tok[1] , "TABLE" ) == __GIM_YES ) && ( id == 10 ) )
         id += 2;
     else if ( ( lex->str_equal( Tok[1] , "FIELD" ) == __GIM_YES ) && ( id == 20 ) )
         id += 1;
     else if ( ( lex->str_equal( Tok[1] , "DB" ) == __GIM_YES ) && ( id == 30 ) )
         id += 1;
     else if ( ( lex->str_equal( Tok[1] , "TABLE" ) == __GIM_YES ) && ( id == 30 ) )
         id += 2;
     else if ( ( lex->str_equal( Tok[1] , "FIELD" ) == __GIM_YES ) && ( id == 30 ) )
         id += 3;
     else if ( ( lex->str_equal( Tok[1] , "TABLE" ) == __GIM_YES ) && ( id == 40 ) )
         id += 1;
     else if ( ( lex->str_equal( Tok[1] , "TABLE" ) == __GIM_YES ) && ( id == 50 ) )
         id += 1;
     else if ( id == 60 )
         id += 1;
     else
         id = 0;
     if ( id == 0 ) {
         gim_error->Set( GIM_ERROR_CRITICAL , "gim_db_obj::gdbs_line_syntax_check" , "UNKNOWN TOKEN : ID = %2d - NoT = %d - [%s] [%s]", id , NoT , Tok[0] , Tok[1] );
         return __SYNTAX_ERROR;
     }
     gim_error->Set( "gim_db_obj::gdbs_line_syntax_check" , "ID = %2d - NoT = %d - [%s] [%s]", id , NoT , Tok[0] , Tok[1] );
     switch ( id ) {
         case 11 : {
             _gim_gdbs_line * line = (_gim_gdbs_line *)gim_memory->Alloc( sizeof( _gim_gdbs_line ) , __GIM_GDBS_LINE , __GIM_HIDE );
             if ( line == NULL ) {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_db_obj::gdbs_line_syntax_check" , "GDBS line allocation failed." , __GIM_ERROR );
                 return __GIM_ERROR;
             }
             line->lline = gdbs_line_num;
             line->command = __GDBS_CREATE_DB;
             strcpy( line->fparameter , Tok[2] );
             gdbs_script->add_item( (void *)line );
             gim_error->set( "gim_db_obj::gdbs_line_syntax_check" , "Syntax ok! CREATE DB command added to list." );
             return __GDBS_CREATE_DB;
         }
         case 12 : {
             _gim_gdbs_line * line = (_gim_gdbs_line *)gim_memory->Alloc( sizeof( _gim_gdbs_line ) , __GIM_GDBS_LINE , __GIM_HIDE );
             if ( line == NULL ) {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_db_obj::gdbs_line_syntax_check" , "GDBS line allocation failed." , __GIM_ERROR );
                 return __GIM_ERROR;
             }
             line->lline = gdbs_line_num;
             line->command = __GDBS_CREATE_TABLE;
             strcpy( line->fparameter , Tok[2] );
             gdbs_script->add_item( line );
             gim_error->set( "gim_db_obj::gdbs_line_syntax_check" , "Syntax ok! CREATE TABLE command added to list." );
             return __GDBS_CREATE_DB;
         }
         case 21 : {
             _gim_gdbs_line * line = (_gim_gdbs_line *)gim_memory->Alloc( sizeof( _gim_gdbs_line ) , __GIM_GDBS_LINE , __GIM_HIDE );
             if ( line == NULL ) {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_db_obj::gdbs_line_syntax_check" , "GDBS line allocation failed." , __GIM_ERROR );
                 return __GIM_ERROR;
             }
             line->lline = gdbs_line_num;
             line->command = __GDBS_ADD_FIELD;
             line->fvalue = atoi( Tok[2] );
             line->svalue = string_to_flag( 3 , __GIM_FIELD );
             if ( line->svalue == __GIM_ERROR ) {
                 gim_error->Set( GIM_ERROR_CRITICAL , "gim_db_obj::gdbs_line_syntax_check" , "UNKNOWN PROPERTIES [%s]." , Tok[3] );
                 return __SYNTAX_ERROR;
             }
             strcpy( line->tparameter , Tok[4] );
             if ( NoT == 6 )
                 line->tvalue = atoi( Tok[5] );
             gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_line_syntax_check" , "[id field %d] [type %d] [name %s]" , line->fvalue , line->svalue , line->tparameter );
             gdbs_script->add_item( line );
             gim_error->set( "gim_db_obj::gdbs_line_syntax_check" , "Syntax ok! ADD FIELD command added to list." );
             return __GDBS_ADD_FIELD;
         }
         case 31 : {
             _gim_gdbs_line * line = (_gim_gdbs_line *)gim_memory->Alloc( sizeof( _gim_gdbs_line ) , __GIM_GDBS_LINE , __GIM_HIDE );
             if ( line == NULL ) {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_db_obj::gdbs_line_syntax_check" , "GDBS line allocation failed." , __GIM_ERROR );
                 return __GIM_ERROR;
             }
             line->lline = gdbs_line_num;
             line->command = __GDBS_SET_DB;
             line->fvalue = string_to_flag( 2 , __GIM_DB );
             if ( line->fvalue == __GIM_ERROR ) {
                 gim_error->Set( GIM_ERROR_CRITICAL , "gim_db_obj::gdbs_line_syntax_check" , "UNKNOWN PROPERTIES [%s]." , Tok[2] );
                 return __SYNTAX_ERROR;
             }
             gdbs_script->add_item( line );
             gim_error->set( "gim_db_obj::gdbs_line_syntax_check" , "Syntax ok! SET DB command added to list." );
             return __GDBS_SET_DB;
         }
         case 32 : {
             _gim_gdbs_line * line = (_gim_gdbs_line *)gim_memory->Alloc( sizeof( _gim_gdbs_line ) , __GIM_GDBS_LINE , __GIM_HIDE );
             if ( line == NULL ) {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_db_obj::gdbs_line_syntax_check" , "GDBS line allocation failed." , __GIM_ERROR );
                 return __GIM_ERROR;
             }
             line->lline = gdbs_line_num;
             line->command = __GDBS_SET_TABLE;
             line->fvalue = string_to_flag( 2 , __GIM_TABLE );
             if ( line->fvalue == __GIM_ERROR ) {
                 gim_error->Set( GIM_ERROR_CRITICAL , "gim_db_obj::gdbs_line_syntax_check" , "UNKNOWN PROPERTIES [%s]." , Tok[2] );
                 return __SYNTAX_ERROR;
             }
             gdbs_script->add_item( line );
             gim_error->set( "gim_db_obj::gdbs_line_syntax_check" , "Syntax ok! SET TABLE command added to list." );
             return __GDBS_SET_TABLE;
         }
         case 33 : {
             _gim_gdbs_line * line = (_gim_gdbs_line *)gim_memory->Alloc( sizeof( _gim_gdbs_line ) , __GIM_GDBS_LINE , __GIM_HIDE );
             if ( line == NULL ) {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_db_obj::gdbs_line_syntax_check" , "GDBS line allocation failed." , __GIM_ERROR );
                 return __GIM_ERROR;
             }
             line->lline = gdbs_line_num;
             line->command = __GDBS_SET_FIELD;
             line->fvalue = atoi( Tok[2] );
             line->svalue = string_to_flag( 3 , __GIM_FIELD );
             if ( line->svalue == __GIM_ERROR ) {
                 gim_error->Set( GIM_ERROR_CRITICAL , "gim_db_obj::gdbs_line_syntax_check" , "UNKNOWN PROPERTIES [%s]." , Tok[3] );
                 return __SYNTAX_ERROR;
             }
 //          printf( "%s = %d  -  %s = %d\n" ,  Tok[2] , line->fvalue , Tok[3] , line->svalue );
             gdbs_script->add_item( line );
             gim_error->set( "gim_db_obj::gdbs_line_syntax_check" , "Syntax ok! SET TABLE command added to list." );
             return __GDBS_SET_FIELD;
         }
         case 41 : {
             _gim_gdbs_line * line = (_gim_gdbs_line *)gim_memory->Alloc( sizeof( _gim_gdbs_line ) , __GIM_GDBS_LINE , __GIM_HIDE );
             if ( line == NULL ) {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_db_obj::gdbs_line_syntax_check" , "GDBS line allocation failed." , __GIM_ERROR );
                 return __GIM_ERROR;
             }
             line->lline = gdbs_line_num;
             line->command = __GDBS_PIN_TABLE;
             strcpy( line->fparameter , Tok[2] );
             gdbs_script->add_item( line );
             gim_error->set( "gim_db_obj::gdbs_line_syntax_check" , "Syntax ok! SET TABLE command added to list." );
             return __GDBS_PIN_TABLE;
         }
         case 51 : {
             _gim_gdbs_line * line = (_gim_gdbs_line *)gim_memory->Alloc( sizeof( _gim_gdbs_line ) , __GIM_GDBS_LINE , __GIM_HIDE );
             if ( line == NULL ) {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_db_obj::gdbs_line_syntax_check" , "GDBS line allocation failed." , __GIM_ERROR );
                 return __GIM_ERROR;
             }
             line->lline = gdbs_line_num;
             line->command = __GDBS_UNPIN_TABLE;
             gdbs_script->add_item( line );
             gim_error->set( "gim_db_obj::gdbs_line_syntax_check" , "Syntax ok! SET TABLE command added to list." );
             return __GDBS_UNPIN_TABLE;
         }
         case 61 : {
 //          _gim_Uint8 iter = 0;
             _gim_gdbs_line * line = (_gim_gdbs_line *)gim_memory->Alloc( sizeof( _gim_gdbs_line ) , __GIM_GDBS_LINE , __GIM_HIDE );
             if ( line == NULL ) {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_db_obj::gdbs_line_syntax_check" , "GDBS line allocation failed." , __GIM_ERROR );
                 return __GIM_ERROR;
             }
             line->lline = gdbs_line_num;
             line->command = __GDBS_INSERT;
             strcpy( line->fparameter , Tok[1] );
             line->ins = new _gim_list;
 //          iter = ( ( NoT - 2 ) / 2 ) ;
             for( int t = 2 ; t < ( NoT ) ; t++ ) {
                 _gim_gdbs_line_insert * Tlins = (_gim_gdbs_line_insert *)gim_memory->Alloc( sizeof( _gim_gdbs_line_insert ) , __GIM_GDBS_LINE , __GIM_HIDE );
                 if ( Tlins == NULL ) {
                     gim_error->set( GIM_ERROR_CRITICAL , "gim_db_obj::gdbs_line_syntax_check" , "GDBS line allocation failed." , __GIM_ERROR );
                     return __GIM_ERROR;
                 }
                 strcpy( Tlins->label , Tok[t] );
                 strcpy( Tlins->value.value.Char , Tok[++t] );
                 gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::gdbs_line_syntax_check" , "GDBS Insert: Data [%16s = %-16s]" , Tlins->label , Tlins->value.value.Char );
                 line->ins->add_item( Tlins );
             }
             gdbs_script->add_item( line );
             gim_error->set( "gim_db_obj::gdbs_line_syntax_check" , "Syntax ok! SET TABLE command added to list." );
             return __GDBS_INSERT;
         }
     }
     return 0;
 }
References __GDBS_ADD_FIELD, __GDBS_CREATE_DB, __GDBS_CREATE_TABLE, __GDBS_INSERT, __GDBS_PIN_TABLE, __GDBS_SET_DB, __GDBS_SET_FIELD, __GDBS_SET_TABLE, __GDBS_UNPIN_TABLE, __GIM_DB, __GIM_ERROR, __GIM_FIELD, __GIM_GDBS_LINE, __GIM_HIDE, __GIM_TABLE, __GIM_YES, __SYNTAX_ERROR, gim_memory_obj::Alloc(), gim_db_value_u::Char, _gim_gdbs_line::command, _gim_gdbs_line::fparameter, _gim_gdbs_line::fvalue, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_MESSAGE, gim_memory, _gim_gdbs_line::ins, _gim_gdbs_line_insert::label, _gim_gdbs_line::lline, gim_error_obj::set(), gim_error_obj::Set(), _gim_gdbs_line::svalue, Tok, _gim_gdbs_line::tparameter, _gim_gdbs_line::tvalue, _gim_db_value::value, and _gim_gdbs_line_insert::value.
Referenced by init_from_gdbs().
gdbs_open()
_gim_flag gim_db_obj::gdbs_open (void)
Definition at line 405 of file gim_db.cc.
{
     if ( !strlen( gdbs_file_name ) ) {
         gim_error->set( GIM_ERROR_CRITICAL , "prsr_lexical_class::gdbs_open" , "No file name set" , __GIM_ERROR  );
         return __GIM_ERROR;
     }
     gdbs_file = gim_file_manager->open( gdbs_file_name , __GIM_FILE_POINTER , __GIM_READ );
     if ( ! gdbs_file ) {
         gim_error->set( GIM_ERROR_CRITICAL , "prsr_lexical_class::gdbs_open" , "File not found" , __GIM_ERROR  );
         return __GIM_ERROR;
     }
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_FILE_POINTER, __GIM_OK, __GIM_READ, gim_error, GIM_ERROR_CRITICAL, gim_file_manager, gim_file_manager_obj::open(), and gim_error_obj::set().
Referenced by init_from_gdbs().
gdbs_tokenizer()
_gim_int8 gim_db_obj::gdbs_tokenizer (char * line)
Definition at line 701 of file gim_db.cc.
{
     if ( !strlen( line ) )
         return __SKIPPED;
     static unsigned int i;
     unsigned int        a , b = 0;
     volatile _gim_flag  for_exit = __GIM_NO , termination = __GIM_NO , comment = __GIM_NO;
     i = 0;
     __GIM_VCLEAR( Tok , 1 , Tok , '\0' );
     strcat( line , " " );
     if ( lex->is_in_string( GDBS_TERMINATOR_CHAR , line ) == __GIM_YES )
         termination = __GIM_YES;
     for( a = 0 ; ( ( a < ( strlen( line ) - 1 ) ) && ( for_exit == __GIM_NO ) ) ; a++ ) {
         if ( ( i > 19 ) || ( line[a] == GDBS_STOP_CHAR ) ) {
             comment = __GIM_YES;
             break;
         }
         if ( lex->is_in_string( line[a] , GDBS_SKIP_STR ) == __GIM_NO ) {
             if ( lex->is_in_string( line[a] , GDBS_SEPARATOR_STR ) ) {
                 if ( b ) {
                     Tok[i++][b] = '\0' ;
                     b=0;
                 }
                 else
                     continue;
             }
             else
                 Tok[i][b++] = line[a];
         }
     }
     gim_error->Set( GIM_ERROR_MESSAGE , "prsr_lexical_class::gdbs_tokenizer" , "Summary: [line: %3d] [Len: %3d] [NoT: %2d] [termination: %d] [comment: %d]" , gdbs_line_num , strlen( line ) , i , termination , comment );
     if ( i > 19 ) {
         gim_error->set( GIM_ERROR_CRITICAL , "prsr_lexical_class::gdbs_tokenizer" , "too much token in line" , __GIM_ERROR  );
         return __TOO_MUCH_TOKEN;
     }
     else if ( ( ( i <= 1 ) && ( comment == __GIM_NO ) && ( strlen( line ) > 2 ) ) ) {
         return __SYNTAX_ERROR;
     }
     else if ( ( i ) && ( strlen( Tok[0] ) ) && ( termination == __GIM_YES ) ) {
         gim_error->Set( GIM_ERROR_MESSAGE , "prsr_lexical_class::gdbs_tokenizer" , "Correct GDBS line analyzed [extracted %d token]" , i );
         return i;
     }
     else if ( ( i ) && ( !strlen( Tok[0] ) ) && ( termination == __GIM_YES ) ) {
         gim_error->set( GIM_ERROR_CRITICAL , "prsr_lexical_class::gdbs_tokenizer" , "Syntax error in GDBS file" , __GIM_ERROR  );
         return __SYNTAX_ERROR;
     }
     else if ( ( i ) && ( strlen( Tok[0] ) ) && ( termination == __GIM_NO ) ) {
         gim_error->set( GIM_ERROR_CRITICAL , "prsr_lexical_class::gdbs_tokenizer" , "Missing line terminator in GDBS file" , __GIM_ERROR  );
         return __MISSING_STOP_CHAR;
     }
     return __SKIPPED;
 }
References __GIM_ERROR, __GIM_NO, __GIM_VCLEAR, __GIM_YES, __MISSING_STOP_CHAR, __SKIPPED, __SYNTAX_ERROR, __TOO_MUCH_TOKEN, GDBS_SEPARATOR_STR, GDBS_SKIP_STR, GDBS_STOP_CHAR, GDBS_TERMINATOR_CHAR, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_MESSAGE, gim_error_obj::set(), gim_error_obj::Set(), and Tok.
Referenced by init_from_gdbs().
get_name()
char* gim_db_obj::get_name (void)
init()
_gim_flag gim_db_obj::init (void)
Definition at line 194 of file gim_db.cc.
{
     _gim_flag   res;
     initiated = __GIM_NO;
     switch( db->conf->Read( file_name_long ) ) {
         case __GIM_OK : {
             gim_error->set( "gim_db_obj::init" , "DB : Properities read succesfully" );
             db->tables_number = db->conf->GetKeyINT( "DB" , "tables" );
             db->type = db->conf->GetKeyINT( "DB" , "type" );
             db->mode = db->conf->GetKeyINT( "DB" , "mode" );
             db->tables_number = db->conf->GetKeyINT( "DB" , "tables" );
             res = GIM_DB_READ;
             break;
         }
         case __GIM_NOT_EXIST : {
             db->conf->Up( file_name_long , name );
             db->conf->SetLex( __LEX_B );
             db->conf->AddSection( "VERSION" );
             db->conf->AddKey( "VERSION" , "major"               , GIM_MAJOR );
             db->conf->AddKey( "VERSION" , "minor"               , GIM_MINOR );
             db->conf->AddSection( "DB" );
             db->conf->AddKey( "DB"      , "application_name"    , gim_application_name );
             db->conf->AddKey( "DB"      , "name"                , name );
             db->conf->AddKey( "DB"      , "type"                , db->type );
             db->conf->AddKey( "DB"      , "mode"                , db->mode );
             db->conf->AddKey( "DB"      , "tables"              , db->tables_number );
             if ( db->type == GIM_DB_PERMANENT ) {
                 make_env();
                 db->conf->Write();
                 gim_error->set( GIM_ERROR_WARNING , "gim_db_obj::init" , "DB : Conf file wrote" , __GIM_ERROR );
             }
             if ( db->type == GIM_DB_VOLATILE ) {
                 gim_error->set( "gim_db_obj::init" , "DB : type VOLATILE : conf only in memory" );
             res = GIM_DB_NEW;
             }
             break;
         }
         case __LEX_UNKNOWN : {
             gim_error->set( GIM_ERROR_WARNING , "gim_db_obj::init" , "DB : Conf file Lex unknown. Rewriting" , __GIM_ERROR );
             db->conf->Up( file_name , name );
             db->conf->SetLex( __LEX_B );
             db->conf->AddSection( "VERSION" );
             db->conf->AddKey( "VERSION" , "major"               , GIM_MAJOR );
             db->conf->AddKey( "VERSION" , "minor"               , GIM_MINOR );
             db->conf->AddSection( "DB" );
             db->conf->AddKey( "DB"      , "application_name"    , gim_application_name );
             db->conf->AddKey( "DB"      , "name"                , name );
             db->conf->AddKey( "DB"      , "file"                , file_name );
             db->conf->AddKey( "DB"      , "type"                , db->type );
             db->conf->AddKey( "DB"      , "mode"                , db->mode );
             db->conf->AddKey( "DB"      , "tables"              , db->tables_number );
             db->conf->Write();
             res = GIM_DB_NEW;
             break;
         }
         case __SYNTAX_ERROR : {
             db->conf->Up( file_name , name );
             db->conf->SetLex( __LEX_B );
             db->conf->AddSection( "VERSION" );
             db->conf->AddKey( "VERSION" , "major"               , GIM_MAJOR );
             db->conf->AddKey( "VERSION" , "minor"               , GIM_MINOR );
             db->conf->AddSection( "DB" );
             db->conf->AddKey( "DB"      , "application_name"    , gim_application_name );
             db->conf->AddKey( "DB"      , "name"                , name );
             db->conf->AddKey( "DB"      , "file"                , file_name );
             db->conf->AddKey( "DB"      , "type"                , db->type );
             db->conf->AddKey( "DB"      , "mode"                , db->mode );
             db->conf->AddKey( "DB"      , "tables"              , db->tables_number );
             db->conf->Write();
             gim_error->set( GIM_ERROR_WARNING , "gim_db_obj::init" , "DB : Some syntax error in the conf file. Rewriting" , __GIM_ERROR );
             res = GIM_DB_NEW;
             break;
         }
     }
     if ( res == GIM_DB_READ ) {
         initiated   = __GIM_YES;
         if ( Lexical.str_equal( db->conf->GetKeySTR( "DB" , "application_name" ) , gim_application_name  ) != __GIM_YES ) {
             gim_error->Set( GIM_ERROR_FATAL , "gim_db_obj::init" , "DB : WRONG APPLICATION NAME [DB %s - APP %s]" , db->conf->GetKeySTR( "DB" , "application_name" ) , gim_application_name );
             initiated   = __GIM_NO;
             return __GIM_ERROR;
         }
         if ( gim_db_version( db->conf->GetKeyINT( "VERSION" , "major" ) , db->conf->GetKeyINT( "VERSION" , "minor" ) ) == __GIM_OK )
             gim_error->set( "gim_db_obj::init" , "DB : This version of Gim is compatible" );
         else {
             gim_error->set( GIM_ERROR_FATAL , "gim_db_obj::init" , "DB : This version of Gim is not compatible with this DB" , __GIM_ERROR );
             initiated   = __GIM_NO;
             gdbs_run = __GIM_NOT_READY;
             return __GIM_ERROR;
         }
         if ( db->tables_number ) {
             read_tables();
         }
     }
     return res;
 }
References __GIM_ERROR, __GIM_NO, __GIM_NOT_EXIST, __GIM_NOT_READY, __GIM_OK, __GIM_YES, __LEX_B, __LEX_UNKNOWN, __SYNTAX_ERROR, _gim_db_main::conf, gim_application_name, GIM_DB_NEW, GIM_DB_PERMANENT, GIM_DB_READ, GIM_DB_VOLATILE, gim_error, GIM_ERROR_FATAL, GIM_ERROR_WARNING, GIM_MAJOR, GIM_MINOR, Lexical, make_env(), _gim_db_main::mode, gim_error_obj::set(), gim_error_obj::Set(), prsr_lexical_class::str_equal(), _gim_db_main::tables_number, and _gim_db_main::type.
Referenced by gdbs_execute(), and read().
init_from_gdbs()
_gim_flag gim_db_obj::init_from_gdbs (const char * gdbs_name)
Definition at line 639 of file gim_db.cc.
{
     _gim_int8 t = 0;
     _gim_int8 s = 0;
     _gim_int8 f = 0;
     _gim_int8 l = 1;
     gdbs_line_num = 1;
     if ( gdbs_run != __GIM_NOT_RUNNING ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_db_obj::init_from_gdbs" , "GDBS engin is not in the correct state" , __GIM_ERROR );
         return __GIM_ERROR;
     }
     gdbs_run = __GIM_RUNNING;
     gim_error->Set( GIM_ERROR_OK , "gim_db_obj::init_from_gdbs" , "Start reading GDBS file [%s]" , gdbs_name );
     strcpy( gdbs_file_name , gdbs_name );
     gdbs_open();
     while ( ( ! gdbs_feof() ) && ( t >= 0 ) ) {
         gim_error->Set( GIM_ERROR_MESSAGE , "prsr_lexical_class::init_from_gdbs" , "Parsing line %d..." , l );
         t = gdbs_tokenizer( gdbs_getline() );
         if ( t < 0 ) {
             if ( t ==  __TOO_MUCH_TOKEN ) {
                 gim_error->Set( GIM_ERROR_CRITICAL , "prsr_lexical_class::init_from_gdbs" , "Parse: too much token in line %d" , l );
                 return __TOO_MUCH_TOKEN;
             }
             else if ( t == __MISSING_STOP_CHAR ) {
                 gim_error->Set( GIM_ERROR_CRITICAL , "prsr_lexical_class::init_from_gdbs" , "Parse: Missing line terminator in line %d" , l );
                 return __MISSING_STOP_CHAR;
             }
             else if ( t == __SYNTAX_ERROR ) {
                 gim_error->Set( GIM_ERROR_CRITICAL , "prsr_lexical_class::init_from_gdbs" , "Parse: Syntax error in line %d" , l );
                 return __MISSING_STOP_CHAR;
             }
             else {
                 gim_error->Set( GIM_ERROR_CRITICAL , "prsr_lexical_class::init_from_gdbs" , "Parse: Something wrong in line %d" , l );
                 return __MISSING_STOP_CHAR;
             }
         }
         else if ( t > 0 ) {
             s = gdbs_line_syntax_check( t );
             if ( s < 0 ) {
                 if ( s == __SYNTAX_ERROR ) {
                     gim_error->Set( GIM_ERROR_CRITICAL , "prsr_lexical_class::init_from_gdbs" , "Syntax: Syntax error in line %d" , l );
                     return __GIM_ERROR;
                 }
                 else {
                     gim_error->Set( GIM_ERROR_CRITICAL , "prsr_lexical_class::init_from_gdbs" , "Syntax: Something wrong in syntax check in line %d" , l );
                     return __GIM_ERROR;
                 }
             }
         }
         else
             gim_error->Set( "prsr_lexical_class::init_from_gdbs" , "SKIPPED" );
         l++;
         gdbs_line_num++;
     }
     gdbs_close();
     f = gdbs_execute();
     gim_error->Set( "prsr_lexical_class::init_from_gdbs" , "GDBS: all done!" );
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_NOT_RUNNING, __GIM_OK, __GIM_RUNNING, __MISSING_STOP_CHAR, __SYNTAX_ERROR, __TOO_MUCH_TOKEN, gdbs_close(), gdbs_execute(), gdbs_feof(), gdbs_getline(), gdbs_line_syntax_check(), gdbs_open(), gdbs_tokenizer(), gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_MESSAGE, GIM_ERROR_OK, GIM_ERROR_WARNING, gim_error_obj::set(), and gim_error_obj::Set().
make_env()
_gim_flag gim_db_obj::make_env (void)
Definition at line 162 of file gim_db.cc.
{
     struct stat stat_home;
     if ( ( strlen( name ) > 64 ) || ( strlen( name ) < 1 ) ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_db_obj::make_env" , "You try to create the DB env but before you must to set the DB name" , __GIM_ERROR );
         return __GIM_ERROR;
     }
     if ( db->type == GIM_DB_PERMANENT ) {
         if ( stat( home , &stat_home ) ) {
             mkdir( home , 0777 );
             gim_error->set( "gim_db_obj::make_env" , "DB : env created" );
         }
         else
             gim_error->set( "gim_db_obj::make_env" , "DB : env already exist" );
     }
     else if ( db->type == GIM_DB_VOLATILE ) {
         if ( stat( home , &stat_home ) )
             gim_error->set( "gim_db_obj::make_env" , "DB : env not created : Volatile db" );
         else {
             gim_error->set( "gim_db_obj::make_env" , "DB : DB is set as VOLATILE but env exists. I remove it..." );
             char command[256];
             sprintf( command , "rm -rf %s" , home );
             system( command );
         }
     }
     else {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_db_obj::make_env" , "The DB state is unknown" , __GIM_ERROR );
         return __GIM_ERROR;
     }
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_OK, GIM_DB_PERMANENT, GIM_DB_VOLATILE, gim_error, GIM_ERROR_CRITICAL, gim_error_obj::set(), and _gim_db_main::type.
Referenced by init().
read()
_gim_flag gim_db_obj::read (const char * dbname)
Definition at line 340 of file gim_db.cc.
{
     if ( ( strlen( dbname ) > 64 ) || ( strlen( dbname ) < 1 ) ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_db_obj::read" , "The db name must be lenght between 1 and 64 std characters" , __GIM_ERROR );
         return __GIM_ERROR;
     }
     char        tmp_name[64];
     _gim_flag   result;
     strcpy( tmp_name    , dbname );
     strcpy( name    , lex->char_subst( tmp_name , ' ' , '_' ) );
     sprintf( home   , "%s%s" , env_data->home , name );
     sprintf( file_name  , "%s.conf" , name );
     sprintf( file_name_long , "%s/%s" , home , file_name );
     gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::read" , " Reading DB : %s" , lex->string_trunc( file_name_long , 60 ) );
     result = db->conf->Exist( file_name_long );
     if ( result == __GIM_NOT_EXIST ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_db_obj::read" , "I cannot found the DB file." , __GIM_ERROR );
         return __GIM_NOT_EXIST;
     }
     init();
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_NOT_EXIST, __GIM_OK, _gim_db_main::conf, env_data, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_MESSAGE, GIM_ERROR_WARNING, gim_conf_data::home, init(), gim_error_obj::set(), and gim_error_obj::Set().
seek_table()
_gim_db_table * gim_db_obj::seek_table (char * table_name)
Definition at line 1028 of file gim_db.cc.
{
     db->tables->rewind();
     for( ; db->tables->get_item() != NULL ; db->tables->next_item() ) {
         _gim_db_table * tmp = (_gim_db_table *)db->tables->get_item();
         if ( lex->str_equal( tmp->name , table_name ) == __GIM_YES ) {
             return tmp;
         }
     }
     return NULL;
 }
References __GIM_YES, _gim_db_table::name, and _gim_db_main::tables.
Referenced by gdbs_execute().
set_name()
_gim_flag gim_db_obj::set_name (const char * dbname)
Definition at line 49 of file gim_db.cc.
{
     if ( ( strlen( dbname ) > 64 ) || ( strlen( dbname ) < 1 ) ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_db_obj::set_name" , "The db name must be lenght between 1 and 64 std characters" , __GIM_ERROR );
         return __GIM_ERROR;
     }
     char    tmp_name[64];
     strcpy( tmp_name , dbname );
     strcpy( name    , lex->char_subst( tmp_name , ' ' , '_' ) );
     sprintf( home   , "%s%s" , env_data->home , name );
     sprintf( file_name  , "%s.conf" , name );
     sprintf( file_name_long , "%s/%s" , home , file_name );
     gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::set_name" , "DB : db name       [%s]" , name );
     gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::set_name" , "DB : db Fname      [%s]" , file_name );
     gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::set_name" , "DB : db home       [%s]" , home );
     gim_error->Set( GIM_ERROR_MESSAGE , "gim_db_obj::set_name" , "DB : db home/Fname [%s]" , file_name_long );
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_OK, env_data, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_MESSAGE, gim_conf_data::home, gim_error_obj::set(), and gim_error_obj::Set().
Referenced by gdbs_execute().
set_property()
_gim_flag gim_db_obj::set_property (_gim_flag property, _gim_flag value)
Definition at line 70 of file gim_db.cc.
{
     switch ( property ) {
         case GIM_DB_SAVE_MEMORY : {
             if ( value == __GIM_YES ) {
                 db->mode = GIM_DB_SAVE_MEMORY;
                 if ( initiated == __GIM_YES )
                     db->conf->ChangeKey( "property" , "mode" , GIM_DB_SAVE_MEMORY );
                 gim_error->set( "gim_db_obj::set_db_property" , "DB : mode setted to GIM_DB_SAVE_MEMORY" );
             }
             else {
                 db->mode = GIM_DB_BALANCED;
                 if ( initiated == __GIM_YES )
                     db->conf->ChangeKey( "property" , "mode" , GIM_DB_BALANCED );
                 gim_error->set( "gim_db_obj::set_db_property" , "DB : mode setted per default to GIM_DB_BALANCED" );
             }
             break;
         }
         case GIM_DB_PERFORMANCE : {
             if ( value == __GIM_YES ) {
                 db->mode = GIM_DB_PERFORMANCE;
                 if ( initiated == __GIM_YES )
                     db->conf->ChangeKey( "property" , "mode" , GIM_DB_PERFORMANCE );
                 gim_error->set( "gim_db_obj::set_db_property" , "DB : mode setted to GIM_DB_PERFORMANCE" );
             }
             else {
                 db->mode = GIM_DB_BALANCED;
                 if ( initiated == __GIM_YES )
                     db->conf->ChangeKey( "property" , "mode" , GIM_DB_BALANCED );
                 gim_error->set( "gim_db_obj::set_db_property" , "DB : mode setted per default to GIM_DB_BALANCED" );
             }
             break;
         }
         case GIM_DB_BALANCED : {
             if ( value == __GIM_YES ) {
                 db->mode = GIM_DB_BALANCED;
                 if ( initiated == __GIM_YES )
                     db->conf->ChangeKey( "property" , "mode" , GIM_DB_BALANCED );
                 gim_error->set( "gim_db_obj::set_db_property" , "DB : mode setted to GIM_DB_BALANCED" );
             }
             else {
                 db->mode = GIM_DB_BALANCED;
                 gim_error->set( "gim_db_obj::set_db_property" , "DB : mode setted per default to GIM_DB_BALANCED" );
                 gim_error->set( GIM_ERROR_WARNING , "gim_db_obj::set_db_property" , "DB :     You can't set GIM_DB_BALANCED to __GIM_MO" , __GIM_ERROR );
                 changed     = __GIM_NO;
                 return __GIM_ERROR;
             }
             break;
         }
         case GIM_DB_VOLATILE : {
             if ( value == __GIM_YES ) {
                 db->type = GIM_DB_VOLATILE;
                 if ( initiated == __GIM_YES )
                     db->conf->ChangeKey( "property" , "type" , GIM_DB_VOLATILE );
                 gim_error->set( "gim_db_obj::set_db_property" , "DB : type setted to GIM_DB_VOLATILE" );
             }
             else {
                 db->mode = GIM_DB_PERMANENT;
                 if ( initiated == __GIM_YES )
                     db->conf->ChangeKey( "property" , "type" , GIM_DB_PERMANENT );
                 gim_error->set( "gim_db_obj::set_db_property" , "DB : mode setted per default to GIM_DB_PERMANENT" );
             }
             break;
         }
         case GIM_DB_PERMANENT : {
             if ( value == __GIM_YES ) {
                 db->type = GIM_DB_PERMANENT;
                 if ( initiated == __GIM_YES )
                     db->conf->ChangeKey( "property" , "type" , GIM_DB_PERMANENT );
                 gim_error->set( "gim_db_obj::set_db_property" , "DB : type setted to GIM_DB_PERMANENT" );
             }
             else {
                 db->mode = GIM_DB_VOLATILE;
                 if ( initiated == __GIM_YES )
                     db->conf->ChangeKey( "property" , "type" , GIM_DB_VOLATILE );
                 gim_error->set( "gim_db_obj::set_db_property" , "DB : mode setted per default to GIM_DB_VOLATILE" );
             }
             break;
         }
         default : {
             gim_error->set( GIM_ERROR_CRITICAL , "gim_db_obj::set_db_property" , "DB :     Unknown property." , __GIM_ERROR );
             changed     = __GIM_NO;
             return __GIM_ERROR;
         }
     }
     if ( initiated == __GIM_YES )
         changed     = __GIM_YES;
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_NO, __GIM_OK, __GIM_YES, _gim_db_main::conf, GIM_DB_BALANCED, GIM_DB_PERFORMANCE, GIM_DB_PERMANENT, GIM_DB_SAVE_MEMORY, GIM_DB_VOLATILE, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, _gim_db_main::mode, gim_error_obj::set(), and _gim_db_main::type.
table_exist()
_gim_flag gim_db_obj::table_exist (char * table_name)
Definition at line 1012 of file gim_db.cc.
{
     if ( db->tables_number < 1 ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_db_obj::table_exist" , "Tables number is 0." , __GIM_ERROR );
         return __GIM_ERROR;
     }
     for ( _gim_int32 c = 1 ; c <= db->tables_number ; c++ ) {
         char Ttable[128];
         sprintf( Ttable , "tab%d_name" , c );
         if ( lex->str_equal( table_name , db->conf->GetKeySTR( "DB" , Ttable ) ) == __GIM_YES )
             return __GIM_YES;
     }
     gim_error->Set( GIM_ERROR_CRITICAL , "gim_db_obj::table_exist" , "Table not found [%s]" , table_name );
     return __GIM_NO;
 }
References __GIM_ERROR, __GIM_NO, __GIM_YES, _gim_db_main::conf, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, gim_error_obj::set(), gim_error_obj::Set(), and _gim_db_main::tables_number.
Referenced by gdbs_execute().