My Project: Main Page
gim_cnc_encoding_obj Class Reference
#include <gim_cnc_coding.h>
Public Member Functions
_gim_buffer Fog_a_buffer (_gim_buffer buffer, _gim_Ulong *buffer_lenght)
Use this function to encode a buffer.
char * Fog_a_byte (_gim_Uchar c, _gim_Uint32 base, _gim_Uint8 digit)
Use this function to encode a byte.
_gim_Uint32 min_digit (_gim_buffer buffer, _gim_Ulong buffer_lenght, _gim_int8 base)
Use this function to calculate the necessary minimum number of characters
to encode a buffer.
_gim_Uint32 min_digit (char *filename, _gim_int8 base)
Use this function to calculate the necessary minimum number of characters
to encode a file.
Detailed Description
Definition at line 42 of file gim_cnc_coding.h.
Member Function Documentation
Fog_a_buffer()
_gim_buffer gim_cnc_encoding_obj::Fog_a_buffer (_gim_buffer buffer, _gim_Ulong * buffer_lenght)
Use this function to encode a buffer.
Parameters
buffer Is the poiter to the buffer you want to encode
buffer != NULL
buffer_lenght Initially is the buffer lenght
At the end will be the lenght of the encoded buffer
buffer_lenght > 0
Returns
The pointer of the encoded buffer or NULL if some errors occurred
See also
Fog_a_byte()
Definition at line 18 of file gim_cnc_coding.cc.
{
     _gim_Uint32 i=0;
     char    *resti;
     _gim_Ulong  t=0,total=0;
     _gim_Uchar  c=0;
     _gim_buffer encoded;
     _gim_rand   mt;
     if ( ! cnc_data.coding_digit )
         cnc_data.coding_digit = min_digit( buffer , *(buffer_lenght) , cnc_data.coding_base ) ;
     cnc_NoSkema( __GIM_YES ) {
         cnc_password->calc();
         mt.seed( cnc_password->seed_md5 );
     }
     encoded = (_gim_buffer)gim_memory->Alloc( ( (*(buffer_lenght) + sizeof ( char )) * cnc_data.coding_digit ) );
     if ( ! encoded )
         gim_error->set( GIM_ERROR_CRITICAL , "cnc_encoding_class::Fog_a_buffer" , "No more free memory" , __GIM_ERROR );
     for (t = 0; t < *(buffer_lenght) ; t++) {
         c =  *(buffer + t );
         cnc_NoSkema( __GIM_YES )
             c ^= ( mt.randInt( 255 ) );
         resti = Fog_a_byte( c , cnc_data.coding_base , cnc_data.coding_digit );
         for ( i=0 ; i < cnc_data.coding_digit ; i++ ,total++ ) {
             *(encoded + total) = *(resti+i);
         }
     }
     *(buffer_lenght) *= cnc_data.coding_digit;
     gim_memory->Free( buffer );
     buffer = encoded;
     return encoded;
 }
References __GIM_ERROR, __GIM_YES, gim_memory_obj::Alloc(), gim_password_obj::calc(), cnc_data, cnc_NoSkema, cnc_password, cnc_Kernel_data_struct::coding_base, cnc_Kernel_data_struct::coding_digit, Fog_a_byte(), gim_memory_obj::Free(), gim_error, GIM_ERROR_CRITICAL, gim_memory, min_digit(), and gim_error_obj::set().
Fog_a_byte()
char * gim_cnc_encoding_obj::Fog_a_byte (_gim_Uchar c, _gim_Uint32 base, _gim_Uint8 digit)
Use this function to encode a byte.
Parameters
c Is the character to encode
((c >= 0) && (c < 256))
base It indicates tne base in which the character will be encoded
((base >= MIN_BASE) && (base <= MAX_BASE))
digit It indicates how many characters will compose the encode character
digit >= 2
Returns
The pointer of the string of the encoded character or NULL if some errors occurred
See also
Fog_a_buffer()
Definition at line 49 of file gim_cnc_coding.cc.
{
     int i=0, j=0 ;
     _gim_Uint32 ch=0;
     int         reverse[MAX_DIGIT];
     static char resti[MAX_DIGIT];
     memset ( resti , 0 , MAX_DIGIT );
     ch = c & 0xff;
     //~ cnc_Additive( __GIM_ON )
         //~ ch += cnc_data->password_seed_sha512;
     //~ cnc_Multiplier( __GIM_ON )
         //~ ch *= cnc_data->password_seed_md5;
     for (j = (digit - 1) ; j >= 0 ; j-- ) {
         reverse[j] = c % base;
         c /= base;
     }
     for (i = 0; i < digit; i++ )
         resti[i] = cnc_generic.num2char(reverse[i]);
     return resti;
 }
References cnc_generic, MAX_DIGIT, and gim_cnc_generic_obj::num2char().
Referenced by Fog_a_buffer().
min_digit() [1/2]
_gim_Uint32 gim_cnc_encoding_obj::min_digit (_gim_buffer buffer, _gim_Ulong buffer_lenght, _gim_int8 base)
Use this function to calculate the necessary minimum number of characters
to encode a buffer.
Parameters
buffer Is the buffer within to which trying the higest value to encode
buffer != NULL
buffer_lenght Is the lenght of the buffer to encode
buffer_lenght > 0
base It indicates tne base in which the character will be encoded
((base >= MIN_BASE) && (base <= MAX_BASE))
Returns
The minimum number of characters to encode the buffer
Definition at line 96 of file gim_cnc_coding.cc.
{
     _gim_Ulong  count = 0 , max = 0;
     _gim_Uchar  ch = 0;
     _gim_int8   mbit = MIN_DIGIT;
     cnc_NoSkema( __GIM_NO ) {
         while ( count < buffer_lenght ) {
             ch = *(buffer + count) ;
             if (ch > max)
                 max = ch;
             count++;
             if ( max == 255 )
                 break;
         }
     }
     cnc_NoSkema( __GIM_YES )
         max = 255;
     for ( ; tmp_crt(base, mbit, max) ; mbit++ );
     return mbit;
 }
References __GIM_NO, __GIM_YES, cnc_NoSkema, and MIN_DIGIT.
min_digit() [2/2]
_gim_Uint32 gim_cnc_encoding_obj::min_digit (char * filename, _gim_int8 base)
Use this function to calculate the necessary minimum number of characters
to encode a file.
Parameters
filename Is the name of the file within to which trying the higest value to encode
filename != NULL
base It indicates tne base in which the character will be encoded
((base >= MIN_BASE) && (base <= MAX_BASE))
Returns
The minimum number of characters to encode the file
Definition at line 69 of file gim_cnc_coding.cc.
{
     int         count = 0, max = 0;
     _gim_Uchar  ch = 0;
     char        * p;
     _gim_int8   mbit = MIN_DIGIT;
     _gim_file   fin( filename );
     cnc_NoSkema( __GIM_NO ) {
         if ( fin.check() == __GIM_NOT_EXIST )
             return __GIM_NO;
         p = fin.fm();
         while ( count < fin.size() )
         {
             ch = *( p + count ) & 0xff ;
             if (ch > max)
                 max = ch;
             count++;
             if ( max == 255 )
                 break;
         }
         fin.close();
     }
     cnc_NoSkema( __GIM_YES )
         max = 255;
     for ( ; tmp_crt( base, mbit, max ) ; mbit++ );
     return mbit;
 }
References __GIM_NO, __GIM_NOT_EXIST, __GIM_YES, cnc_NoSkema, and MIN_DIGIT.
Referenced by Fog_a_buffer().