My Project: Main Page
gim_getopt_obj Class Reference
#include <gim_getopt.h>
Public Member Functions
_gim_Uint32 err_members (void)
_gim_flag errors_present (void)
gim_option_item * geterror (void)
gim_option_item * getoption (void)
gim_getopt_obj ()
void nexterror (void)
void nextoption (void)
_gim_Uint32 opt_members (void)
void rewind (void)
void scanopt (int argc, char *const argv[])
void scanopt (int argc, char *const argv[], const char *useropt)
_gim_flag search (char opt)
void setopt (const char *useropt)
~gim_getopt_obj ()
Detailed Description
Definition at line 76 of file gim_getopt.h.
Constructor & Destructor Documentation
gim_getopt_obj()
gim_getopt_obj::gim_getopt_obj () inline
gim_getopt_obj constructor
Definition at line 102 of file gim_getopt.h.
{
                 gim_error->set( "gim_getopt_obj::gim_getopt_obj()" , "Getopt object allocated" );
                 optlist = new gim_list_obj;
                 errlist = new gim_list_obj;
                 opterr = 0;
             };
References gim_error, and gim_error_obj::set().
~gim_getopt_obj()
gim_getopt_obj::~gim_getopt_obj () inline
gim_getopt_obj distructor
Definition at line 112 of file gim_getopt.h.
{
                 optlist->destroy_list();
                 errlist->destroy_list();
                 gim_error->set( "gim_getopt_obj::gim_getopt_obj()" , "Getopt object deleted" );
             };
References gim_error, and gim_error_obj::set().
Member Function Documentation
err_members()
_gim_Uint32 gim_getopt_obj::err_members (void)
Definition at line 113 of file gim_getopt.cc.
{
     return  errlist->items();
 }
Referenced by errors_present().
errors_present()
_gim_flag gim_getopt_obj::errors_present (void)
Definition at line 124 of file gim_getopt.cc.
{
     if ( err_members() )
         return __GIM_YES;
     return __GIM_NO;
 }
References __GIM_NO, __GIM_YES, and err_members().
geterror()
gim_option_item * gim_getopt_obj::geterror (void)
Definition at line 93 of file gim_getopt.cc.
{
     return (gim_option_item *)errlist->get_item();
 }
getoption()
gim_option_item * gim_getopt_obj::getoption (void)
Definition at line 88 of file gim_getopt.cc.
{
     return (gim_option_item *)optlist->get_item();
 }
nexterror()
void gim_getopt_obj::nexterror (void)
Definition at line 103 of file gim_getopt.cc.
{
     errlist->next_item();
 }
nextoption()
void gim_getopt_obj::nextoption (void)
Definition at line 98 of file gim_getopt.cc.
{
     optlist->next_item();
 }
opt_members()
_gim_Uint32 gim_getopt_obj::opt_members (void)
Definition at line 108 of file gim_getopt.cc.
{
     return  optlist->items();
 }
rewind()
void gim_getopt_obj::rewind (void)
Definition at line 118 of file gim_getopt.cc.
{
     optlist->rewind();
     errlist->rewind();
 }
scanopt() [1/2]
void gim_getopt_obj::scanopt (int argc, char *const argv[])
Definition at line 46 of file gim_getopt.cc.
{
     _gim_option *  temp_opt = NULL;
     char c;
     while ( ( c = getopt ( argc , argv , options )) != -1 ) {
         temp_opt = (_gim_option *)gim_memory->Alloc ( sizeof( _gim_option ) , __GIM_GETOPT_ITEM , __GIM_HIDE  );
         temp_opt->option = c;
         if ( optarg == NULL )
             temp_opt->argument = NULL;
         else
             temp_opt->argument = strdup( optarg );
         temp_opt->opterror = optopt;
 //      printf( "opt %c - arg %s - optopt %X\n" , c , optarg , optopt );
         printf( "opt %c - arg %s - optopt %X\n" , temp_opt->option , temp_opt->argument , temp_opt->opterror );
         if ( ( c != '?' ) && ( c != ':' ) ) {
             temp_opt->status = __GIM_OPT_OK;
             optlist->add_item( temp_opt );
         }
         else {
             temp_opt->option = optopt;
             if ( options[0] == ':' ) {
                 if ( c == ':' )
                     temp_opt->status = __GIM_OPT_NO_ARG;
                 if ( c == '?' )
                     temp_opt->status = __GIM_OPT_UNKNOWN;
             }
             else {
                 if ( c == '?' )
                     temp_opt->status = __GIM_OPT_NOT_OK;
             }
             errlist->add_item( temp_opt );
         }
     }
 }
References __GIM_GETOPT_ITEM, __GIM_HIDE, __GIM_OPT_NO_ARG, __GIM_OPT_NOT_OK, __GIM_OPT_OK, __GIM_OPT_UNKNOWN, gim_memory_obj::Alloc(), gim_option_item::argument, gim_memory, gim_option_item::opterror, gim_option_item::option, and gim_option_item::status.
Referenced by scanopt().
scanopt() [2/2]
void gim_getopt_obj::scanopt (int argc, char *const argv[], const char * useropt)
Definition at line 82 of file gim_getopt.cc.
{
     setopt( useropt );
     scanopt( argc , argv );
 }
References scanopt(), and setopt().
search()
_gim_flag gim_getopt_obj::search (char opt)
Definition at line 131 of file gim_getopt.cc.
{
     optlist->backup();
     optlist->rewind();
     for( ; optlist->get_item() != NULL ; optlist->next_item() ) {
         _gim_option * tmp = (_gim_option *)optlist->get_item();
         if ( tmp->option == opt ) {
             optlist->restore();
             return __GIM_YES;
         }
     }
     return __GIM_NO;
 }
References __GIM_NO, __GIM_YES, and gim_option_item::option.
setopt()
void gim_getopt_obj::setopt (const char * useropt)
Definition at line 41 of file gim_getopt.cc.
{
     strcpy( options , useropt );
 }
Referenced by scanopt().