My Project: Main Page
gim_html_obj Class Reference
The Gim's html obj is useful to easily make by c++ code web page.
In this example we create a simple html page.
.
#include <gim_html.h>
Public Member Functions
_gim_flag add_data_to_paragraph (_gim_buffer data)
This method is useful to add a data to a paragraph.
_gim_flag add_properities (_gim_flag prop_name, const char *value)
_gim_flag add_properities (_gim_flag prop_name, float value)
This method is useful to add a properities to an html obj.
_gim_flag add_properities (_gim_flag prop_name, int value)
This method is useful to add a properities to an html obj.
_gim_flag close_page (void)
This method is useful to close the html page.
_gim_flag close_paragraph (void)
This method is useful to close a paragraph.
_gim_flag Export (const char *to_export)
This method is useful to print a string in the html page.
_gim_flag Export_tag (const char *tag)
This method is useful to print a TAG in the html page.
_gim_flag Export_tag_close (const char *tag)
This method is useful to close a TAG in the html page.
_gim_flag Export_tag_open (const char *tag)
This method is useful to open a TAG in the html page.
_gim_flag Export_with_tag (const char *tag, const char *to_export)
This method is useful to export a string enclosed in a TAG (open and close) in the html page.
gim_html_obj ()
_gim_flag new_page (const char *title, const char *comment, const char *file_name)
This method is the first step after the declaration of the html class.
.
_gim_flag new_paragraph (void)
This method is useful to open a new paragraph to an html page.
_gim_flag page_css (const char *css_name)
This method is useful ti include a css page in the new html page.
_gim_flag page_css_from_gkp (const char *css_name)
This method is useful ti include a css page taken from a GKDP in the new html page.
void render_properities (void)
This method is useful to add a properities to an html obj.
~gim_html_obj ()
Detailed Description
The Gim's html obj is useful to easily make by c++ code web page.
In this example we create a simple html page.
.
#include <gim/gim.h>
int main (int argc , char *argv[]) {
    gim_obj * gim = new gim_obj;
    _gim_html * test = new _gim_html;
    test->new_page( "The first test page " , "no comment" , "./test_page.html" );
    test->Export_tag_open( "center" );
        test->Export_with_tag( "h1" , "This is the first page generated with Gim 2.0[1.9-6 dev]<br><br>" );
        test->Export( gim_version() );
    test->Export_tag_close( "center" );
    delete test;
    delete gim;
    return 0;
}
This is the result.
<html>
<head>
<title>The first test page </title>
</head>
<center>
<h1>This is the first page generated with Gim 2.0[1.9-6 dev]<br><br></h1>
Gim - Ver 1.9-568
</center>
</html>
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
2.0-0
Date
2003-2008
Definition at line 121 of file gim_html.h.
Constructor & Destructor Documentation
gim_html_obj()
gim_html_obj::gim_html_obj () inline
Definition at line 250 of file gim_html.h.
{
                 gim_error->set( "gim_html_obj::gim_html_obj" , "page initialization start" );
                 indent_level = 0;
                 page = (gim_html_page *)gim_memory->Alloc( sizeof( gim_html_page )  , __GIM_HTML_PAGE , __GIM_HIDE );
                 if ( page == NULL ) {
                     gim_error->set( GIM_ERROR_CRITICAL , "gim_html_obj::gim_html_obj" , "    Memory NOT CORRECTLY allocated succesfully" , __GIM_ERROR );
                 }
                 else {
                     gim_error->set( "gim_html_obj::gim_html_obj" , "    Memory allocated succesfully" );
                     page->fh    = NULL;
                     start_prop  = NULL;
                     cur_prop    = NULL;
                     gim_error->set( "gim_html_obj::gim_html_obj" , "    Costructor correctly finish his job" );
                 }
             };
References __GIM_ERROR, __GIM_HIDE, __GIM_HTML_PAGE, gim_memory_obj::Alloc(), gim_html_page::fh, gim_error, GIM_ERROR_CRITICAL, gim_memory, and gim_error_obj::set().
~gim_html_obj()
gim_html_obj::~gim_html_obj () inline
Definition at line 266 of file gim_html.h.
{
                 gim_error->set( "gim_html_obj::~gim_html_obj" , "Destructor start" );
                 if ( page->fh != NULL ) {
                     gim_error->set( "gim_html_obj::~gim_html_obj" , "    Closing page on destruct" );
                     close_page();
                 }
                 gim_memory->Free( page );
                 if ( start_prop != NULL ) {
                     gim_error->set( "gim_html_obj::~gim_html_obj" , "    Destroy the list of properities on destruct" );
                     //destroy_prop_list();
                 }
             };
References close_page(), gim_html_page::fh, gim_memory_obj::Free(), gim_error, gim_memory, and gim_error_obj::set().
Member Function Documentation
add_data_to_paragraph()
_gim_flag gim_html_obj::add_data_to_paragraph (_gim_buffer data)
This method is useful to add a data to a paragraph.
Warning
This method has not yet been developed.
Todo:
Development of this method has not yet been scheduled.
add_properities() [1/3]
_gim_flag gim_html_obj::add_properities (_gim_flag prop_name, const char * value)
add_properities() [2/3]
_gim_flag gim_html_obj::add_properities (_gim_flag prop_name, float value)
This method is useful to add a properities to an html obj.
Warning
This method has not yet been developed.
Todo:
Development of this method has not yet been scheduled.
add_properities() [3/3]
_gim_flag gim_html_obj::add_properities (_gim_flag prop_name, int value)
This method is useful to add a properities to an html obj.
Warning
This method has not yet been developed.
Todo:
Development of this method has not yet been scheduled.
close_page()
_gim_flag gim_html_obj::close_page (void)
This method is useful to close the html page.
Returns
__GIM_OK on success , __GIM_NOT_OK on fail
Definition at line 168 of file gim_html.cc.
{
     if ( page == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_html_obj::close_page" , "Page not initialized" , __GIM_NOT_OK );
         return __GIM_NOT_OK;
     }
     if ( page->fh == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_html_obj::close_page" , "Page initialized but the file handler is NULL " , __GIM_NOT_OK );
         return __GIM_NOT_OK;
     }
     Export_tag_close( "html" );
     gim_file_manager->close( page->fh );
     return __GIM_OK;
 }
References __GIM_NOT_OK, __GIM_OK, gim_file_manager_obj::close(), Export_tag_close(), gim_html_page::fh, gim_error, GIM_ERROR_CRITICAL, gim_file_manager, and gim_error_obj::set().
Referenced by ~gim_html_obj().
close_paragraph()
_gim_flag gim_html_obj::close_paragraph (void)
This method is useful to close a paragraph.
Warning
This method has not yet been developed.
Todo:
Development of this method has not yet been scheduled.
Export()
_gim_flag gim_html_obj::Export (const char * to_export)
This method is useful to print a string in the html page.
Parameters
to_export The string to export
Returns
__GIM_OK if success or __GIM_NOT_OK if fail
Definition at line 39 of file gim_html.cc.
{
     if ( page->fh != NULL ) {
         if ( to_export != NULL ) {
             make_indent();
             fprintf( page->fh->fp , "%s\n" , to_export );
         }
         else {
             gim_error->set( GIM_ERROR_WARNING , "gim_html_obj::Export" , "You cannot pass NULL as parameter" , __GIM_NOT_OK );
             return __GIM_NOT_OK;
         }
     }
     else {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_html_obj::Export" , "Page file must be opened in write mode before" , __GIM_NOT_OK );
         return __GIM_NOT_OK;
     }
     return __GIM_OK;
 }
References __GIM_NOT_OK, __GIM_OK, gim_html_page::fh, gim_global_item_handler::fp, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, and gim_error_obj::set().
Export_tag()
_gim_flag gim_html_obj::Export_tag (const char * tag)
This method is useful to print a TAG in the html page.
Parameters
tag The TAG to export without symbols <>
Returns
__GIM_OK if success or __GIM_NOT_OK if fail
Definition at line 80 of file gim_html.cc.
{
     char compose[64];
     if ( page->fh != NULL ) {
         if ( tag != NULL ) {
             make_indent();
             sprintf( compose , "<%s>" , tag );
             fprintf( page->fh->fp , "%s\n" , compose );
         }
         else {
             gim_error->set( GIM_ERROR_WARNING , "gim_html_obj::Export_tag_open" , "You cannot pass NULL as parameter" , __GIM_NOT_OK );
             return __GIM_NOT_OK;
         }
     }
     else {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_html_obj::Export_tag_open" , "Page file must be opened in write mode before" , __GIM_NOT_OK );
         return __GIM_NOT_OK;
     }
     return __GIM_OK;
 }
References __GIM_NOT_OK, __GIM_OK, gim_html_page::fh, gim_global_item_handler::fp, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, and gim_error_obj::set().
Export_tag_close()
_gim_flag gim_html_obj::Export_tag_close (const char * tag)
This method is useful to close a TAG in the html page.
Parameters
tag The TAG to close without symbols <>
Returns
__GIM_OK if success or __GIM_NOT_OK if fail
Definition at line 101 of file gim_html.cc.
{
     char compose[64];
     if ( page->fh != NULL ) {
         if ( tag != NULL ) {
             indent_level--;
             make_indent();
             sprintf( compose , "</%s>" , tag );
             fprintf( page->fh->fp , "%s\n" , compose );
         }
         else {
             gim_error->set( GIM_ERROR_WARNING , "gim_html_obj::Export_tag_close" , "You cannot pass NULL as parameter" , __GIM_NOT_OK );
             return __GIM_NOT_OK;
         }
     }
     else {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_html_obj::Export_tag_close" , "Page file must be opened in write mode before" , __GIM_NOT_OK );
         return __GIM_NOT_OK;
     }
     return __GIM_OK;
 }
References __GIM_NOT_OK, __GIM_OK, gim_html_page::fh, gim_global_item_handler::fp, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, and gim_error_obj::set().
Referenced by close_page(), and new_page().
Export_tag_open()
_gim_flag gim_html_obj::Export_tag_open (const char * tag)
This method is useful to open a TAG in the html page.
Parameters
tag The TAG to open without symbols <>
Returns
__GIM_OK if success or __GIM_NOT_OK if fail
Definition at line 58 of file gim_html.cc.
{
     char compose[64];
     if ( page->fh != NULL ) {
         if ( tag != NULL ) {
             make_indent();
             sprintf( compose , "<%s>" , tag );
             fprintf( page->fh->fp , "%s\n" , compose );
             indent_level++;
         }
         else {
             gim_error->set( GIM_ERROR_WARNING , "gim_html_obj::Export_tag_open" , "You cannot pass NULL as parameter" , __GIM_NOT_OK );
             return __GIM_NOT_OK;
         }
     }
     else {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_html_obj::Export_tag_open" , "Page file must be opened in write mode before" , __GIM_NOT_OK );
         return __GIM_NOT_OK;
     }
     return __GIM_OK;
 }
References __GIM_NOT_OK, __GIM_OK, gim_html_page::fh, gim_global_item_handler::fp, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, and gim_error_obj::set().
Referenced by new_page().
Export_with_tag()
_gim_flag gim_html_obj::Export_with_tag (const char * tag, const char * to_export)
This method is useful to export a string enclosed in a TAG (open and close) in the html page.
Parameters
to_export The string to export
tag The TAG to export without symbols <>
Returns
__GIM_OK if success or __GIM_NOT_OK if fail
Definition at line 123 of file gim_html.cc.
{
     char compose[8192];
     if ( page->fh != NULL ) {
         if ( ( to_export != NULL ) && ( tag != NULL ) ) {
             make_indent();
             sprintf( compose , "<%s>%s</%s>\n" , tag , to_export , tag );
             fprintf( page->fh->fp , "%s" , compose );
         }
         else {
             gim_error->set( GIM_ERROR_WARNING , "gim_html_obj::Export_with_tag" , "You cannot pass NULL as parameter" , __GIM_NOT_OK );
             return __GIM_NOT_OK;
         }
     }
     else {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_html_obj::Export_with_tag" , "Page file must be opened in write mode before" , __GIM_NOT_OK );
         return __GIM_NOT_OK;
     }
     return __GIM_OK;
 }
References __GIM_NOT_OK, __GIM_OK, gim_html_page::fh, gim_global_item_handler::fp, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, and gim_error_obj::set().
Referenced by new_page().
new_page()
_gim_flag gim_html_obj::new_page (const char * title, const char * comment, const char * file_name)
This method is the first step after the declaration of the html class.
.
Parameters
title The title of the new html page
comment A comment to the new html page
file_name The file name of the new html page
Returns
__GIM_OK if success or __GIM_ERROR if fail
Definition at line 145 of file gim_html.cc.
{
     gim_error->set( "gim_html_obj::new_page" , "New html page requested..." );
     strcpy( page->title , title );
     strcpy( page->comment , comment );
     strcpy( page->file_name , file_name );
     gim_error->set( "gim_html_obj::new_page" , "Parameter setted" );
     page->fh = gim_file_manager->open( page->file_name , __GIM_FILE_POINTER , __GIM_WRITE );
     if ( page->fh == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_html_obj::new_page" , "File NOT CORRECTLY opened for writing" , __GIM_ERROR );
         return __GIM_ERROR;
     }
     else {
         gim_error->set( "gim_html_obj::new_page" , "File correctly opened for writing... Now i define the initial html code" );
         Export_tag_open( "html" );
         Export_tag_open( "head" );
         Export_with_tag( "title" , page->title );
         Export_tag_close( "head" );
         gim_error->set( "gim_html_obj::new_page" , "done!!!" );
     }
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_FILE_POINTER, __GIM_OK, __GIM_WRITE, gim_html_page::comment, Export_tag_close(), Export_tag_open(), Export_with_tag(), gim_html_page::fh, gim_html_page::file_name, gim_error, GIM_ERROR_CRITICAL, gim_file_manager, gim_file_manager_obj::open(), gim_error_obj::set(), and gim_html_page::title.
new_paragraph()
_gim_flag gim_html_obj::new_paragraph (void)
This method is useful to open a new paragraph to an html page.
Warning
This method has not yet been developed.
Todo:
Development of this method has not yet been scheduled.
page_css()
_gim_flag gim_html_obj::page_css (const char * css_name)
This method is useful ti include a css page in the new html page.
Warning
This method has not yet been developed.
Todo:
Development of this method has not yet been scheduled.
page_css_from_gkp()
_gim_flag gim_html_obj::page_css_from_gkp (const char * css_name)
This method is useful ti include a css page taken from a GKDP in the new html page.
Warning
This method has not yet been developed.
Todo:
Development of this method has not yet been scheduled.
render_properities()
void gim_html_obj::render_properities (void)
This method is useful to add a properities to an html obj.
Warning
This method has not yet been developed.
Todo:
Development of this method has not yet been scheduled.