My Project: Main Page
gim_obj Class Reference
Generic Information Manager Documentation base object.
#include <gim.h>
Public Member Functions
virtual void down (_gim_flag code)
This method say to Gim to unload every allocated memory and classes before to delete.
_gim_th_state get_state (void)
This method say to Gim to stop the current operation if possible.
gim_obj ()
void set_state (_gim_th_state state)
With this method you can say to Gim to the new state.
void stop_operation (void)
This method say to Gim to stop the current operation if possible.
virtual ~gim_obj ()
Public Attributes
gim_prsr_obj * alias
With this class you can manage the alias file of Gim [~/.gim/alias.conf].
See the methods of gim_prsr_obj.
gim_checksum_obj * checksum
To make digest of any objects [files or generic buffers] with 4 different algorithms
See the methods of gim_file_manager_obj.
gim_prsr_obj * compatibility
With this class you can manage the compatibility file of Gim [~/.gim/compatibility.conf].
See the methods of gim_prsr_obj.
gim_prsr_obj * conf
With this class you can manage the configuration file of Gim [~/.gim/gim.conf].
See the methods of gim_prsr_obj.
gim_cryptography_obj * crypt
With this class you can crypt and decrypt a GKDP file.
See the methods of gim_cryptography_obj.
gim_prsr_obj * environ
With this class you can manage the alias file of Gim [~/.gim/alias.conf].
See the methods of gim_prsr_obj.
gim_error_obj * error
Useful to report an error divided in 5 levels of priority
See the methods of gim_error_obj.
gim_file_manager_obj * file_manager
To use this class, instead the standard open/close or fopen/fclose, is useful to hold trace of operation on the files or knowing if problems exist.
See the methods of gim_file_manager_obj.
gim_home_obj * home
In this struct you can find the path for your programs and to get the path of the other public keys .
See the methods of gim_home_obj.
gim_identity_obj * identity
Gim knows who you are :) and with this class you can use this informations.
See the methods of gim_identity_obj.
gim_interface_obj * interface
gim_private_key_obj * key
With this class you can manage your key
See the methods of gim_private_key_obj.
gim_memory_obj * memory
Using this class, insted the standard malloc end free, you are sure to hold trace of all the operations in memory and being able to verify if exist any problems.
See the methods of gim_memory_obj.
Detailed Description
Generic Information Manager Documentation base object.
Author
Danilo Zannoni
Corrado Tumiati
Version
2.0-0
Date
2003-2008
Examples
gkfp.cc.
Definition at line 102 of file gim.h.
Constructor & Destructor Documentation
gim_obj()
gim_obj::gim_obj () inline
gim_obj constructor
Definition at line 233 of file gim.h.
{
                 gim_interface = NULL;
                 gim_init();
             };
References gim_interface.
~gim_obj()
virtual gim_obj::~gim_obj () inline virtual
gim_obj destructor
Definition at line 241 of file gim.h.
{
                 gim_release();
             };
Member Function Documentation
down()
void gim_obj::down (_gim_flag code) virtual
This method say to Gim to unload every allocated memory and classes before to delete.
Parameters
code The exit code.
Definition at line 182 of file gim.cc.
{
     set_state( __GIM_TH_EXIT );
     error->set( GIM_ERROR_CRITICAL , "gim_base_obj::down" , "Gim shutdown. Serious!!!" , __GIM_ERROR );
     error->set( "gim_base_obj::down" , 18 );
     gim_file_manager->release();
     gim_identity->release();
     home->down();
     gim_memory->down();
     exit( code );
 }
References __GIM_ERROR, __GIM_TH_EXIT, error, GIM_ERROR_CRITICAL, gim_file_manager, gim_identity, gim_memory, home, gim_error_obj::set(), and set_state().
Referenced by gim_error_obj::get(), and gim_error_obj::set().
get_state()
_gim_th_state gim_obj::get_state (void)
This method say to Gim to stop the current operation if possible.
Returns
The current Gim state. The state are defined in the GimThState enumerator.
Definition at line 204 of file gim.cc.
{
     return gim_state;
 }
Referenced by gim_gkfp_obj::extract_data(), gim_gkfp_obj::read_data(), gim_gkfp_obj::Write(), and gim_gkfp_obj::write_data().
set_state()
void gim_obj::set_state (_gim_th_state state)
With this method you can say to Gim to the new state.
Parameters
state The new Gim state. The state are defined in the GimThState enumerator.
Definition at line 194 of file gim.cc.
{
     gim_state = state;
 }
Referenced by gim_cryptography_obj::advanced_password(), down(), and stop_operation().
stop_operation()
void gim_obj::stop_operation (void)
This method say to Gim to stop the current operation if possible.
Definition at line 199 of file gim.cc.
{
     set_state( __GIM_TH_STOP );
 }
References __GIM_TH_STOP, and set_state().
Member Data Documentation
alias
gim_prsr_obj* gim_obj::alias
With this class you can manage the alias file of Gim [~/.gim/alias.conf].
See the methods of gim_prsr_obj.
Definition at line 157 of file gim.h.
checksum
gim_checksum_obj* gim_obj::checksum
To make digest of any objects [files or generic buffers] with 4 different algorithms
See the methods of gim_file_manager_obj.
Definition at line 199 of file gim.h.
compatibility
gim_prsr_obj* gim_obj::compatibility
With this class you can manage the compatibility file of Gim [~/.gim/compatibility.conf].
See the methods of gim_prsr_obj.
Definition at line 151 of file gim.h.
conf
gim_prsr_obj* gim_obj::conf
With this class you can manage the configuration file of Gim [~/.gim/gim.conf].
See the methods of gim_prsr_obj.
Definition at line 145 of file gim.h.
crypt
gim_cryptography_obj* gim_obj::crypt
With this class you can crypt and decrypt a GKDP file.
See the methods of gim_cryptography_obj.
Definition at line 205 of file gim.h.
environ
gim_prsr_obj* gim_obj::environ
With this class you can manage the alias file of Gim [~/.gim/alias.conf].
See the methods of gim_prsr_obj.
Definition at line 163 of file gim.h.
error
gim_error_obj* gim_obj::error
Useful to report an error divided in 5 levels of priority
See the methods of gim_error_obj.
Definition at line 132 of file gim.h.
Referenced by down().
file_manager
gim_file_manager_obj* gim_obj::file_manager
To use this class, instead the standard open/close or fopen/fclose, is useful to hold trace of operation on the files or knowing if problems exist.
See the methods of gim_file_manager_obj.
Definition at line 187 of file gim.h.
home
gim_home_obj* gim_obj::home
In this struct you can find the path for your programs and to get the path of the other public keys .
See the methods of gim_home_obj.
Definition at line 180 of file gim.h.
Referenced by down().
identity
gim_identity_obj* gim_obj::identity
Gim knows who you are :) and with this class you can use this informations.
See the methods of gim_identity_obj.
Definition at line 169 of file gim.h.
interface
gim_interface_obj* gim_obj::interface
Definition at line 174 of file gim.h.
key
gim_private_key_obj* gim_obj::key
With this class you can manage your key
See the methods of gim_private_key_obj.
Definition at line 193 of file gim.h.
memory
gim_memory_obj* gim_obj::memory
Using this class, insted the standard malloc end free, you are sure to hold trace of all the operations in memory and being able to verify if exist any problems.
See the methods of gim_memory_obj.
Definition at line 139 of file gim.h.