My Project: Main Page
gim_signal.cc File Reference
#include "../include/gim_signal.h"
Functions
void gim_fatal_test (void)
If you call this function Gim generates a FATAL occurrence. It is useful to test the FATAL error.
void gim_forever (void)
If you call this function Gim will enter in a forever loop. You can only type ctrl-c to exit. It is useful to test the signal handler.
void gim_signal_handler (void)
This funtion is automatically called by Gim at the constructor. It set the default action when a signal will be received.
void gim_signal_received (int sig)
This funtion is automatically called by Gim when a signal will be received.
Variables
volatile sig_atomic_t fatal_error_in_progress = __GIM_NO
Function Documentation
gim_fatal_test()
void gim_fatal_test (void)
If you call this function Gim generates a FATAL occurrence. It is useful to test the FATAL error.
Definition at line 76 of file gim_signal.cc.
{
     gim_error->set( GIM_ERROR_FATAL , "::gim_fatal_test" , "This is a test for a FATAL occurrence" , __GIM_ERROR );
 }
References __GIM_ERROR, gim_error, GIM_ERROR_FATAL, and gim_error_obj::set().
gim_forever()
void gim_forever (void)
If you call this function Gim will enter in a forever loop. You can only type ctrl-c to exit. It is useful to test the signal handler.
Definition at line 69 of file gim_signal.cc.
{
     gim_error->set( GIM_ALWAYSE_VERBOSE , __GIM_YES );
     gim_error->set( "::gim_forever" , "Type control-c to exit" );
     gim_error->set( GIM_ALWAYSE_VERBOSE , __GIM_NO );
     while( 1 );
 }
References __GIM_NO, __GIM_YES, GIM_ALWAYSE_VERBOSE, gim_error, and gim_error_obj::set().
gim_signal_handler()
void gim_signal_handler (void)
This funtion is automatically called by Gim at the constructor. It set the default action when a signal will be received.
Warning
It is not possible to use directly this function.
Definition at line 59 of file gim_signal.cc.
{
     signal(SIGINT , gim_signal_received );
     signal(SIGQUIT, gim_signal_received );
     signal(SIGKILL, gim_signal_received );
     signal(SIGABRT, gim_signal_received );
     signal(SIGTERM, gim_signal_received );
     signal(SIGSEGV, gim_signal_received );
     gim_error->set( "::gim_signal_handler" , "Signal are now managed by Gim" );
 }
References gim_error, gim_signal_received(), and gim_error_obj::set().
gim_signal_received()
void gim_signal_received (int sig)
This funtion is automatically called by Gim when a signal will be received.
Warning
It is not possible to use directly this function.
Definition at line 41 of file gim_signal.cc.
{
     if ( fatal_error_in_progress == __GIM_YES )
         raise( sig );
     fatal_error_in_progress = __GIM_YES;
     gim_error->set( GIM_ERROR_CRITICAL , "::gim_signal_received" , "Signal received" , sig );
     char fault[512] , buf[512];
     gim_error->set( GIM_ON_FATAL_EXIT , __GIM_YES );
     strcpy( fault , strsignal( sig ) );
     snprintf( buf , sizeof( buf ), "Gim : [ %s ]", fault );
     signal(SIGINT , SIG_DFL );
     signal(SIGQUIT, SIG_DFL );
     signal(SIGKILL, SIG_DFL );
     signal(SIGABRT, SIG_DFL );
     signal(SIGTERM, SIG_DFL );
     signal(SIGSEGV, SIG_DFL );
     gim_error->set( GIM_ERROR_FATAL , "::gim_signal_received" , buf , sig );
 }
References __GIM_YES, fatal_error_in_progress, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_FATAL, GIM_ON_FATAL_EXIT, and gim_error_obj::set().
Referenced by gim_signal_handler().
Variable Documentation
fatal_error_in_progress
volatile sig_atomic_t fatal_error_in_progress = __GIM_NO
Definition at line 39 of file gim_signal.cc.
Referenced by gim_signal_received().