My Project: Main Page
gim_list_obj Class Reference
"Put your brief here"
#include <gim_list.h>
Public Member Functions
_gim_flag add_item (void *member)
void backup (void)
_gim_flag del_item (_gim_Uint32 index)
_gim_Uint32 get_id (void)
void * get_item (_gim_Uint32 index)
void * get_item (void)
gim_list_obj ()
gim_list_obj (_gim_int32 mem_size)
_gim_Uint32 items (void)
_gim_flag next_item (void)
void restore (void)
_gim_flag rewind (void)
_gim_flag seek (_gim_Uint32 index)
void size (_gim_int32 mem_size)
_gim_int32 size (void)
~gim_list_obj ()
Detailed Description
"Put your brief here"
Author
asyntote
Version
2.5
Date
2003-2018
Author
asyntote
Version
2.5
Date
2003-2011
Definition at line 65 of file gim_list.h.
Constructor & Destructor Documentation
gim_list_obj() [1/2]
gim_list_obj::gim_list_obj () inline
gim_list_obj constructor
Definition at line 98 of file gim_list.h.
{
                 startlist = NULL;
                 endlist = NULL;
                 currentlist = NULL;
                 savelist = NULL;
 //              item_size = 0;
                 item_counter = 0;
                 gim_error->set( "gim_list_obj::gim_list_obj" , "A new list allocated and inizialized" );
             };
References gim_error, and gim_error_obj::set().
gim_list_obj() [2/2]
gim_list_obj::gim_list_obj (_gim_int32 mem_size) inline
gim_list_obj constructor
Definition at line 110 of file gim_list.h.
{
                 startlist = NULL;
                 endlist = NULL;
                 currentlist = NULL;
                 item_size = mem_size;
                 item_counter = 0;
                 gim_error->set( "gim_list_obj::gim_list_obj" , "A new list allocated and inizialized" );
             };
References gim_error, and gim_error_obj::set().
~gim_list_obj()
gim_list_obj::~gim_list_obj () inline
gim_list_obj distructor
Definition at line 121 of file gim_list.h.
{
                 destroy_list();
             };
Member Function Documentation
add_item()
_gim_flag gim_list_obj::add_item (void * member)
Definition at line 52 of file gim_list.cc.
{
     _gim_list_item *    temp_item;
     temp_item = (gim_list_item *)gim_memory->Alloc ( sizeof( gim_list_item ) , __GIM_LIST_ITEM , __GIM_HIDE );
     if ( temp_item == NULL ) {
         return __GIM_ERROR;
     }
     temp_item->index = ++item_counter;
     temp_item->item = member;
     temp_item->nextitem = NULL;
     if ( startlist == NULL ) {
         startlist = temp_item;
         currentlist = startlist;
 //      puts("primo item");
     }
     else {
         endlist->nextitem = temp_item;
 //      puts("ulteriore item");
     }
     endlist = temp_item;
     //gim_error->set( "gim_list_obj::add_item" , "New item allocated" );
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_HIDE, __GIM_LIST_ITEM, __GIM_OK, gim_memory_obj::Alloc(), gim_memory, gim_list_item::index, gim_list_item::item, and gim_list_item::nextitem.
backup()
void gim_list_obj::backup (void)
Definition at line 224 of file gim_list.cc.
{
     savelist = currentlist;
 }
del_item()
_gim_flag gim_list_obj::del_item (_gim_Uint32 index)
Definition at line 76 of file gim_list.cc.
{
     if ( index = 0 ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_list_obj::del_item" , "index cannot be 0" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     _gim_list_item *    tmplist = startlist;
     _gim_list_item *    beforelist = NULL;
     _gim_list_item *    afterlist = NULL;
     if( index == 0 ) {
         startlist = startlist->nextitem;
         currentlist = startlist;
         gim_error->set( "gim_list_obj::add_item" , "Item deleted" );
     }
     while ( tmplist != NULL ) {
         if ( tmplist->index == index ) {
             beforelist = tmplist->previtem;
             afterlist = tmplist->nextitem;
             beforelist->nextitem = afterlist;
             afterlist->previtem = beforelist;
             gim_memory->Unlock_and_free ( tmplist );
             item_counter--;
             gim_error->set( "gim_list_obj::add_item" , "Item found and deleted" );
             return __GIM_OK;
         }
         tmplist = tmplist->nextitem;
     }
     gim_error->set( GIM_ERROR_WARNING , "gim_list_obj::del_item" , "Item NOT FOUND" , __GIM_ERROR );
     return __GIM_NOT_OK;
 }
References __GIM_ERROR, __GIM_NOT_OK, __GIM_OK, gim_error, GIM_ERROR_WARNING, gim_memory, gim_list_item::index, gim_list_item::nextitem, gim_list_item::previtem, gim_error_obj::set(), and gim_memory_obj::Unlock_and_free().
get_id()
_gim_Uint32 gim_list_obj::get_id (void)
Definition at line 219 of file gim_list.cc.
{
     return currentlist->index;
 }
References gim_list_item::index.
get_item() [1/2]
void * gim_list_obj::get_item (_gim_Uint32 index)
Definition at line 154 of file gim_list.cc.
{
     if ( index == 0 ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_list_obj::get_item" , "index cannot be 0" , __GIM_ERROR );
         return NULL;
     }
     _gim_list_item *    tmplist = startlist;
     while ( tmplist != NULL ) {
         if ( tmplist->index == index ) {
             //gim_error->set( "gim_list_obj::get_item" , "Item successfully obtained." );
             return tmplist->item;
         }
         tmplist = tmplist->nextitem;
     }
     gim_error->set( GIM_ERROR_WARNING , "gim_list_obj::get_item" , "Item NOT FOUND" , __GIM_ERROR );
     return NULL;
 }
References __GIM_ERROR, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, gim_list_item::index, gim_list_item::item, gim_list_item::nextitem, and gim_error_obj::set().
get_item() [2/2]
void * gim_list_obj::get_item (void)
Definition at line 145 of file gim_list.cc.
{
     if ( currentlist == NULL ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_list_obj::next_item" , "Endlist reached" , __GIM_ERROR );
         return NULL;
     }
     return currentlist->item;
 }
References __GIM_ERROR, gim_error, GIM_ERROR_WARNING, gim_list_item::item, and gim_error_obj::set().
items()
_gim_Uint32 gim_list_obj::items (void)
Definition at line 214 of file gim_list.cc.
{
     return item_counter;
 }
next_item()
_gim_flag gim_list_obj::next_item (void)
Definition at line 174 of file gim_list.cc.
{
     if ( currentlist == NULL ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_list_obj::next_item" , "Endlist reached" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     currentlist = currentlist->nextitem;
     //gim_error->set( "gim_list_obj::next_item" , "Next item set" );
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_NOT_OK, __GIM_OK, gim_error, GIM_ERROR_WARNING, gim_list_item::nextitem, and gim_error_obj::set().
restore()
void gim_list_obj::restore (void)
Definition at line 229 of file gim_list.cc.
{
     currentlist = savelist;
     savelist = NULL;
 }
rewind()
_gim_flag gim_list_obj::rewind (void)
Definition at line 185 of file gim_list.cc.
{
     if ( startlist == NULL ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_list_obj::rewind" , "The list is empty" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     currentlist = startlist;
     //gim_error->set( "gim_list_obj::rewind" , "Startlit set" );
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_NOT_OK, __GIM_OK, gim_error, GIM_ERROR_WARNING, and gim_error_obj::set().
seek()
_gim_flag gim_list_obj::seek (_gim_Uint32 index)
Definition at line 196 of file gim_list.cc.
{
     if ( index = 0 ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_list_obj::seek" , "index cannot be 0" , __GIM_ERROR );
         return NULL;
     }
     currentlist = startlist;
     while ( currentlist != NULL ) {
         if ( currentlist->index == index ) {
             gim_error->set( "gim_list_obj::seek" , "Item successfully sought." );
             return __GIM_OK;
         }
         currentlist = currentlist->nextitem;
     }
     gim_error->set( GIM_ERROR_WARNING , "gim_list_obj::seek" , "Item NOT FOUND" , __GIM_ERROR );
     return NULL;
 }
References __GIM_ERROR, __GIM_OK, gim_error, GIM_ERROR_WARNING, gim_list_item::index, gim_list_item::nextitem, and gim_error_obj::set().
size() [1/2]
void gim_list_obj::size (_gim_int32 mem_size)
Definition at line 47 of file gim_list.cc.
{
     item_size = mem_size;
 }
size() [2/2]
_gim_int32 gim_list_obj::size (void)
Definition at line 42 of file gim_list.cc.
{
     return item_size;
 }