My Project: Main Page
gim_memory_obj Class Reference
This class is very useful to avoid allocated memory leak. With this class you write the code and Gim takes care of the memory.
#include <gim_memory.h>
Public Member Functions
void * Alloc (size_t size)
This method is useful in order to alloc memory holding trace.
void * Alloc (size_t size, _gim_Uint32 code)
This method is useful in order to alloc memory holding trace.
void * Alloc (size_t size, _gim_Uint32 code, _gim_flag hidden)
This method is useful in order to alloc memory holding trace.
void * Alloc (size_t size, char *id)
This method is useful in order to alloc memory holding trace.
void * Alloc_locked (size_t size)
void * Alloc_unlocked (size_t size)
_gim_Uint32 Allocated (void)
_gim_Uint32 Allocated_peek (void)
_gim_flag Allocation_limit (void)
_gim_flag Check (void *to_check)
Use this method to checl if the memory pointed by to_check was allocated with gim_memory_obj::Alloc.
_gim_flag Free (void *to_free)
Use this method in order to free the memory allocated with gim_memory_obj::Alloc.
_gim_flag Get_lock_status (void *to_check)
gim_memory_obj ()
void hide (_gim_flag flag)
_gim_flag Lock (void *to_lock)
_gim_Uint32 Max_allocable (void)
void mem_alloc_limit (_gim_flag flag, _gim_Uint8 mlimit)
char * metric_converter (_gim_Ulong size)
void peek_reset (void)
void set_default_lock (_gim_flag deflock)
_gim_flag Unlock (void *to_unlock)
_gim_flag Unlock_and_free (void *to_free)
_gim_flag Virtual_memory (void)
void Vmem (_gim_flag flag)
Detailed Description
This class is very useful to avoid allocated memory leak. With this class you write the code and Gim takes care of the memory.
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
2.0-0
Date
2003-2008
Definition at line 146 of file gim_memory.h.
Constructor & Destructor Documentation
gim_memory_obj()
gim_memory_obj::gim_memory_obj () inline
the constuctor
Definition at line 311 of file gim_memory.h.
{
                 caller      = __GIM_MEM_OTHER;
                 Hide        = __GIM_YES;
                 startlist   = NULL;
                 currentlist = NULL;
                 endlist     = NULL;
                 freelist_start = NULL;
                 freelist_current = NULL;
                 freelist_end = NULL;
             };
References __GIM_MEM_OTHER, and __GIM_YES.
Member Function Documentation
Alloc() [1/4]
void * gim_memory_obj::Alloc (size_t size)
This method is useful in order to alloc memory holding trace.
Parameters
size The size of the memory you want to alloc
size >= 0
Returns
An handle to the allocated memory or
NULL in case of error
Definition at line 243 of file gim_memory.cc.
{
     return Alloc( size , __GIM_MEM_OTHER , __GIM_NOT_HIDE );
 }
References __GIM_MEM_OTHER, and __GIM_NOT_HIDE.
Referenced by gim_list_obj::add_item(), gim_prsr_obj::AddKey(), gim_prsr_obj::AddSection(), Alloc(), Alloc_locked(), Alloc_unlocked(), gim_gkfp_obj::extract_data(), gim_cnc_encoding_obj::Fog_a_buffer(), gim_db_obj::gdbs_execute(), gim_db_obj::gdbs_line_syntax_check(), gim_directory_obj::get_item(), gim_directory_obj::get_item_id(), gim_db_obj::gim_db_obj(), gim_html_obj::gim_html_obj(), gim_memory_page_obj::gim_memory_page_obj(), gim_file_manager_obj::load(), gim_file_obj::load(), gim_file_manager_obj::open(), gim_gkfp_obj::read_data(), gim_getopt_obj::scanopt(), gim_ascii_file_obj::set_dimension(), prsr_lexical_class::str_nostd_conv(), gim_gkdp_obj::take(), gim_prsr_obj::Up(), and gim_prsr_obj::WriteOnBuffer().
Alloc() [2/4]
void * gim_memory_obj::Alloc (size_t size, _gim_Uint32 code)
This method is useful in order to alloc memory holding trace.
Parameters
size The size of the memory you want to alloc
size >= 0
code the id indicates the calling function.
Returns
an handle to the allocated memory or
NULL in case of some error
Definition at line 219 of file gim_memory.cc.
{
     if ( code != __GIM_MEM_OTHER ) {
         caller = code;
     }
     return Alloc( size , code , __GIM_NOT_HIDE );
 }
References __GIM_MEM_OTHER, __GIM_NOT_HIDE, Alloc(), and gim_memory_id::code.
Alloc() [3/4]
void * gim_memory_obj::Alloc (size_t size, _gim_Uint32 code, _gim_flag hidden)
This method is useful in order to alloc memory holding trace.
Parameters
size The size of the memory you want to alloc
size >= 0
code the id indicates the calling function.
hidden When is __GIM_HIDE the allocation oparation is not logged
Returns
an handle to the allocated memory or
NULL in case of some error
Definition at line 134 of file gim_memory.cc.
{
     if ( virt_mem == __GIM_OFF ) {
         if ( gim_interface != NULL )
             gim_interface->data->mem_max_allocable = max_allocation;
         if ( size > (size_t)abs( (int)max_allocation - allocated ) ) {
             if ( max_allocation > 0 ) {
                 char message[256];
                 sprintf( message , "The demand for memory exceeds the max_allocation [ %s / %d ]" , metric_converter( size ) , ( max_allocation - allocated ) );
                 gim_error->set( GIM_ERROR_FATAL , "gim_memory_obj::alloc" , message , __GIM_ERROR );
                 return NULL;
             }
         }
     }
     gim_mem_list *  tmplist = NULL;
     if ( id != __GIM_MEM_OTHER ) {
         caller = id;
     }
     tmplist = ( gim_mem_list * ) malloc ( sizeof ( gim_mem_list ) );
     if ( tmplist == NULL )
         gim_error->set( GIM_ERROR_FATAL , "gim_memory_obj::alloc", "Failed during a allocation of a new member of memory list" , __GIM_ERROR );
     tmplist->data = ( void *  ) malloc ( size );
     if ( tmplist->data == NULL ) {
         char message[256];
         sprintf( message , "Memory allocation failed on a request of %s size from %s" , metric_converter( size ) , code_to_id( caller ) );
         gim_error->set( GIM_ERROR_FATAL , "gim_memory_obj::alloc", message , __GIM_ERROR );
         return NULL;
     }
     allocated += size;
     if ( allocated > allocated_peek ) {
         allocated_peek = allocated;
     }
     if ( gim_interface != NULL ) {
         if ( gim_interface->data != NULL ) {
             gim_interface->data->mem_allocated = allocated;
             gim_interface->data->mem_ratio    = (float)( (float)allocated / (float)max_allocation );
             gim_interface->data->mem_allocated_peek = allocated_peek;
             gim_interface->data->mem_allocated_peek_ratio = (float)( (float)allocated_peek / (float)max_allocation );
         }
     }
     memset( tmplist->data , 0 , size );
     tmplist->size = size;
     tmplist->caller = caller;
     tmplist->hide = hidden;
     tmplist->lock = this->lock;
     endlist->next = tmplist;
     endlist = tmplist;
     endlist->next = NULL;
     if ( ( hidden != __GIM_HIDE ) || ( Hide == __GIM_NO ) ) {
         char    message[256];
         sprintf( message , "Allocated [%s] index[%p] , Allocation id : %s" , metric_converter( size ) , endlist->data , code_to_id( caller ) );
         if ( tmplist->caller == id_to_code( "__ID_COMMAND_ERROR" ) ) {
             gim_error->set( GIM_ERROR_CRITICAL , "gim_memory_obj::alloc", message , __GIM_ERROR );
         }
         else {
             gim_error->set( "gim_memory_obj::alloc" , message );
         }
         if ( virt_mem == __GIM_OFF ) {
             sprintf( message , "Total memory allocated [%d] | Free memory for the application [%d]" , allocated , ( max_allocation - allocated ) );
             gim_error->set( "gim_memory_obj::alloc" , message );
         }
     }
     caller = __GIM_MEM_OTHER;
     return tmplist->data;
 }
References __GIM_ERROR, __GIM_HIDE, __GIM_MEM_OTHER, __GIM_NO, __GIM_OFF, gim_mem_list::caller, gim_mem_list::data, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_FATAL, gim_interface, gim_mem_list::hide, gim_memory_id::id, gim_mem_list::lock, gim_interface_data::mem_allocated, gim_interface_data::mem_allocated_peek, gim_interface_data::mem_allocated_peek_ratio, gim_interface_data::mem_max_allocable, gim_interface_data::mem_ratio, metric_converter(), gim_mem_list::next, gim_error_obj::set(), and gim_mem_list::size.
Alloc() [4/4]
void * gim_memory_obj::Alloc (size_t size, char * id)
This method is useful in order to alloc memory holding trace.
Parameters
size The size of the memory you want to alloc
size >= 0
id the id indicates the calling function.
id != NULL
Returns
an handle to the allocated memory or
NULL in case of some error
Definition at line 227 of file gim_memory.cc.
{
     _gim_Uint32 code;
     code = id_to_code( id );
     if ( code != __ID_COMMAND_ERROR ) {
         caller = code;
     }
     else {
         char message[256];
         sprintf( message , "%s : code not found" , id );
         gim_error->set( GIM_ERROR_WARNING , "gim_memory_obj::Alloc" , message , __GIM_ERROR );
         caller = id_to_code( "__ID_COMMAND_ERROR" );
     }
     return Alloc( size , code , __GIM_NOT_HIDE );
 }
References __GIM_ERROR, __GIM_NOT_HIDE, __ID_COMMAND_ERROR, Alloc(), gim_memory_id::code, gim_error, GIM_ERROR_WARNING, and gim_error_obj::set().
Alloc_locked()
void * gim_memory_obj::Alloc_locked (size_t size)
Definition at line 209 of file gim_memory.cc.
{
     void * tmp;
     tmp = Alloc( size );
     if ( Get_lock_status( tmp ) == __GIM_MEM_UNLOCK )
         Lock( tmp );
     return tmp;
 }
References __GIM_MEM_UNLOCK, Alloc(), Get_lock_status(), and Lock().
Alloc_unlocked()
void * gim_memory_obj::Alloc_unlocked (size_t size)
Definition at line 200 of file gim_memory.cc.
{
     void * tmp;
     tmp = Alloc( size );
     if ( Get_lock_status( tmp ) == __GIM_MEM_LOCK )
         Unlock( tmp );
     return tmp;
 }
References __GIM_MEM_LOCK, Alloc(), Get_lock_status(), and Unlock().
Allocated()
_gim_Uint32 gim_memory_obj::Allocated (void)
Definition at line 510 of file gim_memory.cc.
{
     return allocated;
 }
Allocated_peek()
_gim_Uint32 gim_memory_obj::Allocated_peek (void)
Definition at line 515 of file gim_memory.cc.
{
     return allocated_peek;
 }
Allocation_limit()
_gim_flag gim_memory_obj::Allocation_limit (void)
Definition at line 525 of file gim_memory.cc.
{
     return Alloc_limit;
 }
Check()
_gim_flag gim_memory_obj::Check (void * to_check)
Use this method to checl if the memory pointed by to_check was allocated with gim_memory_obj::Alloc.
Parameters
to_check The pointer to the allocated memory to free
to_free != NULL
Returns
__GIM_EXIST if the memory was allocated with gim_memory_obj::Alloc or __GIM_NOT_EXIST if not
Definition at line 317 of file gim_memory.cc.
{
     for ( currentlist = startlist ; currentlist != NULL ; currentlist = currentlist->next ) {
         if ( (unsigned long long)to_check == (unsigned long long)currentlist->data )
             return __GIM_EXIST;
     }
     return __GIM_NOT_EXIST;
 }
References __GIM_EXIST, __GIM_NOT_EXIST, gim_mem_list::data, and gim_mem_list::next.
Referenced by gim_file_manager_obj::load(), and Unlock_and_free().
Free()
_gim_flag gim_memory_obj::Free (void * to_free)
Use this method in order to free the memory allocated with gim_memory_obj::Alloc.
Parameters
to_free The pointer to the allocated memory to free
to_free != NULL
Returns
__GIM_OK if the operation is succesfully terminated or __GIM_NOT_OK if not
Definition at line 257 of file gim_memory.cc.
{
     _gim_flag   found = __GIM_NO;
     gim_mem_list *  before = startlist;
     char    message[256];
     if ( to_free == NULL )
         gim_error->set( GIM_ERROR_FATAL , "gim_memory_obj::Free" , "Is not possible to free a NULL pointer" , __GIM_ERROR );
     if ( startlist == NULL )
         gim_error->set( "gim_memory_obj::Free" , 14 );
     else {
         for ( currentlist = startlist ; currentlist != NULL ; currentlist = currentlist->next ) {
             if ( ( unsigned long long ) to_free == ( unsigned long long )currentlist->data ) {
                 found = __GIM_YES;
                 if ( currentlist->lock == __GIM_MEM_LOCK )  {
                     if ( currentlist->caller == __GIM_MEM_OTHER ) {
                         gim_error->set( GIM_ERROR_CRITICAL , "gim_memory_obj::Free", "CRITICAL : You are attempting to free a  LOCKED frame." , __GIM_ERROR );
                         sprintf( message , "           [%s] index[%p] , Allocation id : %s." , metric_converter( currentlist->size ) , currentlist->data , code_to_id( currentlist->caller ) );
                         gim_error->set( GIM_ERROR_CRITICAL , "gim_memory_obj::Free", message , __GIM_ERROR );
                         gim_error->set( GIM_ERROR_CRITICAL , "gim_memory_obj::Free", "           You cannot free." , __GIM_ERROR );
 //                      tmplist = ( gim_mem_list * ) malloc ( sizeof ( gim_mem_list ) );
                         return __GIM_NOT_OK;
                     }
                 }
                 if ( ( currentlist->hide != __GIM_HIDE ) || ( Hide == __GIM_NO ) ) {
                     sprintf( message , "Free      [%s] index[%p] , Allocation id : %s" , metric_converter( currentlist->size ) , currentlist->data , code_to_id( currentlist->caller ) );
                     gim_error->set( "gim_memory_obj::Free", message );
                 }
                 free( currentlist->data );
                 allocated -= currentlist->size;
                 if ( ( currentlist->hide != __GIM_HIDE ) || ( Hide == __GIM_NO ) ) {
                     if ( virt_mem == __GIM_OFF ) {
                         sprintf( message , "Total memory allocated [%d] | Free memory for the application [%d]" , allocated , (_gim_Uint32)( max_allocation - allocated ) );
                         gim_error->set( "gim_memory_obj::Free" , message );
                     }
                 }
                 if ( gim_interface != NULL ) {
                     if ( gim_interface->data != NULL ) {
                         gim_interface->data->mem_allocated = allocated;
                         gim_interface->data->mem_ratio  = (float)( (float)allocated / (float)max_allocation );
                     }
                 }
                 before->next = currentlist->next;
                 if ( currentlist->next == NULL )
                     endlist = before;
                 free( currentlist );
                 to_free = NULL;
                 return __GIM_OK;
             }
             else
                 before = currentlist;
         }
         if ( found == __GIM_NO ) {
             sprintf( message , "Frame NOT found : index[%p]" , to_free );
             gim_error->set( GIM_ERROR_CRITICAL , "gim_memory_obj::Free" , message , __GIM_ERROR );
             return __GIM_NOT_OK;
         }
     }
     return __GIM_NOT_OK;
 }
References __GIM_ERROR, __GIM_HIDE, __GIM_MEM_LOCK, __GIM_MEM_OTHER, __GIM_NO, __GIM_NOT_OK, __GIM_OFF, __GIM_OK, __GIM_YES, gim_mem_list::caller, gim_mem_list::data, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_FATAL, gim_interface, gim_mem_list::hide, gim_mem_list::lock, gim_interface_data::mem_allocated, gim_interface_data::mem_ratio, metric_converter(), gim_mem_list::next, gim_error_obj::set(), and gim_mem_list::size.
Referenced by gim_file_manager_obj::close(), gim_prsr_obj::DelKey(), gim_prsr_obj::Down(), gim_cnc_encoding_obj::Fog_a_buffer(), gim_directory_obj::free_item(), gim_gkdp_obj::leave(), gim_gkfp_obj::read_data(), prsr_lexical_class::str_nostd_conv(), gim_file_obj::unload(), Unlock_and_free(), gim_db_obj::~gim_db_obj(), gim_html_obj::~gim_html_obj(), and gim_memory_page_obj::~gim_memory_page_obj().
Get_lock_status()
_gim_flag gim_memory_obj::Get_lock_status (void * to_check)
Definition at line 573 of file gim_memory.cc.
{
     char message[256];
     for ( currentlist = startlist ; currentlist != NULL ; currentlist = currentlist->next ) {
         if ( (unsigned long long)to_check == (unsigned long long)currentlist->data ) {
             return currentlist->lock;
         }
     }
     gim_error->set( GIM_ERROR_WARNING , "gim_memory_obj::Get_lock_status", "Frame not found" , __GIM_OK );
     return __GIM_NOT_EXIST;
 }
References __GIM_NOT_EXIST, __GIM_OK, gim_mem_list::data, gim_error, GIM_ERROR_WARNING, gim_mem_list::lock, gim_mem_list::next, and gim_error_obj::set().
Referenced by Alloc_locked(), and Alloc_unlocked().
hide()
void gim_memory_obj::hide (_gim_flag flag)
Definition at line 410 of file gim_memory.cc.
{
     if ( flag == __GIM_YES )
         Hide = __GIM_YES;
     if ( flag == __GIM_NO )
         Hide = __GIM_NO;
 }
References __GIM_NO, and __GIM_YES.
Lock()
_gim_flag gim_memory_obj::Lock (void * to_lock)
Definition at line 554 of file gim_memory.cc.
{
     char message[256];
     for ( currentlist = startlist ; currentlist != NULL ; currentlist = currentlist->next ) {
         if ( (unsigned long long)to_lock == (unsigned long long)currentlist->data ) {
             if ( currentlist->lock == __GIM_MEM_LOCK ) {
                 gim_error->set( GIM_ERROR_WARNING , "gim_memory_obj::Lock", "This frame was already Locked" , __GIM_OK );
                 return __GIM_MEM_LOCK;
             }
             currentlist->lock = __GIM_MEM_LOCK;
             sprintf( message , "Correctly Locked      [%s] index[%p] , Allocation id : %s" , metric_converter( currentlist->size ) , currentlist->data , code_to_id( currentlist->caller ) );
             gim_error->set( "gim_memory_obj::Lock", message );
             return __GIM_MEM_LOCK;
         }
     }
     gim_error->set( GIM_ERROR_WARNING , "gim_memory_obj::Lock", "Frame not found" , __GIM_OK );
     return __GIM_NOT_EXIST;
 }
References __GIM_MEM_LOCK, __GIM_NOT_EXIST, __GIM_OK, gim_mem_list::caller, gim_mem_list::data, gim_error, GIM_ERROR_WARNING, gim_mem_list::lock, metric_converter(), gim_mem_list::next, gim_error_obj::set(), and gim_mem_list::size.
Referenced by Alloc_locked().
Max_allocable()
_gim_Uint32 gim_memory_obj::Max_allocable (void)
Definition at line 505 of file gim_memory.cc.
{
     return max_allocation;
 }
mem_alloc_limit()
void gim_memory_obj::mem_alloc_limit (_gim_flag flag, _gim_Uint8 mlimit)
Definition at line 461 of file gim_memory.cc.
{
     Alloc_limit = flag;
     Limit = mlimit;
     Memory_update();
 }
metric_converter()
char * gim_memory_obj::metric_converter (_gim_Ulong size)
Definition at line 482 of file gim_memory.cc.
{
     static char message[128];
     __GIM_CLEAR( message , 128 , char );
     if ( ( size / __GIM_MB ) >= 1 ) {
         sprintf( message , "%5ld MBytes" , ( size / __GIM_MB ) );
         return message;
     }
     //~ if ( ( ( size / __GIM_MB ) >= 1 ) && ( ( size / __GIM_GB ) < 1 ) ) {
         //~ sprintf( message , "%5ld MBytes" , ( size / __GIM_MB ) );
         //~ return message;
     //~ }
     if ( ( ( size / __GIM_KB ) >= 1 ) && ( ( size / __GIM_MB ) < 1 ) ) {
         sprintf( message , "%5ld KBytes" , ( size / __GIM_KB ) );
         return message;
     }
     if ( ( size / __GIM_KB ) < 1 ) {
         sprintf( message , "%5ld Bytes" , size );
         return message;
     }
     return NULL;
 }
References __GIM_CLEAR, __GIM_KB, and __GIM_MB.
Referenced by Alloc(), Free(), gim_identity_obj::get(), Lock(), and Unlock().
peek_reset()
void gim_memory_obj::peek_reset (void)
Definition at line 530 of file gim_memory.cc.
{
     allocated_peek = 0;
 }
set_default_lock()
void gim_memory_obj::set_default_lock (_gim_flag deflock)
Definition at line 467 of file gim_memory.cc.
{
     this->lock = deflock;
 }
Unlock()
_gim_flag gim_memory_obj::Unlock (void * to_unlock)
Definition at line 535 of file gim_memory.cc.
{
     char message[256];
     for ( currentlist = startlist ; currentlist != NULL ; currentlist = currentlist->next ) {
         if ( (unsigned long long)to_unlock == (unsigned long long)currentlist->data ) {
             if ( currentlist->lock == __GIM_MEM_UNLOCK ) {
                 gim_error->set( GIM_ERROR_WARNING , "gim_memory_obj::Unlock", "This frame was already Unlocked" , __GIM_OK );
                 return __GIM_MEM_UNLOCK;
             }
             currentlist->lock = __GIM_MEM_UNLOCK;
             sprintf( message , "Correctly Unlocked      [%s] index[%p] , Allocation id : %s" , metric_converter( currentlist->size ) , currentlist->data , code_to_id( currentlist->caller ) );
             gim_error->set( "gim_memory_obj::Unlock", message );
             return __GIM_MEM_UNLOCK;
         }
     }
     gim_error->set( GIM_ERROR_WARNING , "gim_memory_obj::Unlock", "Frame not found" , __GIM_OK );
     return __GIM_NOT_EXIST;
 }
References __GIM_MEM_UNLOCK, __GIM_NOT_EXIST, __GIM_OK, gim_mem_list::caller, gim_mem_list::data, gim_error, GIM_ERROR_WARNING, gim_mem_list::lock, metric_converter(), gim_mem_list::next, gim_error_obj::set(), and gim_mem_list::size.
Referenced by Alloc_unlocked(), and Unlock_and_free().
Unlock_and_free()
_gim_flag gim_memory_obj::Unlock_and_free (void * to_free)
Definition at line 248 of file gim_memory.cc.
{
     _gim_flag result = Check( to_free );
     if ( result == __GIM_NOT_EXIST )
         return __GIM_NOT_EXIST;
     Unlock( to_free );
     Free( to_free );
 }
References __GIM_NOT_EXIST, Check(), Free(), and Unlock().
Referenced by gim_list_obj::del_item(), and gim_gkfp_obj::extract_data().
Virtual_memory()
_gim_flag gim_memory_obj::Virtual_memory (void)
Definition at line 520 of file gim_memory.cc.
{
     return virt_mem;
 }
Vmem()
void gim_memory_obj::Vmem (_gim_flag flag)
Definition at line 471 of file gim_memory.cc.
{
     virt_mem = flag;
     if ( virt_mem == __GIM_ON )
         gim_error->set( "gim_memory_obj::Vmem" , "Virtual memory enabled" );
     else if ( virt_mem == __GIM_OFF )
         gim_error->set( "gim_memory_obj::Vmem" , "Virtual memory DISABLED" );
     else
         gim_error->set( GIM_ERROR_CRITICAL , "gim_memory_obj::Vmem" , "Virtual memory : UNKNOWN VALUE" , __GIM_ERROR );
 }
References __GIM_ERROR, __GIM_OFF, __GIM_ON, gim_error, GIM_ERROR_CRITICAL, and gim_error_obj::set().