My Project: Main Page
MTRand Class Reference
Mersenne Twister random number generator.
#include <gim_mersennetwister.h>
Public Member Functions
MTRand ()
MTRand (_gim_Ulong oneSeed)
double operator() ()
double rand ()
double rand (const double &n)
double randDblExc ()
double randDblExc (const double &n)
double randExc ()
double randExc (const double &n)
_gim_Ulong randInt ()
_gim_Ulong randInt (const _gim_Ulong &n)
void seed ()
void seed (const _gim_Ulong oneSeed)
Static Protected Member Functions
static _gim_Ulong hash (time_t t, clock_t c)
Protected Attributes
_gim_Ulong mt [624]
int mti = 624 +1
Detailed Description
Mersenne Twister random number generator.
Author
Based on code by Makoto Matsumoto, Takuji Nishimura considering the suggestions by Topher Cooper and Marc Rieffel
Richard J. Wagner - rjwag.nosp@m.ner@.nosp@m.write.nosp@m.me.c.nosp@m.om
Warning
This class is not documented by gkript.org.
Definition at line 108 of file gim_mersennetwister.h.
Constructor & Destructor Documentation
MTRand() [1/2]
MTRand::MTRand (_gim_Ulong oneSeed) inline
Definition at line 143 of file gim_mersennetwister.h.
{
         seed( oneSeed );
     }
References seed().
MTRand() [2/2]
MTRand::MTRand () inline
Definition at line 147 of file gim_mersennetwister.h.
{
         seed();
     }
References seed().
Member Function Documentation
hash()
_gim_Ulong MTRand::hash (time_t t, clock_t c) inline static protected
Definition at line 245 of file gim_mersennetwister.h.
     {
         // Get a _gim_Ulong from t and c
         // Better than _gim_Ulong(x) in case x is floating point in [0,1]
         // Based on code by Lawrence Kirby (fred@genesis.demon.co.uk)
         static _gim_Ulong differ = 0;  // guarantee time-based seeds will change
         _gim_Ulong h1 = 0;
         unsigned char *p = (unsigned char *) &t;
         for( size_t i = 0; i < sizeof(t); ++i )
         {
             h1 *= UCHAR_MAX + 2U;
             h1 += p[i];
         }
         _gim_Ulong h2 = 0;
         p = (unsigned char *) &c;
         for( size_t j = 0; j < sizeof(c); ++j )
         {
             h2 *= UCHAR_MAX + 2U;
             h2 += p[j];
         }
         return ( h1 + differ++ ) ^ h2;
     }
Referenced by seed().
operator()()
double MTRand::operator() () inline
Definition at line 132 of file gim_mersennetwister.h.
 { return rand(); }  // same as rand()
References rand().
rand() [1/2]
double MTRand::rand () inline
Definition at line 151 of file gim_mersennetwister.h.
{
         return double(randInt()) * (1.0/4294967295.0);
     }
References randInt().
Referenced by operator()().
rand() [2/2]
double MTRand::rand (const double & n) inline
Definition at line 155 of file gim_mersennetwister.h.
{
         return double(randInt()) * n;
     }
References randInt().
randDblExc() [1/2]
double MTRand::randDblExc ()
randDblExc() [2/2]
double MTRand::randDblExc (const double & n)
randExc() [1/2]
double MTRand::randExc () inline
Definition at line 159 of file gim_mersennetwister.h.
{
         return double(randInt()) * (1.0/4294967296.0);
     }
References randInt().
Referenced by randExc().
randExc() [2/2]
double MTRand::randExc (const double & n) inline
Definition at line 163 of file gim_mersennetwister.h.
{
         return randExc() * n;
     }
References randExc().
randInt() [1/2]
_gim_Ulong MTRand::randInt () inline
Definition at line 167 of file gim_mersennetwister.h.
{
         unsigned long y;
         static unsigned long mag01[2]={0x0, MATRIX_A};
         /* mag01[x] = x * MATRIX_A  for x=0,1 */
         if (mti >= MT_N) { /* generate MT_N words at one time */
             int kk;
             if (mti == MT_N+1)   /* if sgenrand() has not been called, */
                 randInt(4357); /* a default initial seed is used   */
             for (kk=0;kk<MT_N-MT_M;kk++) {
                 y = (mt[kk]&UPPER_MASK)|(mt[kk+1]&LOWER_MASK);
                 mt[kk] = mt[kk+MT_M] ^ (y >> 1) ^ mag01[y & 0x1];
             }
             for (;kk<MT_N-1;kk++) {
                 y = (mt[kk]&UPPER_MASK)|(mt[kk+1]&LOWER_MASK);
                 mt[kk] = mt[kk+(MT_M-MT_N)] ^ (y >> 1) ^ mag01[y & 0x1];
             }
             y = (mt[MT_N-1]&UPPER_MASK)|(mt[0]&LOWER_MASK);
             mt[MT_N-1] = mt[MT_M-1] ^ (y >> 1) ^ mag01[y & 0x1];
             mti = 0;
         }
         y = mt[mti++];
         y ^= TEMPERING_SHIFT_U(y);
         y ^= TEMPERING_SHIFT_S(y) & TEMPERING_MASK_B;
         y ^= TEMPERING_SHIFT_T(y) & TEMPERING_MASK_C;
         y ^= TEMPERING_SHIFT_L(y);
         return y;
     }
References LOWER_MASK, MATRIX_A, mt, MT_M, MT_N, mti, TEMPERING_MASK_B, TEMPERING_MASK_C, TEMPERING_SHIFT_L, TEMPERING_SHIFT_S, TEMPERING_SHIFT_T, TEMPERING_SHIFT_U, and UPPER_MASK.
Referenced by rand(), randExc(), and randInt().
randInt() [2/2]
_gim_Ulong MTRand::randInt (const _gim_Ulong & n) inline
Definition at line 201 of file gim_mersennetwister.h.
     {
         _gim_Ulong used = n;
         used |= used >> 1;
         used |= used >> 2;
         used |= used >> 4;
         used |= used >> 8;
         used |= used >> 16;
         _gim_Ulong i;
         do
             i = randInt() & used;  // toss unused bits to shorten search
         while ( i > n );
         return i;
     }
References randInt().
seed() [1/2]
void MTRand::seed () inline
Definition at line 228 of file gim_mersennetwister.h.
{
         register bool success = true;
         FILE* urandom = fopen( "/dev/urandom", "rb" );
         if( urandom ) {
             _gim_Ulong s;
             success = fread( &s, sizeof(_gim_Ulong), 1, urandom );
             fclose(urandom);
             if( success )
                 seed( s );
             else
                 seed( hash( time(NULL), clock() ) );
         }
         else
             seed( hash( time(NULL), clock() ) );
     }
References hash().
Referenced by MTRand().
seed() [2/2]
void MTRand::seed (const _gim_Ulong oneSeed) inline
Definition at line 218 of file gim_mersennetwister.h.
{
         /* setting initial seeds to mt[MT_N] using         */
         /* the generator Line 25 of Table 1 in          */
         /* [KNUTH 1981, The Art of Computer Programming */
         /*    Vol. 2 (2nd Ed.), pp102]                  */
         mt[0]= oneSeed & 0xffffffff;
         for (mti=1; mti<MT_N; mti++)
             mt[mti] = (69069 * mt[mti-1]) & 0xffffffff;
     }
References mt, MT_N, and mti.
Member Data Documentation
mt
_gim_Ulong MTRand::mt[624] protected
Definition at line 114 of file gim_mersennetwister.h.
Referenced by randInt(), and seed().
mti
int MTRand::mti = 624 +1 protected
Definition at line 115 of file gim_mersennetwister.h.
Referenced by randInt(), and seed().