My Project: Main Page
gim_checksum_obj Class Reference
A Gim class to digest everything.
#include <gim_checksum.h>
Public Member Functions
gim_checksum_obj ()
gim_checksum_obj constructor.
char * md5 (char *buffer, _gim_Uint32 size)
Use this function to get an md5 hash from a buffer.
char * md5 (char *file_name)
Use this function to get an md5 hash from a file.
char * sha1 (char *buffer, _gim_Uint32 size)
Use this function to get an sha1 hash from a buffer.
char * sha1 (char *file_name)
Use this function to get an sha1 hash from a file.
char * sha256 (char *buffer, _gim_Uint32 size)
Use this function to get an sha256 hash from a buffer.
char * sha256 (char *file_name)
Use this function to get an sha256 hash from a file.
char * sha512 (char *buffer, _gim_Uint32 size)
Use this function to get an sha512 hash from a buffer.
char * sha512 (char *file_name)
Use this function to get an sha512 hash from a file.
Detailed Description
A Gim class to digest everything.
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
1.0-0
Date
2003-2007
Definition at line 89 of file gim_checksum.h.
Constructor & Destructor Documentation
gim_checksum_obj()
gim_checksum_obj::gim_checksum_obj () inline
gim_checksum_obj constructor.
The gim_checksum_obj constructor make a control on the dimension of the standard type int and if the machine is big-endian or litle-endian.
Definition at line 168 of file gim_checksum.h.
{
                 #ifdef CHECK_HARDWARE_PROPERTIES
                     char message[256];
                     gim_error->set( "gim_checksum_obj::gim_checksum_obj" , "Checking architecture variable size..." );
                     sprintf( message , "short     : %d bytes" , sizeof( short ) );
                     gim_error->set( "gim_checksum_obj::gim_checksum_obj" , message );
                     if ( sizeof( short ) != 2 ) {
                         fprintf(stderr, "** Configuration error.  Setting for \"short\" is incorrect.\n");
                         fprintf(stderr, "   This must be a 16 bit data type, but it\n");
                         fprintf(stderr, "   is configured as a %d bit data type.\n", sizeof( short ) * 8);
                         gim_error->set( GIM_ERROR_CRITICAL , "gim_checksum_obj::gim_checksum_obj" , "Hardware incompatibility. SHORT type is too long" , -1 );
                     }
                     else {
                         gim_error->set( "gim_checksum_obj::gim_checksum_obj" , "short     : OK"  );
                     }
                     sprintf( message , "int       : %d bytes" , sizeof( _gim_int32 ) );
                     gim_error->set( "gim_checksum_obj::gim_checksum_obj" , message );
                     if ( sizeof( _gim_int32 ) != 4 ) {
                         fprintf(stderr, "** Configuration error.  Setting for \"int\" is incorrect.\n");
                         fprintf(stderr, "   This must be a 32 bit data type, but it\n");
                         fprintf(stderr, "   is configured as a %d bit data type.\n", sizeof( int ) * 8);
                         gim_error->set( GIM_ERROR_CRITICAL , "gim_checksum_obj::gim_checksum_obj" , "Hardware incompatibility. INT type is too long" , -1 );
                     }
                     else {
                         gim_error->set( "gim_checksum_obj::gim_checksum_obj" , "int       : OK" );
                     }
                     sprintf( message , "long      : %d bytes" , sizeof( _gim_long ) );
                     gim_error->set( "gim_checksum_obj::gim_checksum_obj" , message );
                     if ( sizeof( _gim_long ) != 4 ) {
                         fprintf(stderr, "** Configuration error.  Setting for \"long\" is incorrect.\n");
                         fprintf(stderr, "   This must be a 32 bit data type, but it\n");
                         fprintf(stderr, "   is configured as a %d bit data type.\n", sizeof( long ) * 8);
                         gim_error->set( GIM_ERROR_CRITICAL , "gim_checksum_obj::gim_checksum_obj" , "Hardware incompatibility. LONG type is too long" , -1 );
                     }
                     else {
                         gim_error->set( "gim_checksum_obj::gim_checksum_obj" , "long      : OK" );
                     }
                     sprintf( message , "long long : %d bytes" , sizeof( long long ) );
                     gim_error->set( "gim_checksum_obj::gim_checksum_obj" , message );
                     if ( sizeof( long long ) != 8 ) {
                         fprintf(stderr, "** Configuration error.  Setting for \"long long\" is incorrect.\n");
                         fprintf(stderr, "   This must be a 64 bit data type, but it\n");
                         fprintf(stderr, "   is configured as a %d bit data type.\n", sizeof( long long ) * 8);
                         gim_error->set( GIM_ERROR_CRITICAL , "gim_checksum_obj::gim_checksum_obj" , "Hardware incompatibility. LONG LONG type is too long" , -1 );
                     }
                     else {
                         gim_error->set( "gim_checksum_obj::gim_checksum_obj" , "long long : OK" );
                     }
                     #ifndef HIGHFIRST
{
                             int t = 0x12345678;
                             if (*((char *) &t) != 0x78) {
                                 fprintf(stderr, "** Configuration error.  Setting for HIGHFIRST in file md5.h\n");
                                 fprintf(stderr, "   is incorrect.  This symbol has not been defined, yet this\n");
                                 fprintf(stderr, "   machine is a big-endian (most significant byte first in\n");
                                 fprintf(stderr, "   memory) architecture.  Please modify md5.h so HIGHFIRST is\n");
                                 fprintf(stderr, "   defined when building for this machine.\n");
                                 gim_error->set( GIM_ERROR_FATAL , "gim_checksum_obj::gim_checksum_obj" , "Hardware incompatibility." , -1 );
                             }
                         }
                     #endif
                 #endif
             }
References gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_FATAL, and gim_error_obj::set().
Member Function Documentation
md5() [1/2]
char * gim_checksum_obj::md5 (char * buffer, _gim_Uint32 size)
Use this function to get an md5 hash from a buffer.
Parameters
buffer The pointer of the buffer
buffer != NULL
size It describes the length of the buffer
size > 0
Returns
an ascii digest
Definition at line 49 of file gim_checksum.cc.
{
     char                digest[16];
     static char         hex[33];
     MD5_CTX             c;
     _gim_Uint8          i;
     gim_md5_obj         md5;
     md5.MD5Init( &c );
     md5.MD5Update( &c , ( unsigned char * ) buffer , size );
     md5.MD5Final( (unsigned char *) digest , &c );
     for( i = 0 ; i < 16 ; i++ )
         snprintf( ( hex + ( 2 * i ) ) , 3 , "%02x" , ( unsigned char ) digest[i] );
     return hex;
 }
Referenced by gim_password_obj::calc(), gim_gkfp_obj::Extract(), gim_db_obj::gdbs_execute(), md5(), gim_gkfp_obj::Open(), gim_gkdp_obj::open(), gim_gkfp_obj::read_data(), and gim_gkfp_obj::write_data().
md5() [2/2]
char * gim_checksum_obj::md5 (char * file_name)
Use this function to get an md5 hash from a file.
Parameters
file_name The file name you want to digest
file_name != NULL
Returns
an ascii md5 digest
Definition at line 64 of file gim_checksum.cc.
{
     char                digest[16];
     static char         hex[33];
     MD5_CTX             c;
     _gim_Uint8          i = 0;
     _gim_handler        * hand = NULL;
     gim_md5_obj         md5;
     hand = gim_file_manager->open( file_name , __GIM_FILE_MAPPING , __GIM_READ );
     if ( hand != NULL) {
         md5.MD5Init( &c );
         md5.MD5Update( &c , ( unsigned char * )hand->fm , hand->size );
         md5.MD5Final( (unsigned char *) digest , &c );
         for( i = 0 ; i < 16 ; i++ )
             snprintf( ( hex + ( 2 * i ) ) , 3 , "%02x" , ( unsigned char ) digest[i] );
         gim_file_manager->close( hand );
         return hex;
     }
     gim_error->set( "gim_checksum_obj::md5" , 2 );
     return NULL;
 }
References __GIM_FILE_MAPPING, __GIM_READ, gim_file_manager_obj::close(), gim_global_item_handler::fm, gim_error, gim_file_manager, md5(), gim_file_manager_obj::open(), gim_error_obj::set(), and gim_global_item_handler::size.
sha1() [1/2]
char * gim_checksum_obj::sha1 (char * buffer, _gim_Uint32 size)
Use this function to get an sha1 hash from a buffer.
Parameters
buffer The pointer of the buffer
buffer != NULL
size It is the length of the buffer
size > 0
Returns
an ascii digest
Definition at line 86 of file gim_checksum.cc.
{
     char                digest[20];
     static char         hex[41];
     SHA1_CTX            c;
     gim_sha1_obj        sha1;
     _gim_Uint8          i;
     sha1.SHA1Init( &c );
     sha1.SHA1Update( &c , ( unsigned char * )buffer , size );
     sha1.SHA1Final( ( unsigned char * )digest , &c );
     for( i = 0 ; i < 20 ; i++ )
         snprintf( ( hex + ( 2 * i ) ) , 3 , "%02x" , ( unsigned char ) digest[i] );
     return hex;
 }
Referenced by gim_password_obj::calc(), gim_gkfp_obj::lmake(), and sha1().
sha1() [2/2]
char * gim_checksum_obj::sha1 (char * file_name)
Use this function to get an sha1 hash from a file.
Parameters
file_name The file name you want to digest
file_name != NULL
Returns
an ascii digest
Definition at line 101 of file gim_checksum.cc.
{
     char                digest[20];
     static char         hex[41];
     SHA1_CTX            c;
     _gim_Uint8          i;
     _gim_buffer         buffer = NULL;
     gim_file_obj        file( file_name );
     gim_sha1_obj        sha1;
     if ( file.check() == __GIM_EXIST ) {
         buffer = file.load();
     }
     else {
         gim_error->set( "gim_checksum_obj::sha1" , 2 );
         return NULL;
     }
     sha1.SHA1Init( &c );
     sha1.SHA1Update( &c , ( unsigned char * ) buffer , file.size() );
     sha1.SHA1Final( ( unsigned char * ) digest , &c );
     for( i = 0 ; i < 20 ; i++ )
         snprintf( ( hex + ( 2 * i ) ) , 3 , "%02x" , (unsigned char)digest[i] );
     file.close();
     return hex;
 }
References __GIM_EXIST, gim_file_obj::check(), gim_file_obj::close(), gim_error, gim_file_obj::load(), gim_error_obj::set(), sha1(), and gim_file_obj::size().
sha256() [1/2]
char * gim_checksum_obj::sha256 (char * buffer, _gim_Uint32 size)
Use this function to get an sha256 hash from a buffer.
Parameters
buffer The pointer of the buffer
buffer != NULL
size It describes the length of the buffer
size > 0
Returns
an ascii digest
Definition at line 149 of file gim_checksum.cc.
{
     char                digest[32];
     static char         hex[65];
     SHA256_ctx          c;
     _gim_Uint8          i;
     gim_sha256_obj      sha256;
     sha256.SHA256_init( &c );
     sha256.SHA256_update( &c , ( unsigned char * ) buffer , size );
     sha256.SHA256_final( &c , ( unsigned char * ) digest );
     for( i = 0 ; i < 32 ; i++ )
         snprintf( ( hex + ( 2 * i ) ) , 3 , "%02x" , ( unsigned char ) digest[i] );
     return hex;
 }
Referenced by gim_password_obj::calc(), and sha256().
sha256() [2/2]
char * gim_checksum_obj::sha256 (char * file_name)
Use this function to get an sha256 hash from a file.
Parameters
file_name The file name you want to digest
file_name != NULL
Returns
an ascii digest
Definition at line 125 of file gim_checksum.cc.
{
     char                digest[32];
     static char         hex[65];
     SHA256_ctx          c;
     _gim_Uint8          i;
     _gim_buffer         buffer = NULL;
     gim_file_obj        file( file_name );
     gim_sha256_obj      sha256;
     if ( file.check() == __GIM_EXIST ) {
         buffer = file.load();
     }
     else {
         gim_error->set( "gim_checksum_obj::sha256" , 2 );
         return NULL;
     }
     sha256.SHA256_init( &c );
     sha256.SHA256_update( &c , (unsigned char *)buffer , file.size() );
     sha256.SHA256_final( &c , (unsigned char *)digest );
     for( i = 0 ; i < 32 ; i++ )
         snprintf( ( hex + ( 2 * i ) ) , 3 , "%02x" , (unsigned char)digest[i] );
     file.close();
     return hex;
 }
References __GIM_EXIST, gim_file_obj::check(), gim_file_obj::close(), gim_error, gim_file_obj::load(), gim_error_obj::set(), sha256(), and gim_file_obj::size().
sha512() [1/2]
char * gim_checksum_obj::sha512 (char * buffer, _gim_Uint32 size)
Use this function to get an sha512 hash from a buffer.
Parameters
buffer The pointer of the buffer
buffer != NULL
size It describes the length of the buffer
size > 0
Returns
an ascii digest
Definition at line 188 of file gim_checksum.cc.
{
     char                digest[64];
     static char         hex[129];
     SHA512_ctx          c;
     _gim_Uint8          i;
     gim_sha512_obj      sha512;
     sha512.SHA512_init( &c );
     sha512.SHA512_update( &c , ( const void * ) buffer , size );
     sha512.SHA512_final( &c );
     sha512.SHA512_digest( &c , ( unsigned char * ) digest );
     for( i = 0 ; i < 64 ; i++ )
         snprintf( ( hex + ( 2 * i ) ) , 3 , "%02x" , ( unsigned char ) digest[i] );
     return hex;
 }
Referenced by gim_password_obj::calc(), and sha512().
sha512() [2/2]
char * gim_checksum_obj::sha512 (char * file_name)
Use this function to get an sha512 hash from a file.
Parameters
file_name The file name you want to digest
file_name != NULL
Returns
an ascii digest
Definition at line 163 of file gim_checksum.cc.
{
     char                digest[64];
     static char         hex[129];
     SHA512_ctx          c;
     _gim_Uint8          i;
     _gim_buffer         buffer = NULL;
     gim_file_obj        file( file_name );
     gim_sha512_obj      sha512;
     if ( file.check() == __GIM_EXIST ) {
         buffer = file.load();
     }
     else {
         gim_error->set( "gim_checksum_obj::sha512" , 2 );
         return NULL;
     }
     sha512.SHA512_init( &c );
     sha512.SHA512_update( &c , ( const void * ) buffer , file.size() );
     sha512.SHA512_final( &c );
     sha512.SHA512_digest( &c , ( unsigned char * ) digest );
     for( i = 0 ; i < 64 ; i++ )
         snprintf( ( hex + ( 2 * i ) ) , 3 , "%02x" , ( unsigned char ) digest[i] );
     file.close();
     return hex;
 }
References __GIM_EXIST, gim_file_obj::check(), gim_file_obj::close(), gim_error, gim_file_obj::load(), gim_error_obj::set(), sha512(), and gim_file_obj::size().