My Project: Main Page
gim_ascii_file_obj Class Reference
#include <gim_ascii_buffer.h>
Public Member Functions
_gim_flag append (char *to_append)
_gim_flag append (const char *format,...)
char * get_buffer (void)
gim_ascii_file_obj ()
_gim_flag insert_variable (char *variable)
_gim_flag is_in_buffer (char *to_find)
_gim_int32 lenght (void)
_gim_int32 lines (void)
_gim_flag seek (_gim_int32 position)
_gim_flag seekf (_gim_flag position)
_gim_flag set_dimension (_gim_int32 size)
_gim_flag substitute (char *variable, char *text)
~gim_ascii_file_obj ()
Detailed Description
Definition at line 58 of file gim_ascii_buffer.h.
Constructor & Destructor Documentation
gim_ascii_file_obj()
gim_ascii_file_obj::gim_ascii_file_obj () inline
gim_list_obj constructor
Definition at line 87 of file gim_ascii_buffer.h.
{
                 index = 0;
                 dimension = 0;
                 lex = new prsr_lexical_class;
                 gim_error->set( "gim_list_obj::gim_ascii_file_obj" , "A new ascii buffer allocated and inizialized" );
             };
References gim_error, and gim_error_obj::set().
~gim_ascii_file_obj()
gim_ascii_file_obj::~gim_ascii_file_obj () inline
gim_list_obj distructor
Definition at line 96 of file gim_ascii_buffer.h.
{
                 delete lex;
 /*              if ( chrbuf != NULL ) {
                     gim_memory->Unlock_and_free( chrbuf );
                 }
 */              gim_error->set( "gim_list_obj::gim_ascii_file_obj" , "An ascii buffer deleted" );
             };
References gim_error, and gim_error_obj::set().
Member Function Documentation
append() [1/2]
_gim_flag gim_ascii_file_obj::append (char * to_append)
Definition at line 59 of file gim_ascii_buffer.cc.
{
     this->seekf( __GIM_LAST );
     if ( ( dimension > 0 ) && ( chrbuf != NULL ) ) {
         strcat( chrbuf , to_append );
         this->seekf( __GIM_LAST );
         return __GIM_OK;
     }
     gim_error->set( GIM_ERROR_WARNING , "gim_ascii_file_obj::append" , "Buffer not defined" , __GIM_ERROR );
     return __GIM_ERROR;
 }
References __GIM_ERROR, __GIM_LAST, __GIM_OK, gim_error, GIM_ERROR_WARNING, seekf(), and gim_error_obj::set().
Referenced by append().
append() [2/2]
_gim_flag gim_ascii_file_obj::append (const char * format, ...)
Definition at line 83 of file gim_ascii_buffer.cc.
{
     char    message[1024];
     _gim_flag   res;
     va_list VAList;
     va_start( VAList , format );
     vsprintf( message , format , VAList );
     va_end( VAList );
     res = append( message );
     return res;
 }
References append().
get_buffer()
char * gim_ascii_file_obj::get_buffer (void)
Definition at line 174 of file gim_ascii_buffer.cc.
{
     if ( ( dimension > 0 ) && ( chrbuf != NULL ) )
         return chrbuf;
     gim_error->set( GIM_ERROR_WARNING , "gim_ascii_file_obj::get_buffer" , "Buffer not defined" , __GIM_ERROR );
     return NULL;
 }
References __GIM_ERROR, gim_error, GIM_ERROR_WARNING, and gim_error_obj::set().
insert_variable()
_gim_flag gim_ascii_file_obj::insert_variable (char * variable)
is_in_buffer()
_gim_flag gim_ascii_file_obj::is_in_buffer (char * to_find)
Definition at line 123 of file gim_ascii_buffer.cc.
{
     if ( ( dimension > 0 ) && ( chrbuf != NULL ) ) {
 //      TO DO !!!
     }
 }
lenght()
_gim_int32 gim_ascii_file_obj::lenght (void)
Definition at line 96 of file gim_ascii_buffer.cc.
{
     _gim_Uint32 pos = 0;
     if ( ( dimension > 0 ) && ( chrbuf != NULL ) ) {
         while ( chrbuf[pos] != '\0' )
             pos++;
         return pos;
     }
     gim_error->set( GIM_ERROR_WARNING , "gim_ascii_file_obj::leght" , "Buffer not defined" , __GIM_ERROR );
     return __GIM_ERROR;
 }
References __GIM_ERROR, gim_error, GIM_ERROR_WARNING, and gim_error_obj::set().
Referenced by seek(), and seekf().
lines()
_gim_int32 gim_ascii_file_obj::lines (void)
Definition at line 108 of file gim_ascii_buffer.cc.
{
     _gim_int32 c = 0 , res = 0;
     if ( ( dimension > 0 ) && ( chrbuf != NULL ) ) {
         while ( chrbuf[c] != '\0' ) {
             if ( chrbuf[c] == '\n' )
                 res++;
         }
         return res;
     }
     gim_error->set( GIM_ERROR_WARNING , "gim_ascii_file_obj::lines" , "Buffer not defined" , __GIM_ERROR );
     return __GIM_ERROR;
 }
References __GIM_ERROR, gim_error, GIM_ERROR_WARNING, and gim_error_obj::set().
seek()
_gim_flag gim_ascii_file_obj::seek (_gim_int32 position)
Definition at line 152 of file gim_ascii_buffer.cc.
{
     _gim_int32 c = 0;
     if ( position > this->lenght() ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_ascii_file_obj::seek" , "Requested position is beyond the end of buffer" , __GIM_ERROR );
         return __GIM_ERROR;
     }
     if ( ( dimension > 0 ) && ( chrbuf != NULL ) ) {
         while ( ( chrbuf[c] != '\0' ) || ( c == position  ) ) {
             index = c++;
         }
         if ( c == position )
             return __GIM_OK;
         else {
             gim_error->set( GIM_ERROR_WARNING , "gim_ascii_file_obj::seek" , "Reached the end of buffer before the requested position" , __GIM_ERROR );
             return __GIM_ERROR;
         }
     }
     gim_error->set( GIM_ERROR_WARNING , "gim_ascii_file_obj::seek" , "Buffer not defined" , __GIM_ERROR );
     return __GIM_ERROR;
 }
References __GIM_ERROR, __GIM_OK, gim_error, GIM_ERROR_WARNING, lenght(), and gim_error_obj::set().
seekf()
_gim_flag gim_ascii_file_obj::seekf (_gim_flag position)
Definition at line 132 of file gim_ascii_buffer.cc.
{
     if ( ( dimension > 0 ) && ( chrbuf != NULL ) ) {
         switch ( position ) {
             case __GIM_FIRST : {
                 index = 0;
                 return __GIM_OK;
             }
             case __GIM_LAST : {
                 index = this->lenght();
                 return __GIM_OK;
             }
             default : {
                 gim_error->set( GIM_ERROR_WARNING , "gim_ascii_file_obj::seekf" , "Position flag unknown" , __GIM_ERROR );
                 return __GIM_ERROR;
             }
         }
     }
 }
References __GIM_ERROR, __GIM_FIRST, __GIM_LAST, __GIM_OK, gim_error, GIM_ERROR_WARNING, lenght(), and gim_error_obj::set().
Referenced by append().
set_dimension()
_gim_flag gim_ascii_file_obj::set_dimension (_gim_int32 size)
Definition at line 42 of file gim_ascii_buffer.cc.
{
     if ( ( dimension == 0 ) && ( size > 0 ) )  {
         dimension = size;
         chrbuf = (char *)gim_memory->Alloc( sizeof( char ) * dimension , __GIM_ASCII_BUFFER , __GIM_HIDE );
         if ( chrbuf == NULL ) {
             gim_error->set( GIM_ERROR_CRITICAL , "gim_ascii_file_obj::set_dimension" , "Allocation of a new file list member failed"  , __GIM_ERROR );
             return __GIM_ERROR;
         }
         __GIM_VCLEAR( chrbuf , dimension , char , '\0' );
         return __GIM_OK;
     }
     gim_error->set( GIM_ERROR_CRITICAL , "gim_ascii_file_obj::set_dimension" , "Buffer already defined." , __GIM_ERROR );
     gim_error->set( GIM_ERROR_CRITICAL , "gim_ascii_file_obj::set_dimension" , "Please, use change_dimension method instead" , __GIM_ERROR );
     return __GIM_ERROR;
 }
References __GIM_ASCII_BUFFER, __GIM_ERROR, __GIM_HIDE, __GIM_OK, __GIM_VCLEAR, gim_memory_obj::Alloc(), gim_error, GIM_ERROR_CRITICAL, gim_memory, and gim_error_obj::set().
substitute()
_gim_flag gim_ascii_file_obj::substitute (char * variable, char * text)