My Project: Main Page
gim_cnc_alfabeto_obj Class Reference
#include <gim_cnc.h>
Public Member Functions
_gim_flag control (int)
void init (void)
void make (void)
Public Attributes
char alfabeto [('~' - '!')]
_gim_int8 posizione [('~' - '!')]
_gim_int8 rotazione [('~' - '!')]
Detailed Description
Definition at line 109 of file gim_cnc.h.
Member Function Documentation
control()
_gim_flag gim_cnc_alfabeto_obj::control (int res)
Definition at line 27 of file gim_cnc_alfabeto.cc.
{
     _gim_Uint8  q;
     for ( q = 0; q < MAX_BASE; q++ )
         if ( alfabeto[q] == res )
             return ( __GIM_NO );
     return __GIM_YES;
 }
References __GIM_NO, __GIM_YES, alfabeto, and MAX_BASE.
Referenced by make().
init()
void gim_cnc_alfabeto_obj::init (void)
Definition at line 22 of file gim_cnc_alfabeto.cc.
{
     memset ( alfabeto   , NL , MAX_BASE );
     memset ( rotazione  , 0  , MAX_BASE );
 }
References alfabeto, MAX_BASE, NL, and rotazione.
Referenced by gim_cnc_obj::set().
make()
void gim_cnc_alfabeto_obj::make (void)
Definition at line 35 of file gim_cnc_alfabeto.cc.
{
     int c, res, s,stack;
     char message[256];
     _gim_rand   mt;
     stack = cnc_feature.VariableAB;
     cnc_feature.VariableAB = __GIM_OFF;
     cnc_password->calc();
     mt.seed( cnc_password->seed_main );
     gim_error->set( "gim_cnc_alfabeto_obj::make" , "Randomize the FOG alphabet..." );
     for (c = 0, s = 0; s < MAX_BASE; c++)   {
         res = cnc_generic.num2char( mt.randInt( MAX_BASE ) );
         if (control( res ) == __GIM_YES ) {
             cnc_alfabeto.alfabeto[s] = res;
             cnc_alfabeto.posizione[s] = s;
             s++;
         }
     }
     sprintf( message , "Done %d attempts on %d FOG char", c, s);
     gim_error->set( "gim_cnc_alfabeto_obj::make" , message );
     cnc_feature.VariableAB = stack;
 }
References __GIM_OFF, __GIM_YES, alfabeto, gim_password_obj::calc(), cnc_alfabeto, cnc_feature, cnc_generic, cnc_password, control(), gim_error, MAX_BASE, gim_cnc_generic_obj::num2char(), posizione, gim_error_obj::set(), and cnc_Kernel_feature_struct::VariableAB.
Referenced by gim_cnc_obj::set().
Member Data Documentation
alfabeto
char gim_cnc_alfabeto_obj::alfabeto[('~' - '!')]
Definition at line 111 of file gim_cnc.h.
Referenced by gim_cnc_generic_obj::char2num(), control(), init(), make(), and gim_cnc_generic_obj::num2char().
posizione
_gim_int8 gim_cnc_alfabeto_obj::posizione[('~' - '!')]
Definition at line 113 of file gim_cnc.h.
Referenced by make().
rotazione
_gim_int8 gim_cnc_alfabeto_obj::rotazione[('~' - '!')]
Definition at line 112 of file gim_cnc.h.
Referenced by init().