My Project: Main Page
gim_prsr_obj Class Reference
With this class you ara able to manage the configuration file key/value. There are two example in the example section abaout a config file in __LEX_A and in __LEX_B.
#include <gim_kvalue.h>
Public Member Functions
_gim_flag AddComment (const char *comment)
This function is used to put a comment on the file.
_gim_flag AddKey (const char *section_name, const char *key, const char *value)
To add a new key in a existing section to a ini file (value must be a char*)
_gim_flag AddKey (const char *section_name, const char *key, float value)
To add a new key in a existing section to a ini file (value must be a float)
_gim_flag AddKey (const char *section_name, const char *key, int value)
To add a new key in a existing section to a ini file (value must be an int)
_gim_flag AddKeyComment (const char *section_name, const char *key, _gim_flag position, const char *comment)
_gim_flag AddKeyFlag (const char *section_name, const char *key, _gim_flag flag)
To add a new key in a existing section to a ini file (value must be a flag)
_gim_flag AddSection (const char *section_name)
To add a new section to the ini file.
_gim_flag AddSectionComment (const char *section_name, _gim_flag position, char *comment)
_gim_flag ChangeKey (const char *section_name, const char *key, const char *string)
To change the value to an existing key.
_gim_flag ChangeKey (const char *section_name, const char *key, int value)
To change the value to an existing key.
_gim_flag ChangeKeyFlag (const char *section_name, const char *key, _gim_flag flag)
_gim_flag CopySection (gim_prsr_obj *from, const char *section_name)
To copy an existing section from a configuration file to another one \paran from A pointer to the class of the source configuration file.
_gim_flag DelKey (const char *section_name, const char *key)
To delete an existing key.
_gim_flag DelSection (const char *section_name)
To delete an existing section from a ini file.
_gim_flag Down (void)
This function is used in order to destroy the object and release all the allocated memmory.
_gim_flag Exist (const char *filename)
This function is used in order to read an existing configuration file.
_gim_flag ExistKey (const char *section_name, const char *key)
In order to check if a key exitst or not inside a specific section.
_gim_flag ExistSection (const char *section_name)
In order to check if a section exitst or not.
_gim_int8 GetHowManyKey (const char *section_name)
To know how many section are present in a ini file.
_gim_int16 GetHowManySection (void)
To know how many section are present in a ini file.
_gim_flag GetKeyFLAG (const char *section_name, const char *key)
In order to obtain the value of one key (flag)
float GetKeyFLT (const char *section_name, const char *key)
In order to obtain the value of one key (float)
int GetKeyINT (const char *section_name, const char *key)
In order to obtain the value of one key (int)
char * GetKeyName (const char *section_name, _gim_int16 kindex)
To get the name of a specific section number.
char * GetKeySTR (const char *section_name, const char *key)
In order to obtain the value of one key (char*)
_gim_flag GetLex (void)
Use this function if you want to get the lexical used in a configuration file.
char * GetSectionName (_gim_int16 secindex)
To get the name of a specific section number.
gim_prsr_obj ()
The constructor.
_gim_flag List (void)
This function is used in order to print on stdout a configuration file.
_gim_flag ParserIsUp (void)
_gim_flag Read (const char *filename)
This function is used in order to read an existing configuration file.
_gim_flag RenameKey (const char *section, const char *old_key, const char *new_key)
To rename an existing section of a ini file.
_gim_flag RenameSection (const char *old_section, const char *new_section)
To rename an existing section of a ini file.
_gim_flag RenameTitle (const char *new_title)
To rename the title of a ini file.
void SetLex (_gim_flag Lex)
This function is used in order to write a configuration file.
_gim_flag ThereIsASection (void)
void Up (const char *filename, const char *title)
This function is used in order to generate a configuration file from code.
_gim_flag Write (void)
This function is used in order to write a configuration file to disk.
_gim_buffer WriteOnBuffer (void)
This function is used in order to get a buffer filled with a configuration file.
Detailed Description
With this class you ara able to manage the configuration file key/value. There are two example in the example section abaout a config file in __LEX_A and in __LEX_B.
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
1.0-0
Date
2003-2007
Definition at line 125 of file gim_kvalue.h.
Constructor & Destructor Documentation
gim_prsr_obj()
gim_prsr_obj::gim_prsr_obj () inline
The constructor.
Definition at line 470 of file gim_kvalue.h.
{
                 prsr_obj = NULL;
                 Lex = __LEX_UNKNOWN;
             }
References __LEX_UNKNOWN.
Member Function Documentation
AddComment()
_gim_flag gim_prsr_obj::AddComment (const char * comment)
This function is used to put a comment on the file.
Parameters
comment The comment to add comment != NULL
Returns
__OK if the object is release
__NOT_OK if not
Definition at line 1039 of file gim_kvalue.cc.
{
     if ( strlen( comment ) > 10240 ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_prsr_obj::AddComment" , "Comment is too long. It will be skipped" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     strcpy( this->prsr_obj->comment , comment );
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_NOT_OK, __GIM_OK, prsr::comment, gim_error, GIM_ERROR_WARNING, and gim_error_obj::set().
Referenced by gim_home_obj::add_default_comment().
AddKey() [1/3]
_gim_flag gim_prsr_obj::AddKey (const char * section_name, const char * key, const char * value)
To add a new key in a existing section to a ini file (value must be a char*)
Parameters
section_name The name of the section you want to add a new key
section_name != NULL
key The name of the new key you want to add
key != NULL
value The value of the new key
value != NULL
Returns
__OK if everything it's ok
__NOT_OK if some error occurred
Definition at line 88 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     prsr_kvalue_field   * tmp_field = NULL;
     prsr_kvalue_field   * new_field = NULL;
     char * tmp_section_name;
     char * tmp_key_name;
     if ( prsr_obj == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::AddKey" , "No parser object defined" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( prsr_obj->first_section == NULL )  {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::AddKey" , "Before to define a Key you must define a Section" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( ( ! strlen( section_name ) ) || ( strlen( section_name ) >= 64 ) )  {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::AddKey" , "Wrong lenght of section name" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( ( ! strlen( value ) ) || ( strlen( value ) >= 64 ) )  {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::AddKey" , "Wrong lenght of value" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( ( ! strlen( key ) ) || ( strlen( key ) >= 64 ) )  {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::AddKey" , "Wrong lenght of Key name" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     tmp_section_name = strdup( Lexical.str_up  ( section_name , strlen( section_name ) ) );
     tmp_key_name     = strdup( Lexical.str_down( key          , strlen( key          ) ) );
     if ( ExistKey( tmp_section_name , tmp_key_name ) == 1 ) return -1;
     for( ; tmp_section ; tmp_section = tmp_section->next_section ) {
         if ( ! strcmp( tmp_section_name , tmp_section->section_name ) ) break;
     }
     if ( ! tmp_section ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::AddKey" , "Section Name not found" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( tmp_section->first_field != NULL ) {
         for( tmp_field = tmp_section->first_field ; tmp_field->next_field ; tmp_field = tmp_field->next_field ) {
             if ( ! ( strcmp( tmp_field->key , tmp_key_name ) ) ) {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::AddKey" , "Section Name already exist" , __GIM_ERROR );
                 return __GIM_NOT_OK;
             }
         }
         new_field = ( prsr_kvalue_field * )gim_memory->Alloc( sizeof( prsr_kvalue_field ) , __GIM_MEM_PRSR_ADDKEY , __GIM_HIDE );
         strcpy( new_field->key , tmp_key_name );
         strcpy( new_field->str_value , value );
         strcpy( new_field->comment , "" );
         new_field->comment_position = PRSR_NONE;
         new_field->key_type = PRSR_GIM_INT;
         new_field->next_field = NULL;
         tmp_field->next_field = new_field;
     }
     if ( tmp_section->first_field == NULL ) {
         new_field = ( prsr_kvalue_field * )gim_memory->Alloc( sizeof( prsr_kvalue_field ) , __GIM_MEM_PRSR_ADDKEY , __GIM_HIDE );
         strcpy( new_field->key , tmp_key_name );
         strcpy( new_field->str_value , value );
         strcpy( new_field->comment , "" );
         new_field->comment_position = PRSR_NONE;
         new_field->key_type = PRSR_GIM_INT;
         new_field->next_field = NULL;
         tmp_section->first_field = new_field;
     }
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_HIDE, __GIM_MEM_PRSR_ADDKEY, __GIM_NOT_OK, __GIM_OK, gim_memory_obj::Alloc(), prsr_kvalue_field::comment, prsr_kvalue_field::comment_position, ExistKey(), prsr_kvalue_section::first_field, prsr::first_section, gim_error, GIM_ERROR_CRITICAL, gim_memory, prsr_kvalue_field::key, prsr_kvalue_field::key_type, Lexical, prsr_kvalue_field::next_field, prsr_kvalue_section::next_section, PRSR_GIM_INT, PRSR_NONE, prsr_kvalue_section::section_name, gim_error_obj::set(), prsr_lexical_class::str_down(), prsr_lexical_class::str_up(), and prsr_kvalue_field::str_value.
AddKey() [2/3]
_gim_flag gim_prsr_obj::AddKey (const char * section_name, const char * key, float value)
To add a new key in a existing section to a ini file (value must be a float)
Parameters
section_name The name of the section you want to add a new key
section_name != NULL
key The name of the new key you want to add
key != NULL
value The value of the new key
Returns
__OK if everything it's ok
__NOT_OK if some error occurred
Definition at line 221 of file gim_kvalue.cc.
{
     static char tmp[64];
     __GIM_CLEAR( tmp , 64 , char );
     sprintf( tmp , "%15.5f" , value );
     return AddKey( section_name , key , tmp );
 }
References __GIM_CLEAR, and AddKey().
AddKey() [3/3]
_gim_flag gim_prsr_obj::AddKey (const char * section_name, const char * key, int value)
To add a new key in a existing section to a ini file (value must be an int)
Parameters
section_name The name of the section you want to add a new key
section_name != NULL
key The name of the new key you want to add
key != NULL
value The value of the new key
Returns
__OK if everything it's ok
__NOT_OK if some error occurred
Definition at line 214 of file gim_kvalue.cc.
{
     static char tmp[64];
     __GIM_CLEAR( tmp , 64 , char );
     sprintf( tmp , "%d" , value );
     return AddKey( section_name , key , tmp );
 }
References __GIM_CLEAR.
Referenced by AddKey(), AddKeyFlag(), CopySection(), and gim_password_obj::gim_password_obj().
AddKeyComment()
_gim_flag gim_prsr_obj::AddKeyComment (const char * section_name, const char * key, _gim_flag position, const char * comment)
Definition at line 980 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     prsr_kvalue_field   * tmp_field;
     char * tmp_section_name;
     char * tmp_key_name;
     tmp_section_name = strdup( Lexical.str_up  ( section_name , strlen( section_name ) ) );
     tmp_key_name     = strdup( Lexical.str_down( key          , strlen( key          ) ) );
     if ( comment == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::AddKeyComment" , "Comment must not be NULL. I cannot add this comment" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( strlen( comment ) > 10240 ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_prsr_obj::AddKeyComment" , "Comment is too long. It will be skipped" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( prsr_obj->first_section != NULL ) {
         for( ; tmp_section != NULL ; tmp_section = tmp_section->next_section ) {
             if( ! strcmp(  tmp_section_name , tmp_section->section_name ) ) {
                 if ( tmp_section->first_field ) {
                     for( tmp_field = tmp_section->first_field ; tmp_field ; tmp_field = tmp_field->next_field ) {
                         if ( ! strcmp( tmp_key_name , tmp_field->key  ) ) {
                             tmp_field->comment_position = position;
                             strcpy( tmp_field->comment , comment );
                         }
                     }
                 }
             }
         }
     }
     return __GIM_NOT_EXIST;
 }
References __GIM_ERROR, __GIM_NOT_EXIST, __GIM_NOT_OK, prsr_kvalue_field::comment, prsr_kvalue_field::comment_position, prsr_kvalue_section::first_field, prsr::first_section, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, prsr_kvalue_field::key, Lexical, prsr_kvalue_field::next_field, prsr_kvalue_section::next_section, prsr_kvalue_section::section_name, gim_error_obj::set(), prsr_lexical_class::str_down(), and prsr_lexical_class::str_up().
Referenced by gim_home_obj::add_default_comment().
AddKeyFlag()
_gim_flag gim_prsr_obj::AddKeyFlag (const char * section_name, const char * key, _gim_flag flag)
To add a new key in a existing section to a ini file (value must be a flag)
Parameters
section_name The name of the section you want to add a new key
section_name != NULL
key The name of the new key you want to add
key != NULL
flag The value of the new key (__GIM_YES or __GIM_NO)
Returns
__OK if everything it's ok
__NOT_OK if some error occurred
Definition at line 154 of file gim_kvalue.cc.
{
     static char tmp[64];
     __GIM_CLEAR( tmp , 64 , char );
     switch (flag) {
         case __GIM_YES : {
             sprintf( tmp , "YES" );
             break;
         }
         case __GIM_NO : {
             sprintf( tmp , "NO" );
             break;
         }
         case __GIM_AUTO : {
             sprintf( tmp , "AUTO" );
             break;
         }
         case __GIM_TRUE : {
             sprintf( tmp , "TRUE" );
             break;
         }
         case __GIM_FALSE : {
             sprintf( tmp , "FALSE" );
             break;
         }
         case __LEX_A : {
             sprintf( tmp , "A" );
             break;
         }
         case __LEX_B : {
             sprintf( tmp , "B" );
             break;
         }
         case __GIM_ON : {
             sprintf( tmp , "ON" );
             break;
         }
         case __GIM_OFF : {
             sprintf( tmp , "OFF" );
             break;
         }
         case __GIM_MEM_LOCK : {
             sprintf( tmp , "LOCKED" );
             break;
         }
         case __GIM_MEM_UNLOCK : {
             sprintf( tmp , "UNLOCKED" );
             break;
         }
         case __GIM_LOG_TEXT : {
             sprintf( tmp , "HTML" );
             break;
         }
         case __GIM_LOG_HTML : {
             sprintf( tmp , "TEXT" );
             break;
         }
     }
     return AddKey( section_name , key , tmp );
 }
References __GIM_AUTO, __GIM_CLEAR, __GIM_FALSE, __GIM_MEM_LOCK, __GIM_MEM_UNLOCK, __GIM_NO, __GIM_OFF, __GIM_ON, __GIM_TRUE, __GIM_YES, __LEX_A, __LEX_B, and AddKey().
AddSection()
_gim_flag gim_prsr_obj::AddSection (const char * section_name)
To add a new section to the ini file.
Parameters
section_name The name of the new section you want to add
section_name != NULL
Returns
__OK if everything it's ok
__NOT_OK if some error occurred
Definition at line 60 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     prsr_kvalue_section * new_section = NULL;
     char * tmp_name;
     if ( ( ! strlen( section_name ) ) || ( strlen( section_name ) >= 64 ) ) return -1;
     tmp_name = strdup( Lexical.str_up( section_name , strlen( section_name ) ) );
     if ( ExistSection( tmp_name ) == __GIM_YES ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_prsr_obj::AddSection" , "Section already exist" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( prsr_obj->first_section != NULL ) {
         for( ; tmp_section->next_section != NULL ; tmp_section = tmp_section->next_section ) ;
         new_section = ( prsr_kvalue_section * )gim_memory->Alloc( sizeof( prsr_kvalue_section ) , __GIM_MEM_PRSR_ADDSECT , __GIM_HIDE );
         strcpy( new_section->section_name , tmp_name );
         new_section->next_section = NULL;
         new_section->comment_position = PRSR_NONE;
         tmp_section->next_section = new_section;
     }
     if ( prsr_obj->first_section == NULL ) {
         new_section = ( prsr_kvalue_section * )gim_memory->Alloc( sizeof( prsr_kvalue_section ) , __GIM_MEM_PRSR_ADDSECT , __GIM_HIDE );
         strcpy( new_section->section_name , tmp_name  );
         new_section->next_section = NULL;
         new_section->comment_position = PRSR_NONE;
         prsr_obj->first_section = new_section;
     }
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_HIDE, __GIM_MEM_PRSR_ADDSECT, __GIM_NOT_OK, __GIM_OK, __GIM_YES, gim_memory_obj::Alloc(), prsr_kvalue_section::comment_position, ExistSection(), prsr::first_section, gim_error, GIM_ERROR_WARNING, gim_memory, Lexical, prsr_kvalue_section::next_section, PRSR_NONE, prsr_kvalue_section::section_name, gim_error_obj::set(), and prsr_lexical_class::str_up().
Referenced by CopySection(), and gim_password_obj::gim_password_obj().
AddSectionComment()
_gim_flag gim_prsr_obj::AddSectionComment (const char * section_name, _gim_flag position, char * comment)
Definition at line 1013 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     prsr_kvalue_field   * tmp_field;
     char * tmp_section_name;
     char * tmp_key_name;
     tmp_section_name = strdup( Lexical.str_up  ( section_name , strlen( section_name ) ) );
     if ( comment == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::AddKeyComment" , "Comment must not be NULL. I cannot add this comment" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( strlen( comment ) > 10240 ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_prsr_obj::AddKeyComment" , "Comment is too long. It will be skipped" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( prsr_obj->first_section != NULL ) {
         for( ; tmp_section != NULL ; tmp_section = tmp_section->next_section ) {
             if( ! strcmp(  tmp_section_name , tmp_section->section_name ) ) {
                 tmp_section->comment_position = position;
                 strcpy( tmp_section->comment , comment );
             }
         }
     }
     return __GIM_NOT_EXIST;
 }
References __GIM_ERROR, __GIM_NOT_EXIST, __GIM_NOT_OK, prsr_kvalue_section::comment, prsr_kvalue_section::comment_position, prsr::first_section, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, Lexical, prsr_kvalue_section::next_section, prsr_kvalue_section::section_name, gim_error_obj::set(), and prsr_lexical_class::str_up().
ChangeKey() [1/2]
_gim_flag gim_prsr_obj::ChangeKey (const char * section_name, const char * key, const char * string)
To change the value to an existing key.
Parameters
section_name The name of the section you want to add a new key
section_name != NULL
key The name of the new key you want to add
key != NULL
string The value of the new key
string != NULL
Returns
__OK if everything it's ok
__NOT_OK if some error occurred
Definition at line 313 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     prsr_kvalue_field   * tmp_field , * before_field = NULL;
     char * tmp_section_name;
     char * tmp_key_name;
     if ( prsr_obj == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::ChangeKey" , "No parser object defined" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( prsr_obj->first_section == NULL )  {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::ChangeKey" , "Before to define a Key you must define a Section" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( ( ! strlen( section_name ) ) || ( strlen( section_name ) >= 64 ) )  {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::ChangeKey" , "Wrong lenght of section name" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( ( ! strlen( string ) ) || ( strlen( string ) >= 64 ) )  {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::ChangeKey" , "Wrong lenght of value" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( ( ! strlen( key ) ) || ( strlen( key ) >= 32 ) )  {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::ChangeKey" , "Wrong lenght of Key name" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     tmp_section_name = strdup( Lexical.str_up  ( section_name , strlen( section_name ) ) );
     tmp_key_name     = strdup( Lexical.str_down( key          , strlen( key          ) ) );
     if ( prsr_obj->first_section != NULL ) {
         for( ; tmp_section != NULL ; tmp_section = tmp_section->next_section ) {
             if( ! strcmp(  tmp_section_name , tmp_section->section_name ) ) {
                 if ( tmp_section->first_field ) {
                     for( tmp_field = tmp_section->first_field ; tmp_field ; before_field=tmp_field , tmp_field = tmp_field->next_field ) {
                         if ( ! strcmp( tmp_key_name , tmp_field->key  ) ) {
                             strcpy( tmp_field->str_value , string );
                             return __GIM_OK;
                         }
                     }
                 }
             }
         }
     }
     return __GIM_NOT_OK;
 }
References __GIM_ERROR, __GIM_NOT_OK, __GIM_OK, prsr_kvalue_section::first_field, prsr::first_section, gim_error, GIM_ERROR_CRITICAL, prsr_kvalue_field::key, Lexical, prsr_kvalue_field::next_field, prsr_kvalue_section::next_section, prsr_kvalue_section::section_name, gim_error_obj::set(), prsr_lexical_class::str_down(), prsr_lexical_class::str_up(), and prsr_kvalue_field::str_value.
Referenced by ChangeKey(), ChangeKeyFlag(), and gim_password_obj::gim_password_obj().
ChangeKey() [2/2]
_gim_flag gim_prsr_obj::ChangeKey (const char * section_name, const char * key, int value)
To change the value to an existing key.
Parameters
section_name The name of the section you want to add a new key
section_name != NULL
key The name of the new key you want to add
key != NULL
value The value of the new key
Returns
__OK if everything it's ok
__NOT_OK if some error occurred
Definition at line 357 of file gim_kvalue.cc.
{
     char tmp[64];
     __GIM_CLEAR( tmp , 64 , char );
     sprintf( tmp , "%d" , value );
     return ChangeKey( section_name , key , tmp );
 }
References __GIM_CLEAR, and ChangeKey().
ChangeKeyFlag()
_gim_flag gim_prsr_obj::ChangeKeyFlag (const char * section_name, const char * key, _gim_flag flag)
Definition at line 1073 of file gim_kvalue.cc.
{
     static char tmp[64];
     __GIM_CLEAR( tmp , 64 , char );
     switch (flag) {
         case __GIM_YES : {
             sprintf( tmp , "YES" );
             break;
         }
         case __GIM_NO : {
             sprintf( tmp , "NO" );
             break;
         }
         case __GIM_TRUE : {
             sprintf( tmp , "TRUE" );
             break;
         }
         case __GIM_FALSE : {
             sprintf( tmp , "FALSE" );
             break;
         }
         case __LEX_A : {
             sprintf( tmp , "A" );
             break;
         }
         case __LEX_B : {
             sprintf( tmp , "B" );
             break;
         }
         case __GIM_ON : {
             sprintf( tmp , "ON" );
             break;
         }
         case __GIM_OFF : {
             sprintf( tmp , "OFF" );
             break;
         }
         case __GIM_MEM_LOCK : {
             sprintf( tmp , "LOCKED" );
             break;
         }
         case __GIM_MEM_UNLOCK : {
             sprintf( tmp , "UNLOCKED" );
             break;
         }
         case __GIM_LOG_TEXT : {
             sprintf( tmp , "HTML" );
             break;
         }
         case __GIM_LOG_HTML : {
             sprintf( tmp , "TEXT" );
             break;
         }
     }
     return ChangeKey( section_name , key , tmp );
 }
References __GIM_CLEAR, __GIM_FALSE, __GIM_MEM_LOCK, __GIM_MEM_UNLOCK, __GIM_NO, __GIM_OFF, __GIM_ON, __GIM_TRUE, __GIM_YES, __LEX_A, __LEX_B, and ChangeKey().
CopySection()
_gim_flag gim_prsr_obj::CopySection (gim_prsr_obj * from, const char * section_name)
To copy an existing section from a configuration file to another one \paran from A pointer to the class of the source configuration file.
Parameters
section_name The name of the section you want to delete
section_name != NULL
Returns
__OK if everything it's ok
__NOT_OK if some error occurred
Definition at line 965 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = from->SearchSection( section_name );
     prsr_kvalue_field   * tmp_field = NULL;
     if ( tmp_section == NULL ) return __GIM_NOT_EXIST;
     AddSection( tmp_section->section_name );
     if ( tmp_section->first_field != NULL ) {
         for( tmp_field = tmp_section->first_field ; tmp_field ; tmp_field = tmp_field->next_field ) {
             AddKey( strdup( tmp_section->section_name ) , strdup( tmp_field->key ) , strdup( tmp_field->str_value ) );
         }
     }
     return __GIM_OK;
 }
References __GIM_NOT_EXIST, __GIM_OK, AddKey(), AddSection(), prsr_kvalue_section::first_field, prsr_kvalue_field::key, prsr_kvalue_field::next_field, prsr_kvalue_section::section_name, and prsr_kvalue_field::str_value.
DelKey()
_gim_flag gim_prsr_obj::DelKey (const char * section_name, const char * key)
To delete an existing key.
Parameters
section_name The name of the section from which you want to delete a key
section_name != NULL
key The name of the new key you want to delete
key != NULL
Returns
__OK if everything it's ok
__NOT_OK if some error occurred
Definition at line 228 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     prsr_kvalue_field   * tmp_field , * before_field = NULL;
     char * tmp_section_name;
     char * tmp_key_name;
     tmp_section_name = strdup( Lexical.str_up  ( section_name , strlen( section_name ) ) );
     tmp_key_name     = strdup( Lexical.str_down( key          , strlen( key          ) ) );
     if ( prsr_obj == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::DelKey" , "No parser object defined" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( prsr_obj->first_section != NULL ) {
         for( ; tmp_section != NULL ; tmp_section = tmp_section->next_section ) {
             if( ! strcmp(  tmp_section_name , tmp_section->section_name ) ) {
                 if ( tmp_section->first_field ) {
                     for( tmp_field = tmp_section->first_field ; tmp_field ; before_field=tmp_field , tmp_field = tmp_field->next_field ) {
                         if ( ! strcmp( tmp_key_name , tmp_field->key  ) ) {
                             if ( ! before_field )
                                 tmp_section->first_field = tmp_field->next_field ;
                             if ( before_field )
                                 before_field->next_field = tmp_field->next_field ;
                             gim_error->set( "gim_prsr_obj::DelKey" , "Removing Key" );
                             if ( gim_memory->Free( tmp_field ) == __GIM_NOT_OK ) {
                                 gim_error->set( GIM_ERROR_WARNING , "gim_prsr_obj::DelKey" , "Some problems with memory" , __GIM_ERROR );
                             }
                             return __GIM_OK;
                         }
                     }
                 }
             }
         }
     }
     return __GIM_NOT_OK;
 }
References __GIM_ERROR, __GIM_NOT_OK, __GIM_OK, prsr_kvalue_section::first_field, prsr::first_section, gim_memory_obj::Free(), gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, gim_memory, prsr_kvalue_field::key, Lexical, prsr_kvalue_field::next_field, prsr_kvalue_section::next_section, prsr_kvalue_section::section_name, gim_error_obj::set(), prsr_lexical_class::str_down(), and prsr_lexical_class::str_up().
DelSection()
_gim_flag gim_prsr_obj::DelSection (const char * section_name)
To delete an existing section from a ini file.
Parameters
section_name The name of the section you want to delete
section_name != NULL
Returns
__OK if everything it's ok
__NOT_OK if some error occurred
Definition at line 263 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     prsr_kvalue_section * before_section = NULL;
     char * tmp_section_name;
     tmp_section_name = strdup( Lexical.str_up  ( section_name , strlen( section_name ) ) );
     if ( prsr_obj == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::DelSection" , "No parser object defined" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( prsr_obj->first_section != NULL ) {
         char message[512];
         sprintf( message , "Removing section %s" , tmp_section_name );
         gim_error->set( "gim_prsr_obj::DelSection" , message );
         for( ; tmp_section ; before_section = tmp_section , tmp_section = tmp_section->next_section ) {
             if( ! strcmp(  tmp_section_name , tmp_section->section_name ) ) {
                 if ( ! before_section )
                     prsr_obj->first_section = tmp_section->next_section ;
                 if ( before_section )
                     before_section->next_section = tmp_section->next_section ;
                 if ( tmp_section->first_field ) {
                     DelSection( tmp_section );
                 }
                 gim_error->set( "gim_prsr_obj::DelSection" , "Done!" );
                 return __GIM_OK;
             }
         }
     }
     return __GIM_NOT_OK;
 }
References __GIM_ERROR, __GIM_NOT_OK, __GIM_OK, prsr::first_section, gim_error, GIM_ERROR_CRITICAL, Lexical, prsr_kvalue_section::next_section, gim_error_obj::set(), and prsr_lexical_class::str_up().
Referenced by Down().
Down()
_gim_flag gim_prsr_obj::Down (void)
This function is used in order to destroy the object and release all the allocated memmory.
Returns
__OK if the object is release
__NOT_OK if not
Definition at line 420 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section  = NULL;
     prsr_kvalue_section * tmp2_section = NULL;
     char    tmp[256];
     if ( prsr_obj == NULL ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_prsr_obj::Down" , "No parser object defined" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     sprintf( tmp , "%s Prsr object goes down..." , prsr_obj->title );
     gim_error->set( "gim_prsr_obj::Down" , tmp );
     if ( prsr_obj->first_section != NULL ) {
         for( tmp_section = prsr_obj->first_section ; tmp_section ; ) {
             tmp2_section = tmp_section->next_section;
             DelSection( tmp_section );
             tmp_section = tmp2_section;
         }
     }
     if ( prsr_obj->fp != NULL )
         Close( __NO_FLUSH );
     if ( gim_memory->Free( prsr_obj ) == __GIM_NOT_OK )
         gim_error->set( GIM_ERROR_WARNING , "gim_prsr_obj::Down" , "Some problems with memory" , __GIM_ERROR );
     prsr_obj = NULL;
     gim_error->set( "gim_prsr_obj::Down" , "Done!" );
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_NOT_OK, __GIM_OK, __NO_FLUSH, DelSection(), prsr::first_section, prsr::fp, gim_memory_obj::Free(), gim_error, GIM_ERROR_WARNING, gim_memory, prsr_kvalue_section::next_section, gim_error_obj::set(), and prsr::title.
Exist()
_gim_flag gim_prsr_obj::Exist (const char * filename)
This function is used in order to read an existing configuration file.
Parameters
filename The name of the file you want to read
filename != NULL
Returns
__NOT_OK if the file exist but some error occurred
__NOT_EXIST if file not found
Definition at line 1132 of file gim_kvalue.cc.
{
     FILE *fp = fopen( filename , "rb" );
     if ( fp == NULL ) {
         gim_error->set( GIM_ERROR_WARNING , "gim_prsr_obj::Exist" , "The conf file NOT exist" , __GIM_NOT_EXIST );
         return __GIM_NOT_EXIST;
     }
     gim_error->set( "gim_prsr_obj::Exist" , "The conf file exist" );
     fclose( fp );
     return __GIM_EXIST;
 }
References __GIM_EXIST, __GIM_NOT_EXIST, gim_error, GIM_ERROR_WARNING, and gim_error_obj::set().
ExistKey()
_gim_flag gim_prsr_obj::ExistKey (const char * section_name, const char * key)
In order to check if a key exitst or not inside a specific section.
Parameters
section_name The section contain the key
section_name != NULL
key The name of the key to check
key != NULL
Returns
__EXIST if the section exist
__NOT_EXIST if don't
Definition at line 396 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     prsr_kvalue_field   * tmp_field;
     char * tmp_section_name;
     char * tmp_key_name;
     tmp_section_name = strdup( Lexical.str_up  ( section_name , strlen( section_name ) ) );
     tmp_key_name     = strdup( Lexical.str_down( key          , strlen( key          ) ) );
     if ( prsr_obj->first_section != NULL ) {
         for( ; tmp_section != NULL ; tmp_section = tmp_section->next_section ) {
             if( ! strcmp(  tmp_section_name , tmp_section->section_name ) ) {
                 if ( tmp_section->first_field ) {
                     for( tmp_field = tmp_section->first_field ; tmp_field ; tmp_field = tmp_field->next_field ) {
                         if ( ! strcmp( tmp_key_name , tmp_field->key  ) ) {
                             return __GIM_EXIST;
                         }
                     }
                 }
             }
         }
     }
     return __GIM_NOT_EXIST;
 }
References __GIM_EXIST, __GIM_NOT_EXIST, prsr_kvalue_section::first_field, prsr::first_section, prsr_kvalue_field::key, Lexical, prsr_kvalue_field::next_field, prsr_kvalue_section::next_section, prsr_kvalue_section::section_name, prsr_lexical_class::str_down(), and prsr_lexical_class::str_up().
Referenced by AddKey(), and gim_password_obj::gim_password_obj().
ExistSection()
_gim_flag gim_prsr_obj::ExistSection (const char * section_name)
In order to check if a section exitst or not.
Parameters
section_name The section to check
section_name != NULL
Returns
__EXIST if the section exist
__NOT_EXIST if don't
Definition at line 366 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     char * tmp_section_name;
     tmp_section_name = strdup( Lexical.str_up  ( section_name , strlen( section_name ) ) );
     if ( prsr_obj->first_section != NULL ) {
         for( ; tmp_section ; tmp_section = tmp_section->next_section ) {
             if( ! strcmp( tmp_section_name , tmp_section->section_name ) ) {
                 return  __GIM_EXIST;
             }
         }
     }
     return __GIM_NOT_EXIST;
 }
References __GIM_EXIST, __GIM_NOT_EXIST, prsr::first_section, Lexical, prsr_kvalue_section::next_section, prsr_kvalue_section::section_name, and prsr_lexical_class::str_up().
Referenced by AddSection(), and gim_password_obj::gim_password_obj().
GetHowManyKey()
_gim_int8 gim_prsr_obj::GetHowManyKey (const char * section_name)
To know how many section are present in a ini file.
Returns
The number of Keys present inside a section
__ERROR if some error occurred
Todo:
Near in the future (inside 2.5 milestone)
Definition at line 703 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     prsr_kvalue_field   * tmp_field;
     char * tmp_section_name;
     _gim_Uint8  cont = 0;
     tmp_section_name = strdup( Lexical.str_up  ( section_name , strlen( section_name ) ) );
     if ( prsr_obj == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::GetHowManyKey" , "No parser object defined" , __GIM_ERROR );
         return __GIM_ERROR;
     }
     if ( prsr_obj->first_section != NULL ) {
         for( ; tmp_section != NULL ; tmp_section = tmp_section->next_section ) {
             if( ! strcmp(  tmp_section_name , tmp_section->section_name ) ) {
                 if ( tmp_section->first_field ) {
                     for( tmp_field = tmp_section->first_field ; tmp_field ; tmp_field = tmp_field->next_field ) {
                         cont++;
                     }
                 }
             }
         }
     }
     else {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::GetHowManyKey" , "No section defined" , __GIM_ERROR );
         return __GIM_ERROR;
     }
     return cont;
 }
References __GIM_ERROR, prsr_kvalue_section::first_field, prsr::first_section, gim_error, GIM_ERROR_CRITICAL, Lexical, prsr_kvalue_field::next_field, prsr_kvalue_section::next_section, prsr_kvalue_section::section_name, gim_error_obj::set(), and prsr_lexical_class::str_up().
GetHowManySection()
_gim_int16 gim_prsr_obj::GetHowManySection (void)
To know how many section are present in a ini file.
Returns
The number of section present
__ERROR if some error occurred
Definition at line 763 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     _gim_int16 c;
     if ( prsr_obj == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::GetHowManySection" , "No parser object defined" , __GIM_ERROR );
         return __GIM_ERROR;
     }
     if ( prsr_obj->first_section != NULL ) {
         for( c = 0 ; tmp_section ; tmp_section = tmp_section->next_section )
             c++;
         return c;
     }
     else {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::GetHowManySection" , "No section defined in this object" , __GIM_ERROR );
     }
     return __GIM_ERROR;
 }
References __GIM_ERROR, prsr::first_section, gim_error, GIM_ERROR_CRITICAL, prsr_kvalue_section::next_section, and gim_error_obj::set().
Referenced by GetSectionName().
GetKeyFLAG()
_gim_flag gim_prsr_obj::GetKeyFLAG (const char * section_name, const char * key)
In order to obtain the value of one key (flag)
Parameters
section_name The section that contains the key
section_name != NULL
key The name of the key
key != NULL
Returns
The flag
if will be __ERROR it's better check the error with the get() from cnc_error_class
Definition at line 656 of file gim_kvalue.cc.
{
     char * tmp = NULL;
     tmp = strdup( GetKeySTR( section_name , key ) );
     if ( tmp != NULL ) {
         if ( Lexical.str_equal( tmp , "YES" ) == __GIM_YES ) return __GIM_YES;
         else if ( Lexical.str_equal( tmp , "NO"  ) == __GIM_YES ) return __GIM_NO;
         else if ( Lexical.str_equal( tmp , "AUTO"  ) == __GIM_YES ) return __GIM_AUTO;
         else if ( Lexical.str_equal( tmp , "TRUE"   ) == __GIM_YES ) return __GIM_TRUE;
         else if ( Lexical.str_equal( tmp , "FALSE"   ) == __GIM_YES ) return __GIM_FALSE;
         else if ( Lexical.str_equal( tmp , "A"   ) == __GIM_YES ) return __LEX_A;
         else if ( Lexical.str_equal( tmp , "B"   ) == __GIM_YES ) return __LEX_B;
         else if ( Lexical.str_equal( tmp , "ON"   ) == __GIM_YES ) return __GIM_ON;
         else if ( Lexical.str_equal( tmp , "OFF"   ) == __GIM_YES ) return __GIM_OFF;
         else if ( Lexical.str_equal( tmp , "LOCKED"   ) == __GIM_YES ) return __GIM_MEM_LOCK;
         else if ( Lexical.str_equal( tmp , "UNLOCKED"   ) == __GIM_YES ) return __GIM_MEM_UNLOCK;
         else if ( Lexical.str_equal( tmp , "TEXT"   ) == __GIM_YES ) return __GIM_LOG_TEXT;
         else if ( Lexical.str_equal( tmp , "HTML"   ) == __GIM_YES ) return __GIM_LOG_HTML;
         else    gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::GetKeyFLAG" , "UNKNOWN flag value" , __GIM_ERROR );
     }
     else
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::GetKeyFLAG" , "GetKeySTR return NULL." , __GIM_ERROR );
     return __GIM_ERROR;
 }
References __GIM_AUTO, __GIM_ERROR, __GIM_FALSE, __GIM_MEM_LOCK, __GIM_MEM_UNLOCK, __GIM_NO, __GIM_OFF, __GIM_ON, __GIM_TRUE, __GIM_YES, __LEX_A, __LEX_B, GetKeySTR(), gim_error, GIM_ERROR_CRITICAL, Lexical, gim_error_obj::set(), and prsr_lexical_class::str_equal().
Referenced by gim_log_obj::start().
GetKeyFLT()
float gim_prsr_obj::GetKeyFLT (const char * section_name, const char * key)
In order to obtain the value of one key (float)
Parameters
section_name The section that contains the key
section_name != NULL
key The name of the key
key != NULL
Returns
The value
if will be __ERROR it's better check the error with the get() from cnc_error_class
Definition at line 692 of file gim_kvalue.cc.
{
     char * tmp = NULL;
     tmp = strdup( GetKeySTR( section_name , key ) );
     if ( tmp != NULL )
         return atof( tmp );
     else
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::GetKeyFLT" , "GetKeySRT return NULL." , __GIM_ERROR );
     return __GIM_ERROR;
 }
References __GIM_ERROR, GetKeySTR(), gim_error, GIM_ERROR_CRITICAL, and gim_error_obj::set().
GetKeyINT()
int gim_prsr_obj::GetKeyINT (const char * section_name, const char * key)
In order to obtain the value of one key (int)
Parameters
section_name The section that contains the key
section_name != NULL
key The name of the key
key != NULL
Returns
The value
if will be __ERROR it's better check the error with the get() from cnc_error_class
Definition at line 682 of file gim_kvalue.cc.
{
     char * tmp = NULL;
     tmp = strdup( GetKeySTR( section_name , key ) );
     if ( tmp != NULL )
         return atoi( tmp );
     else
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::GetKeyINT" , "GetKeySTR return NULL." , __GIM_ERROR );
     return __GIM_ERROR;
 }
References __GIM_ERROR, GetKeySTR(), gim_error, GIM_ERROR_CRITICAL, and gim_error_obj::set().
Referenced by gim_cryptography_obj::gim_cryptography_obj(), and gim_password_obj::gim_password_obj().
GetKeyName()
char * gim_prsr_obj::GetKeyName (const char * section_name, _gim_int16 kindex)
To get the name of a specific section number.
Parameters
section_name The name of section wich you want to get haow many Key are inside
section_name != NULL
kindex The index of the key you want to know the name
kindex > 0
Returns
The name of the Key
__ERROR if an error occurred
Todo:
Near in the future (inside 2.5 milestone)
Definition at line 732 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     prsr_kvalue_field   * tmp_field;
     char * tmp_section_name;
     _gim_int16  cont = 0;
     tmp_section_name = strdup( Lexical.str_up  ( section_name , strlen( section_name ) ) );
     if ( prsr_obj == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::GetKeyName" , "No parser object defined" , __GIM_ERROR );
         return NULL;
     }
     if ( prsr_obj->first_section != NULL ) {
         for( ; tmp_section != NULL ; tmp_section = tmp_section->next_section ) {
             if( ! strcmp(  tmp_section_name , tmp_section->section_name ) ) {
                 if ( tmp_section->first_field ) {
                     for( tmp_field = tmp_section->first_field ; tmp_field ; tmp_field = tmp_field->next_field , cont++ ) {
                         if ( kindex == cont )
                             return tmp_field->key;
                     }
                 }
             }
         }
     }
     else {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::GetKeyName" , "No section defined" , __GIM_ERROR );
         return NULL;
     }
     gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::GetKeyName" , "Index not found" , __GIM_ERROR );
     return NULL;
 }
References __GIM_ERROR, prsr_kvalue_section::first_field, prsr::first_section, gim_error, GIM_ERROR_CRITICAL, prsr_kvalue_field::key, Lexical, prsr_kvalue_field::next_field, prsr_kvalue_section::next_section, prsr_kvalue_section::section_name, gim_error_obj::set(), and prsr_lexical_class::str_up().
GetKeySTR()
char * gim_prsr_obj::GetKeySTR (const char * section_name, const char * key)
In order to obtain the value of one key (char*)
Parameters
section_name The section that contains the key
section_name != NULL
key The name of the key
key != NULL
Returns
The value
NULL if some error occurred
Definition at line 628 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     prsr_kvalue_field   * tmp_field , * before_field = NULL;
     char * tmp_section_name;
     char * tmp_key_name;
     tmp_section_name = strdup( Lexical.str_up  ( section_name , strlen( section_name ) ) );
     tmp_key_name     = strdup( Lexical.str_down( key          , strlen( key          ) ) );
     if ( prsr_obj == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::GetKeySTR" , "No parser object defined" , __GIM_ERROR );
         return NULL;
     }
     if ( prsr_obj->first_section != NULL ) {
         for( ; tmp_section != NULL ; tmp_section = tmp_section->next_section ) {
             if( ! strcmp(  tmp_section_name , tmp_section->section_name ) ) {
                 if ( tmp_section->first_field ) {
                     for( tmp_field = tmp_section->first_field ; tmp_field ; before_field=tmp_field , tmp_field = tmp_field->next_field ) {
                         if ( ! strcmp( tmp_key_name , tmp_field->key  ) ) {
                             return tmp_field->str_value ;
                         }
                     }
                 }
             }
         }
     }
     return NULL;
 }
References __GIM_ERROR, prsr_kvalue_section::first_field, prsr::first_section, gim_error, GIM_ERROR_CRITICAL, prsr_kvalue_field::key, Lexical, prsr_kvalue_field::next_field, prsr_kvalue_section::next_section, prsr_kvalue_section::section_name, gim_error_obj::set(), prsr_lexical_class::str_down(), prsr_lexical_class::str_up(), and prsr_kvalue_field::str_value.
Referenced by GetKeyFLAG(), GetKeyFLT(), GetKeyINT(), and gim_log_obj::start().
GetLex()
_gim_flag gim_prsr_obj::GetLex (void)
Use this function if you want to get the lexical used in a configuration file.
Returns
__LEX_UNKNOW if the lexical is not yet defined
__LEX_A if the lexical if (strlen(filenameis defined as __LEX_A
__LEX_B if the lexical is defined as __LEX_B
Definition at line 819 of file gim_kvalue.cc.
{
     return this->Lex;
 }
GetSectionName()
char * gim_prsr_obj::GetSectionName (_gim_int16 secindex)
To get the name of a specific section number.
Parameters
secindex The section number you want to knwo the name
secindex >= 0
Returns
The name of section
__ERROR if an error occurred
Definition at line 782 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     _gim_int16 c = 0;
     if ( prsr_obj == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::GetSectionName" , "No parser object defined" , __GIM_ERROR );
         return NULL;
     }
     if ( secindex >= GetHowManySection () ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::GetSectionName" , "You have requested an index greater than the maximum" , __GIM_ERROR );
         return NULL;
     }
     if ( prsr_obj->first_section != NULL ) {
         for( c = 0 ; tmp_section ; tmp_section = tmp_section->next_section ) {
             if ( c == secindex ) return tmp_section->section_name;
             c++;
         }
     }
     else {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::GetSectionName" , "No section defined in this object" , __GIM_ERROR );
         return NULL;
     }
     gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::GetSectionName" , "Section not found" , __GIM_ERROR );
     return NULL;
 }
References __GIM_ERROR, prsr::first_section, GetHowManySection(), gim_error, GIM_ERROR_CRITICAL, prsr_kvalue_section::next_section, prsr_kvalue_section::section_name, and gim_error_obj::set().
List()
_gim_flag gim_prsr_obj::List (void)
This function is used in order to print on stdout a configuration file.
Returns
__OK if everything it's ok
__NOT_OK if some error occurred
Definition at line 447 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     prsr_kvalue_field   * tmp_field;
     if ( prsr_obj == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::List" , "No parser object defined" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     printf( PRSR_START_FILE );
     printf( "%s\n\n" , prsr_obj->title );
     if ( prsr_obj->first_section != NULL ) {
         if ( Lex == __LEX_A ) {
             for( ; tmp_section != NULL ; tmp_section = tmp_section->next_section ) {
                 printf( "%s%s\n" , PRSR_START_SECTION , tmp_section->section_name );
                 if ( tmp_section->first_field ) {
                     for( tmp_field = tmp_section->first_field ; tmp_field != NULL ; tmp_field = tmp_field->next_field ) {
                         printf( PRSR_A_KEY_STR , tmp_field->key , tmp_field->str_value );
                         puts("");
                     }
                 }
                 printf( "%s\n\n" , PRSR_END_SECTION);
             }
         }
         else {
             for( ; tmp_section != NULL ; tmp_section = tmp_section->next_section ) {
                 if ( tmp_section->first_field ) {
                     for( tmp_field = tmp_section->first_field ; tmp_field != NULL ; tmp_field = tmp_field->next_field ) {
                         printf( PRSR_B_KEY_STR , Lexical.str_down( tmp_section->section_name, strlen( tmp_section->section_name ) ) , tmp_field->key , tmp_field->str_value );
                         puts("");
                     }
                 }
             }
             puts("");
         }
     }
     puts( PRSR_END_FILE );
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_NOT_OK, __GIM_OK, __LEX_A, prsr_kvalue_section::first_field, prsr::first_section, gim_error, GIM_ERROR_CRITICAL, prsr_kvalue_field::key, Lexical, prsr_kvalue_field::next_field, prsr_kvalue_section::next_section, PRSR_A_KEY_STR, PRSR_B_KEY_STR, PRSR_END_FILE, PRSR_END_SECTION, PRSR_START_FILE, PRSR_START_SECTION, prsr_kvalue_section::section_name, gim_error_obj::set(), prsr_lexical_class::str_down(), prsr_kvalue_field::str_value, and prsr::title.
ParserIsUp()
_gim_flag gim_prsr_obj::ParserIsUp (void)
Definition at line 1049 of file gim_kvalue.cc.
{
     if ( prsr_obj == NULL )
         return __GIM_NO;
     return __GIM_YES;
 }
References __GIM_NO, and __GIM_YES.
Referenced by ThereIsASection().
Read()
_gim_flag gim_prsr_obj::Read (const char * filename)
This function is used in order to read an existing configuration file.
Parameters
filename The name of the file you want to read
filename != NULL
Returns
__OK if everything it's ok
__NOT_OK if the file exist but some error occurred
__NOT_EXIST if file not found
Definition at line 559 of file gim_kvalue.cc.
{
     _gim_int8   scan_result;
     gim_error->set( "gim_prsr_obj::Read" , "I'm try to read" );
     scan_result = Lexical.scan_syntax( filename , this );
     switch ( scan_result ) {
         case __GIM_OK : {
             Up( filename , NULL );
             SetLex( Lexical.lex_type );
             if ( ! prsr_obj ) return __GIM_NOT_OK;
             if ( Open("rb") == __GIM_NOT_EXIST ) {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::Read" , "I cannot read this file" , __GIM_ERROR );
                 return __GIM_NOT_EXIST;
             }
             if ( Lexical.scan( this ) == __GIM_OK ) {
                 Close( __NO_FLUSH );
                 gim_error->set( "gim_prsr_obj::Read" , "Succesfully read" );
                 return __GIM_OK;
             }
             else {
                 gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::Read" , "some problem with the file" , __GIM_ERROR );
                 return __GIM_NOT_OK;
             }
         }
         case __LEX_UNKNOWN : {
             gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::Read" , "I cannot read this file" , __GIM_ERROR );
             return __GIM_NOT_OK;
         }
         case __GIM_NOT_EXIST : {
             gim_error->set( GIM_ERROR_WARNING , "gim_prsr_obj::Read" , "File not exist" , __GIM_ERROR );
             return __GIM_NOT_EXIST;
         }
         case __SYNTAX_ERROR : {
             gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::Read" , "I cannot read this file" , __GIM_ERROR );
             return __GIM_NOT_OK;
         }
     }
     gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::Read" , "I cannot read this file" , __GIM_ERROR );
     return __GIM_NOT_OK;
 }
References __GIM_ERROR, __GIM_NOT_EXIST, __GIM_NOT_OK, __GIM_OK, __LEX_UNKNOWN, __NO_FLUSH, __SYNTAX_ERROR, gim_error, GIM_ERROR_CRITICAL, GIM_ERROR_WARNING, Lexical, prsr_lexical_class::scan(), prsr_lexical_class::scan_syntax(), gim_error_obj::set(), SetLex(), and Up().
RenameKey()
_gim_flag gim_prsr_obj::RenameKey (const char * section, const char * old_key, const char * new_key)
To rename an existing section of a ini file.
Parameters
section The section that contains the key
section != NULL
old_key The key you want to rename
old_key != NULL
new_key The new name for the key
new_key != NULL
Returns
__OK if everything it's ok
__NOT_OK if some error occurred
Definition at line 877 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section;
     prsr_kvalue_field   * tmp_field;
     char * tmp_section_name;
     char * tmp_old_key_name;
     char * tmp_new_key_name;
     if ( prsr_obj == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::RenameKey" , "No parser object defined" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     tmp_section = prsr_obj->first_section;
     if ( ! strlen( section ) ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::RenameKey" , "Section name is NULL" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( ! strlen( new_key ) ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::RenameKey" , "New key is NULL" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( ! strlen( old_key ) ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::RenameKey" , "Old key is NULL" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     tmp_section_name    = strdup( Lexical.str_up  ( section , strlen( section ) ) );
     tmp_old_key_name    = strdup( Lexical.str_down( old_key , strlen( old_key ) ) );
     tmp_new_key_name    = strdup( Lexical.str_down( new_key , strlen( new_key ) ) );
     if ( tmp_section != NULL ) {
         for( ; tmp_section != NULL ; tmp_section = tmp_section->next_section ) {
             if( ! strcmp(  tmp_section_name , tmp_section->section_name ) ) {
                 if ( tmp_section->first_field ) {
                     for( tmp_field = tmp_section->first_field ; tmp_field ; tmp_field = tmp_field->next_field ) {
                         if ( ! strcmp( tmp_old_key_name , tmp_field->key  ) ) {
                             strcpy( tmp_field->key , tmp_new_key_name );
                             return __GIM_OK;
                         }
                     }
                 }
             }
         }
     }
     return __GIM_NOT_OK;
 }
References __GIM_ERROR, __GIM_NOT_OK, __GIM_OK, prsr_kvalue_section::first_field, prsr::first_section, gim_error, GIM_ERROR_CRITICAL, prsr_kvalue_field::key, Lexical, prsr_kvalue_field::next_field, prsr_kvalue_section::next_section, prsr_kvalue_section::section_name, gim_error_obj::set(), prsr_lexical_class::str_down(), and prsr_lexical_class::str_up().
RenameSection()
_gim_flag gim_prsr_obj::RenameSection (const char * old_section, const char * new_section)
To rename an existing section of a ini file.
Parameters
old_section The section you want to rename
old_section != NULL
new_section The new name for the section
new_section != NULL
Returns
__OK if everything it's ok
__NOT_OK if some error occurred
Definition at line 837 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     char    * tmp_section_name;
     char    * tmp_new_section;
     _gim_flag   found = __GIM_NO;
     if ( prsr_obj == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::RenameSection" , "No parser object defined" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( ! strlen( new_section ) ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::RenameSection" , "New section is NULL" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
         if ( ! strlen( old_section ) ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::RenameSection" , "Old section is NULL" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     tmp_section_name = strdup( Lexical.str_up  ( old_section , strlen( old_section ) ) );
     if ( prsr_obj->first_section != NULL ) {
         for( ; tmp_section ; tmp_section = tmp_section->next_section ) {
             if( ! strcmp(  tmp_section_name , tmp_section->section_name ) ) {
                 found = __GIM_YES;
                 __GIM_CLEAR( tmp_section->section_name , 64 , char );
                 strcpy( tmp_section->section_name , new_section );
                 tmp_new_section = strdup( Lexical.str_up  ( new_section , strlen( new_section ) ) );
                 return __GIM_OK;
             }
         }
         if ( found == __GIM_NO ) {
             gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::RenameSection" , "Old Section not found" , __GIM_NOT_EXIST );
             return __GIM_NOT_EXIST;
         }
     }
     else {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::RenameSection" , "No one section is defined in this prsp object" , __GIM_NOT_EXIST );
         return __GIM_NOT_EXIST;
     }
     return __GIM_OK;
 }
References __GIM_CLEAR, __GIM_ERROR, __GIM_NO, __GIM_NOT_EXIST, __GIM_NOT_OK, __GIM_OK, __GIM_YES, prsr::first_section, gim_error, GIM_ERROR_CRITICAL, Lexical, prsr_kvalue_section::next_section, prsr_kvalue_section::section_name, gim_error_obj::set(), and prsr_lexical_class::str_up().
RenameTitle()
_gim_flag gim_prsr_obj::RenameTitle (const char * new_title)
To rename the title of a ini file.
Parameters
new_title The new title
new_title != NULL
Returns
__OK if everything it's ok
__NOT_OK if some error occurred
Definition at line 823 of file gim_kvalue.cc.
{
     if ( prsr_obj == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::RenameTitle" , "No parser object defined" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( ! strlen( new_title ) ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::RenameTitle" , "New title is NULL" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     __GIM_CLEAR( prsr_obj->title , 64 , char );
     strcpy( prsr_obj->title , new_title );
     return __GIM_OK;
 }
References __GIM_CLEAR, __GIM_ERROR, __GIM_NOT_OK, __GIM_OK, gim_error, GIM_ERROR_CRITICAL, gim_error_obj::set(), and prsr::title.
SetLex()
void gim_prsr_obj::SetLex (_gim_flag Lex)
This function is used in order to write a configuration file.
Parameters
Lex You can choose two kind of lexical for your ini file.
Default is __LEX_UNKNOW
((Lex == __LEX_A) || (Lex == __LEX_B))
Definition at line 808 of file gim_kvalue.cc.
{
     if ( Lex == __LEX_A ) {
         gim_error->set( "gim_prsr_obj::SetLex" , "Lex setted to A" );
         this->Lex = __LEX_A;
     }
     if ( Lex == __LEX_B ) {
         gim_error->set( "gim_prsr_obj::SetLex" , "Lex setted to B" );
         this->Lex = __LEX_B;
     }
 }
References __LEX_A, __LEX_B, gim_error, and gim_error_obj::set().
Referenced by Read().
ThereIsASection()
_gim_flag gim_prsr_obj::ThereIsASection (void)
Definition at line 1056 of file gim_kvalue.cc.
{
     if ( ParserIsUp() == __GIM_YES ) {
         gim_error->set( "gim_prsr_obj::ThereIsASection" , "Yes, parser is UP." );
         if ( prsr_obj->first_section != NULL ) {
             gim_error->set( "gim_prsr_obj::ThereIsASection" , "And yes, there is at least a section." );
             return __GIM_YES;
         }
         else
             gim_error->set( "gim_prsr_obj::ThereIsASection" , "But no, there is no one section." );
     }
     else
         gim_error->set( "gim_prsr_obj::ThereIsASection" , "No, no parser in memory." );
     return __GIM_NO;
 }
References __GIM_NO, __GIM_YES, prsr::first_section, gim_error, ParserIsUp(), and gim_error_obj::set().
Up()
void gim_prsr_obj::Up (const char * filename, const char * title)
This function is used in order to generate a configuration file from code.
Parameters
filename The name of the file you want to generate
filename != NULL
title The title of the ini
title > 0
Definition at line 41 of file gim_kvalue.cc.
{
     gim_error->set( "gim_prsr_obj::Up" , "Starting up..." );
     prsr_obj = ( prsr * )gim_memory->Alloc( sizeof( prsr ) , __GIM_MEM_PRSP_UP , __GIM_HIDE );
     if ( filename != NULL )
         strcpy( prsr_obj->filename , filename );
     if ( title != NULL )
         strcpy( prsr_obj->title , title );
     strcpy( prsr_obj->comment , "" );
     prsr_obj->first_section = NULL;
     prsr_obj->fp = NULL;
     if ( title ) {
         char message[256];
         sprintf( message , "Conf file [%s] is UP" , prsr_obj->title );
         gim_error->set( "gim_prsr_obj::Up" , message );
     }
     else
         gim_error->set( "gim_prsr_obj::Up" , "Conf file is UP" );
 }
References __GIM_HIDE, __GIM_MEM_PRSP_UP, gim_memory_obj::Alloc(), prsr::comment, prsr::filename, prsr::first_section, prsr::fp, gim_error, gim_memory, gim_error_obj::set(), and prsr::title.
Referenced by Read().
Write()
_gim_flag gim_prsr_obj::Write (void)
This function is used in order to write a configuration file to disk.
Returns
__OK if everything it's ok
__NOT_OK if some error occurred
Definition at line 485 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     prsr_kvalue_field   * tmp_field;
     if ( prsr_obj == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::Write" , "No parser object defined" , __GIM_ERROR );
         return __GIM_NOT_OK;
     }
     if ( strlen( prsr_obj->filename ) == 0 ) return __GIM_NOT_OK;
     if ( ! prsr_obj->fp ) {
         if ( Open( "wb" ) == __GIM_NOT_EXIST ) return __GIM_NOT_OK;
     }
     fprintf( prsr_obj->fp , "%s" , PRSR_START_FILE );
     fprintf( prsr_obj->fp , "%s\n" , prsr_obj->title );
     if ( strlen( prsr_obj->comment ) != 0 )
         fprintf( prsr_obj->fp , "# %s\n" , prsr_obj->comment );
     if ( prsr_obj->first_section != NULL ) {
         if ( Lex == __LEX_A ) {
             fprintf( prsr_obj->fp , "\n" );
             for( ; tmp_section != NULL ; tmp_section = tmp_section->next_section ) {
                 if ( ( tmp_section->comment != NULL ) && ( tmp_section->comment_position == PRSR_BEFORE ) )
                     fprintf( prsr_obj->fp , "\n    # %s\n" , tmp_section->comment );
                 fprintf( prsr_obj->fp , "%s%s" , PRSR_START_SECTION , tmp_section->section_name );
                 if ( ( tmp_section->comment != NULL ) && ( tmp_section->comment_position == PRSR_INLINE ) )
                     fprintf( prsr_obj->fp , "        # %s" , tmp_section->comment );
                 fprintf( prsr_obj->fp , "\n" );
                 if ( ( tmp_section->comment != NULL ) && ( tmp_section->comment_position == PRSR_AFTER ) )
                     fprintf( prsr_obj->fp , "    # %s\n\n" , tmp_section->comment );
                 if ( tmp_section->first_field ) {
                     for( tmp_field = tmp_section->first_field ; tmp_field != NULL ; tmp_field = tmp_field->next_field ) {
                         if ( ( tmp_field->comment != NULL ) && ( tmp_field->comment_position == PRSR_BEFORE ) )
                             fprintf( prsr_obj->fp , "\n    # %s\n" , tmp_field->comment );
                         fprintf( prsr_obj->fp , PRSR_A_KEY_STR , tmp_field->key , tmp_field->str_value );
                         if ( ( tmp_field->comment != NULL ) && ( tmp_field->comment_position == PRSR_INLINE ) )
                             fprintf( prsr_obj->fp , "  # %s" , tmp_field->comment );
                         fprintf( prsr_obj->fp , "\n" );
                         if ( ( tmp_field->comment != NULL ) && ( tmp_field->comment_position == PRSR_AFTER ) )
                             fprintf( prsr_obj->fp , "    # %s\n\n" , tmp_field->comment );
                     }
                 }
                 fprintf( prsr_obj->fp , "%s\n\n" , PRSR_END_SECTION);
             }
         }
         else {
             for( ; tmp_section != NULL ; tmp_section = tmp_section->next_section ) {
                 if ( tmp_section->first_field ) {
                     if ( ( tmp_section->comment != NULL ) && ( tmp_section->comment_position == PRSR_BEFORE ) )
                         fprintf( prsr_obj->fp , "\n    # %s\n" , tmp_section->comment );
                     fprintf( prsr_obj->fp , "\n  %s" , tmp_section->section_name );
                     if ( ( tmp_section->comment != NULL ) && ( tmp_section->comment_position == PRSR_INLINE ) )
                         fprintf( prsr_obj->fp , "        # %s" , tmp_section->comment );
                     fprintf( prsr_obj->fp , "\n" );
                     if ( ( tmp_section->comment != NULL ) && ( tmp_section->comment_position == PRSR_AFTER ) )
                         fprintf( prsr_obj->fp , "    # %s\n\n" , tmp_section->comment );
                     for( tmp_field = tmp_section->first_field ; tmp_field != NULL ; tmp_field = tmp_field->next_field ) {
                         if ( ( tmp_field->comment != NULL ) && ( tmp_field->comment_position == PRSR_BEFORE ) )
                             fprintf( prsr_obj->fp , "    # %s\n" , tmp_field->comment );
                         fprintf( prsr_obj->fp , PRSR_B_KEY_STR , Lexical.str_down( tmp_section->section_name , strlen( tmp_section->section_name ) ) , tmp_field->key , tmp_field->str_value );
                         if ( ( tmp_field->comment != NULL ) && ( tmp_field->comment_position == PRSR_INLINE ) )
                             fprintf( prsr_obj->fp , "  # %s" , tmp_field->comment );
                         fprintf( prsr_obj->fp , "\n" );
                         if ( ( tmp_field->comment != NULL ) && ( tmp_field->comment_position == PRSR_AFTER ) )
                             fprintf( prsr_obj->fp , "    # %s\n\n" , tmp_field->comment );
                     }
                 }
             }
         }
     }
     fprintf( prsr_obj->fp , "%s\n" , PRSR_END_FILE );
     Close( __NO_FLUSH );
     return __GIM_OK;
 }
References __GIM_ERROR, __GIM_NOT_EXIST, __GIM_NOT_OK, __GIM_OK, __LEX_A, __NO_FLUSH, prsr::comment, prsr_kvalue_section::comment, prsr_kvalue_field::comment, prsr_kvalue_section::comment_position, prsr_kvalue_field::comment_position, prsr::filename, prsr_kvalue_section::first_field, prsr::first_section, prsr::fp, gim_error, GIM_ERROR_CRITICAL, prsr_kvalue_field::key, Lexical, prsr_kvalue_field::next_field, prsr_kvalue_section::next_section, PRSR_A_KEY_STR, PRSR_AFTER, PRSR_B_KEY_STR, PRSR_BEFORE, PRSR_END_FILE, PRSR_END_SECTION, PRSR_INLINE, PRSR_START_FILE, PRSR_START_SECTION, prsr_kvalue_section::section_name, gim_error_obj::set(), prsr_lexical_class::str_down(), prsr_kvalue_field::str_value, and prsr::title.
Referenced by gim_password_obj::gim_password_obj().
WriteOnBuffer()
_gim_buffer gim_prsr_obj::WriteOnBuffer (void)
This function is used in order to get a buffer filled with a configuration file.
Returns
__OK if everything it's ok
__NOT_OK if some error occurred
Definition at line 921 of file gim_kvalue.cc.
{
     prsr_kvalue_section * tmp_section = prsr_obj->first_section;
     prsr_kvalue_field   * tmp_field;
     _gim_buffer         dest;
     if ( prsr_obj == NULL ) {
         gim_error->set( GIM_ERROR_CRITICAL , "gim_prsr_obj::List" , "No parser object defined" , __GIM_ERROR );
         return NULL;
     }
     dest = (_gim_buffer)gim_memory->Alloc( 10240*sizeof( char ) , __GIM_MEM_OTHER , __GIM_HIDE );
     strcat( dest , PRSR_START_FILE );
     sprintf( dest , "%s%s\n\n" , dest , prsr_obj->title );
     if ( prsr_obj->first_section != NULL ) {
         if ( Lex == __LEX_A ) {
             for( ; tmp_section != NULL ; tmp_section = tmp_section->next_section ) {
                 sprintf( dest , "%s%s%s\n", dest , PRSR_START_SECTION , tmp_section->section_name );
                 if ( tmp_section->first_field ) {
                     for( tmp_field = tmp_section->first_field ; tmp_field != NULL ; tmp_field = tmp_field->next_field ) {
                         sprintf( dest , "%s    %s = %s" , dest , tmp_field->key , tmp_field->str_value );
 //                      if ( tmp_field->key_type == PRSR_GIM_INT ) sprintf( dest , "%s    %s = %d" , dest , tmp_field->key , tmp_field->int_value );
                         strcat( dest , "\n");
                     }
                 }
                 sprintf( dest , "%s%s\n\n" , dest , PRSR_END_SECTION);
             }
         }
         else {
             for( ; tmp_section != NULL ; tmp_section = tmp_section->next_section ) {
                 if ( tmp_section->first_field ) {
                     for( tmp_field = tmp_section->first_field ; tmp_field != NULL ; tmp_field = tmp_field->next_field ) {
                         sprintf( dest , "%s    %s::%s = %s" , dest , Lexical.str_down( tmp_section->section_name, strlen( tmp_section->section_name ) ) , tmp_field->key , tmp_field->str_value );
 //                      if ( tmp_field->key_type == PRSR_GIM_INT ) sprintf( dest , "%s    %s::%s = %d" , dest , Lexical.str_down( tmp_section->section_name, strlen( tmp_section->section_name ) ) , tmp_field->key , tmp_field->int_value );
                         strcat( dest , "\n");
                     }
                 }
             }
             strcat( dest , "\n");
         }
     }
     strcat( dest , PRSR_END_FILE );
     strcat( dest , "\n");
     return dest;
 }
References __GIM_ERROR, __GIM_HIDE, __GIM_MEM_OTHER, __LEX_A, gim_memory_obj::Alloc(), prsr_kvalue_section::first_field, prsr::first_section, gim_error, GIM_ERROR_CRITICAL, gim_memory, prsr_kvalue_field::key, Lexical, prsr_kvalue_field::next_field, prsr_kvalue_section::next_section, PRSR_END_FILE, PRSR_END_SECTION, PRSR_START_FILE, PRSR_START_SECTION, prsr_kvalue_section::section_name, gim_error_obj::set(), prsr_lexical_class::str_down(), prsr_kvalue_field::str_value, and prsr::title.