My Project: Main Page
gim_version.cc File Reference
#include "../include/gim_version.h"
Functions
int gim_check_version (int maj, int min)
int gim_check_version (int maj, int min, int sub)
Use this function to check if Gim is at the required version.
char * gim_version (void)
Use this function to print on stdout the Gim version with extended infos.
char * gim_version_micro (void)
Use this function to print on stdout the Gim version with no infos.
char * gim_version_small (void)
Use this function to print on stdout the Gim version with basic infos.
Function Documentation
gim_check_version() [1/2]
int gim_check_version (int maj, int min)
Definition at line 96 of file gim_version.cc.
{
     char    gim_ver[16];
     char    req_ver[16];
     sprintf( gim_ver , "%d%d" , GIM_MAJOR , GIM_MINOR );
     sprintf( req_ver , "%d%d" , maj , min );
     if ( atoi(gim_ver) >= atoi(req_ver) )
         return __GIM_OK;
     else
         return __GIM_NOT_OK;
 }
References __GIM_NOT_OK, __GIM_OK, GIM_MAJOR, and GIM_MINOR.
gim_check_version() [2/2]
int gim_check_version (int maj, int min, int sub)
Use this function to check if Gim is at the required version.
Parameters
maj The major version number of th required gim
min The minor version number of th required gim
sub The subminor version number of th required gim
Returns
__GIM_OK if Gim is at the required version, __GIM_NOT_OK if not.
Parameters
maj The major version number of th required gim
min The minor version number of th required gim
Returns
__GIM_OK if Gim is at the required version, __GIM_NOT_OK if not.
Definition at line 84 of file gim_version.cc.
{
     char    gim_ver[16];
     char    req_ver[16];
     sprintf( gim_ver , "%d%d%d" , GIM_MAJOR , GIM_MINOR , GIM_SUBMINOR );
     sprintf( req_ver , "%d%d%d" , maj , min , sub );
     if ( atoi(gim_ver) >= atoi(req_ver) )
         return __GIM_OK;
     else
         return __GIM_NOT_OK;
 }
References __GIM_NOT_OK, __GIM_OK, GIM_MAJOR, GIM_MINOR, and GIM_SUBMINOR.
gim_version()
char* gim_version (void)
Use this function to print on stdout the Gim version with extended infos.
Definition at line 42 of file gim_version.cc.
{
     static char gim_ver[256];
     if ( Lexical.str_equal( GIM_VERSION_STATE , "rel" ) == __GIM_YES )
         sprintf( gim_ver , "Gim %s - Ver %d.%d-%d compiled on %s" , (const char *)GIM_MILESTONE , GIM_MAJOR , GIM_MINOR , GIM_SUBMINOR , GIM_BUILD_LAST );
     if ( Lexical.str_equal( GIM_VERSION_STATE , "dev" ) == __GIM_YES )
         sprintf( gim_ver , "Gim %s - Ver %d.%d-%d-d compiled on %s" , (const char *)GIM_MILESTONE , GIM_MAJOR , GIM_MINOR , GIM_SUBMINOR , GIM_BUILD_LAST );
     return gim_ver;
 }
References __GIM_YES, GIM_BUILD_LAST, GIM_MAJOR, GIM_MILESTONE, GIM_MINOR, GIM_SUBMINOR, GIM_VERSION_STATE, Lexical, and prsr_lexical_class::str_equal().
Referenced by gim_log_obj::start().
gim_version_micro()
char* gim_version_micro (void)
Use this function to print on stdout the Gim version with no infos.
Definition at line 74 of file gim_version.cc.
{
     static char gim_ver[256];
     if ( Lexical.str_equal( GIM_VERSION_STATE , "rel" ) == __GIM_YES )
         sprintf( gim_ver , "%d.%d-%d" , GIM_MAJOR , GIM_MINOR , GIM_SUBMINOR );
     if ( Lexical.str_equal( GIM_VERSION_STATE , "dev" ) == __GIM_YES )
         sprintf( gim_ver , "%d.%d-%d-d" , GIM_MAJOR , GIM_MINOR , GIM_SUBMINOR );
     return gim_ver;
 }
References __GIM_YES, GIM_MAJOR, GIM_MINOR, GIM_SUBMINOR, GIM_VERSION_STATE, Lexical, and prsr_lexical_class::str_equal().
gim_version_small()
char* gim_version_small (void)
Use this function to print on stdout the Gim version with basic infos.
Definition at line 64 of file gim_version.cc.
{
     static char gim_ver[256];
     if ( Lexical.str_equal( GIM_VERSION_STATE , "rel" ) == __GIM_YES )
         sprintf( gim_ver , "Gim - Ver %d.%d-%d" , GIM_MAJOR , GIM_MINOR , GIM_SUBMINOR );
     if ( Lexical.str_equal( GIM_VERSION_STATE , "dev" ) == __GIM_YES )
         sprintf( gim_ver , "Gim - Ver %d.%d-%d-d" , GIM_MAJOR , GIM_MINOR , GIM_SUBMINOR );
     return gim_ver;
 }
References __GIM_YES, GIM_MAJOR, GIM_MINOR, GIM_SUBMINOR, GIM_VERSION_STATE, Lexical, and prsr_lexical_class::str_equal().