My Project: Main Page
gim_home_obj Class Reference
gim_home_obj manage automatically the Gim's environment.
There are some methods which allow you to have important information
as the environment for your program or the path for the personal key
of your friends
#include <gim_environment.h>
Public Member Functions
void add_default_comment (void)
char * get_generic_programs_env (void)
To get a generic environment for saving your file and share with other programs use Gim.
char * get_other_keys_path (void)
To get the path where Gim store the personal key of your friends.
char * get_programs_env (void)
To get the environment for your program.
gim_home_obj ()
Detailed Description
gim_home_obj manage automatically the Gim's environment.
There are some methods which allow you to have important information
as the environment for your program or the path for the personal key
of your friends
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
1.0-0
Date
2003-2007
Definition at line 109 of file gim_environment.h.
Constructor & Destructor Documentation
gim_home_obj()
gim_home_obj::gim_home_obj () inline
Definition at line 142 of file gim_environment.h.
{
                 initialized = __GIM_NO;
             };
References __GIM_NO.
Member Function Documentation
add_default_comment()
void gim_home_obj::add_default_comment (void)
Definition at line 446 of file gim_environment.cc.
{
     gim_conf->AddKeyComment(    "debug"         , "debug_format"    , PRSR_AFTER , DEBUG_FORMAT_COMMENT );
     gim_conf->AddComment(       "Put your comments beside a key and in any other location.\n# E.g.\n#  __LEX_A\n#    login = asyntote   # this is a comment\n#  __LEX_B\n#    version::name = Gim   # this is a comment" );
 }
References gim_prsr_obj::AddComment(), gim_prsr_obj::AddKeyComment(), DEBUG_FORMAT_COMMENT, gim_conf, and PRSR_AFTER.
Referenced by gim_password_obj::gim_password_obj().
get_generic_programs_env()
char * gim_home_obj::get_generic_programs_env (void)
To get a generic environment for saving your file and share with other programs use Gim.
Returns
The path of the environment for program
Definition at line 426 of file gim_environment.cc.
{
     return env_data->Programs;
 }
References env_data, and gim_conf_data::Programs.
get_other_keys_path()
char * gim_home_obj::get_other_keys_path (void)
To get the path where Gim store the personal key of your friends.
Returns
The others personal keys path
Definition at line 435 of file gim_environment.cc.
{
     return env_data->PrivateKeyPath;
 }
References env_data, and gim_conf_data::PrivateKeyPath.
get_programs_env()
char * gim_home_obj::get_programs_env (void)
To get the environment for your program.
Returns
The path of the environment for program
Definition at line 430 of file gim_environment.cc.
{
     return env_data->home;
 }
References env_data, and gim_conf_data::home.