My Project: Main Page
gim_memory_page_obj Class Reference
#include <gim_memory.h>
Public Member Functions
void * Alloc (size_t size)
void Free (void *to_free)
gim_memory_page_obj (size_t page_size=(1 *1024 *1024 *sizeof(char)))
~gim_memory_page_obj ()
Detailed Description
Author
Danilo Zannoni - asynt.nosp@m.ote@.nosp@m.gkrip.nosp@m.t.or.nosp@m.g
Version
2.5-0
Date
2003-2008
Definition at line 374 of file gim_memory.h.
Constructor & Destructor Documentation
gim_memory_page_obj()
gim_memory_page_obj::gim_memory_page_obj (size_t page_size = (1 * 1024 * 1024 * sizeof(char)))
Definition at line 594 of file gim_memory.cc.
{
     gim_error->set( "gim_memory_page_obj::gim_memory_page_obj", "Allocating a new Memory page" );
     page            = (_gim_buffer)gim_memory->Alloc( page_size , __GIM_MEM_PAGE_ADD , __GIM_HIDE );
     internal_page   = (_gim_buffer)gim_memory->Alloc( page_size , __GIM_MEM_PAGE_ADD , __GIM_HIDE );
     if ( ( page == NULL ) || ( internal_page == NULL ) )
         gim_error->set( GIM_ERROR_FATAL , "gim_memory_page_obj::gim_memory_page_obj", "Failed during the allocation of a new Page" , __GIM_ERROR );
     else {
         lstart = NULL;
         lcurrent = NULL;
         gim_error->set( "gim_memory_page_obj::gim_memory_page_obj", "Allocation done!!!" );
     }
 }
References __GIM_ERROR, __GIM_HIDE, __GIM_MEM_PAGE_ADD, gim_memory_obj::Alloc(), gim_error, GIM_ERROR_FATAL, gim_memory, and gim_error_obj::set().
~gim_memory_page_obj()
gim_memory_page_obj::~gim_memory_page_obj ()
Definition at line 608 of file gim_memory.cc.
{
 //  destroy_list();
     gim_memory->Free( page );
     gim_error->set( "gim_memory_page_obj::~gim_memory_page_obj", "Memory page deallocated" );
     gim_memory->Free( internal_page );
     gim_error->set( "gim_memory_page_obj::~gim_memory_page_obj", "Internal memory page deallocated" );
 }
References gim_memory_obj::Free(), gim_error, gim_memory, and gim_error_obj::set().
Member Function Documentation
Alloc()
void* gim_memory_page_obj::Alloc (size_t size)
Free()
void gim_memory_page_obj::Free (void * to_free)