/***************************************************************************
 *            gim_gkmake.h
 *
 *  Sunday 14-06-2020 12:34:49
 *  Copyright  2006  asyntote
 *  gkmake version : 0.7-3
 *  asyntote@gkript.org
 ***************************************************************************
 *
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place
 *  Suite 330, Boston, MA 02111-1307, USA.
 */

    /*!
        \version   gkmake 0.7-3
        \brief     File generated by gkmake<BR>
                   gkmake is an opensource project release under the terms<BR>
                   of the GNU General Public License v3<BR>
                   Distribuite with GIM static library<BR><BR>
                   http://www.gkript.org<BR>
    */


#ifndef	GIM_GKMAKE_VERSIONING
#define	GIM_GKMAKE_VERSIONING

   #define GIM_AUTHOR                       asyntote
   #define GIM_GKMAKE_TOTAL_BUILD           1080
   #define GIM_GKMAKE_BUILD                 966
   #define GIM_GKMAKE_LAST_BUILD            "Sunday 14-06-2020 12:34:49"

#endif

