/***************************************************************************
 *            bmake.h                                                       
 *                                                                          
 *  Sun Dec 17 15:49:42 2006                                                
 *  Copyright  2006  AsYntote                                               
 *  bmake version : 0.4-0
 *  asyntote@gkript.org                                                     
 ***************************************************************************
 *                                                                          
 *                                                                          
 *  This program is free software; you can redistribute it and/or modify    
 *  it under the terms of the GNU General Public License as published by    
 *  the Free Software Foundation; either version 2 of the License, or       
 *  (at your option) any later version.                                     
 *                                                                          
 *  This program is distributed in the hope that it will be useful,         
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of          
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           
 *  GNU General Public License for more details.                            
 *                                                                          
 *  You should have received a copy of the GNU General Public License       
 *  along with this program; if not, write to the Free Software             
 *  Foundation, Inc., 59 Temple Place                                       
 *  Suite 330, Boston, MA 02111-1307, USA.                                  
 */                                                                         

/*!	\file       gim_bmake.h
    \version    Bmake 0.4-0
    \brief      File generated by Bmake<BR>
                http://gkript.org/gk_prj_download.php?name_prj=bmake<BR>
                Bmake is an opensource project release under the terms<BR>
                of the GNU General Public License v2<BR>
                http://gkript.org/gk_gpl_v2.php<BR>
*/

#ifndef	GIM_BMAKE_VERSIONING                                   
#define	GIM_BMAKE_VERSIONING                                 

        #define GIM_AUTHOR                   AsYntote                 
        #define GIM_BMAKE_TOTAL_BUILD        6                 
        #define GIM_BMAKE_BUILD              6                 
        #define GIM_BMAKE_LAST_BUILD         "Wednesday 29-04-2009 14:00:09"           

#endif
